// FMCG Core Foundations — cross-category depth pack for the parent FMCG deck.
// These cards sit above the six specialist decks: they explain the shared operating system,
// innovation discipline, commercial language and Vietnam-specific realities of FMCG.

import type { DepthCard } from './industryDepthTypes';

export const FMCG_CORE_DEPTH_CARDS: DepthCard[] = [
  {
    module: 6, topic: 'overview', emoji: '🗺️', type: 'concept',
    title: 'Vietnam FMCG is one market with several buying systems',
    front: 'A national market-share number hides the most important fact: Vietnamese FMCG reaches households through buying systems with different missions, economics and measures of success.',
    back: [
      'Traditional trade — neighbourhood groceries, market stalls and specialist outlets — provides dense reach, small baskets and immediate replenishment. Winning it requires distributor coverage, the right cash price points and relentless outlet execution.',
      'Modern trade — supermarkets, hypermarkets and convenience chains — concentrates volume into fewer accounts. Listings, planograms, promotions, data sharing and account-level profitability become central.',
      'E-commerce and social commerce over-index on discovery, reviews, bundles and premium products, while food service and institutions buy different formats under negotiated terms.',
      'Urban and rural demand cannot be treated as one gradient. Pack size, income cadence, transport, cold availability and outlet density all change what can sell economically.',
      'Sources: Kantar Worldpanel, Vietnam FMCG Monitor; Ministry of Industry and Trade, Vietnam Domestic Market Report 2023; Ministry of Industry and Trade, Vietnam E-Commerce Whitebook 2024.',
    ],
    visual: [
      'VIETNAM FMCG DEMAND',
      '├─ Traditional trade → reach + cash price point',
      '├─ Modern trade      → range + promotion + data',
      '├─ E-commerce       → discovery + bundles + reviews',
      '└─ Food service     → bulk format + negotiated service',
    ],
  },
  {
    module: 7, topic: 'supply-chain', emoji: '🔄', type: 'concept',
    title: 'The forecast-to-shelf loop every category shares',
    front: 'FMCG operations is not a straight factory-to-shop line. It is a weekly feedback loop that converts noisy demand into production, inventory and outlet availability.',
    back: [
      'Demand planning starts with a statistical baseline, then overlays promotions, holidays, weather, launches and distributor intelligence. Tet makes the cost of a weak assumption especially visible.',
      'Supply planning translates that demand into line time, materials, labour and deployment by region. A feasible factory plan can still fail if packaging, warehouse space or truck capacity is missing.',
      'Deployment positions stock before demand occurs. Vietnam’s long geography and fragmented last mile mean national inventory can look healthy while one province is out of stock.',
      'Sales and operations planning closes the loop: commercial, supply chain and finance agree one constrained plan, then measure bias, service level, waste and working capital together.',
      'Sources: ASCM, Sales and Operations Planning framework; Ministry of Industry and Trade, Vietnam Logistics Report 2023; GS1 Vietnam traceability guidance.',
    ],
    visual: [
      'CONSUMPTION SIGNAL',
      '       ↓',
      'Demand plan → Supply plan → Make / buy → Deploy → Shelf',
      '       ↑                                      │',
      '       └──── sales, stock, waste & service ───┘',
    ],
  },
  {
    module: 7, topic: 'rnd-product', emoji: '🚦', type: 'concept',
    title: 'The FMCG innovation funnel: ideas are cheap, launches are not',
    front: 'A credible FMCG idea must pass consumer, technical, regulatory and financial gates before it earns factory time and shelf space.',
    back: [
      'The brief begins with a defined consumer, occasion and job to be done. “A healthier product” is not a brief until the target, benefit, benchmark and price point are explicit.',
      'Concept testing checks whether people understand and value the promise before R&D spends months building it. Product testing then asks whether the formulation beats a benchmark blind and branded.',
      'Pilot and line trials expose scale-up constraints: heat, shear, filling speed, seal integrity and ingredient variation can turn a laboratory success into a factory failure.',
      'A launch gate combines validated demand, lawful claims, target cost, capacity, shelf life and a channel plan. Post-launch review measures repeat purchase and incrementality, not shipment alone.',
      'Sources: Stage-Gate International, Consumer Packaged Goods development model; NielsenIQ BASES innovation guidance; Vietnam Law on Food Safety No. 55/2010/QH12.',
    ],
    visual: [
      'Need → Concept → Prototype → Pilot → Launch → Learn',
      '       consumer    technical   commercial',
      '         gate        gate         gate',
      '   STOP weak ideas before cost compounds',
    ],
  },
  {
    module: 8, topic: 'rnd-product', emoji: '🛠️', type: 'fact',
    title: 'Renovation often creates more value than a headline launch',
    front: 'The highest-return R&D work is often invisible: improve an existing high-volume product by one meaningful step without breaking what consumers already love.',
    back: [
      'Renovation includes reformulating for lower sugar or salt, improving yield, localising an ingredient, strengthening a pack seal, extending shelf life or removing material from the package.',
      'The scale effect is decisive. A tiny saving per unit on a national core SKU can fund far more value than a fashionable niche launch that never reaches repeat purchase.',
      'The risk is asymmetric: loyal buyers notice changes in taste, texture, fragrance and pack handling. Blind sensory testing and controlled changeover are therefore as important as the saving.',
      'Good renovation uses a dual scorecard: consumer acceptance and cost or sustainability benefit. Passing only one side is not success.',
      'Sources: NielsenIQ, Breakthrough Innovation reporting; Ellen MacArthur Foundation, reusable and recyclable packaging guidance; Codex Alimentarius General Principles of Food Hygiene CXC 1-1969.',
    ],
  },
  {
    module: 8, topic: 'rnd-product', emoji: '🌡️', type: 'concept',
    title: 'Shelf life must survive Vietnam, not the laboratory',
    front: 'A product is not finished when it tastes right on day one. It is finished when it remains safe, legal and acceptable through heat, humidity, transport and the final outlet.',
    back: [
      'Shelf-life design begins with the failure mode: microbial growth, oxidation, moisture pickup, flavour loss, colour change, fragrance drift, separation or package failure.',
      'R&D then builds barriers around that failure — formulation, heat treatment, water activity, oxygen control, light protection, preservative system and packaging barrier all work together.',
      'Accelerated testing provides an early warning, but real-time and distribution trials matter because vibration, hot warehouses and repeated handling are difficult to reproduce perfectly.',
      'The label date must leave enough life for factory release, national deployment, distributor stock, store rotation and household use. A longer claim that creates expiry in trade is commercially worse than an honest shorter one.',
      'Sources: Codex Alimentarius General Principles of Food Hygiene CXC 1-1969; Vietnam Law on Food Safety No. 55/2010/QH12; World Bank Climate Change Knowledge Portal, Vietnam climate profile.',
    ],
    visual: [
      'FORMULA + PROCESS + PACK',
      '            ↓',
      'Factory → Warehouse → Truck → Outlet → Home',
      '            heat • humidity • time • handling',
      '            ↓',
      'Safety + sensory quality through stated date',
    ],
  },
  {
    module: 7, topic: 'finance', emoji: '🧾', type: 'concept',
    title: 'From shelf price to contribution: the FMCG money waterfall',
    front: 'Revenue is not the shelf price multiplied by units. Between the shopper’s payment and company profit sits a waterfall of tax, channel margin, trade terms and variable cost.',
    back: [
      'Start with consumer sales value, then remove indirect tax and the retailer and distributor economics to understand what can reach the manufacturer.',
      'Gross-to-net deductions include invoice discounts, rebates, listing support, promotional funding, returns and other customer terms. Weak control here lets reported growth hide deteriorating quality of revenue.',
      'Net sales minus product and conversion cost gives gross profit; subtract variable logistics, selling and activation costs to see contribution. Different channels can sell the same SKU at very different contribution.',
      'The management question is therefore not only “Did volume grow?” but “Was growth incremental, collected, and profitable after every term used to buy it?”',
      'Sources: IFRS 15, Revenue from Contracts with Customers; NielsenIQ Revenue Growth Management guidance; Ministry of Finance, Vietnam Accounting Standards framework.',
    ],
    visual: [
      'SHOPPER SHELF VALUE                 100',
      '− VAT / channel margin / terms      (35)',
      '= MANUFACTURER NET SALES             65',
      '− product + conversion cost         (32)',
      '= GROSS PROFIT                       33',
      '− variable logistics + activation  (13)',
      '= CONTRIBUTION                       20',
      'Illustrative only — structure matters, not the numbers',
    ],
  },
  {
    module: 6, topic: 'marketing-sales', emoji: '🪜', type: 'concept',
    title: 'Price-pack architecture is strategy made visible',
    front: 'FMCG does not have one price. It has a ladder of packs designed for different cash outlays, occasions, channels and levels of value.',
    back: [
      'An entry pack protects accessibility through a low absolute outlay; a core pack carries the familiar reference price; a stock-up pack rewards planned purchase; a premium pack monetises a superior benefit or occasion.',
      'Price per gram or litre should usually fall as pack size rises, but the shopper first sees cash outlay. That distinction is critical in traditional trade, where the amount paid today may matter more than theoretical value.',
      'Architecture also prevents self-cannibalisation. If two packs offer the same job at nearly the same unit economics, the larger one may simply subsidise buyers who would have paid more.',
      'The strongest case answer specifies the role, channel, price point and margin of each pack rather than proposing one universal SKU for Vietnam.',
      'Sources: NielsenIQ Revenue Growth Management guidance; Kantar Worldpanel, Vietnam FMCG Monitor and Brand Footprint Vietnam.',
    ],
    visual: [
      'Premium / occasion pack     ↑ benefit + margin',
      'Stock-up / family pack      ↓ unit price',
      'Core pack                   = reference choice',
      'Entry / trial pack          ↓ cash outlay',
      'Each rung needs a distinct shopper job',
    ],
  },
  {
    module: 7, topic: 'marketing-sales', emoji: '🤝', type: 'concept',
    title: 'Brand marketing creates pull; trade marketing converts it',
    front: 'A campaign can make people want a brand. Trade marketing makes sure the right pack is listed, visible, priced and available when that desire reaches a store.',
    back: [
      'Brand marketing defines the target, promise, distinctive assets and communication. Its job is mental availability: being remembered in a buying situation.',
      'Trade marketing translates that strategy by channel: assortment, planogram, display, promotion mechanics, retailer story, field standards and activation materials.',
      'Sales owns the customer agreement and execution; revenue growth management protects price, mix and trade-spend productivity. The boundaries overlap, which is why shared measures matter.',
      'The best launch plan joins both halves. Media without distribution creates disappointed demand; distribution without consumer pull creates slow stock and retailer resistance.',
      'Sources: Ehrenberg-Bass Institute, mental and physical availability framework; NielsenIQ Revenue Growth Management guidance; Kantar, Vietnam Brand Footprint.',
    ],
    visual: [
      'BRAND MARKETING                 TRADE MARKETING',
      'Who + promise + memory    →    channel + pack + shelf',
      '        CONSUMER PULL  +  PHYSICAL AVAILABILITY',
      '                         ↓',
      '                      PURCHASE',
    ],
  },
  {
    module: 7, topic: 'marketing-sales', emoji: '➡️', type: 'concept',
    title: 'Sell-in is not sell-out, and neither is consumption',
    front: 'Three numbers can all be called sales. Confusing them is one of the fastest ways to misread an FMCG business.',
    back: [
      'Sell-in is manufacturer shipment to a distributor or retailer. It records company revenue but can rise because the channel is building inventory rather than because shoppers want more.',
      'Sell-out is the channel’s sale to an outlet or shopper, depending on the route. It is closer to demand, but distributor sell-out can still leave stock sitting in a shop.',
      'Consumer offtake is the final purchase or use signal measured through retail scans, audits or household panels. It is the best demand evidence and is never perfectly complete in fragmented trade.',
      'Healthy growth keeps the three signals aligned over time. If sell-in runs ahead, days of inventory, returns, expiry and future order cuts reveal the bill later.',
      'Sources: NielsenIQ Retail Measurement Services methodology; Kantar Worldpanel consumer-panel methodology; Ministry of Industry and Trade, Vietnam Domestic Market Report 2023.',
    ],
    visual: [
      'MANUFACTURER ── sell-in ──▶ DISTRIBUTOR / RETAILER',
      '                                   │',
      '                              sell-out',
      '                                   ▼',
      '                              OUTLET / SHOPPER',
      '                                   │',
      '                           purchase / consumption',
      'Inventory between arrows can disguise demand',
    ],
  },
  {
    module: 8, topic: 'marketing-sales', emoji: '📍', type: 'fact',
    title: 'One launch needs four channel versions',
    front: 'A single national launch deck is operationally incomplete. The proposition may be one, but assortment, activation and economics must be translated by channel.',
    back: [
      'Traditional trade needs a tight hero assortment, a clear cash price point, distributor availability and a field-sales story that can be delivered in minutes.',
      'Modern trade can support broader range, shelf blocking, sampling and promotions, but listing lead times and customer terms must be built into the economics.',
      'Convenience stores reward immediate-consumption formats and cold or checkout placement; e-commerce rewards bundles, content, ratings and official-store trust.',
      'The disciplined launch scorecard separates numeric distribution, weighted distribution, on-shelf availability, rate of sale, repeat and contribution by channel.',
      'Sources: Kantar Worldpanel, Vietnam FMCG Monitor; NielsenIQ Retail Measurement Services; Ministry of Industry and Trade, Vietnam E-Commerce Whitebook 2024.',
    ],
  },
  {
    module: 7, topic: 'people-career', emoji: '🧩', type: 'role',
    title: 'The best FMCG decisions are made between functions',
    front: 'A management trainee is rarely rewarded for optimising one department. The real work is resolving trade-offs that cross marketing, sales, supply chain, R&D and finance.',
    back: [
      'Marketing wants a stronger proposition and faster launch; R&D protects safety and technical proof; operations protects repeatability and capacity; sales protects customer adoption; finance protects return.',
      'Sales and operations planning is the recurring forum where these views become one demand, supply and financial plan rather than five incompatible forecasts.',
      'The transferable skills are structured problem framing, comfort with imperfect data, stakeholder mapping and the ability to state which metric is being traded for which.',
      'A strong interview story names the conflict, the shared business outcome, the evidence used and the decision rule — not simply that the candidate “communicated well.”',
      'Sources: ASCM, Sales and Operations Planning framework; Prosci change-management research; VietnamWorks and major FMCG graduate-programme role descriptions.',
    ],
    visual: [
      'CONSUMER NEED',
      'Marketing ─ R&D ─ Supply ─ Sales ─ Finance',
      '     proposition → feasible → available → profitable',
      'One plan; shared measures; explicit trade-offs',
    ],
  },
  {
    module: 9, topic: 'surprising', emoji: '🧊', type: 'fact',
    title: 'Availability can beat preference at the moment of truth',
    front: 'A shopper can prefer your brand and still buy the competitor because yours is warm, absent, hidden or available only in the wrong pack.',
    back: [
      'FMCG purchases are frequent and low-risk, so substitution is easy. The penalty for an out-of-stock is often an immediate competitor sale rather than a delayed purchase.',
      'Physical availability has several layers: the outlet carries the brand, the right SKU is in stock, it is findable, the displayed price is correct and the product is usable for the occasion — cold if immediate consumption requires cold.',
      'This is why weighted distribution and on-shelf availability often explain growth better than raw outlet count. Presence in the outlets that matter is more valuable than nominal presence everywhere.',
      'The counterintuitive lesson: another advertising point may create less incremental demand than fixing replenishment in the highest-velocity stores.',
      'Sources: Ehrenberg-Bass Institute, physical availability research; NielsenIQ Retail Measurement Services and on-shelf availability guidance.',
    ],
  },
  {
    module: 9, topic: 'surprising', emoji: '🧴', type: 'fact',
    title: 'A smaller pack can be more inclusive and more profitable',
    front: 'Small formats are often dismissed as the cheap end of FMCG. In Vietnam they can lower the cash barrier, recruit a household and earn a higher price per unit at the same time.',
    back: [
      'The shopper optimises the cash paid now; the manufacturer manages price per gram or millilitre. Those are different calculations, especially where income and shopping are frequent.',
      'Sachets and trial packs reduce commitment and let consumers access branded quality without funding a large pack. They are therefore recruitment tools, not merely down-market variants.',
      'The economics can be attractive because unit price is higher, but packaging and conversion cost per gram are also higher and the waste burden is materially worse.',
      'The strategic answer is not “small packs everywhere.” It is a deliberate entry rung plus a migration path into refills or larger packs once trust and cash flow allow.',
      'Sources: Kantar, Brand Footprint Vietnam; World Bank, Vietnam household and financial-inclusion data; Ellen MacArthur Foundation, flexible-packaging circularity guidance.',
    ],
  },
  {
    module: 10, topic: 'surprising', emoji: '📉', type: 'case',
    title: 'A promotion can grow volume and destroy value',
    front: 'A 20% volume lift is not evidence that a promotion worked. The extra units may have been subsidised purchases that would have happened anyway or stock pulled forward from next week.',
    back: [
      'Measure the baseline first. Incremental units are promoted sales above what the SKU would otherwise have sold, not every unit scanned during the event.',
      'Then remove cannibalisation of the brand’s other packs, forward buying by households or retailers, post-promotion dip, display fees and the discount on baseline units.',
      'A promotion can still be strategically sound when it recruits new households, triggers trial of a repeatable product or wins a critical occasion — but that objective must be named before the discount starts.',
      'The interview move is to ask for incremental contribution and repeat after the event, not celebrate shipment or redemption alone.',
      'Sources: NielsenIQ Revenue Growth Management and promotion-effectiveness guidance; Kantar Worldpanel shopper-panel methodology.',
    ],
    visual: [
      'PROMOTED VOLUME',
      '− baseline units discounted',
      '− cannibalised sister SKUs',
      '− forward buying / post-event dip',
      '= TRUE INCREMENTAL UNITS',
      '× incremental margin − activation cost = VALUE CREATED',
    ],
  },
  {
    module: 10, topic: 'surprising', emoji: '📱', type: 'fact',
    title: 'Digital can shape the sale without booking the sale',
    front: 'Looking only at e-commerce revenue understates digital influence. Vietnamese shoppers may discover, compare and validate a product online, then buy it in a neighbourhood store.',
    back: [
      'Search, short video, livestreams, ratings and official stores compress discovery and trust-building, particularly for beauty, wellness, premium food and unfamiliar innovations.',
      'The final purchase may still happen offline because the outlet is closer, the product is needed now, delivery economics are poor or the shopper wants a smaller cash outlay.',
      'That makes last-click return on advertising incomplete. Useful measures include branded search, new-to-brand buyers, content engagement, store-level uplift and household penetration alongside online conversion.',
      'The counterintuitive strategy is to design online content and offline availability as one route to market rather than forcing every digital interaction into an online basket.',
      'Sources: Ministry of Industry and Trade, Vietnam E-Commerce Whitebook 2024; Google, Temasek and Bain, e-Conomy SEA 2024; Kantar, Vietnam FMCG Monitor.',
    ],
    visual: [
      'VIDEO / SEARCH / REVIEWS',
      '          ↓ discovery + proof',
      'Official store / marketplace ─┐',
      'Neighbourhood store          ├─▶ PURCHASE',
      'Supermarket / convenience    ┘',
      'Influence path ≠ checkout path',
    ],
  },
];
