// Technology & Digital — deep Vietnam-specific card pack (modules 6-10).
// FY2025 actuals and 2026 policy where available; global figures are labelled as global.

import type { DepthCard } from './industryDepthTypes';

export const TECH_DEPTH_CARDS: DepthCard[] = [
  {
    module: 6, topic: 'overview', emoji: '💻', type: 'fact',
    title: 'Vietnam’s digital economy by the numbers (2025)',
    front: 'Vietnam’s four largest e-commerce platforms turned over roughly VND429.7 trillion (about USD16.35 billion) in 2025, up 34.75% year on year — inside a digital economy estimated near USD39 billion.',
    back: [
      'Two credible estimates disagree, and quoting both makes you sound like an analyst: Metric puts top-four platform GMV at VND429.7 trillion (+34.75%); YouNet ECI puts it at VND458.16 trillion (about USD17.43 billion, +26%). The gap comes from what each counts as a transaction.',
      'Volume grew slower than value: 3.94 billion items were sold across the four platforms in 2025, up 15.23% — so average order value rose. Growth came from bigger baskets and higher prices, not only more orders.',
      'Demand is heavily urban: Shopee’s Vietnam GMV was about VND224.2 trillion, with Ho Chi Minh City contributing roughly 42% and Hanoi about 41% of that total.',
      'Interview move: say “GMV” only when you mean gross merchandise value, then immediately follow it with take rate. GMV is a scale metric, not a revenue metric.',
    ],
  },
  {
    module: 6, topic: 'overview', emoji: '🛍️', type: 'fact',
    title: 'The Shopee-TikTok Shop duopoly',
    front: 'Vietnamese e-commerce is now a two-horse race: Shopee held about 56% of platform GMV in 2025 and TikTok Shop about 41% — roughly 97% between them.',
    back: [
      'Shopee’s share fell from about 64% in 2024 to 56.04% in 2025 with growth of only about 6%; TikTok Shop rose from about 29% to 41.31% on roughly 93% revenue growth (Metric / YouNet ECI).',
      'Lazada and Tiki have faded to the margins, which changes the strategic question from “how do we win share” to “how do we monetise an installed habit”.',
      'The mechanism behind TikTok Shop’s rise is shoppertainment: short-form video and livestream discovery replace search intent, so merchandising, creator commissions and content velocity matter more than keyword bidding.',
      'Consequence for sellers: two platforms with different physics. Shopee rewards ratings, warranty and logistics reliability; TikTok Shop rewards content output and creator economics. A seller plan must be platform-specific.',
    ],
  },
  {
    module: 6, topic: 'overview', emoji: '🧩', type: 'concept',
    title: 'Five different businesses all called “tech” in Vietnam',
    front: 'Naming the model correctly in your first sentence is the fastest way to sound informed in a tech interview.',
    back: [
      'Marketplace / commerce platform (Shopee, TikTok Shop, Lazada, Tiki): revenue is commission plus advertising plus fulfilment fees; the metric set is GMV, take rate and contribution margin per order.',
      'IT services and outsourcing (FPT Software, KMS Technology, Axon Active, NashTech): revenue is billable capacity and project fees; metrics are utilisation, rate, revenue per employee and new signings.',
      'Product / SaaS (MISA, Base.vn, KiotViet, and gaming studios such as Sky Mavis): revenue is recurring subscription; metrics are ARR, net revenue retention and CAC payback.',
      'Fintech and payments (MoMo, VNPay, ZaloPay, bank super-apps): revenue is merchant fees and financial-service distribution under SBV payment-intermediary licensing.',
      'Ecosystem platform (Viettel, FPT, VNG): telecom or gaming cash flows funding cloud, data centres, AI and enterprise products. Always ask which business actually pays for the others.',
    ],
    diagram: ['Marketplace', 'IT services', 'SaaS product', 'Fintech', 'Ecosystem platform'],
  },
  {
    module: 6, topic: 'finance', emoji: '📈', type: 'fact',
    title: 'FPT: what a Vietnamese technology champion looks like',
    front: 'FPT reported FY2025 revenue of VND70,113 billion (+11.6%) and pre-tax profit of VND13,039 billion (+17.8%). Technology alone was VND44,475 billion — 63% of revenue and 45% of profit.',
    back: [
      'Global IT services (offshore delivery for overseas clients) reached VND35,382 billion, up 14.3%, with Japan growing 25.4% — Japan, not the US, is the engine of Vietnamese IT services.',
      'Digital transformation work was VND16,751 billion (+16.8%), or 47.3% of global IT revenue, and new signings hit VND40,636 billion (+23.2%), including 26 contracts above USD10 million each — double the prior year.',
      'Domestic IT was the weak spot: revenue VND9,093 billion (+11.5%) but pre-tax profit down 9.7%. Domestic enterprise and public-sector work is lower margin than export delivery.',
      'From FY2026 FPT Telecom (about VND18.7 trillion of FY2025 revenue) is deconsolidated to the equity method, so reported revenue drops while profit per share is unaffected. If you quote FPT growth, name the year and the accounting basis.',
    ],
  },
  {
    module: 6, topic: 'supply-chain', emoji: '📱', type: 'fact',
    title: 'The hardware layer: why Vietnam matters to global tech',
    front: 'Vietnam’s biggest tech story is still physical. Computers, electronics and components exported USD106 billion in 2025 — up about 46%, and the country’s first single export group above USD100 billion.',
    back: [
      'Phones and accessories added about USD57.6 billion. Samsung is reported to make around half its global smartphone output in Vietnam, and electronics has overtaken garments and footwear as the largest export category to the United States.',
      'R&D is following assembly: Samsung runs a Vietnamese R&D centre of roughly 2,400 engineers, NVIDIA announced a Vietnam R&D centre in December 2024, and Intel, Amkor, Hana Micron and Bosch anchor the back-end ecosystem.',
      'Talent scale: about 1.9 million people work in Vietnam’s technology sector, with more than 7,000 chip-design engineers and roughly 70,000 IT graduates entering the workforce each year.',
      'Interview move: connect hardware to software — assembly built the workforce and the FDI relationships that now make design, testing and applied AI services plausible.',
    ],
  },
  {
    module: 6, topic: 'supply-chain', emoji: '💳', type: 'fact',
    title: 'Payments: the rails everything else runs on',
    front: 'Vietnam went cashless faster than almost any comparable market, and that is the precondition for e-commerce, super-apps and embedded finance.',
    back: [
      'In H1 2026 the State Bank of Vietnam recorded more than 15 billion cashless transactions worth over VND190 quadrillion — volume up 34.28% — while more than 89% of adults hold a payment account and ATM transactions fell about 9%.',
      'The players split by role: VNPay dominates bank-linked QR acquiring, MoMo (reported over 30 million users) monetises merchant payments and financial-service distribution, ZaloPay leverages messaging reach, and bank apps compete head-on.',
      'Licensing shapes strategy: wallets are payment intermediaries, not banks, so lending, deposits and insurance need a licensed partner. Every fintech growth plan is also a partnership plan.',
      'Since 1 July 2025, platforms with payment functions must withhold VAT and personal income tax on each transaction for household and individual sellers (Decree 117/2025/ND-CP) — the rails are now a tax-collection mechanism too.',
    ],
  },
  {
    module: 6, topic: 'finance', emoji: '🧮', type: 'quiz',
    title: 'Market check: GMV versus revenue',
    front: 'A marketplace reports VND100 billion GMV, a 4% commission take rate and VND2 billion of advertising revenue. What is platform revenue?',
    back: ['VND6 billion — VND4 billion of commission plus VND2 billion of ads. GMV is what buyers spent, not what the platform earned; take rate plus ancillary revenue converts one into the other.'],
    options: ['VND100 billion', 'VND6 billion', 'VND4 billion only', 'It cannot be calculated'],
    answer: 1,
  },
  {
    module: 7, topic: 'people-career', emoji: '👩‍💻', type: 'role',
    title: 'What a tech graduate hire actually does in week one',
    front: 'Tech programmes put you on a live metric almost immediately. Here is the shape of the work by track.',
    back: [
      'Product: read support tickets and session recordings, write the problem statement, then define the one metric the next release must move. You will spend more time cutting scope than adding it.',
      'Growth / marketing: run a channel experiment with a holdout group, measure incrementality rather than attributed clicks, and calculate CAC payback by cohort.',
      'Business operations / category: own a seller or merchant segment — onboarding conversion, catalogue quality, fulfilment SLA breaches, and the exception queue nobody has automated yet.',
      'Data / analytics: define an event taxonomy, fix a metric that two teams calculate differently, and build the cohort table that settles the argument.',
      'Whatever the track, your first deliverable is usually a number with a defensible definition. Ambiguous metrics are the most common junior failure.',
    ],
  },
  {
    module: 7, topic: 'finance', emoji: '📊', type: 'concept',
    title: 'The tech KPI dictionary MTs are tested on',
    front: 'These terms come up in almost every Vietnamese tech interview. Know the formula, the failure mode and one benchmark.',
    back: [
      'GMV and take rate — platform scale and monetisation. Failure mode: celebrating GMV bought with vouchers.',
      'Contribution margin per order — revenue minus payment fees, logistics subsidy, voucher cost and support cost. This is the number that decides whether growth is fatal.',
      'CAC, payback and LTV:CAC — acquisition cost, months to recover it, and lifetime contribution over that cost. Failure mode: lifetime value estimated from three weeks of data.',
      'Cohort retention and DAU/MAU — whether users return without a promotion. For commerce, the honest version is repeat purchase rate at 30, 60 and 90 days.',
      'ARR, net revenue retention and revenue per employee — the SaaS and services equivalents; an IT-services model such as FPT’s lives on utilisation, rate and signings rather than ARR.',
    ],
  },
  {
    module: 7, topic: 'people-career', emoji: '🏗️', type: 'concept',
    title: 'How a Vietnamese tech company is organised',
    front: 'Understanding the seams between these teams tells you where a graduate actually has leverage.',
    back: [
      'Product, design and engineering form the delivery core, usually in squads owning one funnel step or surface.',
      'Commercial sits opposite: category management or merchant acquisition in commerce, enterprise sales in services and SaaS, partnerships and BD in fintech.',
      'Operations is the part outsiders forget: seller onboarding, content moderation, fraud review, fulfilment coordination and support. In Vietnamese marketplaces this is where most headcount and most cost sit.',
      'Data and finance provide the scoreboard; risk, legal and compliance own licensing, personal-data obligations and platform-tax withholding.',
      'In ecosystem groups (Viettel, FPT, VNG) each unit has its own P&L and the centre allocates capital — so an internal proposal competes against other units, not just the status quo.',
    ],
    diagram: ['Product & engineering', 'Commercial / category', 'Operations', 'Data & finance', 'Risk & compliance'],
  },
  {
    module: 7, topic: 'people-career', emoji: '🔁', type: 'role',
    title: 'Graduate and MT tracks in Vietnamese tech',
    front: 'Tech programmes are less standardised than FMCG or banking. Read the structure before you apply.',
    back: [
      'Regional platform programmes (for example the Shopee and Monee Global Development Program) rotate across business functions with regional exposure and heavy analytics screening.',
      'Telecom and state-linked groups (Viettel’s Future Changemakers) offer scale, infrastructure and public-sector projects, with more structured and slower-moving ladders.',
      'Fintech programmes (MoMo Talent) are closest to startup work: narrow ownership, fast feedback and product metrics visible from week one.',
      'IT services (FPT, KMS, Axon Active) hire in volume into delivery roles with a technical assessment; the later differentiator is domain expertise — banking, healthcare, automotive — not language alone.',
      'Bank technology streams compete for the same graduates: Techcombank Future Gen runs Technology and Data & AI streams, and VPBank Young Talents targeted AI/ML and data-science majors. Apply across sectors with one portfolio.',
    ],
  },
  {
    module: 7, topic: 'marketing-sales', emoji: '🎟️', type: 'quiz',
    title: 'Operating check: which growth is real',
    front: 'A marketplace doubles orders during a voucher campaign, then sees 30-day repeat purchase fall from 38% to 24%. What is the most defensible read?',
    back: ['The campaign bought transactions, not habit. A volume spike alongside falling cohort repeat rate is the signature of subsidy-driven growth; check contribution margin per order and the new cohort’s retention before scaling.'],
    options: [
      'Growth is healthy because orders doubled',
      'The campaign acquired low-intent buyers; check cohort retention and contribution margin before scaling',
      'Repeat purchase rate is irrelevant for e-commerce',
      'The platform should double the voucher budget immediately',
    ],
    answer: 1,
  },
  {
    module: 8, topic: 'marketing-sales', emoji: '🏪', type: 'fact',
    title: 'E-commerce has entered its consolidation phase',
    front: 'The land-grab is over. Fees are rising, tax rules tightened, and growth is concentrating among larger, professionalised sellers.',
    back: [
      'Platforms raised seller commissions and service fees through 2025, squeezing the long tail of small shops that survived on subsidised shipping and low fees.',
      'Since 1 July 2025, Decree 117/2025/ND-CP forces platforms to withhold VAT and personal income tax at transaction confirmation for household and individual sellers — formalising a previously grey segment and raising the compliance floor.',
      'The winners are official brand stores and larger operators: “Mall”-type storefronts punch far above their share of listings, and content-led selling favours sellers who can fund daily livestream output.',
      'Strategic implication for a case: the growth question is no longer seller acquisition but monetisation and quality — advertising revenue, fulfilment services and repeat purchase.',
    ],
  },
  {
    module: 8, topic: 'rnd-product', emoji: '🧠', type: 'fact',
    title: 'AI and semiconductors are now national policy',
    front: 'Resolution 57-NQ/TW (December 2024) made science, technology, innovation and digital transformation a Politburo-level priority, with explicit AI and semiconductor targets.',
    back: [
      'Stated targets: top three in ASEAN and top 50 globally for AI readiness by 2030; 50,000 semiconductor personnel trained by 2030 (about 15,000 in chip design, 35,000 in manufacturing, packaging and testing) plus roughly 5,000 AI specialists.',
      'Industrial plan: Decision 1018/QD-TTg targets ten advanced testing-and-packaging plants by 2030. Viettel broke ground on Vietnam’s first 32nm chip plant at Hoa Lac Hi-Tech Park with trial production expected in 2028, and FPT announced an advanced test-and-packaging facility staffed by Vietnamese engineers.',
      'Compute is the bottleneck: Vietnam has an estimated 10,000-15,000 GPUs against roughly 50,000-60,000 in South Korea, which is why more than USD7 billion of AI data-centre investment has been announced and why FPT built a USD200 million AI Factory with NVIDIA.',
      'Honest framing: policy ambition is real, but Vietnam competes today in back-end assembly, testing and applied AI services rather than leading-edge design. Saying that makes you credible rather than promotional.',
    ],
  },
  {
    module: 8, topic: 'rnd-product', emoji: '🔒', type: 'fact',
    title: 'The new rulebook for digital businesses',
    front: 'Three regulatory shifts now shape every Vietnamese product roadmap: personal data, digital-industry law, and platform tax.',
    back: [
      'The Personal Data Protection Law takes effect at the start of 2026, adding consent, purpose-limitation and accountability obligations that hit marketing, data science and recommendation systems directly.',
      'The Law on Digital Technology Industry creates a dedicated framework and incentives for digital-technology enterprises and emerging technologies — relevant whenever a case touches investment incentives or data-centre siting.',
      'Platform tax withholding (Decree 117/2025/ND-CP, effective 1 July 2025) shifts collection responsibility onto marketplaces, including foreign operators, with monthly declaration duties.',
      'Practical interview line: in Vietnam a growth idea that ignores consent, data residency or seller tax status is not a growth idea — it is a compliance incident with a marketing budget.',
    ],
  },
  {
    module: 8, topic: 'rnd-product', emoji: '🤖', type: 'fact',
    title: 'AI pressure on the outsourcing model',
    front: 'Vietnam’s IT services industry sells engineering capacity. AI tooling makes capacity cheaper — so the model must move up the value chain.',
    back: [
      'The shift is visible in FPT’s own mix: digital transformation reached 47.3% of global IT revenue in FY2025 and the firm won 26 contracts above USD10 million each, while domestic IT profit fell 9.7%.',
      'Japan is the anchor market (+25.4% in FY2025), driven by client digital-transformation demand and an ageing domestic engineering workforce — a structural rather than cyclical advantage.',
      'The threat is repricing: if AI cuts the hours needed for maintenance and testing, a per-hour business must sell outcomes, platforms or domain expertise instead of headcount.',
      'For candidates: the credible answer to “how does AI affect Vietnamese IT services?” is contract structure and margin mix — not “engineers will be replaced”.',
    ],
  },
  {
    module: 8, topic: 'finance', emoji: '🧾', type: 'quiz',
    title: 'Trend check: who withholds the tax',
    front: 'Since 1 July 2025, who withholds VAT and personal income tax on a Vietnamese individual seller’s marketplace order?',
    back: ['The platform. Decree 117/2025/ND-CP makes domestic and foreign platform operators with payment functions withhold and remit VAT and PIT per transaction and declare monthly; sellers covered by that withholding do not declare those transactions themselves.'],
    options: [
      'The individual seller, quarterly',
      'The e-commerce platform operator, at transaction confirmation',
      'The logistics partner',
      'Nobody — online sales are tax exempt',
    ],
    answer: 1,
  },
  {
    module: 9, topic: 'overview', emoji: '🏢', type: 'case',
    title: 'FPT: from body-shop to AI-era systems integrator',
    front: 'FPT is the reference case for Vietnamese technology because every claim can be checked against disclosed numbers.',
    back: [
      'FY2025: revenue VND70,113 billion (+11.6%), pre-tax profit VND13,039 billion (+17.8%), EPS VND5,211 (+21.4%), technology 63% of revenue and 45% of profit.',
      'Strategy: move from staff augmentation toward digital transformation and large multi-year contracts (signings +23.2%; 26 deals above USD10 million), plus a “Made-by-FPT” product line at VND2,672 billion (+19.1%).',
      'Capability bets: the USD200 million AI Factory with NVIDIA, a chip test-and-packaging plant, and a semiconductor and AI training pipeline through FPT University.',
      'Structural change to know: from FY2026 FPT Telecom is deconsolidated, so reported revenue falls while profit attributable to shareholders is unaffected — an accounting-versus-economics distinction interviewers enjoy.',
      'Interview question this unlocks: how would you measure whether FPT is genuinely moving up the value chain rather than just adding engineers?',
    ],
  },
  {
    module: 9, topic: 'marketing-sales', emoji: '📹', type: 'case',
    title: 'Shopee versus TikTok Shop: two ways to own demand',
    front: 'The same market, two completely different growth engines — the clearest live case study in Vietnamese consumer tech.',
    back: [
      'Shopee holds about 56% of platform GMV on roughly 6% growth: its assets are search intent, ratings, warranty and refund trust, logistics reliability, and an advertising business built on habit.',
      'TikTok Shop grew revenue about 93% to roughly 40% share: its asset is content-driven discovery, where creators and livestreams generate demand that never started as a search.',
      'The economics differ: search-led commerce monetises high-intent traffic through ads and commission; content-led commerce pays creators and depends on content volume, so contribution per order behaves differently.',
      'Both now face the same constraint: fee increases and tax withholding professionalised the seller base, so platform growth comes increasingly from larger sellers and better monetisation rather than new merchants.',
      'Interview question this unlocks: if you ran a mid-size Vietnamese brand, how would you split budget between the two platforms and why?',
    ],
  },
  {
    module: 9, topic: 'overview', emoji: '👛', type: 'case',
    title: 'MoMo and VNPay: distribution without a banking licence',
    front: 'Vietnam’s payment platforms won the habit but must rent the balance sheet — which shapes every strategic option they have.',
    back: [
      'MoMo reports more than 30 million users and monetises merchant payments, bill payments, mini-apps and distribution of partners’ financial products; VNPay built the bank-linked QR acceptance network used across millions of merchant touchpoints.',
      'Because they are licensed as payment intermediaries rather than banks, credit, deposits and insurance sit with partner institutions — revenue is shared and product design is bounded by the partner’s risk appetite.',
      'Their sharpest competitive threat is the banks themselves: with over 95% of transactions digital at many banks and QR payment value up around 40% year on year, the bank app substitutes directly for the wallet.',
      'The honest strategic question is monetisation depth: revenue per active user, share of users monetised through financial services, and the cost of promotional incentives.',
      'Interview question this unlocks: which single partnership would most improve a Vietnamese wallet’s revenue per user, and what does the partner get in return?',
    ],
  },
  {
    module: 9, topic: 'overview', emoji: '🕋', type: 'case',
    title: 'Viettel and VNG: ecosystems funded by a cash engine',
    front: 'Both use a profitable core to fund adjacent technology bets — the dominant model in Vietnamese enterprise tech.',
    back: [
      'Viettel uses telecom cash flow to fund data centres, cloud, defence-adjacent technology and now semiconductor manufacturing (its first 32nm plant at Hoa Lac, trial production targeted for 2028), plus large public-sector digital programmes.',
      'VNG built on games and Zalo — the dominant local messaging platform — then expanded into payments, cloud and AI services, with each adjacency needing its own right to win rather than inheriting one.',
      'For graduates this means scale plus process: bigger systems, clearer ladders, more stakeholders and slower decisions than a startup. Acknowledge that trade-off honestly in interview.',
      'The test to apply to both: does the adjacency share a real capability — network, data, distribution, engineering — or only a brand and a balance sheet?',
      'Interview question this unlocks: which of Viettel’s or VNG’s adjacent businesses would you fund next, and which would you stop?',
    ],
  },
  {
    module: 9, topic: 'people-career', emoji: '📅', type: 'fact',
    title: 'Tech recruitment: timeline and round structure',
    front: 'Tech hiring in Vietnam is less calendar-bound than banking or FMCG, but the round structure is remarkably consistent.',
    back: [
      'Regional platform programmes usually open mid-year: online application, numerical and logical assessment, a business-problem exercise, then two or three interviews including a hiring manager.',
      'Product and analytics roles add a take-home or live exercise — read a funnel, propose a metric, size a market, interpret an A/B test. Practise saying “here is what I would check before deciding” out loud.',
      'Engineering and IT-services roles run technical screens (coding, systems, sometimes Japanese or English proficiency for delivery teams) with faster cycles and rolling intake.',
      'Bank technology streams overlap usefully: Techcombank Future Gen 2027 ran applications 30 July to 30 September 2026 with January 2027 onboarding, and VPBank Young Talents 2026 closed 5 June 2026.',
      'Portfolio beats pedigree here: one documented project with a measured outcome — users, latency, revenue, hours saved — outperforms a longer list of coursework.',
    ],
  },
  {
    module: 10, topic: 'people-career', emoji: '🎤', type: 'fact',
    title: 'Competency questions tech interviewers actually ask',
    front: 'Tech interviews test decision hygiene: how you choose a metric, how you handle ambiguity, how you kill your own idea.',
    back: [
      '“Pick a product you use daily and tell me the one metric you would improve.” They want a defined user, a value moment, and a metric that is not vanity.',
      '“Tell me about a time your data contradicted your assumption.” Show the correction and what you changed afterwards.',
      '“How would you choose between two features with equal engineering cost?” Expected: reach, impact per user, confidence, effort — plus what you would measure post-launch.',
      '“A campaign shows a 5x return on ad spend. Do you scale it?” Correct instinct: ask about incrementality, holdout groups and attribution window before spending more.',
      '“What if engineering says your request is impossible this quarter?” Trade-offs, scope reduction and a written decision — not escalation as a first move.',
    ],
  },
  {
    module: 10, topic: 'overview', emoji: '🔢', type: 'fact',
    title: 'Analyst-ready Vietnam tech numbers',
    front: 'Six clusters of numbers that make a tech answer sound researched rather than enthusiastic.',
    back: [
      'Top-four platform GMV 2025: VND429.7 trillion / about USD16.35 billion, +34.75% (Metric); YouNet ECI alternative USD17.43 billion, +26%; 3.94 billion items sold (+15.23%).',
      'Share: Shopee about 56% (from ~64% in 2024), TikTok Shop about 41% (from ~29%), together roughly 97% of platform GMV.',
      'FPT FY2025: revenue VND70,113 billion (+11.6%), PBT VND13,039 billion (+17.8%), global IT VND35,382 billion (+14.3%), Japan +25.4%, DX 47.3% of global IT revenue.',
      'Hardware: electronics and computer exports USD106 billion in 2025 (+46%); phones about USD57.6 billion; roughly 1.9 million tech workers and more than 7,000 chip-design engineers.',
      'AI and compute: an estimated 10,000-15,000 GPUs in country; over USD7 billion of announced AI data-centre investment; targets of 50,000 semiconductor personnel and about 5,000 AI specialists by 2030.',
      'Payments: more than 15 billion cashless transactions worth over VND190 quadrillion in H1 2026 (+34.28% by volume); over 89% of adults hold a payment account.',
    ],
  },
  {
    module: 10, topic: 'people-career', emoji: '🧩', type: 'concept',
    title: 'The five tech case archetypes',
    front: 'Recognise the archetype, then use its specific chain instead of a generic framework.',
    back: [
      'Grow a funnel: acquisition, activation, retention, revenue, referral — find the biggest drop-off, size the prize, propose one experiment with a guardrail metric.',
      'Fix unit economics: contribution margin per order or per user, then attack the largest variable cost — logistics subsidy, voucher, payment fee, support contact rate.',
      'Enter a new segment or market: demand evidence, willingness to pay, supply availability, regulatory constraint, and the cost of the first 1,000 customers.',
      'Build versus buy versus partner: common in fintech and AI cases where a licence, a dataset or GPU capacity is the real constraint.',
      'Monetise an installed base: pricing, packaging, ads, take rate — and the churn risk of charging for something previously free.',
    ],
    diagram: ['Diagnose funnel', 'Fix unit economics', 'Enter segment', 'Build / buy / partner', 'Monetise base'],
  },
  {
    module: 10, topic: 'people-career', emoji: '👀', type: 'fact',
    title: 'What tech interviewers are really scoring',
    front: 'The signal is not enthusiasm about technology — it is disciplined reasoning under uncertainty.',
    back: [
      'You define before you calculate: state the metric, its numerator and denominator, and the period. Ambiguity is scored as sloppiness.',
      'You separate correlation from causation, mentioning holdouts, cohorts and confounders without being asked.',
      'You think in trade-offs: every recommendation names what you give up — speed for reliability, growth for margin, personalisation for privacy.',
      'You are specific about Vietnam. “TikTok Shop grew to about 41% share while Shopee fell to 56%” beats “Vietnam’s e-commerce market is booming” every time.',
    ],
  },
  {
    module: 10, topic: 'people-career', emoji: '⏱️', type: 'concept',
    title: 'Your 60-second tech answer template',
    front: 'A repeatable structure for product, growth and strategy questions alike.',
    back: [
      'Step 1 — Name the user and the value moment: who, doing what, and when they first get value.',
      'Step 2 — Name the business model and the revenue event: commission, subscription, ad, fee or contract.',
      'Step 3 — Give the metric you would move and its baseline, or a defensible estimate.',
      'Step 4 — Give one experiment or intervention, with a guardrail metric you refuse to damage.',
      'Step 5 — Name the operational or regulatory constraint — fraud, moderation, data protection, licensing — that a naive plan would miss.',
    ],
    diagram: ['User & value moment', 'Model & revenue event', 'Metric baseline', 'Experiment + guardrail', 'Constraint'],
  },
];
