// Consulting & Professional Services — deep Vietnam-specific card pack (modules 6-10).
// Firm financials are FY2025 filings for the Vietnamese audit entities; frameworks are drilled for case use.

import type { DepthCard } from './industryDepthTypes';

export const CONSULTING_DEPTH_CARDS: DepthCard[] = [
  {
    module: 6, topic: 'overview', emoji: '💼', type: 'fact',
    title: 'The Vietnamese consulting market, by the numbers',
    front: 'The Big Four dominate professional services in Vietnam, and their published Vietnamese revenues are smaller than most candidates assume.',
    back: [
      'FY2025 filings for the audit entities: EY Vietnam about VND1,473.7 billion (+15.3%), PwC Vietnam about VND648 billion, Deloitte Vietnam about VND634 billion — EY leads on scale by roughly two times.',
      'Margins are thin: EY Vietnam’s reported post-tax profit was around VND24 billion on that revenue, with staff costs about 50% of revenue (Deloitte about 52.5%, PwC about 60.3%). Professional services is a people business with little cushion.',
      'Headcount context: Deloitte Vietnam reports more than 1,200 professionals across Hanoi and Ho Chi Minh City after 30-plus years in the market, as part of Deloitte Southeast Asia.',
      'Interview move: these numbers let you talk about leverage and utilisation concretely. A firm where salaries are 60% of revenue has a very different pricing problem from one at 50%.',
    ],
  },
  {
    module: 6, topic: 'overview', emoji: '🏢', type: 'fact',
    title: 'Who competes, and for what work',
    front: 'Four tiers compete in Vietnam, and they are not chasing the same projects.',
    back: [
      'Big Four (Deloitte, PwC, KPMG, EY): audit and assurance, tax and legal, deals and transaction services, risk, and technology-led consulting. Broadest client coverage, most structured graduate intake.',
      'Strategy houses (McKinsey, BCG, Bain and regional peers) maintain a Vietnam presence and staff from regional hubs for large corporate and government strategy work: market entry, growth strategy, operating-model design, digital transformation.',
      'Specialists and boutiques: local corporate-finance advisers, market-research firms, tech implementation partners, ESG and engineering consultancies. Smaller teams, faster responsibility, narrower brand.',
      'In-house consulting: banks, Viettel, FPT, Masan and Vingroup all run internal strategy or transformation teams that hire the same candidate profile — a route many students overlook.',
    ],
  },
  {
    module: 6, topic: 'finance', emoji: '💰', type: 'concept',
    title: 'How a consulting firm actually makes money',
    front: 'Consulting economics come down to three numbers: rate, utilisation and leverage. Everything else is commentary.',
    back: [
      'Rate: what the client pays per unit of senior time — set by perceived value, competition and the firm’s brand, not by cost.',
      'Utilisation: billable hours over available hours. Bench time is pure margin loss, which is why staffing calls are political.',
      'Leverage: the ratio of junior to senior staff on an engagement. A pyramid with more analysts per partner earns more — provided quality holds.',
      'Then subtract: salaries, bonuses, travel, subcontractors, knowledge tools and recruitment. Scope creep is the fourth silent margin killer on fixed-fee work.',
      'The compounding asset is reusable intellectual property — benchmarks, diagnostics, code and methods — because it raises value without adding hours.',
    ],
    diagram: ['Win the work', 'Set rate & scope', 'Staff the pyramid', 'Deliver & manage scope', 'Project margin'],
  },
  {
    module: 6, topic: 'marketing-sales', emoji: '🛒', type: 'fact',
    title: 'What Vietnamese clients actually buy',
    front: 'Demand in Vietnam is driven by regulation, foreign investment and capital-market development — not by strategy fashion.',
    back: [
      'Tax and transfer pricing: related-party transaction rules under Decree 132/2020 and its 2025 amendment, plus Vietnam’s adoption of the 15% global minimum tax (Resolution 107/2023/QH15) created durable advisory demand from multinationals.',
      'Accounting and reporting: the Ministry of Finance’s IFRS roadmap (Decision 345/QD-BTC) moves companies from Vietnamese accounting standards toward IFRS, a multi-year conversion programme for banks and large corporates.',
      'Deals and capital markets: FDI entry, M&A diligence, restructuring, and preparation for the FTSE Russell reclassification effective 21 September 2026 — which raises disclosure and governance expectations.',
      'Technology and ESG: core-system replacement, data and AI programmes under the national digital agenda, plus carbon and sustainability reporting for exporters facing the EU carbon border mechanism.',
    ],
  },
  {
    module: 6, topic: 'supply-chain', emoji: '📆', type: 'fact',
    title: 'Regulation and seasonality in professional services',
    front: 'Audit is a licensed profession in Vietnam, and that licensing shapes both the calendar and the career path.',
    back: [
      'The Ministry of Finance regulates audit practice and approves firms and practising auditors; independence rules restrict which non-audit services a firm may sell to an audit client, which is why cross-selling has limits.',
      'The qualification ladder matters: the Vietnamese CPA, and international qualifications such as ACCA or CFA, materially affect promotion timing and pay in audit, tax and financial advisory.',
      'Busy season is real: audit work concentrates from December to March around 31 December year ends, with long hours; consulting and deals work is lumpier and driven by client transactions.',
      'Interview move: acknowledge the workload honestly. Candidates who claim busy season is fine, without describing how they manage it, are less convincing than those who name a concrete strategy.',
    ],
  },
  {
    module: 6, topic: 'rnd-product', emoji: '🧬', type: 'concept',
    title: 'Service lines, decoded',
    front: 'Applying to “consulting” is not a plan. These are the lines you will actually choose between, and what the work feels like.',
    back: [
      'Audit and assurance: testing financial statements against standards. Structured, methodology-heavy, strong grounding in how businesses report, clear qualification path.',
      'Tax and legal: compliance plus planning — transfer pricing, incentives, cross-border structuring. Technical depth, long client relationships, less travel.',
      'Deals and transaction advisory: financial due diligence, valuation, commercial diligence, restructuring. Fast, deadline-driven, excellent for modelling skills.',
      'Management and technology consulting: operating model, growth strategy, cost transformation, system implementation. Broadest problem set, most stakeholder management.',
      'Risk and internal audit: controls, cyber, regulatory compliance, third-party risk. Underrated for career optionality inside banks and insurers.',
    ],
  },
  {
    module: 6, topic: 'finance', emoji: '🧮', type: 'quiz',
    title: 'Market check: firm economics',
    front: 'Firm A spends 50% of revenue on staff costs; Firm B spends 60%. Both have the same revenue. What is the most useful inference?',
    back: ['Firm B has less room for overheads, investment and profit, so it must either raise rates, increase leverage, or improve utilisation. Staff cost as a share of revenue is the core efficiency metric in professional services.'],
    options: [
      'Firm B pays better, so it must be more profitable',
      'Firm B has less margin room and must fix rate, leverage or utilisation',
      'Staff cost ratios say nothing about profitability',
      'Firm A must be smaller',
    ],
    answer: 1,
  },
  {
    module: 7, topic: 'people-career', emoji: '🗒️', type: 'role',
    title: 'What a first-year consultant or auditor really does',
    front: 'The honest version, because interviewers can tell instantly whether you know it.',
    back: [
      'Strategy or management consulting analyst: own one module of the problem — build the market model, run six expert interviews, clean the data, produce the exhibit, and present it in the internal review before it reaches the client.',
      'Deals analyst: rebuild a target’s revenue by customer and product, normalise earnings, chase management for data, and flag the three findings that could change the price.',
      'Audit associate: test transactions and balances, document evidence to a standard another professional can re-perform, and escalate exceptions rather than resolve them alone.',
      'Tax associate: prepare filings and transfer-pricing documentation, research a treaty or circular, and write the memo that a manager will challenge line by line.',
      'Common to all: version control, meeting notes, deadlines that do not move, and the habit of saying what you do not yet know.',
    ],
  },
  {
    module: 7, topic: 'finance', emoji: '📊', type: 'concept',
    title: 'The consulting KPI dictionary',
    front: 'Firms manage themselves with these numbers. Referencing them shows you understand the business you are joining.',
    back: [
      'Utilisation — billable hours over available hours; the individual and team efficiency metric.',
      'Realisation — fees actually collected against standard rates; discounts and write-offs show up here, not in utilisation.',
      'Leverage — junior-to-senior mix on an engagement; the main driver of project margin.',
      'Project margin — fee minus direct delivery cost; scope creep and rework destroy it fastest on fixed-fee work.',
      'Pipeline, win rate and repeat rate — the growth engine. In Vietnam, referrals and long client relationships matter more than cold pitching.',
    ],
  },
  {
    module: 7, topic: 'people-career', emoji: '🪜', type: 'concept',
    title: 'The career ladder and what changes at each rung',
    front: 'Promotion in professional services is a change of job, not just a change of title. Know what each level is actually paid for.',
    back: [
      'Analyst / associate: analysis quality and reliability. You are paid to produce correct work on time.',
      'Consultant / senior associate: module ownership and client-facing communication. You are paid to need less supervision.',
      'Manager: engagement delivery, team management, scope and margin. You are paid to make the project work without the partner in the room.',
      'Senior manager / principal: client relationships, proposals and practice building. You are paid to create work, not only deliver it.',
      'Partner / director: revenue ownership, risk and firm reputation. In Big Four audit and tax, professional licensing gates this rung.',
    ],
    diagram: ['Analyst', 'Consultant', 'Manager', 'Senior manager', 'Partner'],
  },
  {
    module: 7, topic: 'supply-chain', emoji: '🗃️', type: 'concept',
    title: 'How an engagement actually runs',
    front: 'Cases are set in a project. Knowing the mechanics lets you answer “how would you run this?” convincingly.',
    back: [
      'Scoping and proposal: problem statement, workstreams, deliverables, timeline, team, fee basis — and explicitly what is out of scope.',
      'Mobilisation: data request list, interview plan, steering-committee cadence, and a hypothesis map so the team knows what it is trying to prove or disprove.',
      'Delivery: parallel workstreams with weekly internal reviews; the storyline is drafted early and revised as evidence arrives, not written at the end.',
      'Client management: no surprises. Preview findings with the sponsor before the steering committee, so the meeting is a decision, not a debate.',
      'Close and impact: handover, owner and milestone list, and — if the firm is good — a measured outcome that becomes the credential for the next sale.',
    ],
  },
  {
    module: 7, topic: 'finance', emoji: '🪓', type: 'quiz',
    title: 'Operating check: the margin killer',
    front: 'A fixed-fee project adds two extra analyses at the client’s request without changing the fee. What has actually happened?',
    back: ['Delivery hours rose with no revenue, so project margin fell — the classic scope-creep loss. The correct response is a documented change request that either resets scope or resets fee.'],
    options: [
      'Utilisation improved, so the firm is better off',
      'Project margin fell; scope or fee must be formally reset',
      'The client will automatically pay more',
      'Nothing changes because the team is salaried',
    ],
    answer: 1,
  },
  {
    module: 8, topic: 'marketing-sales', emoji: '📈', type: 'fact',
    title: 'Why demand keeps growing: FDI and China-plus-one',
    front: 'Vietnam’s consulting market grows because companies keep arriving, expanding and restructuring — each of which is a project.',
    back: [
      'Disbursed FDI hit USD27.62 billion in 2025 with 82.8% going to manufacturing, so market-entry studies, site selection, licensing, tax structuring and supplier diligence are steady work.',
      'Domestic groups are the other half: Vingroup, Masan, Viettel, FPT, Hoa Phat and the banks buy strategy, operating-model and transformation work as they scale and diversify.',
      'Cross-border capital adds deal flow: joint ventures, minority stakes, divestments and restructuring — all of which need diligence, valuation and post-merger integration support.',
      'Interview move: when asked why you want Vietnamese consulting, cite this pipeline rather than “I like solving problems”. Demand backed by numbers is a better answer.',
    ],
  },
  {
    module: 8, topic: 'marketing-sales', emoji: '📜', type: 'fact',
    title: 'Regulation is the consulting growth engine',
    front: 'Three regulatory programmes are generating multi-year advisory work in Vietnam right now.',
    back: [
      'Global minimum tax: Vietnam applies the 15% minimum effective rate to in-scope multinational groups under Resolution 107/2023/QH15, forcing groups to remodel incentives that used to make Vietnam cheap.',
      'Transfer pricing: related-party rules under Decree 132/2020, amended in 2025, require benchmarking studies, local files and defence work — a specialist tax practice in its own right.',
      'IFRS conversion: the Ministry of Finance roadmap (Decision 345/QD-BTC) moves large corporates and banks from Vietnamese standards toward IFRS, a long programme touching systems, chart of accounts and staff training.',
      'Add carbon and sustainability reporting for exporters facing the EU carbon border mechanism from 2026, and personal-data compliance under the law effective 2026.',
    ],
  },
  {
    module: 8, topic: 'overview', emoji: '🌐', type: 'fact',
    title: 'Capital markets, governance and the FTSE upgrade',
    front: 'Vietnam’s reclassification to Secondary Emerging status from 21 September 2026 raises the bar for disclosure, and that creates advisory demand.',
    back: [
      'Phased inclusion into FTSE global indices runs from September 2026 into September 2027, with 117 Vietnamese stocks added at the first review — which brings foreign institutional scrutiny of reporting quality.',
      'Practical consequences for clients: English-language disclosure, IFRS-comparable numbers, board governance, related-party transparency and investor relations capability.',
      'This is where audit, deals and consulting overlap: better reporting requires systems, controls and people, not just a new template.',
      'For an interview: this is a strong example of a regulatory event with a commercial consequence — exactly the type of connection consulting interviewers reward.',
    ],
  },
  {
    module: 8, topic: 'rnd-product', emoji: '🤖', type: 'fact',
    title: 'AI is changing the delivery model, not the value',
    front: 'Consulting sells judgement plus leverage. AI compresses the leverage half, so firms are repricing what juniors do.',
    back: [
      'What AI absorbs first: document review, first-draft research, data cleaning, benchmark collection, testing sampling support, slide drafting — the classic analyst tasks.',
      'What it does not absorb: framing an ambiguous problem, interviewing a defensive executive, judging data quality, and getting a client to actually change behaviour.',
      'Consequence for candidates: firms increasingly hire for structured thinking, client presence and domain depth over speed at mechanical tasks — so your evidence should show judgement, not diligence alone.',
      'A strong interview line: “If a tool can produce the first draft, the value moves to knowing which question to ask and whether the answer is credible.”',
    ],
  },
  {
    module: 8, topic: 'marketing-sales', emoji: '🧲', type: 'quiz',
    title: 'Trend check: where the work comes from',
    front: 'Which pairing best explains durable consulting demand in Vietnam rather than a one-off spike?',
    back: ['Regulatory change plus foreign investment. Rules such as the global minimum tax, transfer pricing and IFRS conversion force multi-year programmes, while continued FDI keeps generating entry, expansion and diligence work.'],
    options: [
      'Marketing campaigns and brand refreshes',
      'Regulatory change (global minimum tax, transfer pricing, IFRS) plus sustained FDI inflows',
      'Falling salaries in the market',
      'Fewer companies needing advice',
    ],
    answer: 1,
  },
  {
    module: 9, topic: 'overview', emoji: '🟩', type: 'case',
    title: 'Deloitte Vietnam: the multidisciplinary platform',
    front: 'Deloitte has been in Vietnam for over 30 years and runs the broadest local service mix — audit, consulting, financial advisory, risk, and tax and legal.',
    back: [
      'Scale: more than 1,200 professionals across Hanoi and Ho Chi Minh City, inside Deloitte Southeast Asia’s 21-office network; the Vietnamese audit entity reported about VND634 billion of revenue.',
      'What that means for a graduate: real internal mobility between service lines, plus secondment and regional-project exposure through the Southeast Asia network.',
      'Programme signal: Deloitte’s graduate and internship pathways in Vietnam run structured campus cycles with case and behavioural rounds.',
      'The constraint to understand: audit independence rules limit which advisory services can be sold to an audit client, so “cross-sell everything” is not how the platform actually works.',
      'Interview question this unlocks: when does breadth create client value, and when does it create conflicts?',
    ],
  },
  {
    module: 9, topic: 'overview', emoji: '🟨', type: 'case',
    title: 'EY Vietnam: scale first, margin later',
    front: 'EY is the revenue leader among the Big Four in Vietnam, and its financials show a deliberate strategic choice.',
    back: [
      'FY2025 (year to 30 June 2025): revenue about VND1,473.7 billion, up 15.3% — more than double Deloitte or PwC Vietnam by revenue.',
      'The trade-off is visible: post-tax profit of roughly VND24 billion means a very thin net margin, with staff costs near 50% of revenue and other operating costs about 47.8%, well above peers.',
      'Read it as strategy: prioritising market share, brand and client coverage over short-term profit. That is a legitimate choice and an excellent thing to discuss in interview.',
      'The client base includes major listed and public-interest entities, which brings regulatory scrutiny and heavy quality control into daily work.',
      'Interview question this unlocks: if you were managing partner, would you defend the scale strategy or shift to margin — and which metric would decide it?',
    ],
  },
  {
    module: 9, topic: 'overview', emoji: '🟦', type: 'case',
    title: 'PwC and KPMG Vietnam: the specialist routes in',
    front: 'Same tier, but often the better entry point for one specific skill — deals, tax or risk.',
    back: [
      'PwC Vietnam reported about VND648 billion of revenue with staff costs around 60.3% of revenue — the most people-heavy structure of the three disclosed, which puts pressure on rate and utilisation.',
      'Both firms recruit heavily into Deals and Transaction Services (financial due diligence, valuation), Tax (transfer pricing, incentives, global minimum tax) and Risk and Technology consulting.',
      'Internships are the real front door: these firms advertise internships specifically into deals and due-diligence teams for final-year students, and conversion to graduate offers is common.',
      'Practical advice: pick the line where your evidence is strongest. Deals rewards modelling, tax rewards precise technical reading, consulting rewards structure and communication.',
      'Interview question this unlocks: why this service line rather than the firm’s other three?',
    ],
  },
  {
    module: 9, topic: 'overview', emoji: '🎯', type: 'case',
    title: 'McKinsey, BCG and Bain in the Vietnam context',
    front: 'Strategy houses run smaller Vietnamese teams that draw on regional expertise — which changes both the work and the hiring bar.',
    back: [
      'Typical work: national and sector growth strategy, market entry for multinationals, banking and consumer transformation, and operating-model redesign for the largest domestic groups.',
      'Staffing model: local teams supplemented by regional and global experts, so you may work with Singapore, Bangkok or Jakarta colleagues on a Vietnamese client problem.',
      'Hiring bar: case interviews with heavy numerical pressure plus firm-specific screens — McKinsey uses an assessment game and interviewer-led cases, while BCG and Bain lean candidate-led.',
      'Career reality: steep learning curve, strong exit optionality into private equity, corporate strategy and startups, and much smaller cohorts than the Big Four.',
      'Interview question this unlocks: how would you size the Vietnamese market for a product that does not exist here yet?',
    ],
  },
  {
    module: 9, topic: 'people-career', emoji: '📅', type: 'fact',
    title: 'Consulting recruitment: timeline and rounds',
    front: 'Professional-services recruiting in Vietnam is calendar-driven. Miss the autumn window and you usually wait a year.',
    back: [
      'Typical Big Four cycle: applications open around August to October, aptitude and technical tests within weeks, then a group case or assessment centre, then manager and partner interviews, with offers landing before busy season.',
      'Internships are the highest-conversion route, especially into audit, tax and deals — a summer or busy-season internship often decides the graduate offer.',
      'Strategy-house cycles run separately and often earlier, with online tests or assessment games before any human interview.',
      'Round-by-round: numerical and verbal tests (practise under time), a group case (contribute structure, not volume), a personal-experience interview, then cases with progressively senior interviewers.',
      'Prepare three things in advance: three sharp personal stories, one market-sizing drill you can run from memory, and a 60-second walk-through of your CV without notes.',
    ],
  },
  {
    module: 10, topic: 'rnd-product', emoji: '🌳', type: 'concept',
    title: 'MECE and issue trees, done properly',
    front: 'MECE means mutually exclusive, collectively exhaustive: no overlaps, no gaps. It is a test you apply to your own structure, not a phrase you say out loud.',
    back: [
      'Start from the decision, not the topic. “Should this bank enter SME lending?” produces a different tree from “why is SME profit falling?”',
      'Break the problem into three or four branches you can actually test with data, then prioritise: say which branch you would examine first and why.',
      'Good breaks in practice: by customer segment, by geography, by channel, by product, or by the arithmetic of the metric itself (price times volume).',
      'Bad trees overlap (“online” and “young customers”), leave gaps, or list everything at once. Interviewers notice both instantly.',
      'Finish each branch with a hypothesis: “I expect the loss is concentrated in provincial branches because acquisition cost is higher there — I would check cost per acquired account by region.”',
    ],
    diagram: ['Define the decision', 'Break into 3-4 branches', 'Test for overlaps & gaps', 'Prioritise one branch', 'State the hypothesis'],
  },
  {
    module: 10, topic: 'finance', emoji: '🌲', type: 'concept',
    title: 'The profitability tree you must be able to draw',
    front: 'Most cases are profit problems. This structure, drawn in ten seconds, is the backbone of a clean answer.',
    back: [
      'Profit = revenue minus cost. Revenue = volume times price, where volume breaks into market size times share, or customers times frequency times basket.',
      'Cost splits into variable (materials, delivery, commissions, payment fees) and fixed (rent, salaries, depreciation, marketing commitments).',
      'Diagnose by comparing periods or peers: is the fall in price, mix, volume, variable cost per unit, or fixed-cost absorption? Name the driver before recommending anything.',
      'Mix is the most commonly missed answer: total volume can be flat while a shift toward cheaper products cuts revenue and margin.',
      'Close the loop with the operating constraint — capacity, credit room, shelf space, headcount — because that is what stops a mathematically valid recommendation.',
    ],
    diagram: ['Profit', 'Revenue = volume x price', 'Volume = market x share', 'Cost = variable + fixed', 'Name the driver'],
  },
  {
    module: 10, topic: 'overview', emoji: '📏', type: 'concept',
    title: 'Market sizing with Vietnamese anchors',
    front: 'Sizing is scored on structure and stated assumptions, not on being right. Memorise a few Vietnam anchors so your numbers are defensible.',
    back: [
      'Anchors worth knowing: population about 101 million; roughly 28-29 million households at about 3.5 people each; GDP per capita in the region of USD5,000; total retail sales of goods and services about USD270 billion in 2025.',
      'Channel anchors: about 1.4 million traditional retail outlets and 8,300 markets; modern trade about 30% of retail sales; top-four e-commerce platform GMV about USD16.4 billion in 2025.',
      'Worked example — annual market for a VND50,000 specialty coffee in Ho Chi Minh City: about 9 million residents, say 35% are working adults who buy out-of-home coffee, of whom perhaps 30% buy the premium tier, at 2 purchases per week.',
      'That gives roughly 9m x 0.35 x 0.30 = about 950,000 buyers, times 2 per week times 52 weeks times VND50,000 = around VND4,900 billion a year. State it, then sanity-check it against known chain revenues.',
      'Always end with the sensitivity: “if premium penetration is 20% rather than 30%, the market is about a third smaller — that is the assumption I would validate first.”',
    ],
  },
  {
    module: 10, topic: 'rnd-product', emoji: '🧰', type: 'fact',
    title: 'The framework toolkit — and when not to use it',
    front: 'Frameworks are checklists for your own thinking. Reciting one without tailoring it is the fastest way to fail a case.',
    back: [
      'Porter’s Five Forces: industry attractiveness — rivalry, new entrants, substitutes, supplier power, buyer power. Use for entry and profit-pool questions, not for a single-company cost problem.',
      'BCG growth-share matrix: portfolio allocation across business units by growth and relative share. Useful when a group must choose where to invest, as with Vietnamese conglomerates.',
      '3Cs (customer, company, competitor) and 4Ps (product, price, place, promotion): quick coverage checks for commercial questions and launch cases.',
      'Value chain and SWOT: value chain locates where cost and margin sit; SWOT is weak alone and only useful as a summary once you have evidence.',
      'The senior move is a custom structure: two or three branches drawn from the specific question, then name the framework only if it genuinely fits.',
    ],
  },
  {
    module: 10, topic: 'people-career', emoji: '🎭', type: 'fact',
    title: 'Case interview formats by firm type',
    front: 'The same case skills are tested differently. Know which format you are walking into.',
    back: [
      'McKinsey style: interviewer-led. They drive the sequence, ask a structuring question, then a maths question, then an insight question. Answer precisely and follow their lead; an assessment game may screen before interviews.',
      'BCG and Bain style: candidate-led. You own the structure and pace, so you must ask for data, state hypotheses and synthesise as you go.',
      'Big Four style: often a group case or assessment centre plus a behavioural interview, testing collaboration and communication as much as analysis; technical rounds appear in deals and tax.',
      'Local firms and in-house strategy teams: shorter, more practical cases on the actual business — expect “how would you improve our margin?” with real numbers.',
      'Universal rules: repeat the question, take 60 to 90 seconds to structure, talk through your arithmetic, and end every section with a one-sentence “so what”.',
    ],
  },
  {
    module: 10, topic: 'people-career', emoji: '🎤', type: 'fact',
    title: 'Behavioural questions in Vietnamese consulting interviews',
    front: 'The personal-experience interview carries real weight, especially at Big Four and in final rounds. Prepare stories, not adjectives.',
    back: [
      '“Tell me about a time you led a team through a setback.” Give the situation in one sentence, your specific actions, the measurable result, and what you changed afterwards.',
      '“Describe a time you disagreed with someone more senior.” Show respect plus evidence — the point is that you raised it and how you framed it.',
      '“When did you have to deliver with incomplete information?” Consulting is this question every week; describe the assumption you made explicit and how you tested it.',
      '“Why consulting, and why our firm?” Name the service line, one piece of evidence about the firm (a service line, a client type, a published figure) and the skill you want to build.',
      'Prepare four stories that can be recycled across themes: leadership, conflict, failure and analytical impact. Rehearse them at 90 seconds each.',
    ],
  },
  {
    module: 10, topic: 'people-career', emoji: '⏱️', type: 'concept',
    title: 'The 60-second “walk me through your background”',
    front: 'This is the first question in most consulting interviews and the one candidates waste. Use a four-beat structure and stop talking on time.',
    back: [
      'Beat 1 (10 seconds) — Position: “I am a final-year Economics student at Foreign Trade University, focused on data-driven commercial problems.”',
      'Beat 2 (20 seconds) — Proof: one experience with a number. “In a retail internship I analysed 40 SKUs and proposed a range change that cut waste by 12% in the pilot store.”',
      'Beat 3 (15 seconds) — Pattern: what those experiences have in common — structuring messy problems, working with numbers, persuading people without authority.',
      'Beat 4 (15 seconds) — Purpose: why this firm and service line specifically, ending with a forward statement rather than a plea.',
      'Two rules: no chronology from high school, and never exceed 90 seconds. Interviewers read discipline as a proxy for how you will behave in front of a client.',
    ],
    diagram: ['Position', 'Proof with a number', 'Pattern', 'Purpose', 'Stop on time'],
  },
  {
    module: 10, topic: 'people-career', emoji: '👀', type: 'fact',
    title: 'What consulting interviewers are really scoring',
    front: 'Two candidates can reach the same answer and be graded very differently. These four behaviours decide it.',
    back: [
      'Structure before analysis: you state how you will approach the problem before touching any number.',
      'Numerical control: you talk through arithmetic out loud, round sensibly, and sanity-check the result against something known.',
      'Synthesis: after every chunk of analysis you say what it means for the decision — not what you calculated.',
      'Coachability: when the interviewer nudges you, you adjust visibly instead of defending your first structure. This is scored explicitly at most firms.',
    ],
  },
  {
    module: 10, topic: 'people-career', emoji: '🧠', type: 'quiz',
    title: 'Interview check: synthesis versus summary',
    front: 'Which statement is genuine synthesis?',
    back: ['“Profit fell because premium mix declined, so restore mix before cutting price” — it combines the evidence into an answer and an implication. Listing analyses or data sources is only a summary of activity.'],
    options: [
      'We built 14 exhibits and interviewed nine managers',
      'Profit fell because premium mix declined, so restore mix before cutting price',
      'Here are the three data sources we used',
      'The market is growing and competition is intense',
    ],
    answer: 1,
  },
];
