// Phase 2 deep-enrichment pack A — Banking, Technology, Retail and Industrial & Manufacturing.
// These cards fill the chapters the original packs under-served: the actual operating process
// end to end, the R&D / product side, the commercial engine, and the counterintuitive facts an
// interviewer uses to separate a candidate who has read a headline from one who has read the market.

import type { DepthCard } from './industryDepthTypes';

export const BANKING_PHASE2_CARDS: DepthCard[] = [
  {
    module: 7, topic: 'supply-chain', emoji: '🔎', type: 'concept',
    title: 'Inside a Vietnamese loan approval, end to end',
    front: 'Candidates say “the bank assesses risk”. Interviewers want the actual conveyor belt — who touches the file, which system it sits in, and where it stalls.',
    back: [
      'Origination: a relationship manager or the mobile app captures the application. Identity is verified through eKYC against the chip-based citizen ID, which is why account and small-loan onboarding moved off the branch counter.',
      'Credit bureau pull: every regulated lender queries the National Credit Information Centre (CIC) under the State Bank of Vietnam for existing exposure, group classification and repayment history. A CIC group-2 flag can stop a file before any human reads it.',
      'Scoring and underwriting: retail and small-ticket files run through a scorecard in a loan origination system and are auto-decided or referred; corporate files get spread financials, a credit memo and a committee. Collateral needs independent valuation and registration of the security interest.',
      'Disbursement and servicing: approved limits are booked into the core banking system (Temenos T24 at many private banks, Silverlake SIBS historically at several state banks), which then owns interest accrual, repayment schedules and loan classification.',
      'Monitoring and collection: early-warning triggers, day-past-due buckets and provisioning follow the SBV loan-classification groups 1 to 5. The MT project is almost always “why does this stage take eleven days”.',
    ],
    diagram: ['Apply & eKYC', 'CIC bureau pull', 'Score / underwrite', 'Approve & price', 'Disburse in core', 'Monitor & collect'],
    visual: [
      'RETAIL FILE          CORPORATE FILE',
      '  app / branch          RM + client visit',
      '  eKYC + CIC            CIC + spread financials',
      '  scorecard  ~mins      credit memo   ~days',
      '  auto-decide           credit committee',
      '  book in core          collateral registration',
      '  ------------------------------------------',
      '  hours to days         two to eight weeks',
    ],
  },
  {
    module: 8, topic: 'rnd-product', emoji: '🖥️', type: 'case',
    title: 'Core banking replacement: what a migration actually involves',
    front: 'The core banking system is the ledger every product, branch and app depends on. Replacing it is the largest, riskiest programme a Vietnamese bank ever runs — and a favourite interview topic because it exposes whether you understand banks as systems.',
    back: [
      'The Vietnamese vendor map: Temenos is the clear leader, with T24 / Transact running at Techcombank, Sacombank, MB, OCB, SeABank and SHB among others; Silverlake’s SIBS was historically the core at Vietcombank, BIDV and Maritime Bank; Oracle FLEXCUBE won newer mandates such as Kien Long Bank.',
      'A real path, not a slogan: Techcombank went Temenos GLOBUS (2003) to T24, and then selected Temenos T24 Transact R25 over Thought Machine and 10x for its cloud-native rebuild — choosing the incumbent because it already had a deep in-house Temenos engineering bench.',
      'Vietcombank went the other way and replaced Silverlake SIBS with a new core plus teller and channel platforms, which is the harder version: new data model, new interfaces, retrained staff, and a parallel-run period where both systems must reconcile to the dong.',
      'What the work actually is: chart-of-accounts and product-catalogue redesign, data migration and reconciliation, rebuilding hundreds of interfaces (cards, payments, treasury, reporting, regulatory returns), then a cutover weekend nobody forgets.',
      'Why it is slow: the core cannot be down, the regulator requires uninterrupted reporting, and any migration defect is a customer’s balance. Techcombank kept core banking and card management as the last systems outside the cloud precisely because they are the riskiest to move.',
      'Interview question this unlocks: how would you decide between upgrading your existing core and replacing it, and what evidence would change your answer?',
    ],
    visual: [
      'LEGACY CORE            MODERN CORE',
      ' monolith, batch    ->  modular, real-time',
      ' overnight cut-off  ->  24/7 processing',
      ' on-premise         ->  cloud / hybrid',
      ' custom spaghetti   ->  API + event driven',
      ' RISK: data migration, interface rebuild,',
      '       parallel run, cutover weekend',
    ],
  },
  {
    module: 7, topic: 'rnd-product', emoji: '🧪', type: 'concept',
    title: 'How a bank actually builds a product',
    front: 'Banks do not have an R&D lab, but they do have a product factory — and it is far more constrained than a consumer-goods launch.',
    back: [
      'Start with the economics, not the feature: a product owner models expected volume, funding cost, expected credit loss, capital consumption and fee income before a single screen is designed.',
      'Risk and compliance sign-off is a gate, not a review. Underwriting policy, AML screening, personal-data handling and conduct rules must be settled before build, because retro-fitting them means rebuilding.',
      'Build usually means configuration plus integration: new product codes in the core, pricing and fee tables, limits, statements, regulatory reporting fields, then the app or branch journey on top.',
      'Pilot and scale: a limited launch on selected branches or a customer segment, watched on activation, first-transaction rate, funnel drop-off and early delinquency — then a decision to widen, reprice or stop.',
      'The honest constraint to name in interview: a bank cannot A/B test a credit policy on real customers the way an app tests a button. Experimentation is bounded by fairness, disclosure and prudential rules.',
    ],
    diagram: ['Economics case', 'Risk & compliance gate', 'Configure core', 'Journey build', 'Pilot', 'Scale or stop'],
  },
  {
    module: 6, topic: 'finance', emoji: '📏', type: 'fact',
    title: 'NIM in Vietnam versus developed markets',
    front: 'Vietnamese sector net interest margin fell to about 2.9% in FY2025. Candidates who compare that with a US bank without adjusting look naive — the same number means different things in different systems.',
    back: [
      'Vietnamese banks earn spread in a high-nominal-rate, high-growth economy but give much of it back: credit cost is structurally higher, fee income is a smaller share of revenue, and policy-priority lending is priced administratively rather than commercially.',
      'Vietcombank is the clearest illustration — NIM only 2.7% in FY2025 because preferential-rate credit reached roughly VND800 trillion, close to half its loan book. Its margin is low by policy, not by weakness: NPL was about 0.6% and ROAE 15.3%.',
      'Developed-market banks run thinner gross spreads but on far cheaper and stickier funding, much lower credit cost, and a large fee and wealth franchise — so a 1.5% NIM can still produce a strong return on equity.',
      'The comparison that actually works is risk-adjusted spread: NIM minus credit cost, then cost-to-income, then return on equity. Techcombank at 3.9% NIM with 0.6% credit cost and Vietcombank at 2.7% with near-zero loss rates are two valid ways to reach a similar answer.',
      'Interview line worth memorising: “NIM is a gross number. Until you subtract credit cost and account for the funding mix, comparing it across markets tells you almost nothing.”',
    ],
    visual: [
      'GROSS NIM ->  minus credit cost  ->  RISK-ADJ.',
      ' Vietnam sector  ~2.9%   ~1.0-1.3%   ~1.6-1.9%',
      ' Techcombank      3.9%       0.6%        3.3%',
      ' Vietcombank      2.7%   very low       ~2.5%',
      ' Developed mkt  1.5-3.0%   0.1-0.4%   1.4-2.6%',
      ' + fee income share decides the rest',
    ],
  },
  {
    module: 7, topic: 'marketing-sales', emoji: '📣', type: 'fact',
    title: 'How a Vietnamese bank actually acquires customers',
    front: 'Retail banking growth in Vietnam is not won by advertising. It is won by owning a moment where money already changes hands.',
    back: [
      'Payroll mandates are the single best acquisition channel: sign a corporate’s salary account and you get a primary relationship, a predictable inflow and cheap current-account balances — which is why CASA campaigns target HR departments, not consumers.',
      'Merchant acquiring and QR acceptance work the same way from the other side: the bank sits in the merchant’s daily settlement, then cross-sells working capital, cards and payroll.',
      'Zero-fee transfers and free accounts are not generosity. They are a funding-cost strategy: the bank buys frequency and primacy, then monetises through spread on the balances that stay.',
      'Ecosystem and partnership distribution — developers, auto dealers, insurers, e-commerce platforms and telcos — puts the bank at the point of purchase where credit is actually needed.',
      'The metric that decides whether any of it worked: share of customers whose salary or main spending runs through the bank, not the number of accounts opened.',
    ],
  },
  {
    module: 7, topic: 'marketing-sales', emoji: '🏷️', type: 'concept',
    title: 'Pricing psychology in Vietnamese retail banking',
    front: 'Bank pricing is deliberately hard to compare — and knowing the standard mechanics stops you being fooled in a case.',
    back: [
      'Teaser rates: a low fixed mortgage or consumer-loan rate for the first six to twenty-four months, then a floating rate set as a reference rate plus a margin. The headline sells the loan; the margin earns the money.',
      'Zero-percent instalment on cards is funded by the merchant, not the bank — the merchant discount rate covers it. In a case, always ask who is actually paying for a free offer.',
      'Fee waivers conditional on behaviour (minimum balance, salary credit, card spend) turn a giveaway into a retention mechanism.',
      'Bundling deposits with investment or insurance products raises perceived value and blurs comparison — which is exactly why conduct regulation now restricts tying life insurance to credit.',
      'The candidate move that impresses: convert every offer to an effective annual cost or effective yield before judging it, and say out loud which assumption you had to make.',
    ],
  },
  {
    module: 8, topic: 'surprising', emoji: '🧊', type: 'fact',
    title: 'Reported NPLs versus the real picture',
    front: 'Vietnam’s sector NPL ratio has sat near 1.9%. Almost nobody outside the industry understands how much accounting sits between that number and reality — and this is one of the highest-value things you can know in a banking interview.',
    back: [
      'The ratio is a fraction, and in 2025 both parts moved in the bank’s favour: net write-offs rose to roughly 1.3% of average gross loans while the loan book itself grew about 19%. A bad loan removed from the numerator and a fast-growing denominator flatter the ratio without any borrower improving.',
      'Loan classification is rule-based across five groups by days past due, so restructured or rescheduled debt can sit outside the non-performing buckets while the underlying cash-flow problem is unresolved.',
      'Historically, debt sold to the Vietnam Asset Management Company came off the bank’s balance sheet in exchange for special bonds that were then provisioned over several years — recognising the loss slowly rather than avoiding it.',
      'The honest way to read asset quality: look at special-mention (group 2) formation, which fell to roughly 1.2% by end-2025 from about 1.9%; loan-loss coverage, which recovered to around 84% system-wide while Vietcombank held about 259%; and vintage curves by disbursement month.',
      'State versus private is a real gap and worth quoting carefully: Vietcombank reported roughly 0.6% NPL with about 259% coverage, while fast-growing retail and consumer-finance lenders carry visibly higher loss rates as the price of higher yield.',
    ],
    visual: [
      'WHY A FLAT NPL RATIO CAN HIDE STRESS',
      '  NPL% = bad loans / total loans',
      '         |             |',
      '  write-offs cut    fast lending',
      '  the numerator     grows the denominator',
      '  ---------------------------------------',
      '  Read instead: group-2 formation,',
      '  coverage ratio, vintage curves',
    ],
  },
  {
    module: 9, topic: 'surprising', emoji: '💡', type: 'fact',
    title: 'Five banking facts candidates consistently get wrong',
    front: 'Each of these reverses a common assumption. Using one correctly signals that you read the market rather than a careers page.',
    back: [
      'The largest securities firms in Vietnam are bank subsidiaries, not independents. TCBS, VPBankS and MBS sit inside Techcombank, VPBank and MB — so “bank versus capital markets” is often the same employer.',
      'Cheap deposits do not come from paying the highest rate. They come from payroll, merchant settlement and daily-use accounts — the banks with the best CASA ratios usually advertise rates least.',
      'Digital did not kill the branch, it changed its job. Over 95% of transactions run through digital channels at many banks while branches shifted to advice, complex lending and SME relationships.',
      'Fintechs are not licensed to lend. MoMo, VNPay and ZaloPay are payment intermediaries, so credit, deposits and insurance require a bank or insurer partner — a constraint candidates routinely miss when proposing “the wallet should offer loans”.',
      'A conduct rule can outrank a growth strategy. The 60-day ban on selling life insurance after loan disbursement cut bancassurance revenue about 39% in six months and rewrote fee-income plans across the sector.',
    ],
  },
];

export const TECH_PHASE2_CARDS: DepthCard[] = [
  {
    module: 6, topic: 'supply-chain', emoji: '📲', type: 'fact',
    title: 'Why one company is close to a fifth of Vietnam’s exports',
    front: 'Samsung’s Vietnamese complexes have accounted for roughly a fifth of national export value in recent years. Understanding why explains most of Vietnam’s industrial policy.',
    back: [
      'The mechanism is assembly accounting: a phone assembled in Bac Ninh counts its full export value at the border even though imported components make up most of that value. High gross exports, much thinner domestic value added.',
      'The scale is real regardless: Samsung is reported to produce around half its global smartphone output in Vietnam, and phones plus accessories exported about USD57.6 billion in 2025 inside a computers-and-electronics group worth USD106 billion.',
      'Why Samsung came and stayed: wage competitiveness at the time of entry, political stability, proximity to the Chinese component base, port access at Hai Phong, and incentives inside high-tech industrial parks.',
      'The strategic worry this creates: concentration. A single foreign group’s product cycle moves the national trade balance, which is precisely why localisation, supplier development and semiconductor back-end capability are policy priorities.',
      'Interview move: separate gross exports from domestic value added in your first sentence. It is the fastest way to sound like an economist rather than a headline reader.',
    ],
  },
  {
    module: 8, topic: 'supply-chain', emoji: '🧬', type: 'concept',
    title: 'Where Vietnam sits in the semiconductor value chain',
    front: 'The chip value chain has four stages and Vietnam competes in two of them. Saying which two is the single most credible thing you can do in a technology interview.',
    back: [
      'Design (EDA tools, IP, layout): Vietnam has more than 7,000 chip-design engineers, mostly in design-services centres for foreign principals rather than owning products — Marvell, Synopsys, Renesas and Ampere all run Vietnamese design teams.',
      'Fabrication (wafer manufacturing): essentially absent today. Viettel broke ground on Vietnam’s first plant at Hoa Lac targeting 32nm with trial production expected in 2028 — mature-node, not leading edge, and years away.',
      'Assembly, test and packaging (the back end): this is Vietnam’s actual position. Intel Products Vietnam runs a large assembly-and-test site, Amkor and Hana Micron built northern packaging plants, and Decision 1018/QD-TTg targets ten advanced test-and-packaging plants by 2030.',
      'Materials and equipment: thin. Substrates, chemicals and tooling are largely imported, which is where the supply-chain risk and the localisation opportunity both sit.',
      'The national target frames the ambition honestly: 50,000 semiconductor personnel by 2030, roughly 15,000 in design and 35,000 in manufacturing, packaging and testing — the split itself tells you where the country expects to compete.',
    ],
    visual: [
      'CHIP VALUE CHAIN        VIETNAM TODAY',
      ' 1 Design / IP       ->  growing (services)',
      ' 2 Wafer fab         ->  none (32nm ~2028)',
      ' 3 Assembly/Test/Pkg ->  STRONG, expanding',
      ' 4 Materials & tools ->  mostly imported',
      ' ---------------------------------------',
      ' Value captured rises 4 < 3 < 1 < 2',
    ],
  },
  {
    module: 7, topic: 'rnd-product', emoji: '🛠️', type: 'role',
    title: 'What MTs at FPT, VNG and MoMo actually rotate through',
    front: 'These three are the most-asked-about Vietnamese tech employers, and their graduate work is genuinely different. Naming the difference shows you researched rather than applied everywhere.',
    back: [
      'FPT: delivery-first. Rotations run through software delivery for an overseas client (often Japanese), business analysis, quality engineering and increasingly data and AI. The differentiator that gets you promoted is domain depth — banking, healthcare, automotive — plus language capability, since Japan grew 25.4% in FY2025 and is the anchor market.',
      'VNG: product and platform. Rotations cover games publishing and live operations, Zalo product and growth, cloud and enterprise services, and data. Because each unit carries its own P&L, a graduate proposal competes against other units for investment, not just against the status quo.',
      'MoMo: closest to startup work. Narrow ownership from week one across merchant and partner business development, financial-services distribution, growth and CRM, risk and fraud, and data analytics — with product metrics visible daily.',
      'What all three test at interview: whether you can define a metric precisely, read a funnel, and say what you would check before committing. A documented project with a measured outcome beats a longer CV.',
      'Cross-apply deliberately: bank technology streams hire the same profile. Techcombank Future Gen runs Technology and Data & AI tracks, and VPBank Young Talents targeted AI/ML and data-science majors.',
    ],
  },
  {
    module: 7, topic: 'rnd-product', emoji: '🚢', type: 'concept',
    title: 'How a Vietnamese product team actually ships',
    front: 'The word “agile” tells an interviewer nothing. The sequence below tells them you have been in the room.',
    back: [
      'Discovery: support tickets, session recordings, funnel data and five customer conversations — ending in a written problem statement and the one metric a release must move.',
      'Definition: a spec that names the user, the value moment, the success metric with a baseline, the guardrail metric you refuse to damage, and explicitly what is out of scope.',
      'Build: a squad owning one surface or funnel step, working in short cycles with design and engineering, plus a compliance review whenever payments, credit or personal data are touched.',
      'Release and measure: staged rollout with a holdout group so you measure incrementality rather than attributed clicks, then a written decision — scale, iterate or kill.',
      'The Vietnam-specific constraint to name: the Personal Data Protection Law effective from 2026 adds consent and purpose-limitation duties that hit personalisation, recommendation and marketing data directly.',
    ],
    diagram: ['Discover', 'Define & spec', 'Build in squad', 'Staged release', 'Measure vs holdout', 'Scale or kill'],
  },
  {
    module: 8, topic: 'finance', emoji: '💸', type: 'concept',
    title: 'The unit economics of one e-commerce order',
    front: 'Almost every Vietnamese tech case eventually becomes this arithmetic. Build it bottom-up and you will never be caught celebrating unprofitable growth.',
    back: [
      'Platform revenue per order is commission (take rate) plus advertising plus fulfilment and payment fees — not the basket value. A VND100,000 basket at a 4% take rate earns the platform VND4,000 before ads.',
      'Then subtract the real costs: payment processing, logistics subsidy on “free shipping”, voucher and coupon funding, customer-service contact cost, and returns and refunds.',
      'What remains is contribution margin per order. If it is negative, every additional order makes the loss bigger — which is why fee increases and the shift toward larger, professionalised sellers defined 2025.',
      'For a seller the mirror-image stack applies: product cost, platform commission, ad spend, creator commission on content-led channels, shipping and the return rate — which is why the same product needs different pricing on Shopee and TikTok Shop.',
      'The diagnostic question to ask before scaling anything: at what basket size does this order become contribution-positive, and what share of orders clears that line today?',
    ],
    visual: [
      'ONE ORDER (illustrative, VND)',
      '  Basket value            100,000',
      '  Commission @4%            4,000  <- platform rev',
      '  Ad revenue                1,500',
      '  ------------------------------',
      '  Revenue                   5,500',
      '  Payment fee                (900)',
      '  Shipping subsidy         (3,000)',
      '  Voucher funding          (1,200)',
      '  Support + returns          (700)',
      '  ==============================',
      '  Contribution              (300)  <- scale = worse',
    ],
  },
  {
    module: 8, topic: 'marketing-sales', emoji: '🎥', type: 'fact',
    title: 'Livestream commerce: the economics behind the boom',
    front: 'TikTok Shop went from roughly 29% to about 41% of Vietnamese platform GMV in a single year on content-led selling. The mechanics are specific, and most candidates describe them wrongly.',
    back: [
      'The demand does not start as a search. Short-form video and livestream create the intent, so merchandising, creator selection and content volume replace keyword bidding as the growth lever.',
      'The cost structure is different too: creator and affiliate commissions, studio and host time, sample cost and heavy discounting during a session — against Shopee’s model of paying for high-intent traffic through ads.',
      'Session economics are what an operator actually manages: viewers, conversion rate, average order value, GMV per streaming hour, and the return rate afterwards, which is materially higher on impulse-driven sessions.',
      'The durable question is retention. A livestream buyer acquired at a deep discount is not the same asset as a repeat searcher — check 30-day repeat purchase by cohort before calling the growth real.',
      'Practical implication for a brand plan: split budget by intent. Search-led platforms defend existing demand; content-led platforms create new demand but need continuous content investment to hold share.',
    ],
  },
  {
    module: 7, topic: 'marketing-sales', emoji: '🧲', type: 'concept',
    title: 'Growth channels and what CAC really means here',
    front: 'Vietnamese consumer tech is cheap to reach and expensive to keep. Knowing which channel does what protects you from the classic “scale the 5x ROAS campaign” trap.',
    back: [
      'Owned and organic: Zalo as the default messaging surface, app push, SEO and community. Low marginal cost, slow to build, and the only channel that compounds.',
      'Paid performance: platform ads, affiliate and creator commissions. Fast, measurable, and systematically over-credited by last-click attribution — which is why holdout groups matter more than dashboards.',
      'Partnership and embedded distribution: banks, telcos, wallets, e-commerce platforms and device makers. Lower acquisition cost per user but revenue is shared and the partner shapes the product.',
      'Incentives and vouchers: these buy transactions, not habit. The honest test is whether the cohort returns after the subsidy stops, measured at 30, 60 and 90 days.',
      'The number that settles arguments: CAC payback in months, calculated on contribution margin rather than revenue, cohort by cohort.',
    ],
  },
  {
    module: 9, topic: 'surprising', emoji: '🤯', type: 'fact',
    title: 'Six Vietnamese tech facts that surprise people',
    front: 'Each of these contradicts an assumption most candidates walk in with.',
    back: [
      'Japan, not the United States, drives Vietnam’s IT services growth. FPT’s Japanese business grew 25.4% in FY2025, powered by client digital transformation and an ageing Japanese engineering workforce.',
      'Shopee is losing share while growing. It fell from about 64% to 56.04% of platform GMV in 2025 on roughly 6% growth, because TikTok Shop grew about 93%. Growth and share can move in opposite directions.',
      'Compute, not talent, is Vietnam’s AI bottleneck. Estimates put the country at 10,000-15,000 GPUs against roughly 50,000-60,000 in South Korea — which is why over USD7 billion of AI data-centre investment has been announced.',
      'The platform, not the seller, now collects the tax. Since 1 July 2025, Decree 117/2025/ND-CP makes marketplaces withhold VAT and personal income tax at transaction confirmation for household and individual sellers.',
      'Vietnam’s biggest “tech” export is physical. Computers, electronics and components exported USD106 billion in 2025, up about 46% — the first single export group above USD100 billion, and far larger than all software services.',
      'FPT’s reported revenue will fall in FY2026 without the business shrinking, because FPT Telecom moves to equity-method accounting. Always ask whether a change is economic or accounting.',
    ],
  },
];

export const RETAIL_PHASE2_CARDS: DepthCard[] = [
  {
    module: 7, topic: 'supply-chain', emoji: '🗺️', type: 'concept',
    title: 'How category management actually works at a large retailer',
    front: 'Central Retail, AEON and the domestic chains all run the same core discipline. This is what a category manager physically does over a review cycle — the level of detail an interviewer is testing for.',
    back: [
      'Define the category role first: traffic builder, profit generator, basket filler, or seasonal destination. The role decides price stance, promotion depth and how much space the category can justify.',
      'Ranging: build the assortment from the shopper decision hierarchy — whether the shopper picks brand first, then size, then flavour, or some other order — then set a range that covers each decision node without duplicating it. Every listing must displace something.',
      'Space allocation: space is granted in proportion to sales and margin contribution, adjusted for rate of sale so a fast SKU does not sell out mid-day. This is capital allocation measured in centimetres of shelf.',
      'Planogram: destination SKUs at eye level, blocks arranged the way shoppers scan the fixture, entry-price and private label positioned to defend the low end, impulse lines at the till and aisle ends.',
      'Review and negotiate: quarterly range review with a delisting decision, then the joint business plan with suppliers covering terms, promotional calendar, listing support and in-store activity. A review with no removals is not a review.',
    ],
    visual: [
      'CATEGORY REVIEW CYCLE',
      '  1 Role      traffic / profit / basket / seasonal',
      '  2 Range     decision hierarchy -> SKU list',
      '  3 Space     sales + margin + rate of sale',
      '  4 Planogram eye level = destination SKUs',
      '  5 Price     entry / mainstream / premium ladder',
      '  6 Promo     mechanic + funding + calendar',
      '  7 Review    delist the bottom, measure the swap',
    ],
  },
  {
    module: 8, topic: 'rnd-product', emoji: '🧾', type: 'concept',
    title: 'How a private-label product actually gets made',
    front: 'Private label is the biggest structural margin lever in Vietnamese retail, and it is a product-development job, not a pricing job.',
    back: [
      'Opportunity: find a category where the branded price gap is wide, quality is not a strong differentiator, and rate of sale is high enough to fund a production run.',
      'Specification: write the product brief — formulation or ingredient spec, pack size, shelf life, packaging format and the branded benchmark it must match on blind test.',
      'Sourcing: tender to co-manufacturers, audit their plants for food-safety and quality systems, negotiate cost per unit at a committed volume, and agree minimum order quantities that the retailer must then actually sell.',
      'Quality and compliance: labelling, origin, nutrition claims, food-safety certification and traceability sit with the retailer now, because the retailer is the brand owner. This is the risk most candidates forget.',
      'Launch and prove: shelf position next to the branded benchmark, an honest price gap, and a repeat-purchase target. Private label only works if the second purchase happens — a first purchase is just a price experiment.',
    ],
    diagram: ['Spot the gap', 'Write the spec', 'Tender & audit', 'Quality sign-off', 'List & price', 'Measure repeat'],
  },
  {
    module: 7, topic: 'rnd-product', emoji: '🧊', type: 'fact',
    title: 'Fresh food: the operation that decides grocery profit',
    front: 'Fresh brings shoppers in daily and destroys margin faster than any other category. In Vietnamese minimart grocery it is the whole game.',
    back: [
      'The cold chain has to hold end to end: field or farm pre-cooling, refrigerated transport, distribution-centre chill and freeze rooms, store back-of-house, then the display case. One weak link shortens shelf life everywhere downstream.',
      'Ordering is the real skill: fresh is ordered daily against a forecast at store-SKU level, and both errors are expensive — too little loses the trip, too much becomes markdown then waste.',
      'Shrink has several sources that need different fixes: expiry, damage and handling, weighing and pricing error, and theft. Attacking “shrink” as one number is why most improvement projects fail.',
      'The standard MT project: find the ten SKUs driving most fresh waste, diagnose whether it is order quantity, delivery frequency, display size or price ladder, and quantify the saving per store per week.',
      'Why it matters competitively: wet markets still win on freshness perception, so modern trade competes on hygiene, consistency, traceability and comfort — all of which are operational, not marketing, promises.',
    ],
  },
  {
    module: 6, topic: 'finance', emoji: '📉', type: 'fact',
    title: 'Typical retail gross margin by category in Vietnam',
    front: 'A grocery retailer does not have “a” margin. Knowing the shape of the ladder lets you diagnose a mix problem in seconds.',
    back: [
      'Fresh produce, meat and fish carry the highest headline gross margin but the highest waste and handling cost, so net contribution is far lower than the gross number suggests. This is the classic trap in a retail case.',
      'Packaged food and beverages sit in the middle on margin and are the volume backbone — heavily promoted, heavily supplier-funded, and where trade terms and listing income matter most.',
      'Household and personal care are usually the best real margin per unit of shelf: shelf-stable, high value density, no waste, and receptive to private label.',
      'Tobacco, top-up cards, gift cards and bill payment run on very thin margin and exist for footfall and basket completion, not profit. A store with a heavy mix here will look weak on gross margin and be fine on traffic.',
      'The number that actually matters is gross margin return on inventory investment — margin multiplied by turns. A 15% margin turning twenty times a year beats a 35% margin turning three times.',
    ],
    visual: [
      'GROSS MARGIN LADDER   (typical direction)',
      '  Fresh produce/meat   highest %  | high waste',
      '  Household & PC       high %     | best net',
      '  Packaged food        mid %      | volume base',
      '  Beverages            mid %      | promo heavy',
      '  Tobacco / top-up     lowest %   | traffic only',
      '  -------------------------------------------',
      '  Judge on GMROI = margin x inventory turns',
    ],
  },
  {
    module: 7, topic: 'marketing-sales', emoji: '🏷️', type: 'concept',
    title: 'Price architecture and promotion mechanics',
    front: 'Retail pricing is a structure, not a list. Once you can describe the ladder and the mechanics, most pricing cases become straightforward.',
    back: [
      'The price ladder has three rungs: an entry tier that defends against cheaper competition, a mainstream tier that carries volume, and a premium tier that lifts mix. Private label usually anchors the entry rung.',
      'Known-value items are the SKUs shoppers actually remember the price of — rice, cooking oil, instant noodles, milk, eggs. Price perception for the whole store is set by a few dozen of them, so they are priced sharply and margin is recovered elsewhere.',
      'Mechanics behave differently: straight price-off drives trial and is easy to compare; multibuy raises basket size but pulls forward demand; gift-with-purchase protects the price point; loyalty-member pricing identifies the shopper, which is worth more than the discount.',
      'Funding matters as much as depth. A supplier-funded promotion costs the retailer nothing in margin but commits shelf and space; a retailer-funded one must earn its return in incremental units, not total units.',
      'The discipline that separates a good answer: always ask what share of promoted volume was incremental rather than volume that would have sold anyway.',
    ],
  },
  {
    module: 8, topic: 'marketing-sales', emoji: '📱', type: 'fact',
    title: 'Loyalty, retail media and the shopper-data business',
    front: 'The fastest-growing profit line in modern retail is not selling groceries. It is selling access to the shopper.',
    back: [
      'Loyalty programmes exist to attach a purchase to an identity. Once you know who bought what and how often, you can measure incrementality, personalise offers, and prove reach to a supplier.',
      'Retail media turns that data and the store itself into advertising inventory: sponsored placements in the app, screens in store, aisle ends and targeted offers — high margin because the cost base already exists.',
      'Supplier income is the older version of the same idea: listing fees, promotional allowances and joint business plans, which is why category managers negotiate terms as hard as they negotiate cost price.',
      'The constraint that is now commercial, not just legal: the Personal Data Protection Law effective from 2026 adds consent and purpose-limitation duties that directly govern how loyalty and CRM data can be used.',
      'The risk to name when you recommend it: over-selling placement degrades the assortment shoppers came for. Retail media revenue rises while trust falls, and trust is what brought the traffic.',
    ],
  },
  {
    module: 9, topic: 'surprising', emoji: '🏪', type: 'fact',
    title: 'Why Vietnamese convenience stores still lose money',
    front: 'Convenience chains have grown in Vietnam for a decade and most of them still do not make a profit — while the same format is a cash machine in Thailand. This is one of the best-value facts in Vietnamese retail.',
    back: [
      'The scoreboard (Nielsen Vietnam, end-2023, by revenue share): Circle K about 48%, FamilyMart 18.8%, Ministop 14.3%, 7-Eleven 7.3% — the segment is dominated by foreign chains.',
      'The losses are documented: in 2023 GS25 lost about USD4 million (improved from USD6.7 million in 2022), 7-Eleven lost over USD4 million, Ministop about USD2 million and FamilyMart around USD0.4 million. Circle K is the notable exception, clearing accumulated losses in 2022 on about USD160 million of revenue.',
      'Ambitions have been cut to match: GS25 revised its target to roughly 500 stores by 2025 and 700 by 2027 — about 28% of its original plan — despite a USD20 million IFC investment.',
      'Why Thailand works and Vietnam does not, structurally: CP All runs 7-Eleven at a scale of many thousands of stores with its own distribution, food manufacturing and ready-meal supply chain. Density plus owned supply turns fixed cost into advantage.',
      'Vietnam’s specific drags: high urban rent against a small basket, a fresh-and-cheap street-food and wet-market culture that competes directly with ready meals, a lower average transaction value, and too few stores per distribution centre to spread logistics cost.',
      'The case answer this unlocks: convenience is a density business. Until stores per catchment and own-supply ready food reach a threshold, adding outlets multiplies losses rather than amortising them.',
    ],
    visual: [
      'CONVENIENCE UNIT ECONOMICS',
      '  small basket  x  high trip frequency',
      '        - urban rent per sqm',
      '        - 24/7 labour (3 shifts)',
      '        - low stores per DC = high logistics',
      '        - street food substitutes ready meals',
      '  =====================================',
      '  Profit needs: density + own food supply',
      '  Thailand (CP All): thousands of stores,',
      '  owned manufacturing -> fixed cost = moat',
    ],
  },
  {
    module: 9, topic: 'surprising', emoji: '🤔', type: 'fact',
    title: 'Five retail facts that surprise candidates',
    front: 'Retail is the industry where confident assumptions are most often wrong. Each of these reverses one.',
    back: [
      'Foreign retailers are not taking over. Domestic operators hold about 81% of modern retail stores in Vietnam — WinCommerce, Bach Hoa Xanh and Saigon Co.op are the scale players, not the foreign groups.',
      'The growth frontier is rural, not urban. About 70% of WinCommerce’s roughly 800 openings in 2025 were rural, and Bach Hoa Xanh concentrated its roughly 400 new stores in central Vietnam and the Central Highlands.',
      'Modern trade is still the minority channel. It is around 30% of retail sales, so a national plan that assumes supermarket distribution overstates addressable demand by a wide margin.',
      'Online grocery frequently loses money per order. A VND300,000 basket at 22% margin earns VND66,000 against roughly VND90,000 of picking, packing and delivery cost — negative before any overhead.',
      'Land-grab retail turned profitable only after it stopped growing fastest. WinCommerce reported like-for-like growth around 10.6% and roughly VND243 billion of nine-month 2025 net profit after years of losses, and Bach Hoa Xanh about VND255 billion — both after deliberately fixing store economics first.',
    ],
  },
];

export const MANUFACTURING_PHASE2_CARDS: DepthCard[] = [
  {
    module: 7, topic: 'supply-chain', emoji: '🎌', type: 'concept',
    title: 'The Toyota Production System inside a Vietnamese factory',
    front: 'Kanban, andon and kaizen get named in every operations interview and understood in very few. Here is what each one physically looks like on a Vietnamese line — and where it usually breaks.',
    back: [
      'Kanban is a pull signal, not a scheduling app: a card or empty bin authorises the upstream step to make exactly what was consumed. It caps work in progress by design, so inventory cannot quietly build between stations. It fails when supplier lead times are long and unreliable, which is common where tier-two parts are imported — so Vietnamese plants often run kanban internally and forecast-push externally.',
      'Andon is the right to stop: any operator can signal an abnormality and halt the line. Culturally this is the hardest element to transplant, because stopping production to report your own problem requires a supervisor who thanks you rather than blames you. Where andon exists on paper but nobody pulls it, the system is decoration.',
      'Kaizen is small, continuous, operator-led improvement with a measured before-and-after — not an annual consultant project. It works where standard work exists, because without a standard there is nothing to improve against, only opinions.',
      'Heijunka (level scheduling) is the piece most often skipped and the reason the rest fails: if the plan swings wildly week to week, pull systems and stable takt time cannot survive. Tet shutdowns and export order lumpiness make levelling genuinely hard here.',
      'Where it does work: Japanese and Korean FDI plants and their tier-one suppliers run these systems seriously, with a parallel reporting line to a regional technical function that owns the standards. That is also where a graduate learns them properly.',
      'The interview line that lands: “I would not launch a lean programme. I would find the largest measured loss, then use whichever tool fits it — and I would fix scheduling stability before installing kanban.”',
    ],
    visual: [
      'PUSH (forecast)        PULL (kanban)',
      '  plan -> make -> hope   consume -> signal -> make',
      '  WIP piles up           WIP is capped by cards',
      '',
      'THE STACK THAT MAKES IT WORK',
      '  4 Kaizen      continuous improvement',
      '  3 Andon       stop-and-fix authority',
      '  2 Kanban      pull / WIP cap',
      '  1 Heijunka + standard work   <- foundation',
      '  Skip level 1 and levels 2-4 collapse',
    ],
  },
  {
    module: 8, topic: 'supply-chain', emoji: '🚚', type: 'fact',
    title: 'China-plus-one: what is actually moving, and what is not',
    front: 'The relocation story is usually told as “factories are leaving China for Vietnam”. The accurate version is far more selective — and being specific here is an easy way to outperform other candidates.',
    back: [
      'What has moved: final assembly of electronics and consumer devices, garments and footwear, furniture, and increasingly semiconductor back-end assembly, test and packaging. These are labour-intensive or logistics-sensitive stages where relocation is technically straightforward.',
      'What has partly moved: tier-one component supply following anchor customers, plus some machinery and electrical-equipment production — visible in 2025 FDI, with metal fabrication taking about USD1.2 billion across 181 projects and electronics about USD1.5 billion across 148.',
      'What has NOT moved: deep tier-two and tier-three component ecosystems, precision materials and chemicals, advanced tooling, and leading-edge wafer fabrication. Vietnam still imports most of what its factories convert, which is why headline exports outrun domestic value added.',
      'The binding constraints are physical and human, not political: engineering talent depth, power reliability at scale, logistics costs of roughly 16-20% of GDP, and a supplier base that thins quickly below tier one.',
      'Wage arbitrage is no longer the story. Vietnam competes on reliability, workforce scale, trade agreements (CPTPP, EVFTA, RCEP, UKVFTA) and proximity to the Chinese component base — saying that instead of “cheap labour” is the credible framing.',
    ],
    visual: [
      'MOVED       PARTLY MOVED     NOT MOVING',
      ' assembly     tier-1 parts     tier-2/3 base',
      ' garments     machinery        materials/chem',
      ' footwear     electrical eq.   precision tools',
      ' furniture    packaging/test   leading-edge fab',
      ' ------------------------------------------',
      ' Rule: the more specialised the input,',
      '       the stickier it is to its origin',
    ],
  },
  {
    module: 7, topic: 'rnd-product', emoji: '📐', type: 'concept',
    title: 'How a new product gets industrialised',
    front: 'Designing a product and being able to make it 40,000 times a week are different problems. New product introduction is the bridge, and it is where graduate engineers actually work.',
    back: [
      'Design for manufacture: engineering reviews the design for tolerances, part count, assembly sequence and test access before tooling is cut. A change here costs a drawing revision; the same change after tooling costs a tool.',
      'Tooling, fixtures and process design: moulds, jigs, test rigs and the line layout are built and proven, with cycle time balanced against takt time so no station becomes a bottleneck at volume.',
      'Pilot and validation runs: small builds that prove the process is capable and repeatable, not just that one good unit can be made. This is where first-pass yield gets measured honestly for the first time.',
      'Qualification and sign-off: process capability studies, control plans, supplier part approval and customer approval — in automotive this is formalised as PPAP, in food and pharma as validation against HACCP or GMP.',
      'Ramp: volume climbs while yield is still stabilising, which is why new-model ramp-ups concentrate quality problems and overtime. Planning for the ramp curve rather than the steady state is the mark of an experienced answer.',
    ],
    diagram: ['Design for manufacture', 'Tooling & line', 'Pilot build', 'Capability & sign-off', 'Ramp to volume'],
  },
  {
    module: 7, topic: 'rnd-product', emoji: '🔬', type: 'fact',
    title: 'The quality systems Vietnamese plants actually run on',
    front: 'Quality is a management system with names and audits, not an attitude. Naming the right standard for the right sector is instant credibility.',
    back: [
      'ISO 9001 is the baseline quality-management system almost every exporting plant holds; ISO 14001 covers environmental management and is increasingly demanded by brand customers.',
      'Sector-specific standards matter more: IATF 16949 for automotive, GMP and HACCP plus ISO 22000 for food and beverage, and cleanroom plus statistical process control discipline for electronics and semiconductor back-end work.',
      'Statistical process control is the daily practical tool: control charts distinguish normal variation from a real shift, so you fix the process rather than react to every data point.',
      'Problem solving is standardised too — 8D, five-why and A3 — because a customer complaint requires containment first, then root cause, then a permanent corrective action and a control that prevents recurrence.',
      'Customer audits are the real enforcement mechanism. Brand customers audit energy, water, waste, chemical compliance and labour standards, and failing an audit can cost an order faster than a price increase.',
    ],
  },
  {
    module: 8, topic: 'finance', emoji: '🏦', type: 'concept',
    title: 'Capex versus opex in a factory investment case',
    front: 'Industrial MTs are asked to justify spending money. The split between capital and operating expenditure decides how the decision is made, who approves it, and what evidence you need.',
    back: [
      'Capital expenditure buys capacity or capability that lasts years: machines, tooling, automation cells, buildings, utilities. It is depreciated over the asset life, consumes cash up front, and is approved against payback, net present value or internal rate of return.',
      'Operating expenditure is the cost of running what you already have: labour, materials, energy, maintenance, consumables, subcontracting. It hits profit immediately and is judged against budget rather than a hurdle rate.',
      'The classic trade-off: automating a packing line is capex that reduces labour opex. The case must compare capital cost plus maintenance against labour saved, quality improvement and capacity released — and state the payback period honestly.',
      'The order to test options in: exhaust debottlenecking, changeover reduction and scheduling improvements first, because they are opex or free. Only recommend capex when the constraint survives those.',
      'The caution that impresses an operations interviewer: automating an unstable process locks the instability in permanently. Standardise first, then automate.',
    ],
    visual: [
      'CAPEX                     OPEX',
      '  machine, tooling         labour, materials',
      '  building, utilities      energy, maintenance',
      '  cash out now             hits P&L monthly',
      '  depreciated over life    expensed in period',
      '  judged on payback/NPV    judged vs budget',
      '  ------------------------------------------',
      '  Test order: debottleneck -> changeover ->',
      '              scheduling  -> THEN capex',
    ],
  },
  {
    module: 8, topic: 'marketing-sales', emoji: '🤝', type: 'fact',
    title: 'How a Vietnamese manufacturer actually wins work',
    front: 'Most Vietnamese industrial companies sell to a handful of large business customers, not to consumers. The sales process is an audit, not a campaign.',
    back: [
      'It starts with qualification: the customer audits the plant on quality systems, capacity, financial stability, environmental and labour compliance, and business continuity before pricing is even discussed.',
      'Then the request for quotation: the customer supplies drawings, specifications and volume forecasts, and the manufacturer returns a piece price, tooling cost and lead time. Costing accuracy here decides whether the contract is profitable for years.',
      'Samples and validation follow: first-article inspection, capability studies and customer approval. Only after sign-off does serial production start, which is why winning a new customer takes months and losing one takes a week.',
      'Contracts routinely include annual price-down clauses, so the manufacturer must plan continuous cost reduction from day one rather than hoping for it.',
      'Relationship and responsiveness decide repeat business. In a category where several plants can meet the specification, the supplier who communicates a problem early keeps the order.',
    ],
  },
  {
    module: 8, topic: 'marketing-sales', emoji: '🧾', type: 'concept',
    title: 'How a piece price is actually built',
    front: 'If you can build a quote from the bottom up, you can answer almost any manufacturing cost or pricing question.',
    back: [
      'Direct material is usually the largest block in electronics and food: bill-of-materials cost plus scrap allowance plus inbound freight and duty. This is where procurement and yield have more leverage than direct labour.',
      'Direct labour is minutes per unit multiplied by the loaded labour rate — wages plus social insurance and benefits — divided by first-pass yield, because rework consumed labour that produced nothing sellable.',
      'Manufacturing overhead is allocated per machine hour or per unit: depreciation, energy, maintenance, quality, supervision and facility cost. Overhead absorption is why volume assumptions change the quoted price so much.',
      'Then add outbound logistics, packaging, warranty or defect allowance, working-capital cost for the inventory you will carry, and the target margin.',
      'The sensitivity to state out loud: quoted cost depends on assumed volume and assumed yield. If actual volume comes in below the quote, overhead per unit rises and the contract can be loss-making at the agreed price.',
    ],
    visual: [
      'PIECE PRICE BUILD-UP  (illustrative)',
      '  Direct material            55%',
      '  Direct labour / yield      12%',
      '  Manufacturing overhead     16%',
      '  Logistics & packaging       6%',
      '  Warranty / defect           2%',
      '  ------------------------------',
      '  Total cost                 91%',
      '  Target margin               9%',
      '  ==============================',
      '  Quoted price              100%',
      '  Sensitive to: volume, yield, FX, metal price',
    ],
  },
  {
    module: 9, topic: 'surprising', emoji: '⚡', type: 'fact',
    title: 'Five manufacturing facts that surprise candidates',
    front: 'Industrial interviewers notice immediately when a candidate is repeating a stereotype about Vietnamese manufacturing. Each of these replaces one.',
    back: [
      'Labour is not the biggest cost in most modern plants. In electronics and food processing, materials usually dominate cost of goods — so procurement, yield and scrap have far more leverage than headcount.',
      'Vietnam is not the cheapest option any more. Regional minimum wages have risen repeatedly, and several regional peers are now cheaper. The competitive case rests on reliability, workforce scale and trade access.',
      'Most of “Vietnamese manufacturing” is foreign-owned. Manufacturing took USD22.88 billion of realised FDI in 2025, about 82.8% of the total — which is why localisation and supplier upgrading, not attracting more plants, is the actual strategic question.',
      'Carbon is now a market-access issue, not a reporting issue. The EU carbon border mechanism moves to its definitive regime from 2026 covering steel, aluminium, cement and fertilisers — categories Vietnam exports — so unmeasured emissions become a price disadvantage.',
      'Weather shows up in the national statistics. Late-2025 storms lengthened supplier delivery times and pushed input-cost inflation to a three-and-a-half-year high, visible directly in the PMI — supply-chain resilience is a Vietnamese operating reality, not a slide.',
    ],
  },
];
