// Retail — deep Vietnam-specific card pack (modules 6-10).
// Store counts and financials are 2025 disclosures; channel-share estimates name their source.

import type { DepthCard } from './industryDepthTypes';

export const RETAIL_DEPTH_CARDS: DepthCard[] = [
  {
    module: 6, topic: 'overview', emoji: '🏬', type: 'fact',
    title: 'Vietnam retail by the numbers (2025)',
    front: 'Total retail sales of goods and services reached about VND7,093 trillion (roughly USD270 billion) in 2025, up 10% — the fastest growth in five years outside the pandemic distortion.',
    back: [
      'Retail goods alone were about VND5,405 trillion (roughly USD205.7 billion), up 9.7%, with food and foodstuff the largest category at roughly a third of goods sales (Ministry of Industry and Trade, 2025 domestic market review).',
      'Modern trade — supermarkets, minimarts, convenience, malls, specialty and e-commerce — accounts for around 30% of retail sales and grew about 22% in 2025, far faster than the market.',
      'The traditional base is enormous: roughly 1.4 million small and convenience stores plus more than 8,300 markets, most of them sub-scale.',
      'Ownership matters for interviews: domestic retailers hold about 81% of modern retail stores, ahead of Thai, Japanese and Korean groups — so “foreign retailers are taking over” is factually wrong.',
    ],
  },
  {
    module: 6, topic: 'overview', emoji: '🏪', type: 'fact',
    title: 'Who actually operates Vietnamese retail',
    front: 'Five names carry most of organised grocery, and they are chasing different geographies and formats.',
    back: [
      'WinCommerce (Masan): about 4,600 WinMart, WinMart+ and Win stores — roughly 800 opened in 2025 with about 70% in rural areas — and annual revenue near USD3.3 billion, making it the largest food retailer.',
      'Bach Hoa Xanh (Mobile World): about 2,000-2,200 fresh-focused stores, roughly 400 opened in 2025 with about 70% in central Vietnam and the Central Highlands, revenue around USD1.6 billion, now pushing north.',
      'Saigon Co.op: a cooperative with roughly 700-800 Co.opmart and Co.opXtra outlets and about USD1.3 billion of revenue, strongest in the south.',
      'Central Retail (Thailand): about 330 outlets including 44 GO!/Big C hypermarkets and 43 malls, roughly 1.3 million square metres of space, about 15,000 employees and around 500,000 customers a day.',
      'AEON (Japan) runs mall-anchored supermarkets and department stores at the premium end, with roughly USD1.6 billion of Vietnam revenue.',
    ],
  },
  {
    module: 6, topic: 'finance', emoji: '💰', type: 'concept',
    title: 'How a retailer actually makes money',
    front: 'A retailer earns three ways, and candidates usually mention only the first.',
    back: [
      'Merchandise margin: buy price versus sell price, multiplied by inventory turns. Thin per unit, profitable only at velocity.',
      'Supplier income: listing fees, promotional allowances, joint business plans and retail media. This is why category managers negotiate as hard as they buy.',
      'Services and adjacencies: private-label margin, memberships, delivery fees, financial services, and rental income where the retailer owns the mall.',
      'Then the cost stack eats it: rent, labour, logistics, utilities, shrink and markdowns. A one-point improvement in shrink or waste can matter as much as a promotion.',
      'The output is the store P&L: sales, gross margin, then store contribution before overhead — the number that decides whether the next 100 stores should open.',
    ],
    diagram: ['Merchandise margin', 'Supplier income', 'Services & private label', 'Store cost base', 'Store contribution'],
  },
  {
    module: 6, topic: 'supply-chain', emoji: '🧺', type: 'fact',
    title: 'Route to market: why Vietnamese grocery is still local',
    front: 'Vietnamese shoppers buy fresh food frequently, close to home, in small baskets — which is the physics behind the minimart boom.',
    back: [
      'High trip frequency and small basket size favour dense small-format stores over weekly hypermarket trips; that is why WinMart+ and Bach Hoa Xanh scaled faster than large formats.',
      'Fresh is the traffic driver and the margin risk at once: it brings shoppers in daily but carries waste, cold-chain cost and strict handling standards.',
      'Wet markets remain formidable competitors on freshness perception and price, so modern trade competes on hygiene, consistency, comfort, promotions and trust rather than pure price.',
      'Rural and provincial expansion is the growth frontier — about 70% of WinCommerce’s 2025 openings were rural and Bach Hoa Xanh concentrated on central provinces — which changes assortment, price laddering and logistics reach.',
    ],
  },
  {
    module: 6, topic: 'supply-chain', emoji: '🎋', type: 'fact',
    title: 'Seasonality: Tet is the retail year',
    front: 'In Vietnamese retail a single festival period can carry a disproportionate share of annual profit — and a forecasting error there is expensive all year.',
    back: [
      'Tết demand builds for four to six weeks: gifting hampers, confectionery, beer and beverages, premium dry goods — then collapses sharply in the week after the holiday.',
      'Operationally that means peak inventory, extended supplier lead times, temporary labour, extra delivery slots and a hard cut-off: leftover Tết-branded stock is a markdown, not inventory.',
      'The mid-year lull (roughly April to August) is when retailers renegotiate terms, reset planograms, remodel stores and pilot new formats.',
      'Mid-Autumn Festival, back-to-school and the 9.9/10.10/11.11/12.12 online sale days create secondary peaks that mostly pull demand between channels rather than adding it.',
    ],
  },
  {
    module: 6, topic: 'supply-chain', emoji: '⚖️', type: 'fact',
    title: 'The regulatory frame retailers work inside',
    front: 'Retail looks unregulated until you try to open a store, run a promotion or import a product.',
    back: [
      'The Ministry of Industry and Trade governs the domestic market, distribution licensing and promotion rules; foreign-invested retailers face additional scrutiny when adding outlets.',
      'Food safety, labelling, origin traceability and recall obligations bind assortment decisions, especially in fresh and imported categories.',
      'Promotion mechanics have legal limits, including caps on discount depth in defined cases, so “just cut price 70%” is not always an available answer.',
      'Two newer rules matter for omnichannel: platform tax withholding from 1 July 2025 (Decree 117/2025/ND-CP) and the Personal Data Protection Law from 2026, which constrains loyalty and CRM data use.',
    ],
  },
  {
    module: 6, topic: 'overview', emoji: '🔀', type: 'quiz',
    title: 'Market check: channel structure',
    front: 'Modern trade is roughly 30% of Vietnamese retail sales. What is the most useful implication for a growth case?',
    back: ['Most volume still moves through traditional trade, so a national plan needs both: modern trade for data, visibility and premium mix; traditional trade for reach and frequency. Treating Vietnam as a modern-trade market overstates addressable demand.'],
    options: [
      'Traditional trade can be ignored because it is shrinking',
      'The majority of sales still run through traditional trade, so plans need a dual-channel design',
      'Modern trade is unprofitable by definition',
      'E-commerce has already replaced physical retail',
    ],
    answer: 1,
  },
  {
    module: 7, topic: 'people-career', emoji: '🧍', type: 'role',
    title: 'What a retail MT actually does, by rotation',
    front: 'Retail graduate programmes are unusually hands-on: expect to be on a shop floor early and to own a number quickly.',
    back: [
      'Category management: analyse sales, margin and basket data by SKU, propose a range change, model the space trade-off, sit in a supplier negotiation — then defend which SKUs you would delist.',
      'Store operations: run shift huddles, chase availability and queue times, investigate shrink, coach service standards, and reconcile a store P&L line by line.',
      'Supply chain: forecast at store-SKU level, set replenishment parameters, monitor distribution-centre service and truck fill, and cut waste and out-of-stocks together rather than trading one for the other.',
      'Omnichannel / CRM: track app conversion, picking productivity, substitution rates, delivery cost per order, and whether a loyalty campaign was actually incremental.',
      'A typical first project: find the ten SKUs driving most fresh waste and propose an ordering or planogram fix with a quantified saving.',
    ],
  },
  {
    module: 7, topic: 'finance', emoji: '📊', type: 'concept',
    title: 'Retail KPI dictionary: the numbers on the wall',
    front: 'These metrics are reviewed weekly in every Vietnamese retail chain. Learn the formula and the trade-off each one hides.',
    back: [
      'Like-for-like (LFL) sales growth — growth from stores open a full comparable period. WinCommerce reported LFL up about 10.6% in a 2025 quarter, its best on record; this is the number that proves a format works.',
      'Traffic x conversion x average basket — the sales identity you should build every retail case from.',
      'Gross margin, GMROI and inventory turns — profit per unit of shelf and per dong of working capital. Shelf space is capital allocation.',
      'Shrink and waste — loss from theft, damage, error and expiry; in fresh grocery this is often the difference between store profit and loss.',
      'On-shelf availability and days of supply — the operational pair: too little stock loses sales, too much creates markdowns and waste.',
    ],
  },
  {
    module: 7, topic: 'people-career', emoji: '🏗️', type: 'concept',
    title: 'How a Vietnamese retail chain is organised',
    front: 'Retail organisations split into buying, moving and selling — and most conflict happens at those seams.',
    back: [
      'Commercial / merchandising: category managers own range, price, promotion and supplier terms, supported by private-label and sourcing teams.',
      'Store operations: regional and area managers above store managers, plus a service and standards function. This is the largest headcount block.',
      'Supply chain: demand planning, replenishment, distribution centres, transport and cold chain.',
      'Support: finance (store P&L and margin control), loss prevention, HR for high-volume frontline hiring, marketing and CRM, and property or store development for site selection.',
      'Online sits either inside operations (store-picked orders) or as a separate P&L with dark stores. Ask which model a company uses, because the economics differ sharply.',
    ],
    diagram: ['Merchandising', 'Supply chain', 'Store operations', 'Finance & loss prevention', 'Online / CRM'],
  },
  {
    module: 7, topic: 'marketing-sales', emoji: '🗂️', type: 'concept',
    title: 'Category management, concretely',
    front: 'Category management is the core retail craft: run a category like a business, not a shelf.',
    back: [
      'Define the category role — traffic builder, profit generator, basket filler or seasonal — because the role sets price and promotion strategy.',
      'Build the range from the shopper decision hierarchy (does the shopper choose brand first, or size, or flavour?), not from supplier pressure.',
      'Set the planogram: eye level for destination SKUs, blocks that match how shoppers scan, and enough facings that a fast seller does not sell out mid-day.',
      'Design promotion mechanics deliberately: price-off, multibuy, bundle, gift-with-purchase and loyalty offers shift volume differently and cost different margin.',
      'Review with the delisting question: which SKUs are not earning their shelf, and what replaces them? A range review with no removals is not a review.',
    ],
  },
  {
    module: 7, topic: 'finance', emoji: '📈', type: 'quiz',
    title: 'Operating check: same-store growth',
    front: 'A chain grows total sales 22% while opening 800 stores, and like-for-like sales rise 10.6%. What does that combination tell you?',
    back: ['Both the network and the existing stores are working. Total growth alone could be pure expansion; positive LFL shows the base estate improved too — which is what justifies further rollout.'],
    options: [
      'Growth is entirely from new stores',
      'Existing stores also improved, which is what makes further expansion defensible',
      'The chain is losing customers',
      'Like-for-like growth is irrelevant when opening stores',
    ],
    answer: 1,
  },
  {
    module: 8, topic: 'marketing-sales', emoji: '📍', type: 'fact',
    title: 'Minimart density is the decisive battle',
    front: 'The strategic contest in Vietnamese grocery is not hypermarkets versus supermarkets — it is who wins the neighbourhood.',
    back: [
      'WinCommerce and Bach Hoa Xanh added roughly 1,200 stores between them in 2025, mostly outside the two largest cities, pushing organised grocery into provincial and rural catchments.',
      'Density is an economics play: more stores per distribution centre lowers delivery cost per store, improves fresh replenishment frequency and raises private-label volume.',
      'Both chains moved the scoreboard from footprint to profit — Bach Hoa Xanh reported about VND255 billion of nine-month 2025 net profit with a full-year expectation of at least VND600 billion, and WinCommerce about VND243 billion over nine months.',
      'The lesson for cases: expansion is only defensible once the store model is repeatable. Ask for payback per store and LFL before approving the next 500 openings.',
    ],
  },
  {
    module: 8, topic: 'marketing-sales', emoji: '📲', type: 'fact',
    title: 'E-commerce reshapes what a store is for',
    front: 'With top-four platform GMV at roughly USD16.4 billion in 2025 (+34.75%), online is now large enough to change store roles.',
    back: [
      'Non-food and discretionary categories moved online fastest, so physical stores lean harder on fresh, immediate need and services — the missions online serves worst.',
      'Live commerce competes for the impulse purchase that used to happen at the shelf, especially in beauty, apparel and small electronics.',
      'Retailers respond with omnichannel: click-and-collect, store-picked delivery, dark stores in dense districts, and app-only offers designed to identify the shopper.',
      'The trap is economics: picking labour, substitutions, packaging and last-mile cost can exceed merchandise margin on a small online grocery basket. Quote cost to serve per order, not just online sales growth.',
    ],
  },
  {
    module: 8, topic: 'rnd-product', emoji: '🏷️', type: 'fact',
    title: 'Private label, retail media and the margin hunt',
    front: 'With thin merchandise margins and rising labour and rent, Vietnamese retailers are chasing two structural margin sources.',
    back: [
      'Private label: higher percentage margin, differentiation and price-entry defence — but only if quality earns repeat purchase. Masan’s consumer-plus-retail structure makes this easier because it owns both brands and shelves.',
      'Retail media and supplier funding: turning shopper data and in-store space into advertising inventory. High margin, fast growing globally, and emerging in Vietnam.',
      'Loyalty data underpins both, which is exactly why the Personal Data Protection Law effective from 2026 is a commercial issue and not only a legal one.',
      'The counterweight is trust: over-indexing on private label or paid placement degrades the assortment shoppers came for. Name that risk when you recommend it.',
    ],
  },
  {
    module: 8, topic: 'finance', emoji: '💸', type: 'fact',
    title: 'Cost pressure: labour, rent and logistics',
    front: 'The 2025-2026 retail problem is not demand — it is holding store contribution while operating costs rise.',
    back: [
      'Labour is the largest controllable line in a store P&L, and minimum-wage plus social-insurance changes flow straight into it. Scheduling labour to the traffic curve is a real MT project.',
      'Prime retail rent in central Ho Chi Minh City and Hanoi is high relative to basket size, pushing new formats toward suburbs, provincial towns and mall anchors.',
      'Vietnam’s logistics costs run at roughly 16-20% of GDP, well above regional peers, so distribution design is a margin lever rather than a back-office concern.',
      'Standard levers: shrink control, fresh waste reduction, energy management, better truck fill, and shifting mix to private label. Quantify each one per store per week.',
    ],
  },
  {
    module: 8, topic: 'finance', emoji: '🚚', type: 'quiz',
    title: 'Trend check: online grocery economics',
    front: 'An online grocery order has a VND300,000 basket, 22% gross margin, and VND90,000 of picking, packaging and delivery cost. What is the honest read?',
    back: ['It loses money: VND66,000 of gross margin against VND90,000 of fulfilment cost, so about VND24,000 negative per order. Online grocery needs bigger baskets, delivery fees, denser routes or more efficient store picking before it works.'],
    options: [
      'It is profitable because gross margin is positive',
      'It loses about VND24,000 per order — fulfilment cost exceeds gross margin',
      'Delivery cost is irrelevant if sales grow',
      'Basket size does not affect profitability',
    ],
    answer: 1,
  },
  {
    module: 9, topic: 'overview', emoji: '🌾', type: 'case',
    title: 'WinCommerce: rural density and the turn to profit',
    front: 'WinCommerce is the clearest Vietnamese example of moving from land-grab to unit economics.',
    back: [
      'Scale: about 4,600 stores under WinMart, WinMart+ and Win after adding roughly 800 in 2025, about 70% of them rural; annual revenue near USD3.3 billion.',
      'Performance evidence: like-for-like growth around 10.6%, its highest on record, and roughly VND243 billion of net profit over nine months of 2025 after years of losses.',
      'Strategic logic: pair Masan’s consumer brands and distribution with owned shelf space, then use rural density where modern trade barely existed to buy growth competitors cannot easily copy.',
      'Culture and MT reality: Masan-group retail work is target-driven and operationally intense, with fast decisions and frequent store visits. Expect commercial ownership early.',
      'Interview question this unlocks: which three store-level metrics would justify — or stop — the next 500 rural openings?',
    ],
  },
  {
    module: 9, topic: 'overview', emoji: '🥬', type: 'case',
    title: 'Bach Hoa Xanh: relearning a category with discipline',
    front: 'Mobile World transferred retail discipline from electronics into fresh grocery — and had to relearn the category’s physics first.',
    back: [
      'Path: rapid expansion, then a deliberate pause to fix waste, labour, assortment and layout, then renewed expansion once the economics worked — roughly 400 new stores in 2025, about 70% in central Vietnam and the Central Highlands.',
      'Result: about 2,000-2,200 stores, roughly USD1.6 billion of revenue, nine-month 2025 net profit near VND255 billion and a full-year target of at least VND600 billion.',
      'What transferred: process rigour, staff productivity systems, data discipline, ruthless format iteration. What did not: shelf-stable inventory logic — fresh food punishes over-ordering immediately.',
      'The northern expansion is the live strategic question: new distribution centres, an unfamiliar supply base, and competition against WinCommerce’s established rural density.',
      'Interview question this unlocks: what capabilities transfer from electronics retail to fresh grocery, and which must be rebuilt from scratch?',
    ],
  },
  {
    module: 9, topic: 'overview', emoji: '🏢', type: 'case',
    title: 'Central Retail and AEON: the foreign multi-format play',
    front: 'Foreign groups compete on experience, scale per store and mall ecosystems rather than raw store count.',
    back: [
      'Central Retail Vietnam: about 330 outlets including 44 GO!/Big C hypermarkets and 43 malls, roughly 1.3 million square metres of space, about 15,000 employees, around 500,000 customers a day, and expansion into northern provinces such as Hung Yen and Yen Bai.',
      'AEON Vietnam anchors large malls with supermarkets and department stores aimed at middle and upper-income urban families, competing on assortment quality, imported ranges and the day-out experience.',
      'Their management-associate programmes typically rotate through category management or buying, store operations, supply chain and often mall or property operations — broader commercial exposure than a pure grocery chain.',
      'Cultural signal: Thai and Japanese groups run structured, standards-heavy training with regional mobility. Expect more documentation and slower but more durable decisions.',
      'Interview question this unlocks: which format would you take into a tier-two Vietnamese city first, and what evidence would you need before committing capital?',
    ],
  },
  {
    module: 9, topic: 'overview', emoji: '🤝', type: 'case',
    title: 'Saigon Co.op: the incumbent with local trust',
    front: 'Saigon Co.op shows both the strength and the constraint of a long-standing domestic cooperative retailer.',
    back: [
      'Strengths: roughly 700-800 outlets, about USD1.3 billion of revenue, deep southern presence, strong price-value trust, and long relationships with domestic suppliers and farmers.',
      'Constraint: a cooperative governance model raises capital more slowly than a listed group — which matters when a competitor adds 800 stores in a year.',
      'Strategic response: format diversification (Co.opmart, Co.opXtra, smaller formats), fresh-food credibility, and gradual e-commerce and delivery build-out.',
      'For a candidate this is the classic incumbency case: how do you convert trust and supplier depth into speed and data capability without breaking what customers value?',
      'Interview question this unlocks: if you cannot outspend WinCommerce on new stores, where would you compete instead?',
    ],
  },
  {
    module: 9, topic: 'people-career', emoji: '📅', type: 'fact',
    title: 'Retail recruitment: what the cycle looks like',
    front: 'Retail hires MTs to run things, so selection leans heavily on practical judgement and stamina.',
    back: [
      'Typical route: application, aptitude test, group case or in-tray exercise, then interviews with a category or operations leader. Foreign-owned groups such as Central Retail (Management Associate) and AEON run the most structured cycles.',
      'Expect a store visit or store-based task. Walk a WinMart+, a Bach Hoa Xanh, a GO! and a Circle K before interviewing, and take notes on availability, pricing, promotion mechanics and staffing.',
      'Strong preparation artefact: a one-page comparison of two nearby stores — range, price ladder, fresh quality, queue length, promotion type — with one recommendation each. Interviewers remember candidates who bring observations.',
      'Rotations usually include a compulsory operations placement. If shift work and shop-floor time do not appeal, retail MT is the wrong programme, and interviewers test for exactly that.',
      'Local chains (Masan/WinCommerce, Mobile World) often hire on a rolling basis rather than a fixed annual calendar, so monitor their career pages continuously.',
    ],
  },
  {
    module: 10, topic: 'people-career', emoji: '🎤', type: 'fact',
    title: 'Competency questions retail interviewers actually ask',
    front: 'Retail interviews test whether you can act on incomplete information, fast, without losing control of the numbers.',
    back: [
      '“A store’s sales are down 8% while the market is up. What do you check first?” Walk availability, pricing, competitor openings, staffing and footfall in order, naming the data you would pull.',
      '“Tell me about a time you influenced someone who did not report to you.” Retail runs on persuading store teams and suppliers without authority.',
      '“How would you decide which SKUs to delist?” Rate of sale, margin contribution, incrementality within the category, supplier terms, and the space released.',
      '“A supplier demands better terms or they walk. What do you do?” Quantify category dependency, model shopper substitution, and prepare an alternative range before negotiating.',
      '“Describe a time you fixed something operationally messy.” Be concrete and quantified, and mention the control you left behind so it did not recur.',
    ],
  },
  {
    module: 10, topic: 'overview', emoji: '🔢', type: 'fact',
    title: 'Analyst-ready Vietnam retail numbers',
    front: 'Quote these with the period and source and you will sound like someone who reads this market weekly.',
    back: [
      'Total 2025 retail sales of goods and services about VND7,093 trillion (roughly USD270 billion), +10%, the fastest in five years; retail goods about VND5,405 trillion (+9.7%).',
      'Modern trade around 30% of retail sales, growing about 22% in 2025; roughly 1.4 million traditional stores and more than 8,300 markets remain.',
      'WinCommerce: about 4,600 stores, roughly 800 added in 2025 (about 70% rural), revenue near USD3.3 billion, LFL up about 10.6%, nine-month net profit about VND243 billion.',
      'Bach Hoa Xanh: about 2,000-2,200 stores, roughly 400 added in 2025, revenue near USD1.6 billion, nine-month net profit about VND255 billion.',
      'Central Retail: about 330 outlets, 44 GO!/Big C hypermarkets, 43 malls, roughly 1.3 million square metres, around 500,000 customers daily; domestic players hold about 81% of modern retail stores.',
      'Channel context: top-four e-commerce platform GMV about USD16.4 billion in 2025 (+34.75%), and logistics costs of roughly 16-20% of GDP shaping distribution economics.',
    ],
  },
  {
    module: 10, topic: 'people-career', emoji: '🧩', type: 'concept',
    title: 'The five retail case archetypes',
    front: 'Every retail case reduces to one of these. Start at the store or order level, never at national market growth.',
    back: [
      'Fix a store or format: build sales as traffic x conversion x basket, deduct margin, labour, rent and shrink, then find the one lever worth more than the rest.',
      'Should we expand? Payback per store, LFL of the existing estate, distribution-centre coverage, and cannibalisation of nearby stores.',
      'Category profitability: range, price architecture, promotion mix, private-label share and space productivity.',
      'Omnichannel economics: cost to serve per online order versus in-store, picking productivity, substitution rate, and whether online demand is incremental.',
      'Supply chain and waste: forecast accuracy, replenishment frequency, cold-chain integrity, and the trade-off between availability and markdown.',
    ],
    diagram: ['Store P&L', 'Expansion payback', 'Category profit', 'Omnichannel cost to serve', 'Availability vs waste'],
  },
  {
    module: 10, topic: 'people-career', emoji: '👀', type: 'fact',
    title: 'What retail interviewers are really scoring',
    front: 'Retail leaders hire for bias to action with numeric control. Show both in the same answer.',
    back: [
      'You start small and specific — one store, one category, one week — then scale the logic upward.',
      'You quantify operationally: units per store per week, waste percentage, hours per shift, not only percentages of revenue.',
      'You respect the frontline: recommendations that add store-team workload without removing something else fail in practice.',
      'You are comfortable with speed: retail decisions are made weekly on imperfect data, and interviewers test whether you can commit and then measure.',
    ],
  },
  {
    module: 10, topic: 'people-career', emoji: '⏱️', type: 'concept',
    title: 'Your 60-second retail answer template',
    front: 'Use this chain for anything from “how would you grow this chain” to “why are sales falling”.',
    back: [
      'Step 1 — Name the shopper mission and the format that serves it: daily fresh top-up, weekly stock-up, impulse, or gifting.',
      'Step 2 — Build sales bottom-up: traffic x conversion x average basket, at store level.',
      'Step 3 — Deduct the real cost stack: cost of goods, labour, rent, logistics, shrink and markdown.',
      'Step 4 — Name the working-capital effect: inventory turns, days of supply, supplier terms.',
      'Step 5 — Close with one operational metric you would review weekly, and the point at which you would stop the initiative.',
    ],
    diagram: ['Shopper mission', 'Traffic x conversion x basket', 'Cost stack', 'Working capital', 'Weekly control metric'],
  },
];
