// Casemate Domain Knowledge — glossary-first cards and dedicated sub-sector foundations.
// Compact source records generate consistent cards while keeping each Vietnam example and
// candidate implication explicit.

import type { TopicGroupId } from './topicGroups';

export interface ExpansionCard {
  key: string;
  module: number;
  topic: TopicGroupId;
  emoji: string;
  type: 'fact' | 'concept' | 'quiz' | 'case' | 'role';
  title: string;
  front: string;
  back: string[];
}

type GlossaryRow = [term: string, definition: string, vietnamExample: string, candidateUse: string];

const GLOSSARIES: Record<string, GlossaryRow[]> = {
  fmcg: [
    ['SKU', 'A stock-keeping unit is one exact product and pack combination. A 330 ml can and a 1.5 litre bottle are different SKUs even when the brand and flavour match.', 'A Suntory PepsiCo distributor plans Pepsi cans and family bottles separately because their outlets, margins and demand patterns differ.', 'MT and consulting candidates use SKU-level thinking to diagnose assortment, stock and profitability instead of hiding behind brand averages.'],
    ['Trade spend', 'Trade spend is the money a manufacturer gives retailers or distributors for discounts, displays, listings and incentives. It reduces the net revenue the company keeps.', 'A Tet end-cap in WinMart may combine a temporary price cut, display fee and volume rebate funded by the supplier.', 'Candidates must test whether promotion creates incremental contribution after every customer term.'],
    ['Off-take', 'Off-take is product moving out of the channel toward the final shopper or outlet. It is closer to real demand than manufacturer shipments into a distributor.', 'A Masan shipment can rise while distributor off-take stays flat, leaving excess stock in neighbourhood stores.', 'Candidates who separate sell-in from off-take avoid recommending growth that is only inventory loading.'],
    ['In-store execution', 'In-store execution means making the agreed assortment, availability, price and display real at each outlet. A plan has no value if shoppers cannot find the product.', 'A Unilever field team checks whether priority SKUs are present, correctly priced and visible in general-trade stores.', 'MT roles often own execution metrics, and case answers should state the outlet standard and audit method.'],
    ['Nielsen data', 'NielsenIQ retail measurement estimates category sales and market share from audited outlets. It is directional evidence, not a perfect census of every Vietnamese transaction.', 'A brand team may use NIQ data to compare share in modern trade while distributor data explains its own sell-out.', 'Candidates should name the coverage and combine market data with internal sales before drawing a conclusion.'],
    ['Planogram', 'A planogram is a diagram showing where products should sit on a shelf and how many facings each receives. It converts category strategy into a repeatable store standard.', 'A supermarket beverage aisle may place cold single-serve packs at eye level and family packs on lower shelves.', 'Consulting and MT candidates use planograms to link shopper behaviour with availability and shelf productivity.'],
    ['GT vs MT', 'General trade is the fragmented network of traditional stores and market outlets, while modern trade is organised chains such as supermarkets and convenience stores. Their data, terms, service and pack economics differ.', 'Vinamilk may reach rural households through distributors in GT but negotiate listings and promotions centrally with AEON or WinMart.', 'Candidates should never propose one route-to-market plan for both channels.'],
  ],
  banking: [
    ['NIM', 'Net interest margin is interest income minus interest expense, divided by average earning assets. It shows how much spread a bank earns from its balance sheet.', 'Techcombank and Vietcombank can report different NIMs because their loan mix, deposit cost and policy roles differ.', 'Candidates use NIM with credit cost to compare risk-adjusted banking economics.'],
    ['NPL', 'A non-performing loan is a loan whose repayment is seriously overdue or otherwise impaired. The NPL ratio compares these loans with the total loan book.', 'Vietnamese banks report NPL formation and write-offs because fast credit growth can make the ratio look stable.', 'Candidates should ask whether asset quality improved or the denominator simply grew.'],
    ['LDR', 'The loan-to-deposit ratio compares customer loans with customer deposits. A high ratio can support income but leaves less funding and liquidity headroom.', 'Vietnamese banks manage LDR against the State Bank of Vietnam limit while competing for low-cost deposits.', 'It matters because a growth recommendation can fail even when demand is strong if funding capacity is constrained.'],
    ['Basel III', 'Basel III is a global framework for bank capital, liquidity and resilience. It makes banks hold buffers against losses and unstable funding.', 'Large Vietnamese banks are progressively adopting Basel III practices alongside local SBV rules.', 'Candidates should connect a lending plan to risk-weighted assets, capital and liquidity rather than discussing sales alone.'],
    ['CASA ratio', 'The CASA ratio is current-account and savings-account deposits as a share of total deposits. These balances are usually cheaper than term deposits.', 'Payroll accounts, merchant acquiring and free transfers help Vietnamese banks make an account the customer’s primary account.', 'CASA is a core lever for funding cost and therefore NIM.'],
    ['ROE', 'Return on equity is profit divided by shareholders’ equity. It shows the return generated on owners’ capital.', 'A Vietnamese bank can lift ROE through better margin and efficiency, but excessive leverage or credit risk can create a misleading result.', 'Candidates should explain the source and sustainability of ROE, not quote it in isolation.'],
    ['ROA', 'Return on assets is profit divided by total assets. For banks it measures how efficiently a very large balance sheet produces earnings.', 'A bank with low-cost deposits and controlled provisions can earn a stronger ROA even at similar asset scale.', 'ROA helps candidates compare operating quality before differences in leverage.'],
  ],
  tech: [
    ['TAM / SAM / SOM', 'TAM is total theoretical demand, SAM is the portion a product can serve, and SOM is the realistic near-term share it can win. The three levels prevent a huge headline market from becoming a fake forecast.', 'A Vietnamese payroll SaaS product may address all employers in TAM but only digitally ready SMEs in its initial SAM.', 'Candidates use the framework to make market sizing operational and credible.'],
    ['ARR / MRR', 'Annual and monthly recurring revenue measure contracted subscription revenue normalised to a year or month. They exclude one-off services that will not repeat.', 'A Vietnamese SaaS company such as Base.vn can separate subscription MRR from implementation fees.', 'Candidates need recurring revenue to evaluate growth quality and forecastability.'],
    ['Churn', 'Churn is the share of customers or revenue lost during a period. Revenue churn can differ from customer churn when larger accounts behave differently.', 'An SME software product may add many trial users while losing paying shops after promotional pricing ends.', 'Candidates should pair acquisition with retention before calling growth healthy.'],
    ['LTV:CAC', 'LTV:CAC compares expected lifetime contribution from a customer with the cost to acquire that customer. The assumptions must use margin and realistic retention.', 'A MoMo campaign with high sign-ups can still fail if voucher cost is never recovered through merchant or partner revenue.', 'It forces candidates to connect growth activity with unit economics.'],
    ['Sprint', 'A sprint is a short, fixed development cycle in which a team commits to a defined set of work. It creates a learning rhythm, not permission to ignore longer-term architecture.', 'A Shopee product squad may use a two-week sprint to test a checkout improvement and review conversion data.', 'Candidates should describe the user outcome, metric and trade-off rather than merely saying agile.'],
    ['API', 'An application programming interface is a defined way for software systems to exchange data or actions. It lets one product use another product’s capability without rebuilding it.', 'A Vietnamese merchant app can call a bank or VNPay API to create a QR payment and receive confirmation.', 'APIs shape partnership speed, reliability, data ownership and build-versus-buy decisions.'],
    ['SaaS vs PaaS', 'Software as a Service provides a finished application, while Platform as a Service provides building blocks for developers. The buyer, pricing and support model are different.', 'An SME may buy MISA software as SaaS while a developer team rents cloud application services as PaaS.', 'Candidates must identify what is sold and who operates each layer before discussing margins or competition.'],
  ],
  retail: [
    ['Same-store sales growth', 'Same-store sales growth measures revenue change only in stores open in both periods. It separates underlying store performance from growth caused by opening new locations.', 'A WinMart+ network can grow total sales through new stores while mature-store sales remain flat.', 'Candidates use it to test whether the retail concept itself is improving.'],
    ['Shrinkage', 'Shrinkage is inventory lost through theft, damage, expiry, error or fraud. It is revenue that can never be sold but still carried a purchase cost.', 'Fresh-food waste and checkout discrepancies can make shrinkage material in Vietnamese supermarkets.', 'MT candidates should treat controls, forecasting and handling as direct margin levers.'],
    ['Sell-through rate', 'Sell-through rate is units sold divided by units received during a period. It shows whether inventory is moving at the intended speed.', 'A Tet gift assortment with low sell-through before the holiday may require an early markdown.', 'Candidates use it to balance availability, working capital and markdown risk.'],
    ['Markdown', 'A markdown is a reduction in the normal selling price to clear inventory or stimulate demand. It can recover cash but gives up gross margin.', 'A department store may mark down seasonal fashion after Tet to avoid carrying obsolete stock.', 'Candidates should compare margin recovered now with the cost of holding and deeper future discounting.'],
    ['Replenishment cycle', 'The replenishment cycle is the sequence and timing for detecting stock need, ordering and refilling the shelf. Faster is useful only when supply and store labour can support it.', 'A convenience chain can replenish fast-moving drinks daily while a department store orders slower categories weekly.', 'It matters because an out-of-stock is often a process failure rather than a demand problem.'],
  ],
  'industrial-manufacturing': [
    ['CAPEX vs OPEX', 'Capital expenditure buys or improves long-lived assets, while operating expenditure pays for the current period’s activity. The distinction changes cash flow, depreciation and investment approval.', 'A new electronics line in Bắc Ninh is CAPEX; its electricity, operators and maintenance are OPEX.', 'Candidates should separate one-time capacity investment from recurring unit cost.'],
    ['OEE', 'Overall equipment effectiveness combines availability, performance speed and quality yield. It shows how much of ideal line capacity becomes good output.', 'A Samsung supplier can lose OEE through changeovers, micro-stops or rejected components even when the plant is scheduled all day.', 'OEE lets candidates locate the operational loss instead of recommending a new factory too early.'],
    ['Utilisation rate', 'Utilisation rate compares actual output or hours with available capacity. High utilisation spreads fixed cost but can reduce resilience.', 'A Vietnamese cement plant running below capacity faces high fixed cost per tonne during a construction slowdown.', 'Candidates use utilisation to test whether volume growth improves margin or requires new investment.'],
    ['Bill of materials', 'A bill of materials lists every component, quantity and specification needed to build one product. It is the product’s cost and supply blueprint.', 'An electronics assembler tracks imported chips, screens, connectors and local packaging in the BOM.', 'Candidates use BOM thinking to find localisation, cost and shortage risks.'],
    ['Throughput', 'Throughput is the rate at which a process produces good output. It is constrained by the slowest effective step, not the fastest machine.', 'A packaging bottleneck can cap a beverage or chemicals line even when upstream mixing has spare capacity.', 'Candidates should improve the constraint before optimising non-bottleneck activity.'],
  ],
  consulting: [
    ['Engagement', 'An engagement is a defined piece of client work with a scope, team, timeline and commercial agreement. It is the unit through which a consulting firm delivers and bills.', 'A Vietnam market-entry engagement may run eight weeks with a partner, manager and case team.', 'Candidates should discuss client outcome, scope control and team economics together.'],
    ['Deliverable', 'A deliverable is the agreed output a consulting team must provide. It may be a decision, model, deck, blueprint or implemented result.', 'A Big 4 advisory team may deliver a target operating model and implementation roadmap to a Vietnamese bank.', 'Candidates need to distinguish polished output from the decision it enables.'],
    ['MECE', 'MECE means mutually exclusive and collectively exhaustive. Categories should not overlap and should cover the important whole.', 'A retail profitability tree can separate revenue, product margin, store labour and occupancy without double counting.', 'It helps candidates structure cases cleanly, but practical usefulness matters more than forcing perfect labels.'],
    ['Hypothesis-led', 'Hypothesis-led work begins with a testable explanation and seeks evidence that could confirm or reject it. It prevents teams from collecting data without a decision path.', 'A consultant may hypothesise that a Vietnamese retailer’s margin decline comes from promotion depth rather than rent.', 'Interviewers look for focused analysis and willingness to change the hypothesis.'],
    ['Workstream', 'A workstream is one coordinated block of analysis within a larger engagement. It has an owner, output and dependencies with other workstreams.', 'A banking transformation can split customer journey, technology, risk and change management into linked workstreams.', 'Candidates should show how they manage interfaces rather than optimise one analysis in isolation.'],
    ['Deck', 'A deck is the slide-based document used to communicate analysis and recommendations. Its value comes from a clear storyline and evidence, not decoration.', 'A strategy team may use a 30-page steering-committee deck to secure a market-entry decision.', 'Candidates need concise synthesis because senior clients read for implications and actions.'],
    ['Client management', 'Client management is the ongoing work of aligning expectations, earning trust and handling disagreement. It is distinct from simply being agreeable.', 'A project manager may reset scope when a client requests additional analysis that threatens the Vietnam launch deadline.', 'Consulting candidates are judged on judgement, communication and constructive challenge.'],
  ],
  logistics: [
    ['3PL', 'A third-party logistics provider performs transport, warehousing or fulfilment for another company. The customer buys service capacity instead of owning every asset.', 'DHL Supply Chain or a local provider can operate a warehouse for a Vietnamese consumer-goods company.', 'Candidates should define the service level, asset model and margin source in outsourcing cases.'],
    ['OTIF', 'On time in full measures whether an order arrives by the promised time with the complete quantity. Both timing and completeness must pass.', 'A modern retailer can penalise a supplier whose truck arrives on time but misses half the ordered cases.', 'OTIF connects planning, warehouse accuracy and transport reliability in one customer metric.'],
    ['Last mile', 'Last mile is the final movement from a hub or store to the recipient. It is usually the most fragmented and expensive part of parcel delivery.', 'GHN and Viettel Post improve density by grouping deliveries across urban wards.', 'Candidates use stops per route, first-attempt success and cost per drop to assess the model.'],
    ['Fill rate', 'Fill rate is the share of requested quantity supplied immediately. It measures product availability at the order line or unit level.', 'A distributor ordering 100 cases and receiving 92 has a 92% unit fill rate.', 'Candidates should balance service improvement against inventory and working-capital cost.'],
    ['Cross-docking', 'Cross-docking moves goods from inbound to outbound transport with little or no storage. It reduces dwell time when timing and data are reliable.', 'A Vietnamese retail distribution centre can cross-dock fast-moving produce to stores on the same day.', 'It matters when a case asks how to increase flow without expanding warehouse space.'],
  ],
  insurance: [
    ['Premium', 'A premium is the price a policyholder pays for insurance coverage. It must fund expected claims, expenses, capital and profit over time.', 'A Vietnamese motor policy prices vehicle risk and mandatory coverage within local rules.', 'Candidates should connect growth in premiums with risk selection and retention.'],
    ['Underwriting', 'Underwriting is the process of assessing risk and deciding coverage, price and conditions. It protects the insurance pool from mispriced exposure.', 'A life insurer may use health declarations and medical evidence when issuing a large policy.', 'Candidates need to separate sales volume from sound risk acceptance.'],
    ['Loss ratio', 'The loss ratio is claims incurred divided by earned premium. It shows how much premium is consumed by insured losses before operating cost.', 'Flood or motor claims can raise a Vietnamese non-life insurer’s loss ratio in one period.', 'It is the first economic check in pricing and portfolio cases.'],
    ['Combined ratio', 'The combined ratio adds the loss ratio and expense ratio for non-life insurance. Below 100% means underwriting profit before investment income.', 'An insurer can improve combined ratio through better pricing, claims control and lower acquisition cost.', 'Candidates use it to avoid mistaking investment gains for healthy underwriting.'],
    ['Persistency', 'Persistency measures how many policies remain active after a set period. Weak persistency often signals poor fit, affordability or sales conduct.', 'Vietnam’s bancassurance reset increased attention to whether life policies survive beyond the first year.', 'Candidates should include retention and suitability when evaluating distribution growth.'],
  ],
  tobacco: [
    ['Excise tax', 'Excise is a selective tax on products such as tobacco that raises price and public revenue. It is also a public-health policy lever.', 'Vietnam applies tobacco excise and is debating stronger structures to reduce consumption.', 'Candidates must put law and health objectives before ordinary commercial optimisation.'],
    ['Illicit trade', 'Illicit trade is production or sale outside legal tax and control systems. Its economics often come from avoiding excise and regulation.', 'Untaxed cigarettes can undercut lawful products while bypassing age and quality controls.', 'Candidates should discuss enforcement and traceability without using illicit trade to dismiss health policy.'],
    ['Track and trace', 'Track and trace links legal product units to their origin and movement. It helps authorities and companies detect diversion or counterfeit supply.', 'Tax stamps and controlled distribution support lawful tobacco monitoring in Vietnam.', 'It matters because compliance and channel control are core capabilities in a restricted category.'],
    ['Price / mix', 'Price / mix is revenue change caused by selling at different prices or changing the portfolio mix. It can offset falling volume without implying more consumption.', 'A shift toward higher-priced legal products can support revenue while total cigarette units decline.', 'Candidates should separate volume, price and product mix and acknowledge the harm context.'],
    ['Harm reduction', 'Harm reduction seeks to lower health damage for people who continue risky behaviour. Evidence, regulation and population effects determine whether a product can credibly claim it.', 'Vietnam prohibits e-cigarettes and heated-tobacco products, so global category claims do not create a local legal option.', 'Candidates must treat regulation as the boundary of the strategy, not an obstacle to work around.'],
  ],
  'fmcg-dairy': [
    ['UHT', 'Ultra-high-temperature processing heats milk briefly to make it shelf stable in sealed packaging. It enables ambient distribution before opening.', 'Vinamilk can send UHT packs through general trade without the cold chain required by fresh pasteurised milk.', 'Candidates should connect processing choice with shelf life, reach, energy and consumer positioning.'],
    ['Cold chain', 'A cold chain keeps temperature-sensitive products within a controlled range from factory to shopper. A break can damage safety, quality and shelf life.', 'Yogurt distribution to Vietnamese convenience stores depends on refrigerated storage, trucks and cabinets.', 'MT cases should include temperature compliance, service level and expiry waste.'],
    ['Milk solids', 'Milk solids are the fat, protein, lactose and minerals left when water is excluded. Their level shapes nutrition, texture, yield and cost.', 'A dairy formula may use local fresh milk and imported milk powder to hit a consistent specification.', 'Candidates need the term to explain formulation economics rather than discussing milk as one undifferentiated input.'],
    ['Fortification', 'Fortification adds nutrients such as calcium, vitamins or protein to a product. The benefit must remain stable, safe and lawfully claimed.', 'Vietnamese brands offer fortified milk for children, adults and older consumers with different needs.', 'Candidates should link the claim to evidence, target segment, affordability and repeat.'],
    ['Expiry loss', 'Expiry loss is inventory written off because too little shelf life remains to sell safely. It is often a forecasting and rotation problem, not just a product problem.', 'A short-dated yogurt promotion can clear stock but destroy margin if demand was overestimated.', 'Candidates should manage freshness, FEFO rotation and service together.'],
  ],
  'fmcg-beer': [
    ['ABV', 'Alcohol by volume is the share of a beverage that is pure alcohol. It affects product style, tax, responsible consumption and labelling.', 'A mainstream lager and a zero-alcohol variant compete in different occasions and regulatory contexts in Vietnam.', 'Candidates need ABV to discuss portfolio and policy accurately.'],
    ['Brewhouse yield', 'Brewhouse yield measures how efficiently malt ingredients become fermentable extract. Losses raise cost before packaging begins.', 'A HEINEKEN Vietnam brewery tracks extract recovery across milling, mashing and lautering.', 'Operations candidates use yield to connect process control with cost per hectolitre.'],
    ['On-trade vs off-trade', 'On-trade is consumption in bars and restaurants, while off-trade is purchase from stores for later consumption. Occasion, price and execution differ.', 'A beer brand may prioritise cold draught visibility in Ho Chi Minh City restaurants and multipacks in supermarkets.', 'Candidates should build separate channel economics and activation plans.'],
    ['Returnable glass bottle', 'A returnable glass bottle is collected, inspected, washed and refilled many times. It lowers new packaging need but requires reverse logistics.', 'Vietnamese beer distributors manage full crates out and empty bottles back through the same network.', 'Candidates should include deposit, loss rate, washing capacity and trip efficiency.'],
    ['Hectolitre', 'A hectolitre is 100 litres and is a standard brewery volume unit. It lets production, energy and cost compare across pack formats.', 'A brewery can report water use or conversion cost per hectolitre of beer.', 'Candidates need a consistent denominator for productivity and sustainability.'],
  ],
  'fmcg-beverages': [
    ['Brix', 'Brix approximates dissolved sugar concentration in a liquid. Beverage plants use it to control taste and formulation consistency.', 'A Vietnamese soft-drink line checks syrup and finished-product Brix against specification.', 'Candidates can connect reformulation, quality and ingredient cost with one operating measure.'],
    ['PET', 'PET is a lightweight plastic commonly used for beverage bottles. Its design affects cost, barrier performance, transport and recycling.', 'A water brand can lightweight a PET bottle but must keep it strong enough for Vietnam distribution conditions.', 'Candidates should balance material saving with consumer use, line speed and circularity.'],
    ['Concentrate', 'Concentrate is a high-strength flavour or syrup base diluted and blended at the bottling plant. It standardises the brand while reducing transport of water.', 'A Pepsi bottler combines concentrate, sweetener, treated water and carbonation locally.', 'Candidates use the model to map value capture and quality control.'],
    ['Cold availability', 'Cold availability means the right chilled product is present and ready for immediate consumption. It combines distribution with functioning refrigeration.', 'A soft drink in a hot neighbourhood outlet can lose the sale when the competitor owns the cold cabinet.', 'Commercial candidates should treat cold equipment productivity as a route-to-market metric.'],
    ['Sugar reformulation', 'Sugar reformulation reduces or replaces sugar while protecting taste, safety and stability. Consumer acceptance can be harder than hitting the laboratory target.', 'Vietnam’s beverage tax and health debate increase pressure for lower-sugar portfolios.', 'Candidates should propose sensory tests, claims, price and repeat metrics together.'],
  ],
  'fmcg-snacks': [
    ['Extrusion', 'Extrusion cooks and shapes a mixed snack dough under heat and pressure. Small parameter changes can alter texture, expansion and yield.', 'A Vietnamese corn snack line controls moisture, temperature and die shape before seasoning.', 'Candidates use the term to connect product design with scalable operations.'],
    ['Seasoning adhesion', 'Seasoning adhesion is how evenly flavour powder stays on the snack surface. It affects taste consistency, dust loss and cost.', 'A potato-chip line controls oil and tumbler settings so every pack delivers the intended flavour.', 'It matters because consumer quality and material yield move together.'],
    ['Nitrogen flush', 'Nitrogen flushing replaces oxygen in a pack to slow oxidation and protect fragile snacks. The gas also helps cushion the product.', 'A Vietnamese chip pack may look partly empty because headspace protects freshness and breakage.', 'Candidates should explain packaging function before recommending material or space cuts.'],
    ['Breakage rate', 'Breakage rate is the share of product damaged before consumption. It can rise during conveying, packing, transport or shelf handling.', 'Long distribution routes to provincial stores can turn intact chips into crumbs without stronger control.', 'Candidates should link pack design, case configuration and logistics to perceived quality.'],
    ['Impulse purchase', 'An impulse purchase is an unplanned decision triggered by visibility, convenience or immediate desire. Availability at the moment matters more than lengthy consideration.', 'Single-serve snacks near a Vietnamese convenience-store checkout target an immediate consumption mission.', 'Candidates should define placement, pack, price and incremental basket value.'],
  ],
  'fmcg-personal-home-care': [
    ['Surfactant', 'A surfactant helps water lift oil and soil or create foam. Different surfactants change cleaning, mildness, cost and environmental profile.', 'A detergent formula for Vietnamese handwashing balances cleaning power with skin feel and rinse effort.', 'Candidates need ingredient logic to evaluate renovation beyond advertising claims.'],
    ['Active ingredient', 'An active ingredient is the component intended to deliver the main functional benefit. Its level and evidence support product performance and claims.', 'An anti-dandruff shampoo uses a recognised active within local cosmetic rules.', 'Candidates should connect claim, dosage, safety, cost and consumer proof.'],
    ['Sachet economics', 'Sachet economics combine low cash outlay with high packaging and conversion cost per gram. The pack can recruit users but creates waste challenges.', 'Single-use shampoo and detergent sachets remain important in Vietnamese general trade.', 'Candidates should discuss accessibility, margin, migration to larger packs and circularity together.'],
    ['Claims substantiation', 'Claims substantiation is the evidence showing that a product promise is true and not misleading. Testing must match the exact wording and conditions of use.', 'A “removes stains in one wash” claim needs a defined test against relevant Vietnamese laundry habits.', 'Candidates should include legal and technical proof in every innovation plan.'],
    ['Penetration', 'Household penetration is the share of target households buying the product in a period. It differs from how often existing buyers repurchase.', 'A cleaning brand can grow by recruiting more rural homes even when current buyer frequency is stable.', 'Candidates use penetration and frequency to identify the actual growth engine.'],
  ],
  'fmcg-seasonings': [
    ['Umami', 'Umami is the savoury taste associated with glutamates and certain nucleotides. It is one part of a balanced flavour profile, not a product category.', 'Vietnamese seasoning powders and fish sauce use savoury depth to support familiar dishes.', 'Candidates should connect sensory language with the meal occasion and responsible formulation.'],
    ['Fermentation', 'Fermentation uses microorganisms and time to transform ingredients and develop flavour. Control of salt, temperature and hygiene determines consistency and safety.', 'Traditional fish sauce production matures fish and salt before blending and bottling.', 'Candidates need to distinguish long biological processing from simple mixing.'],
    ['Cost per serving', 'Cost per serving divides pack price or product cost by the amount used in one meal. It makes affordability comparable across formats.', 'A premium fish sauce can have a higher bottle price but a modest cost per family meal.', 'Candidates use it to explain value without relying only on price per litre.'],
    ['Sensory panel', 'A sensory panel is a structured group that evaluates taste, aroma, texture or appearance. Blind and controlled testing reduces brand and interviewer bias.', 'A seasoning renovation can be tested in actual Vietnamese dishes across regional taste preferences.', 'Candidates should require sensory acceptance before scaling a health or cost change.'],
    ['Traceability', 'Traceability records where ingredients and finished batches came from and where they went. It enables control, recall and supplier improvement.', 'A fish-sauce producer links raw fish lots, fermentation tanks and bottle batches.', 'Candidates should include traceability when local agricultural variation or food safety matters.'],
  ],
};

interface SubsectorProfile {
  parent: string;
  topic: TopicGroupId;
  label: string;
  overview: string[];
  players: string[];
  economics: string[];
  careers: string[];
}

const SUBSECTORS: SubsectorProfile[] = [
  { parent: 'tech', topic: 'tech-telecom', label: 'Telecom', overview: ['Vietnam telecom combines nationwide mobile networks with fibre, data centres and enterprise digital services.', 'Mature subscriber growth shifts competition toward 5G use cases, data consumption and services beyond connectivity.'], players: ['Viettel leads through network scale and a broad technology ecosystem; VNPT/VinaPhone and MobiFone are the other national anchors.', 'FPT Telecom is important in fixed broadband and enterprise connectivity.'], economics: ['Revenue comes from subscriptions, data usage, enterprise contracts and infrastructure services.', 'Spectrum, towers, fibre and data centres create heavy fixed cost, so utilisation, ARPU and churn drive returns.'], careers: ['Commercial roles manage segments, channels and ARPU; network roles manage coverage, capacity and quality; digital roles build adjacent products.', 'A strong interview answer links customer value to spectrum, network CAPEX and service reliability.'] },
  { parent: 'tech', topic: 'tech-blockchain', label: 'Blockchain', overview: ['Blockchain is a shared ledger useful when multiple parties need a trusted transaction history without one party rewriting it.', 'Vietnam has strong developer and digital-asset participation, but enterprise value depends on a real coordination problem rather than token speculation.'], players: ['Sky Mavis is Vietnam’s best-known Web3 company; Kyber Network and local developer communities add technical depth.', 'Banks, logistics firms and public agencies explore permissioned ledgers for controlled use cases.'], economics: ['Protocols may earn transaction fees, while enterprise projects earn software and implementation revenue.', 'Token incentives can create activity without durable demand, so retained users, fee revenue, security cost and regulatory exposure matter.'], careers: ['Paths include protocol engineering, security, product, compliance and ecosystem development.', 'Candidates should explain why a ledger is better than a normal database for the specific Vietnam use case.'] },
  { parent: 'tech', topic: 'tech-ai-ml', label: 'AI & Machine Learning', overview: ['Applied AI turns data and models into predictions, generated content or automated decisions inside a workflow.', 'Vietnam’s opportunity is strongest in local-language products, enterprise automation and export services, while compute and senior talent remain constraints.'], players: ['FPT, Viettel AI, VinAI, Zalo AI and CMC develop models, platforms and enterprise solutions.', 'Banks, retailers and manufacturers are major buyers because they already own high-value workflows and data.'], economics: ['Cost includes data preparation, model training or API usage, inference, evaluation and human oversight.', 'Value should be measured in revenue, risk reduction or hours saved after adoption, not model accuracy alone.'], careers: ['Paths span data science, ML engineering, AI product, data governance and change management.', 'Candidates should name the user decision, baseline, error cost and human control.'] },
  { parent: 'tech', topic: 'tech-semiconductor', label: 'Semiconductor', overview: ['The semiconductor chain spans design, wafer fabrication, assembly, packaging and testing.', 'Vietnam is strongest today in design talent and back-end manufacturing, with policy aiming to deepen the ecosystem.'], players: ['Intel Products Vietnam, Amkor and Hana Micron anchor assembly and testing; Viettel and FPT are building design and packaging capability.', 'Samsung’s electronics base and university programmes support the wider talent pipeline.'], economics: ['Fabrication requires enormous CAPEX and high utilisation; design is talent and intellectual-property intensive; packaging competes on yield and reliability.', 'Cycle timing, customer qualification and equipment lead times make cash flow volatile.'], careers: ['Paths include chip design, verification, process, equipment, yield, quality and supply-chain engineering.', 'Candidates should position Vietnam honestly in the value chain and avoid claiming leading-edge fabrication capability that does not yet exist.'] },
  { parent: 'tech', topic: 'tech-ecommerce', label: 'E-commerce', overview: ['E-commerce links buyer demand, seller supply, payments, advertising and fulfilment on one digital platform.', 'Vietnam’s market is concentrated around Shopee and TikTok Shop, with search-led and content-led shopping behaving differently.'], players: ['Shopee and TikTok Shop dominate platform GMV; Lazada remains present, while Tiki has a much smaller role.', 'GHN, GHTK, Viettel Post, VNPay and wallets support delivery and payment layers.'], economics: ['Platform revenue comes from commission, ads and services, not GMV itself.', 'Contribution per order subtracts vouchers, payment, logistics support, returns and service cost; cohort retention tests whether growth survives incentives.'], careers: ['Category, seller operations, product, growth, analytics and fulfilment roles all own live metrics.', 'Candidates should separate GMV, take rate, contribution margin and repeat purchase.'] },
  { parent: 'tech', topic: 'tech-fintech', label: 'Fintech', overview: ['Fintech applies software and data to payments, credit, wealth, insurance or financial operations.', 'In Vietnam, wallets and payment intermediaries need licensed banks or insurers for balance-sheet products.'], players: ['MoMo, VNPay and ZaloPay lead consumer payment habits; Finhay and other specialists address investment or financial access.', 'Banks are competitors and essential partners at the same time.'], economics: ['Revenue comes from merchant fees, distribution commissions, software services and partner economics.', 'Thin transaction revenue makes active use, revenue per user, fraud loss, incentive cost and partner share critical.'], careers: ['Product, risk, partnerships, compliance, data and merchant operations are common paths.', 'Candidates should name the licence boundary and show unit economics after promotions.'] },
  { parent: 'banking', topic: 'banking-commercial', label: 'Commercial Banking', overview: ['Commercial banking gathers deposits and provides credit, payments and advice to households and businesses.', 'Vietnam combines large state-controlled banks, fast private banks and specialised foreign banks.'], players: ['Vietcombank, BIDV, VietinBank and Agribank lead scale; Techcombank, MB, VPBank and ACB compete strongly in private banking.', 'UOB, HSBC and Standard Chartered focus on FDI, trade and affluent segments.'], economics: ['Profit is interest spread plus fees minus operating cost and credit losses.', 'CASA, loan yield, NIM, credit cost, cost-to-income and capital consumption form the core unit structure.'], careers: ['Relationship management, credit, risk, branch, treasury, product and operations offer distinct routes.', 'Candidates should price growth after expected loss and regulatory constraints.'] },
  { parent: 'banking', topic: 'banking-investment', label: 'Investment Banking', overview: ['Investment banking advises companies and governments on raising capital, mergers and major transactions.', 'Vietnam activity grows with equitisation, private capital, infrastructure and cross-border investment.'], players: ['SSI, Vietcap, TCBS, HSC and other securities firms house local advisory and underwriting teams.', 'Global and regional banks participate selectively in larger cross-border transactions.'], economics: ['Revenue is transaction fees tied to deal completion, while senior relationships and execution talent are the main cost base.', 'A lumpy pipeline, long sales cycle and regulatory approval make utilisation and conversion important.'], careers: ['Analysts build models, valuations, materials and due diligence; associates coordinate execution and clients.', 'Candidates should understand enterprise value, dilution, transaction rationale and process discipline.'] },
  { parent: 'banking', topic: 'banking-insurance', label: 'Insurance', overview: ['Insurance pools premiums from many customers to pay the losses of the few who experience covered events.', 'Vietnam remains underpenetrated but conduct and trust have become central after bancassurance problems.'], players: ['Bao Viet, PVI, Prudential, Manulife, AIA and Dai-ichi are prominent across life and non-life markets.', 'Banks remain important distributors under tighter suitability rules.'], economics: ['Life economics depend on persistency, reserves and investment spread; non-life economics depend on loss and expense ratios.', 'Acquisition commission can create growth that destroys value when policies lapse early.'], careers: ['Underwriting, actuarial, claims, distribution, product, finance and risk are core paths.', 'Candidates should pair premium growth with suitability, persistency and claims outcomes.'] },
  { parent: 'banking', topic: 'banking-capital-markets', label: 'Securities & Capital Markets', overview: ['Capital markets connect issuers needing long-term funding with investors seeking return and liquidity.', 'Vietnam’s equity-market upgrade and bond-market reforms are deepening infrastructure and institutional participation.'], players: ['HOSE, HNX and VSDC form the market infrastructure; SSI, VNDirect, Vietcap, HSC and TCBS are major intermediaries.', 'Fund managers, banks and insurers supply investment capital and research demand.'], economics: ['Brokerage earns fees and margin-lending interest; exchanges earn transaction services; asset managers earn fees on assets under management.', 'Market volumes and asset prices create operating leverage and cyclicality.'], careers: ['Paths include research, sales and trading, brokerage, operations, risk, compliance and asset management.', 'Candidates should separate issuer economics, investor returns and intermediary revenue.'] },
  { parent: 'banking', topic: 'banking-microfinance', label: 'Microfinance', overview: ['Microfinance provides small loans, savings support and related services to customers underserved by mainstream banking.', 'Vietnam uses policy banks, microfinance institutions and community structures to extend inclusion.'], players: ['Vietnam Bank for Social Policies is the scale policy lender; TYM and licensed microfinance institutions serve specific communities.', 'Fintech partnerships can improve reach but do not remove consumer-protection duties.'], economics: ['Small balances produce high servicing cost per dong, so group models, field productivity and repayment discipline matter.', 'Portfolio-at-risk, repeat borrowing, cost per account and customer outcome are more useful than disbursement alone.'], careers: ['Credit officers combine field verification, education and collections; central roles cover risk, product, data and partnerships.', 'Candidates should balance inclusion, affordability, sustainability and over-indebtedness risk.'] },
  { parent: 'retail', topic: 'retail-traditional-modern', label: 'Traditional Trade vs Modern Trade', overview: ['Traditional trade offers dense neighbourhood reach and flexible small baskets; modern trade offers organised formats, central buying and richer data.', 'Vietnam needs both systems, and the same category can perform differently in each.'], players: ['Independent shops and wet markets define traditional trade; WinMart, Saigon Co.op, Central Retail and AEON anchor modern grocery.', 'Distributors are critical connectors between manufacturers and fragmented outlets.'], economics: ['GT carries route and distributor cost but lighter central fees; MT concentrates volume but adds listings, promotions and account terms.', 'Net margin depends on assortment, stock turns, service and trade spend by channel.'], careers: ['Field sales and distributor management dominate GT; category, key-account and store operations roles dominate MT.', 'Candidates should propose different packs, service levels and measures for each.'] },
  { parent: 'retail', topic: 'retail-ecommerce', label: 'E-commerce Retail', overview: ['E-commerce retail sells through digital storefronts, marketplaces and social content with delivery or collection.', 'Vietnamese shoppers increasingly discover products online even when the final purchase happens elsewhere.'], players: ['Shopee, TikTok Shop and Lazada host broad assortments; brand official stores and omnichannel retailers compete within them.', 'Logistics and payment partners shape service quality.'], economics: ['Gross margin must absorb platform commission, ads, fulfilment, returns and discounts.', 'Conversion, basket value, repeat, return rate and contribution per order define healthy growth.'], careers: ['Digital merchandising, marketplace operations, content, performance marketing, product and fulfilment are common roles.', 'Candidates should connect online traffic with inventory and profitable repeat.'] },
  { parent: 'retail', topic: 'retail-convenience', label: 'Convenience Chains', overview: ['Convenience stores sell speed, proximity and immediate consumption through small footprints and long hours.', 'Vietnam’s urban density supports the model, but rent and store labour make sales per square metre critical.'], players: ['Circle K, GS25, FamilyMart, Ministop and WinMart+ compete with different mixes of food-to-go and grocery.', 'Local neighbourhood stores remain the closest substitute.'], economics: ['High-frequency drinks, snacks, meals and services support margin while occupancy and labour create a high fixed-cost base.', 'Store-level contribution, basket, transactions, waste and same-store sales are core measures.'], careers: ['Store operations, network planning, category, food service, supply chain and analytics are key paths.', 'Candidates should test daypart, location and assortment rather than proposing generic expansion.'] },
  { parent: 'retail', topic: 'retail-department-stores', label: 'Department Stores', overview: ['Department stores curate multiple categories and brands in large destination locations.', 'Their role shifts from pure product access toward experience, services and trusted brand environments.'], players: ['Takashimaya, AEON, LOTTE and Vincom-linked retail environments shape Vietnam’s premium destination shopping.', 'Brands may operate concessions inside the store rather than sell through a simple wholesale model.'], economics: ['Revenue comes from merchandise margin, concession rent or commission and services, while prime occupancy and staffing are major costs.', 'Sales per square metre, tenant productivity, markdown and footfall conversion drive returns.'], careers: ['Merchandising, leasing, store experience, CRM, finance and operations offer common paths.', 'Candidates should explain why the destination earns a visit when products are available online.'] },
  { parent: 'industrial-manufacturing', topic: 'manufacturing-automotive', label: 'Automotive', overview: ['Automotive combines vehicle design, tiered component suppliers, assembly, distribution and after-sales service.', 'Vietnam’s market is growing but localisation is constrained by scale and imported component economics.'], players: ['THACO, VinFast, Toyota Vietnam, Hyundai Thành Công, Honda and Ford anchor assembly and market activity.', 'Bosch and a wider supplier base contribute components and engineering.'], economics: ['High tooling and plant fixed cost require volume; model mix, localisation, warranty and dealer margin shape unit profitability.', 'Electric vehicles add battery cost, charging infrastructure and software economics.'], careers: ['Paths include manufacturing, supplier quality, product, procurement, sales, after-sales and engineering.', 'Candidates should map the tiered supply chain and avoid treating vehicle price as manufacturer revenue.'] },
  { parent: 'industrial-manufacturing', topic: 'manufacturing-electronics', label: 'Electronics Manufacturing', overview: ['Electronics manufacturing converts complex bills of materials into high-volume products under strict yield and delivery requirements.', 'It is central to Vietnam’s export economy and FDI base.'], players: ['Samsung, LG, Intel, Foxconn, Luxshare and Pegatron anchor major clusters in northern and southern Vietnam.', 'Local suppliers participate in packaging, plastics, metal parts and selected components.'], economics: ['Material cost dominates, while conversion margin depends on yield, labour productivity, uptime and customer utilisation.', 'FX, component shortages and qualification requirements can overwhelm small unit savings.'], careers: ['Process, industrial, quality, equipment, planning, procurement and supplier-development roles are common.', 'Candidates should use BOM, first-pass yield, OEE and on-time delivery.'] },
  { parent: 'industrial-manufacturing', topic: 'manufacturing-steel-materials', label: 'Steel & Materials', overview: ['Steel and materials businesses transform energy- and commodity-intensive inputs into standard and specialised products.', 'Vietnam demand tracks construction, infrastructure, manufacturing and export cycles.'], players: ['Hòa Phát and Formosa Hà Tĩnh are major steel producers; Hoa Sen and Nam Kim are important in coated products.', 'Import competition and trade remedies shape market balance.'], economics: ['Margin is selling price minus ore, scrap, coal, energy, conversion and freight, with large fixed assets underneath.', 'Utilisation, product mix, inventory timing and commodity spreads create sharp cycles.'], careers: ['Operations, metallurgy, maintenance, energy, procurement, logistics, sales and project roles dominate.', 'Candidates should stress-test the cycle and cash tied up in raw material and finished stock.'] },
  { parent: 'industrial-manufacturing', topic: 'manufacturing-chemicals', label: 'Chemicals', overview: ['Chemical manufacturing converts feedstocks through controlled reactions, separation and blending into industrial or consumer inputs.', 'Safety, process stability and specification consistency are non-negotiable.'], players: ['Petrovietnam Fertilizer and Chemicals, Đức Giang Chemicals and Lâm Thao are notable local players.', 'Global suppliers serve coatings, industrial gases and specialty applications.'], economics: ['Feedstock and energy drive variable cost, while plant utilisation and product grade drive contribution.', 'Environmental controls, shutdowns and safety incidents can dominate financial outcomes.'], careers: ['Process engineering, EHS, quality, R&D, maintenance, procurement and technical sales are key paths.', 'Candidates should put process safety and regulatory limits before throughput improvement.'] },
  { parent: 'industrial-manufacturing', topic: 'manufacturing-construction-materials', label: 'Construction Materials', overview: ['Construction materials include cement, concrete, glass, tiles and related products whose demand follows building and infrastructure activity.', 'Products are heavy, so plant location and logistics matter almost as much as factory cost.'], players: ['VICEM, INSEE Vietnam, Viglacera and Hòa Phát participate across cement, glass, ceramics and building products.', 'Regional producers compete within practical delivery radiuses.'], economics: ['Energy, quarry inputs, kiln or furnace utilisation and freight define delivered cost.', 'Price, utilisation and product mix can move profit sharply in a cyclical market.'], careers: ['Plant operations, mining, energy, quality, logistics, project sales and sustainability roles are common.', 'Candidates should calculate delivered margin by region rather than use one national average.'] },
  { parent: 'consulting', topic: 'consulting-strategy', label: 'Strategy Consulting', overview: ['Strategy consulting helps senior leaders choose where to compete and how to create advantage.', 'Typical Vietnam work includes market entry, growth, portfolio and due-diligence questions.'], players: ['McKinsey, BCG and Bain serve selective regional and Vietnam mandates alongside boutique strategy firms.', 'Corporate strategy teams and Big 4 strategy practices compete for adjacent work.'], economics: ['Fees reflect senior judgement and intensive case teams; partner relationships create the pipeline.', 'Leverage, utilisation, project duration and pricing determine engagement margin.'], careers: ['Analysts research, model and synthesise; managers integrate workstreams; partners shape the client decision.', 'Candidates need hypothesis-led cases, clear maths and concise recommendation.'] },
  { parent: 'consulting', topic: 'consulting-management', label: 'Management Consulting', overview: ['Management consulting improves operating models, performance and large transformations across functions.', 'The work sits between recommendation and implementation more often than pure strategy.'], players: ['Accenture, Kearney, Roland Berger and specialist firms work alongside large professional-services networks.', 'Local consultancies add sector and regulatory knowledge.'], economics: ['Projects are longer and use broader teams than many strategy cases, so staffing mix and scope control matter.', 'Value comes from measurable operational change rather than a final presentation alone.'], careers: ['Business analysis, process design, PMO, change and functional expertise form common paths.', 'Candidates should translate a recommendation into owners, milestones and adoption measures.'] },
  { parent: 'consulting', topic: 'consulting-it', label: 'IT Consulting', overview: ['IT consulting connects business goals with architecture, software selection, implementation and digital operating change.', 'Vietnam combines domestic transformation demand with regional and global delivery talent.'], players: ['Accenture, FPT, KPMG, Deloitte, PwC, EY and technology vendors deliver major programmes.', 'Cloud providers and software partners participate in implementation ecosystems.'], economics: ['Revenue may be time-and-materials, fixed-price delivery or managed service; rework and scope creep erode margin.', 'Utilisation, blended rate, delivery quality and recurring support shape economics.'], careers: ['Business analyst, architect, developer, data, cybersecurity, ERP and programme roles are common.', 'Candidates should connect technology choices with process, controls and user adoption.'] },
  { parent: 'consulting', topic: 'consulting-big4', label: 'Big 4 Advisory', overview: ['Big 4 advisory spans deals, risk, tax, technology and transformation around a large audit and professional-services base.', 'Vietnam clients value regulatory depth, execution scale and cross-border networks.'], players: ['Deloitte, PwC, EY and KPMG are the four global networks, each with different local strengths by service line.', 'Their competitors vary by engagement: banks in deals, law firms in tax and tech firms in implementation.'], economics: ['Engagement fees fund staff-heavy teams, specialist review and partner oversight.', 'Independence rules, utilisation, write-offs, collections and cross-service conflicts affect what work is feasible and profitable.'], careers: ['Graduate routes include deals, risk, tax, audit-adjacent assurance, technology and transformation.', 'Candidates should name the exact service line and understand independence and client-delivery discipline.'] },
];

function keyOf(value: string): string {
  return value.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');
}

export function expansionCardsFor(industrySlug: string): ExpansionCard[] {
  const glossaryCards = (GLOSSARIES[industrySlug] || []).map(([term, definition, vietnamExample, candidateUse], index) => ({
    key: `glossary-${String(index + 1).padStart(2, '0')}-${keyOf(term)}`,
    module: 0,
    topic: 'glossary' as TopicGroupId,
    emoji: '',
    type: 'concept' as const,
    title: term,
    front: definition,
    back: [`Vietnam example: ${vietnamExample}`, `Why it matters: ${candidateUse}`],
  }));

  const subsectorCards = SUBSECTORS.filter((profile) => profile.parent === industrySlug).flatMap((profile) => {
    const base = keyOf(profile.label);
    return [
      { key: `${base}-overview`, module: 6, topic: profile.topic, emoji: '', type: 'fact' as const, title: `${profile.label}: market overview`, front: profile.overview[0], back: profile.overview.slice(1) },
      { key: `${base}-players`, module: 6, topic: profile.topic, emoji: '', type: 'fact' as const, title: `${profile.label}: key players in Vietnam`, front: profile.players[0], back: profile.players.slice(1) },
      { key: `${base}-economics`, module: 7, topic: profile.topic, emoji: '', type: 'concept' as const, title: `${profile.label}: economics & unit structure`, front: profile.economics[0], back: profile.economics.slice(1) },
      { key: `${base}-careers`, module: 7, topic: profile.topic, emoji: '', type: 'role' as const, title: `${profile.label}: career paths`, front: profile.careers[0], back: profile.careers.slice(1) },
    ];
  });

  return [...glossaryCards, ...subsectorCards];
}
