// FMCG specialist depth pack B — Confectionery & Snacks, Personal Care & Home Care, Seasonings.
// These extend each sub-industry's twenty base cards into the chapters the base deck cannot
// reach: the physical supply chain, the product science, the cost stack, the commercial engine
// and the counterintuitive facts a category interviewer uses to separate candidates.

import type { DepthCard } from './industryDepthTypes';

export const SNACKS_DEPTH_CARDS: DepthCard[] = [
  {
    module: 6, topic: 'supply-chain', emoji: '🍪', type: 'concept',
    title: 'How snacks are actually made, and why changeovers cost money',
    front: 'Snacking is not one process. Biscuits, chips, chocolate and candy run on completely different lines, and the shared constraint is how expensive it is to switch between products.',
    back: [
      'Biscuits and wafers: mix dough, sheet and cut or rotary-mould it, bake in a long tunnel oven, cool, then cream, coat or sandwich, and pack. Oven profile and dough hydration control texture, and texture is the product.',
      'Savoury snacks: potato or corn is sliced or extruded, fried or baked, then seasoned in a rotating drum. Oil quality and seasoning pick-up decide both taste and cost, and used oil management is a genuine operating discipline.',
      'Chocolate and candy: refining and conching for chocolate, cooking and depositing for candy, then tempering and moulding. Chocolate is temperature-sensitive all the way to the shelf, which is a real problem in a hot, humid market.',
      'Packaging is functional, not decorative: barrier films protect against moisture and oxygen, and nitrogen flushing keeps crisps crisp. A pack that fails on barrier does not just look bad — it shortens shelf life and creates returns.',
      'The economics of changeover: switching a line from one flavour or format to another means stopping, cleaning, resetting and running waste product until the process stabilises. Every extra variant marketing adds consumes capacity that could have been output.',
      'The MT tension this creates: marketing wants range and seasonal variants, operations wants long runs. A strong answer quantifies the changeover cost per switch and proposes which variants actually earn their complexity.',
    ],
    diagram: ['Raw material prep', 'Form or extrude', 'Bake or fry', 'Season or coat', 'Barrier pack', 'Distribute'],
  },
  {
    module: 7, topic: 'rnd-product', emoji: '🔬', type: 'fact',
    title: 'The science of texture, shelf life and a hot humid market',
    front: 'Snack R&D in Vietnam solves problems that barely exist in temperate markets. Naming them shows you understand the operating environment, not just the consumer.',
    back: [
      'Water activity is the controlling variable. Crisp products must stay dry and soft products must stay moist, so barrier packaging, humidity control in the plant and desiccants exist to hold water activity in a narrow band.',
      'Heat is the enemy of chocolate. Standard chocolate softens and blooms in Vietnamese ambient conditions, so recipes and fat systems are adjusted for heat resistance and distribution is planned around it — which is why chocolate is a smaller and more premium segment here than in cooler markets.',
      'Oil oxidation limits shelf life in fried snacks. Frying oil quality, antioxidant systems and nitrogen flushing determine whether the product tastes fresh at month six as well as at week one.',
      'Reformulation pressure is growing: less salt, less sugar, baked rather than fried, added protein or fibre, and cleaner ingredient lists. Each change risks the texture that made the product succeed, so sensory testing gates every reformulation.',
      'Local taste development is a genuine advantage: seasoning profiles built around Vietnamese flavours travel poorly but win locally, which is why regional players compete effectively against global snack brands.',
      'Interview move: when proposing a healthier snack, immediately name the texture or shelf-life risk you would test for. That single sentence separates a marketer from someone who has worked with R&D.',
    ],
  },
  {
    module: 6, topic: 'finance', emoji: '💰', type: 'concept',
    title: 'Snack economics and the seasonal gifting bet',
    front: 'Snacking has attractive margins and a brutal seasonal risk. The gifting season can make the year or leave you with a warehouse of branded stock nobody wants.',
    back: [
      'The cost stack: commodity raw materials (flour, sugar, edible oil, cocoa, dairy, potato or corn) that are volatile and often imported, then packaging film and cartons, factory conversion including significant energy for baking or frying, then distribution and trade spend.',
      'Margins are generally healthier than in liquid categories because value density is high and the product is shelf-stable — you are not shipping water and you are not paying for a cold chain.',
      'Then the season arrives. Tet and Mid-Autumn gifting concentrate a disproportionate share of annual volume and profit into a few weeks, in dated, festival-branded packaging.',
      'That creates the defining risk in the category: festive stock has no life after the festival. Leftover Tet or Mid-Autumn inventory is a markdown, not inventory, so a forecasting error is realised immediately and in full.',
      'The operational consequence: peak inventory build, extended supplier lead times, temporary labour, and a hard cut-off date after which nothing more can be produced profitably.',
      'The MT question this generates: how much upside are you willing to leave on the table to avoid write-off? Quantify the cost of a stock-out against the cost of a markdown before committing the production plan.',
    ],
    visual: [
      'THE FESTIVE FORECAST BET',
      '  Build ----------> PEAK -----> CLIFF',
      '  6-8 weeks ahead   festival    day after',
      '',
      '  Under-forecast -> lost sales you cannot',
      '                    recover (no second Tet)',
      '  Over-forecast  -> dated packaging becomes',
      '                    markdown, then waste',
      '  ---------------------------------------',
      '  Quantify stock-out cost vs markdown cost',
      '  BEFORE fixing the production plan.',
    ],
  },
  {
    module: 7, topic: 'marketing-sales', emoji: '🎯', type: 'fact',
    title: 'Snacking is sold by occasion, not by product',
    front: 'The category splits by when and why someone eats, and each occasion wants a different pack, price and location in the store.',
    back: [
      'Impulse and on-the-go: single-serve packs at the till, near school gates and in convenience stores. The decision takes seconds, so visibility and price point matter more than brand consideration.',
      'Household sharing: family packs and multipacks bought in modern trade for home consumption, where value per gram and pack resealability matter.',
      'Gifting: premium boxed formats for Tet and Mid-Autumn, where the pack is most of the perceived value and the buyer is not the eater. This is the highest-margin occasion in the category.',
      'Kids and school: smaller formats, character licensing and parental permission dynamics, with the parent paying and the child choosing.',
      'Health-conscious and functional snacking: nuts, baked products, protein and reduced-sugar lines, growing from a small base and concentrated in urban modern trade and e-commerce.',
      'The channel logic that follows: general trade drives impulse and neighbourhood reach, modern trade builds family packs and gift displays, convenience serves on-the-go, and e-commerce expands bundles and seasonal gifting.',
    ],
  },
  {
    module: 8, topic: 'marketing-sales', emoji: '🏷️', type: 'concept',
    title: 'Winning the shelf and the display in snacks',
    front: 'Snacking is the most display-driven FMCG category. A large share of purchases are decided in the aisle, so in-store execution is the strategy rather than a consequence of it.',
    back: [
      'Secondary display is where the volume is: aisle ends, floor stacks, till-point units and seasonal gift islands often outsell the main fixture during peak periods.',
      'Facings and blocking matter because shoppers scan quickly. A brand block that reads as one confident presence beats scattered single facings even at the same total space.',
      'Price points are psychological and sticky. Vietnamese impulse snacking works around familiar price points, so brands often shrink the pack rather than break the price point — a decision that must be handled honestly on pack.',
      'Promotion mechanics differ in effect: price-off drives trial, multibuy raises basket but pulls demand forward, and gift-with-purchase protects the price point while adding perceived value.',
      'Trade investment must be earned back: display fees, listing support and promotional allowances are real cash, so measure incremental units rather than total units sold during the promotion.',
      'The discipline to state in a case: separate the incremental effect of a display from the underlying rate of sale, otherwise every promotion looks like a success.',
    ],
  },
  {
    module: 9, topic: 'surprising', emoji: '🤯', type: 'fact',
    title: 'Five snacking facts that surprise candidates',
    front: 'Each of these overturns something people assume about the category.',
    back: [
      'Chocolate is a difficult category in Vietnam, not an obvious one. Heat and humidity make distribution and shelf presentation genuinely hard, which is why chocolate stays smaller and more premium here than in cooler markets.',
      'The pack can be worth more than the product. In Tet and Mid-Autumn gifting, presentation is most of the perceived value and the buyer never eats the product — which is why gifting formats carry premium margin.',
      'Every new flavour costs capacity. Line changeovers consume production time and generate waste, so an expanded range quietly reduces total output. Complexity has a measurable price.',
      'Local flavour knowledge beats global scale here. Regionally developed seasoning profiles compete effectively against global snack brands because the taste reference is local rather than aspirational.',
      'Festive inventory has a hard expiry that has nothing to do with food safety. Dated festival packaging is unsellable the day after the festival, so the forecasting error is realised immediately and in full.',
    ],
  },
];

export const CARE_DEPTH_CARDS: DepthCard[] = [
  {
    module: 6, topic: 'supply-chain', emoji: '🧴', type: 'concept',
    title: 'How a shampoo or detergent is actually made',
    front: 'Personal and home care is chemical formulation and mixing rather than cooking. The process is simple; the difficulty is consistency, claims and packaging.',
    back: [
      'Compounding: raw materials are dosed into a large mixing vessel in a defined order and at controlled temperature — surfactants that clean, emulsifiers that hold oil and water together, thickeners, preservatives, fragrance and actives.',
      'The actives are the expensive part and the reason the product can make a claim: anti-dandruff agents, fluoride in toothpaste, enzymes in detergent, sunscreen filters, niacinamide or retinol in skin care.',
      'Quality release is analytical: viscosity, pH, colour, odour, microbiological safety and stability testing. A batch that fails release is a full batch loss, because you cannot rework a formulation the way you can rework a mechanical part.',
      'Filling and packaging usually dominate the plant footprint: bottles, caps, pumps, tubes, sachets and laminates, with sachet lines running at very high speed because sachets carry enormous volume in Vietnam.',
      'Stability and shelf life are tested under accelerated heat and humidity conditions, which matters more here than in temperate markets because the product must survive an unairconditioned shop and a bathroom shelf.',
      'The strategic consequence: because the process is not the barrier, the defensible assets are brand, claim evidence and distribution reach — which is exactly why this category spends so heavily on advertising and route to market.',
    ],
    diagram: ['Dose raw materials', 'Compound & heat', 'Add actives & fragrance', 'QC release', 'Fill bottle or sachet', 'Pack & distribute'],
  },
  {
    module: 7, topic: 'rnd-product', emoji: '🧬', type: 'fact',
    title: 'Claims, evidence and why R&D gates the marketing plan',
    front: 'In care categories the product claim is the product. Every claim has to be substantiated before a campaign can run, which is why R&D and regulatory sit upstream of marketing rather than beside it.',
    back: [
      'Efficacy claims require testing: clinical or instrumental studies for skin and hair benefits, consumer panel testing for perceived performance, and standardised laboratory methods for cleaning and whitening claims.',
      'Regulatory compliance sets what may be said at all: cosmetic product notification, ingredient restrictions, labelling requirements, and a hard boundary between a cosmetic claim and a medicinal one that a brand may not cross.',
      'Safety substantiation runs in parallel: patch testing, irritation and sensitisation assessment, preservative efficacy testing and full stability data across the claimed shelf life.',
      'Sensory work is not decoration. Fragrance, texture, foam and after-feel drive repeat purchase in these categories more than measured efficacy does, because the consumer experiences the sensory cues immediately and the benefit slowly.',
      'Innovation is mostly incremental and regimen-led: a new active, a lighter texture, a targeted variant, a refill format, or a new step in a routine that creates an additional purchase occasion.',
      'Interview move: when asked how you would launch a new care product, name the claim, the evidence you would need for it, and the regulatory step — before you talk about the campaign.',
    ],
  },
  {
    module: 6, topic: 'finance', emoji: '💰', type: 'concept',
    title: 'Care economics: high gross margin, high advertising',
    front: 'Personal and home care carries some of the best gross margins in FMCG and spends much of it back on demand creation. Understanding that trade is the core of any case in this category.',
    back: [
      'Cost of goods is comparatively low: actives, surfactants and fragrance, plus packaging that is often the largest single block — a pump bottle or laminate tube can cost more than the formulation inside it.',
      'That produces high gross margin, which is exactly why the category can afford heavy advertising, sampling and in-store investment. The advertising is not a luxury; it is the mechanism that makes an undifferentiated formulation preferred.',
      'Sachets are a Vietnamese economics lesson: a shampoo sachet has terrible margin per gram because packaging cost per unit of product is high, but it recruits users who cannot afford a bottle and builds habit. It is an acquisition cost disguised as a product.',
      'Premium and dermocosmetic tiers carry far better margin per unit and are concentrated in modern trade, pharmacies, beauty specialists and e-commerce where the shopper will read a claim.',
      'The costs that erode it: trade spend and promotional depth, distributor margin, e-commerce commission and creator fees, and returns in online channels.',
      'The metric to build a case on: contribution after trade spend and advertising for each brand and tier, then penetration and repeat purchase to see whether the spend actually built a franchise or just bought a spike.',
    ],
    visual: [
      'CARE P&L SHAPE (illustrative)',
      '  Net revenue                 100',
      '  - Formulation                12',
      '  - Packaging                  18',
      '  - Conversion + logistics     12',
      '  ------------------------------',
      '  Gross margin                 58   <- high',
      '  - Trade spend                14',
      '  - Advertising & sampling     20   <- the trade',
      '  ------------------------------',
      '  Contribution                 24',
      '  High margin exists to fund demand creation.',
    ],
  },
  {
    module: 7, topic: 'marketing-sales', emoji: '🎯', type: 'fact',
    title: 'Routines, regimens and the cross-sell engine',
    front: 'Care categories grow by adding steps to a routine, not just by winning a brand switch. That is the mechanism candidates most often miss.',
    back: [
      'Start from the routine and the user, not the product: a hair routine, an oral care routine, a facial skin regimen, a laundry routine. Growth comes from penetration, frequency, premium mix or an extra step in the regimen.',
      'Regimen cross-sell is the highest-value move: a cleanser user who adds a toner, serum and sunscreen multiplies category value from the same consumer without any switching required.',
      'Channel maps to the mission precisely: general trade for sachets, detergent and everyday oral care; modern trade for larger packs and planned stock-up; pharmacies and beauty specialists for expert trust and dermocosmetics; e-commerce for discovery, reviews and bundles.',
      'The Vietnamese beauty market has real scale and real competition, with Unilever and L’Oréal leading broad beauty and personal care while P&G, Colgate-Palmolive and regional players compete by segment. L’Oréal’s portfolio breadth helped it reach about 29% of Vietnam skin-care value in 2025.',
      'Online is where beauty is discovered now: reviews, creator content and live commerce drive trial, then repeat purchase migrates to whichever channel is most convenient — so measure the funnel across channels, not within one.',
      'The diagnostic to use in a case: is the problem penetration, frequency, regimen depth or premium mix? Each one has a different intervention and a different payback period.',
    ],
  },
  {
    module: 8, topic: 'marketing-sales', emoji: '📱', type: 'concept',
    title: 'Online plus offline: how beauty is actually won now',
    front: 'Care is the FMCG category most transformed by content-led commerce in Vietnam, and the mechanics are specific enough to be worth knowing precisely.',
    back: [
      'Discovery moved to content: short-form video, creator reviews and livestream demonstrations create demand for products a shopper was not searching for — which suits categories where the benefit can be shown.',
      'Trust is built through third-party voices rather than brand claims, so influencer and dermatologist credibility and user reviews carry more weight than advertising in the premium tiers.',
      'Conversion splits by channel economics: content platforms pay creator commissions and discount heavily, marketplaces monetise high-intent search through ads, and offline pharmacies and beauty stores convert through expert advice.',
      'The operational cost most candidates forget: returns. Online beauty has meaningful return rates on shade, texture and expectation mismatch, and returns eat contribution quickly.',
      'Counterfeit and grey-market product is a genuine issue in Vietnamese beauty, which is why brands invest in authorised-seller programmes, official flagship stores and authentication — protecting trust is a commercial activity here.',
      'The framing that works in interview: online creates demand and offline still converts a large share of it, so measure incrementality across the whole journey rather than crediting the last click.',
    ],
  },
  {
    module: 9, topic: 'surprising', emoji: '🤯', type: 'fact',
    title: 'Five care facts that surprise candidates',
    front: 'This is the category where the intuitive economics are most often backwards.',
    back: [
      'The sachet is the worst-margin format and one of the most valuable. Packaging cost per gram is high, but it recruits consumers who cannot afford a bottle and builds a habit that upgrades later.',
      'Packaging frequently costs more than the formulation. A pump, a tube or a decorated bottle can exceed the cost of what is inside, which is why pack engineering is a serious margin lever.',
      'Advertising is not overhead in this category, it is the product moat. With low barriers to formulation, brand meaning and distribution reach are the only defensible assets — which is why gross margins are high and net margins are ordinary.',
      'The claim is made before the campaign. Efficacy testing, safety substantiation and regulatory notification gate what marketing may say, so R&D and regulatory sit upstream of the brand plan rather than alongside it.',
      'Vietnamese heat and humidity are formulation constraints. Stability testing under accelerated conditions matters more here because the product must survive an unairconditioned shop, a motorbike delivery and a humid bathroom.',
    ],
  },
];

export const SEASONINGS_DEPTH_CARDS: DepthCard[] = [
  {
    module: 6, topic: 'supply-chain', emoji: '🫘', type: 'concept',
    title: 'How fish sauce, soy sauce and seasoning are actually made',
    front: 'Condiments are fermentation businesses. The process takes months, which makes capacity planning and quality control fundamentally different from the rest of FMCG.',
    back: [
      'Traditional fish sauce: anchovies and salt are layered in vats and left to ferment and hydrolyse for roughly nine to eighteen months, after which the liquid is drawn off and graded by protein content, measured in degrees of nitrogen. That protein grade is the quality currency of the category.',
      'Industrial seasoning production blends a fermented base with water, salt, sugar, flavour enhancers and preservatives to hit a consistent taste at an accessible price — precisely the distinction behind the public argument between traditional and industrial fish sauce in Vietnam.',
      'Soy sauce runs a parallel path: soybean and wheat are inoculated with koji mould, brined and fermented, then pressed, pasteurised and filtered. Fermentation time and mould culture set the flavour depth.',
      'Instant noodles and processed foods sit in the same portfolio for most Vietnamese players: flour is mixed, sheeted, cut into strands, steamed, fried or air-dried, then packed with a seasoning sachet — a high-speed line where oil quality and moisture control govern shelf life.',
      'The planning consequence: a nine-to-eighteen-month fermentation cycle means today’s capacity decision serves next year’s demand. You cannot answer a demand surge with an extra shift, so vat capacity and inventory are the strategic assets.',
      'Food safety and traceability are release-critical: microbiological testing, histamine limits in fish sauce, contaminant screening and batch traceability — because a recall in a staple food category damages a brand permanently.',
    ],
    diagram: ['Raw material & salt', 'Ferment 9-18 months', 'Draw off & grade', 'Blend & standardise', 'Bottle & pasteurise', 'Distribute'],
  },
  {
    module: 7, topic: 'rnd-product', emoji: '👅', type: 'fact',
    title: 'Taste science and the localisation problem',
    front: 'Seasonings is the FMCG category where local taste knowledge is hardest to replicate, and that is exactly why domestic players compete so effectively against global food companies here.',
    back: [
      'Taste is measured, not guessed: protein grade in fish sauce, salt content, umami intensity, viscosity, colour and aroma profile are specified and tested, then validated on trained sensory panels.',
      'Regional taste preferences within Vietnam are real and commercially significant. Northern, central and southern palates differ in salt, sweetness and chilli intensity, so a national brand often needs regional variants rather than one recipe.',
      'Reformulation is genuinely risky in staples. A condiment is used daily in dishes people have cooked the same way for years, so a change in taste is detected immediately and punished with switching.',
      'The health direction is reduced sodium, reduced monosodium glutamate, cleaner labels and higher protein grades — each of which removes something that was doing flavour work, so the reformulation has to replace the sensory effect rather than just the ingredient.',
      'Premiumisation runs on provenance and craft: traditional fermentation, a higher nitrogen degree, single-origin anchovy and artisanal positioning, sold at a multiple of mainstream price into modern trade and gifting.',
      'Interview move: this is the strongest category in which to argue that local capability beats global scale, because taste is culturally specific and cannot be imported.',
    ],
  },
  {
    module: 6, topic: 'finance', emoji: '💰', type: 'concept',
    title: 'Condiment economics: staples, working capital and platform margin',
    front: 'Seasonings look like a low-excitement category and generate some of the most durable profit in Vietnamese FMCG. The reason is habit combined with an unusual working-capital structure.',
    back: [
      'Demand is exceptionally stable because these are cooking staples bought at high frequency and low deliberation. That predictability is worth a great deal: forecasting is easier, waste is lower and distribution is efficient.',
      'The cost stack is favourable: raw fish or soybean, salt, sugar and flavour ingredients, plus glass or PET bottles and closures, factory conversion, and distribution of a shelf-stable product with no cold chain.',
      'The working-capital line most candidates miss: fermentation ties up inventory for many months before a single bottle can be sold. Vat capacity, raw material bought a year ahead and work in progress all sit on the balance sheet.',
      'Brand strength converts directly into pricing power, because switching a household staple carries a real perceived risk of ruining the family meal. That is why leading condiment brands hold price better than most FMCG categories.',
      'The platform effect is the strategic prize: once you own a trusted flavour brand and national distribution, adjacent products — chilli and cooking sauces, instant noodles, processed and ready foods — travel on the same shelf, the same distributor and the same trust.',
      'The case discipline: separate the condiment category from broader instant noodles and processed food before quoting growth or share, because they carry different margins, competitors and volatility.',
    ],
    visual: [
      'THE FLAVOUR PLATFORM',
      '  Trusted staple brand + national distribution',
      '        |',
      '        +--> fish sauce / soy sauce   core',
      '        +--> chilli & cooking sauces  adjacent',
      '        +--> instant noodles          adjacent',
      '        +--> processed & ready foods  adjacent',
      '  -------------------------------------------',
      '  Same shelf, same distributor, same trust.',
      '  BUT fermentation ties up months of working',
      '  capital before any revenue appears.',
    ],
  },
  {
    module: 7, topic: 'marketing-sales', emoji: '🎯', type: 'fact',
    title: 'Why independent grocers still own the condiment shelf',
    front: 'Seasonings is the most general-trade-dependent FMCG sub-category, and understanding why explains the entire route-to-market design.',
    back: [
      'The shopping mission is replenishment of a pantry staple, bought close to home the moment it runs out. That favours the nearest shop over a planned supermarket trip, which is why independent grocers remain the dominant condiment channel.',
      'The consequence for route to market: broad numeric distribution across tens of thousands of small outlets, layered distributors, and field sales routines that audit availability and facings rather than negotiate central listings.',
      'Modern trade plays a different role: portfolio blocking so a shopper sees the whole range together, premium and craft sauces that need a label to be read, and larger formats for households stocking up.',
      'E-commerce contributes bundles, gifting and exports to the Vietnamese diaspora — a genuinely meaningful channel for a category where people abroad want a specific taste from home.',
      'Occasions still matter despite the stability: Tet lifts cooking, gifting and hosting, and cooler or rainy weather shifts consumption toward hot dishes and soups.',
      'The execution metric that decides share: weighted distribution and rate of sale by outlet type. In a category bought at the nearest shop, an out-of-stock loses the sale outright rather than delaying it.',
    ],
  },
  {
    module: 9, topic: 'surprising', emoji: '🤯', type: 'fact',
    title: 'Five seasoning facts that surprise candidates',
    front: 'The least glamorous FMCG category has some of the most interesting economics.',
    back: [
      'The product takes longer to make than a car takes to design. Traditional fish sauce ferments for roughly nine to eighteen months, so this year’s capacity decision serves next year’s sales.',
      'Fish sauce is graded on protein, not on taste. The degree of nitrogen is the quality currency of the category, and it is the technical fact underneath the traditional-versus-industrial argument that has played out publicly in Vietnam.',
      'Local brands beat global food companies here, and it is not sentiment. Taste preference is culturally specific and varies by region within Vietnam, so recipe knowledge is a genuine barrier that scale cannot overcome.',
      'Staples resist promotion better than they resist reformulation. Households will pay a little more rather than risk ruining a familiar dish, but they will switch permanently if the taste changes.',
      'The condiment brand is really a distribution platform. Once you own a trusted flavour brand plus national reach, adjacent categories such as instant noodles and processed foods travel on the same shelf and the same trust — which is exactly how the largest Vietnamese food groups were built.',
    ],
  },
];
