// FMCG specialist depth pack A — Dairy, Beer & Alcoholic Drinks, Soft Drinks.
// These extend each sub-industry's twenty base cards into the chapters the base deck cannot
// reach: the physical supply chain, the product science, the cost stack, the commercial engine
// and the counterintuitive facts a category interviewer uses to separate candidates.

import type { DepthCard } from './industryDepthTypes';

export const DAIRY_DEPTH_CARDS: DepthCard[] = [
  {
    module: 6, topic: 'supply-chain', emoji: '🐄', type: 'fact',
    title: 'Raw milk sourcing: three companies, three different models',
    front: 'Vinamilk, TH true MILK and Dutch Lady all sell milk in Vietnam and none of them get it the same way. The sourcing model determines cost, quality control, scalability and the story the brand can credibly tell.',
    back: [
      'TH true MILK is the vertically integrated mega-farm model: very large company-owned herds in Nghe An with imported genetics, mechanised milking and total control of feed, welfare and hygiene. It buys consistency and a provenance story at the cost of enormous capital intensity and long payback.',
      'FrieslandCampina (Dutch Lady) runs the cooperative-heritage collection model: thousands of contracted smallholder farmers supplying through village collection points, with the company providing veterinary support, feed advice and quality-based pricing. Low capital, wide social footprint, and quality that must be built through farmer development rather than owned outright.',
      'Vinamilk runs the hybrid at scale: its own farm system plus a large contracted smallholder network plus imported milk powder to bridge the gap. That flexibility is exactly why it can hold more than 40% of industry revenue in brokerage estimates while others cannot.',
      'The economics that separate them: owned farms fix your cost base and your quality but tie up capital and expose you to feed and herd risk. Contracted collection is capital-light and flexible but needs constant investment in farmer capability, and quality varies by collection point.',
      'Quality control is where the models converge: raw milk is tested at collection for fat, protein, total solids, somatic cell count, antibiotic residue and bacterial load, and rejected loads are a real commercial event for a smallholder.',
      'Interview move: when asked “how would you improve dairy margin”, ask which sourcing model the company runs before answering. The lever is completely different in each case.',
    ],
    visual: [
      'THREE SOURCING MODELS',
      '  MEGA-FARM (TH)        capital heavy',
      '    own herd -> own plant -> own quality',
      '  SMALLHOLDER (Dutch Lady)  capital light',
      '    farmers -> collection point -> plant',
      '    quality built via farmer development',
      '  HYBRID (Vinamilk)     flexible',
      '    own farms + contracted milk + imported',
      '    powder to flex with demand and price',
    ],
  },
  {
    module: 6, topic: 'rnd-product', emoji: '🌡️', type: 'concept',
    title: 'Pasteurised versus UHT: the decision that shapes the whole business',
    front: 'Heat treatment is not a technical footnote. It decides shelf life, which channel you can sell through, how much working capital you tie up, and what the product is allowed to claim.',
    back: [
      'Pasteurisation heats milk to roughly 72-75 degrees Celsius for around 15 seconds, killing pathogens but leaving some spoilage organisms alive. Result: a fresh taste, a shelf life measured in days to a couple of weeks, and an absolute requirement for unbroken refrigeration.',
      'Ultra-high-temperature treatment heats milk to roughly 135-150 degrees Celsius for a few seconds and fills it into sterile aseptic packaging. Result: months of ambient shelf life, national distribution without a cold chain, and a slightly cooked flavour that Vietnamese consumers have largely accepted.',
      'Extended shelf life sits between the two, using higher heat plus tighter filling hygiene to reach a few weeks chilled — a premium fresh-milk play in modern trade.',
      'The commercial consequence is the whole point: UHT can reach general trade in the provinces where refrigeration is unreliable, so it carries volume and reach. Pasteurised fresh milk needs modern trade with working chillers, so it is an urban premium product with higher waste risk.',
      'The working-capital consequence: short shelf life means small, frequent orders, tight forecasting at store-SKU level, and expiry write-offs when you get it wrong. Ambient product forgives forecast error; chilled product punishes it immediately.',
      'Interview move: if a case asks whether to launch a fresh-milk line, the first question is not about the consumer. It is whether the target channel has reliable refrigeration.',
    ],
    visual: [
      '            PASTEURISED    ESL      UHT',
      ' Heat        72-75C/15s   ~125C   135-150C',
      ' Shelf life  days-2wks    ~3-6wk  6-9 months',
      ' Storage     chilled      chilled ambient',
      ' Channel     modern trade MT      GT + MT + rural',
      ' Waste risk  HIGH         medium  low',
      ' Taste       freshest     fresh   slightly cooked',
      ' ---------------------------------------------',
      ' Reach and freshness trade directly against',
      ' each other. Pick the channel first.',
    ],
  },
  {
    module: 6, topic: 'rnd-product', emoji: '⚗️', type: 'concept',
    title: 'Homogenisation, standardisation and spray drying, explained',
    front: 'Three processing steps appear in almost every dairy plant and almost no candidate can explain them. Each exists to solve a specific commercial problem.',
    back: [
      'Standardisation sets fat and protein content to a fixed specification by separating cream and recombining it. This is why every carton of a given product tastes identical even though raw milk composition varies by farm, season and feed.',
      'Homogenisation forces milk through a narrow valve at high pressure, shattering fat globules into much smaller ones so they no longer float. Without it a cream line separates at the top of the carton and consumers read that as spoilage — so it is a shelf-appearance decision as much as a texture one.',
      'Spray drying turns liquid milk into powder: concentrate the milk, then atomise it into a chamber of hot air so water flashes off and dry particles fall out. The result is shelf-stable, cheap to ship and storable across seasons.',
      'Why spray drying matters commercially in Vietnam: powder is how the industry stores and trades milk across time and distance. It lets a processor buy when global prices are low and produce when domestic raw supply is short.',
      'Fortification and blending sit alongside: vitamins, minerals, protein and functional ingredients are added to a base to create infant, child, adult and senior nutrition — which is where the real margin in Vietnamese dairy lives.',
      'Interview move: connect each process to the P&L. Standardisation protects the claim, homogenisation protects the shelf appearance, spray drying protects the supply chain.',
    ],
    diagram: ['Raw milk in', 'Test & chill', 'Standardise fat', 'Homogenise', 'Heat treat', 'Fill or spray dry'],
  },
  {
    module: 8, topic: 'surprising', emoji: '🤯', type: 'fact',
    title: 'How much Vietnamese milk actually starts as imported powder',
    front: 'Most people assume the milk in a Vietnamese carton came from a Vietnamese cow. The truth is more complicated in both directions — and getting it right is one of the highest-value facts in this deck.',
    back: [
      'The headline that surprises everyone: domestic fresh milk covers only around 38-45% of Vietnam’s processing demand. The rest is bridged with imported milk powder and dairy ingredients from New Zealand, Australia, the European Union and the United States, at a cost of over USD1 billion a year.',
      'But the direction of travel surprises people the other way. The share of liquid milk made from reconstituted powder collapsed from 92% in 2008 to 48.6% in 2020 and to about 32.3% in 2023 — so roughly two-thirds of liquid milk is now made from fresh milk, not powder.',
      'Both facts are true at once because powder does not only become drinking milk. It also goes into yogurt, condensed milk, ice cream, confectionery, bakery and nutrition products, which is why total import dependence stays high while the reconstituted share of liquid milk falls.',
      'Scale check (USDA): Vietnam’s herd reached about 335,000 cows producing over 1.2 million tonnes of raw milk in 2024, against roughly 2.7 million tonnes of annual consumption.',
      'The policy target frames the next decade: domestic fresh milk to meet 60-65% of processing demand by 2030 and 80-85% by 2045, with raw milk output rising toward 2.6 million tonnes and then 8 million tonnes.',
      'Why this wins points: a candidate who says “most Vietnamese milk is reconstituted” is repeating something that stopped being true. A candidate who explains that liquid milk is now mostly fresh while the industry still imports over a billion dollars of ingredients a year has actually read the market.',
    ],
    visual: [
      'LIQUID MILK MADE FROM RECONSTITUTED POWDER',
      '2008  92%',
      '2020  48.6%',
      '2023  32.3%',
      'Domestic raw milk share of total processing demand  38-45%',
      'Annual powder and ingredient imports  Over USD1bn',
      '2030 self-sufficiency target  60-65%',
    ],
  },
  {
    module: 6, topic: 'finance', emoji: '💰', type: 'concept',
    title: 'The COGS breakdown of a Vietnamese dairy brand',
    front: 'If you can build the cost stack of a carton of milk from memory, almost every dairy margin question becomes arithmetic instead of guesswork.',
    back: [
      'Raw material dominates. Raw milk or reconstituted powder is typically around half of cost of goods for a liquid dairy product, which is why farmgate and global powder prices move gross margin more than anything a marketer does.',
      'Packaging is the second block, commonly in the mid-teens as a percentage. Aseptic carton is expensive because the sterile barrier is what creates the ambient shelf life — you are paying for the supply chain, not the container.',
      'Conversion cost — factory labour, energy, depreciation, water and cleaning — usually runs around a tenth. Dairy is energy-hungry because everything is heated, cooled and cleaned in place between batches.',
      'Distribution and cold chain add roughly another tenth, higher for chilled products where refrigerated transport and chiller placement in outlets are real costs the brand often subsidises.',
      'Then come the items that turn gross margin into net: trade spend and promotional depth, distributor margin, expiry and waste, and advertising. In a case, always ask whether you are being shown gross margin or margin after trade spend — they behave very differently.',
      'Sensitivity to state out loud: if raw material is half of cost of goods, a 10% rise in milk or powder prices removes roughly 5 points of gross margin unless it is passed through in price or offset by mix.',
    ],
    visual: [
      'CARTON OF MILK: ILLUSTRATIVE COGS',
      'Raw milk / powder  50%',
      'Packaging  15%',
      'Factory conversion  10%',
      'Logistics + cold chain  10%',
      'Ingredients and additives  5%',
      'Waste, expiry and other  10%',
      'Contribution then subtracts trade spend, distributor margin and advertising.',
    ],
  },
  {
    module: 7, topic: 'supply-chain', emoji: '🧊', type: 'fact',
    title: 'The cold chain, link by link',
    front: 'Cold chain is named in every dairy interview and understood in very few. It is a sequence of links where the weakest one sets the shelf life for everything downstream.',
    back: [
      'Farm and collection: milk must be chilled to around 4 degrees Celsius within hours of milking. Village collection points with bulk cooling tanks exist precisely because smallholder farms cannot each afford one, and this link is where smallholder quality is won or lost.',
      'Transport to plant: insulated or refrigerated tankers with time and temperature logged. A load arriving warm is rejected, which is a serious commercial event for the supplying farmers.',
      'Plant and storage: chilled silos before processing, then chilled finished-goods storage for fresh products or ordinary ambient warehousing for UHT.',
      'Distribution: refrigerated trucks to distributors and modern-trade distribution centres for chilled lines. This is the link that limits how far fresh products can travel in Vietnam, and the reason UHT carries provincial and rural volume.',
      'The outlet: the final and least controllable link. The brand often funds the chiller in the store, and a chiller switched off overnight to save electricity destroys the product regardless of everything upstream.',
      'The MT project this generates: measure temperature compliance and expiry by route and outlet type, then decide whether the fix is chiller investment, delivery frequency, order quantity, or simply delisting fresh lines from outlets that cannot hold the chain.',
    ],
    diagram: ['Farm cooling', 'Tanker to plant', 'Chilled silo', 'Process & fill', 'Refrigerated DC', 'Store chiller'],
  },
  {
    module: 7, topic: 'marketing-sales', emoji: '🎯', type: 'fact',
    title: 'Dairy go-to-market: occasion, pack and channel',
    front: 'Dairy is not one market. It is a set of life-stage and occasion needs that each want a different pack, price and channel — and confusing them is the classic case-interview error.',
    back: [
      'Segment by need state, not by product: everyday family nutrition, children’s growth, infant formula, adult and senior nutrition, yogurt and gut health, and indulgence such as flavoured milk and ice cream. Each has a different buyer, decision driver and price ceiling.',
      'Pack architecture does the commercial work: small single-serve packs recruit new users and improve affordability in general trade, multipacks build household stock-up value in modern trade, and large formats serve family consumption where refrigeration exists.',
      'Channel by mission: general trade for impulse, immediate consumption and rural reach; modern trade for stock-up, premium visibility and shopper data; school and institutional channels for volume and habit formation; e-commerce for bulk nutrition and gifting.',
      'Vietnamese seasonality is real and plannable: Tet gifting lifts premium and condensed milk, school terms drive children’s nutrition, and hot weather lifts ready-to-drink and yogurt. Infant and senior nutrition are the steadiest need states.',
      'The channel evidence to quote: Vinamilk reported modern trade growing 6.5% in 2024 while traditional trade declined 2.1% — a mix shift that changes pack strategy, not just where the truck goes.',
      'Metric discipline: penetration tells you how many households bought, frequency tells you how often. Diagnose which one is broken before recommending a campaign, because they need completely different interventions.',
    ],
  },
  {
    module: 10, topic: 'people-career', emoji: '🎓', type: 'fact',
    title: 'What interviewers actually test in a dairy category case',
    front: 'Dairy cases appear constantly in Vietnamese MT interviews because the category has real physical constraints. Here is what the interviewer is scoring while you talk.',
    back: [
      'Can you scope the category correctly? The first test is whether you ask which segment — liquid milk, yogurt, formula, condensed, plant-based — before quoting any growth number. Comparing a liquid-milk share against a total-dairy market size is an instant credibility loss.',
      'Do you respect shelf life? A strong answer connects the recommendation to heat treatment, cold chain and expiry risk. A weak answer proposes a fresh-milk push into rural general trade without ever mentioning refrigeration.',
      'Can you separate sell-in from sell-out? Loading distributors before Tet inflates shipments and creates a post-holiday hangover. Interviewers deliberately present a shipment spike to see whether you ask about off-take and stock days.',
      'Can you do the cost arithmetic out loud? Raw material at roughly half of cost of goods means commodity and currency movements drive margin. Being able to say what a 10% powder price rise does to gross margin is the numerical control they are looking for.',
      'Do you diagnose before prescribing? Penetration versus frequency, premium mix versus volume, waste versus availability — name which one is broken and give the metric you would pull, rather than jumping to a campaign.',
      'And the human test: dairy sales rotations involve real time in outlets and with distributors. Interviewers probe whether you will genuinely enjoy riding a general-trade route in the heat, because that is actually part of the job.',
    ],
  },
  {
    module: 9, topic: 'surprising', emoji: '👶', type: 'fact',
    title: 'Five dairy facts that surprise candidates',
    front: 'Each of these reverses something most people assume about Vietnamese dairy.',
    back: [
      'The category is not booming. Vinamilk reported dairy consumer spending down 0.3% year on year as the category stabilised, so growth now has to come from premium mix, new occasions and exports rather than from a rising tide.',
      'Vietnamese consumers often prefer imported dairy, and local producers responded by going abroad in order to sell back home. Nutifood partnered with ViPlus Dairy in Australia to form Nutifood Australia and export products back into Vietnam — an unusual and very quotable move.',
      'Exports quietly rescue a weak domestic year. Vinamilk’s international revenue rose 12.6% in 2024 while the domestic category was flat, which makes overseas expansion a margin argument rather than a vanity project.',
      'The birth rate is a strategic risk, not a footnote. Infant formula is among the highest-margin dairy segments, and a falling birth rate structurally shrinks it — which is why every major player is building adult and senior nutrition.',
      'Provenance only pays when it is proven and visible. TH true MILK’s farm investment converts into a premium price only where shoppers can see the proof and the refrigeration works; a price gap larger than perceived value simply loses the sale.',
    ],
  },
];

export const BEER_DEPTH_CARDS: DepthCard[] = [
  {
    module: 6, topic: 'supply-chain', emoji: '🌾', type: 'concept',
    title: 'How beer is brewed, and why tanks constrain the whole business',
    front: 'Brewing is the rare FMCG process where time itself is the bottleneck. A brewery cannot simply run an extra shift to make more beer, and that single fact drives most commercial decisions in the category.',
    back: [
      'Malting and milling: barley is germinated and kilned to develop enzymes and colour, then milled. Vietnam imports almost all of its malt and hops, so raw-material cost carries direct foreign-exchange exposure.',
      'Mashing and lautering: milled malt is mixed with hot water so enzymes convert starch into fermentable sugar, then the sweet liquid (wort) is separated from the grain husks.',
      'Boiling with hops: the wort is boiled and hops are added for bitterness and aroma. Late additions give aroma, early additions give bitterness — the recipe lever behind product differentiation.',
      'Fermentation: yeast converts sugar into alcohol and carbon dioxide over roughly one to two weeks in a tank. Then lagering or conditioning holds the beer cold for a further period to clean up flavour. This is the time nobody can compress.',
      'Filtration and packaging: the beer is filtered or centrifuged, carbonated, and filled into cans, bottles or kegs. Packaging format changes the price point, the occasion and the logistics cost more than the liquid inside does.',
      'The commercial consequence: tank capacity multiplied by tank turns sets your maximum output. A promotion that outruns the plan cannot be fixed in the same month, so demand planning in beer is a capacity commitment made weeks ahead.',
    ],
    diagram: ['Malt & mill', 'Mash & lauter', 'Boil with hops', 'Ferment 7-14 days', 'Condition & filter', 'Can, bottle or keg'],
  },
  {
    module: 7, topic: 'rnd-product', emoji: '🧫', type: 'fact',
    title: 'Yeast, water and the science of tasting identical every time',
    front: 'A national beer brand promises that a can in Can Tho tastes exactly like a can in Hanoi. Delivering that is a serious technical achievement, not a marketing claim.',
    back: [
      'Yeast is the intellectual property. Each brewery propagates and re-pitches its own strain under tight control, because the yeast produces most of the flavour compounds that make a brand recognisable. Contamination or drift is a brand-level risk, not a batch-level one.',
      'Water chemistry is adjusted deliberately. Mineral content affects mash pH, hop bitterness perception and mouthfeel, so brewers treat water to a target profile rather than using whatever comes from the tap.',
      'Process control is measured continuously: original and final gravity, alcohol content, bitterness units, colour, dissolved oxygen and microbiological cleanliness. Dissolved oxygen in particular is the enemy of shelf life.',
      'Cleaning in place is a major cost and time consumer. Every tank and line is cleaned and sanitised between batches, which is part of why energy and water use are large in brewery conversion cost.',
      'Product development in Vietnam is mostly incremental and occasion-led: lower-alcohol and zero-alcohol variants, lighter or more refreshing profiles for hot weather, and premium and craft-style extensions. Reformulating a mainstream brand is genuinely risky because loyal drinkers detect change.',
      'Interview line worth using: in beer, consistency is the product. Innovation happens around the core brand, rarely inside it.',
    ],
  },
  {
    module: 6, topic: 'finance', emoji: '💵', type: 'concept',
    title: 'Beer economics: excise is rising every single year to 2031',
    front: 'Beer is one of the most heavily taxed consumer categories in Vietnam, and the tax is now on a legislated escalator. This is the single most important number in the category.',
    back: [
      'The roadmap under the Law on Excise Tax 66/2025/QH15: beer is taxed at 65% from 1 January 2026, then rises 5 percentage points a year — 70% in 2027, 75% in 2028, 80% in 2029, 85% in 2030 and 90% from 1 January 2031.',
      'Spirits follow the same shape: alcohol at 20% ABV and above goes from 65% in 2026 to 90% in 2031, while alcohol under 20% ABV runs from 35% in 2026 to 60% in 2031.',
      'Why this dominates planning: an annual, known tax increase forces an annual pricing decision. Pass it fully to the consumer and defend margin per litre while risking volume, or absorb part of it and defend volume and share.',
      'The rest of the cost stack: imported malt and hops with currency exposure, packaging that is often the largest single controllable line (aluminium cans, glass, crown caps), brewery conversion cost including energy and water, then logistics on a heavy, low-value-density product, and trade investment in the on-trade.',
      'Returnable glass changes the arithmetic in general trade: the bottle is an asset that must come back, so breakage, float size and reverse logistics become real cost lines that candidates almost never mention.',
      'The forecasting trap to name: trade will buy forward ahead of each known tax increase, so a strong December followed by a weak January may be inventory movement rather than consumption.',
    ],
    visual: [
      'BEER EXCISE ROADMAP (Law 66/2025/QH15)',
      '2026  65%',
      '2027  70%',
      '2028  75%',
      '2029  80%',
      '2030  85%',
      '2031  90%',
      'A known annual increase creates an annual pass-through-or-absorb pricing decision.',
    ],
  },
  {
    module: 7, topic: 'marketing-sales', emoji: '🍻', type: 'fact',
    title: 'On-trade versus off-trade: two different businesses',
    front: 'Where the beer is drunk changes almost everything — the pack, the price, the margin, who decides, and what the salesperson actually negotiates.',
    back: [
      'On-trade means restaurants, beer clubs, karaoke venues and street eateries, where beer is consumed on the premises. It is where brand image is built, where premium mix is achievable, and where the outlet owner is the real decision maker.',
      'Winning on-trade is an investment negotiation, not a listing: cooling equipment, glassware, signage, staff incentives, listing payments and exclusivity arrangements. The salesperson is managing a small commercial contract per outlet.',
      'Off-trade means general trade shops, supermarkets and convenience stores where beer is bought to take away. It carries the multipack and case volume, is more price-transparent, and is heavily driven by Tet gifting and promotional cycles.',
      'The pack follows the channel: kegs and single bottles or cans for on-trade immediate consumption, multipacks and cases for off-trade stock-up, and gift-format cases for the Tet season.',
      'Regulation constrains the commercial toolkit: the Law on Prevention and Control of Harmful Effects of Alcohol and Beer restricts advertising, sponsorship and sales practices, so activation is more tightly bounded than in other FMCG categories.',
      'The metric that matters most: outlet-level distribution and cold availability. A brand that is listed but warm loses to a competitor that is chilled, because beer is bought for immediate consumption.',
    ],
  },
  {
    module: 8, topic: 'marketing-sales', emoji: '🏷️', type: 'concept',
    title: 'Premiumisation and price-pack architecture in beer',
    front: 'With volume mature and tax rising every year, value growth in Vietnamese beer has to come from mix. That makes price-pack architecture the central commercial discipline.',
    back: [
      'The tier ladder runs from economy through mainstream to premium and international premium, with craft and specialty at the top. Each tier needs a distinct reason to exist — not just a different price.',
      'Premiumisation works when the occasion justifies it: celebrations, hosting guests, gifting and social display. Vietnamese drinking is highly social, which is why the on-trade is the natural home of premium.',
      'The pack is a pricing instrument: a smaller can lowers the entry price point without cutting the price per litre, while a multipack raises basket value and locks in the next few occasions.',
      'Low and no-alcohol is now a genuine segment rather than a novelty, driven directly by drink-driving enforcement rather than by health positioning — a rare case where regulation created a product category.',
      'The trap in a case: cutting price to defend volume in a category with rising excise destroys value twice, because tax is charged on the price base. Defend mix first, then availability, then price.',
      'The measurement discipline: track value share alongside volume share. In a rising-tax category, losing a little volume while gaining value share can be exactly the right outcome.',
    ],
  },
  {
    module: 8, topic: 'surprising', emoji: '🚔', type: 'fact',
    title: 'A traffic law reshaped the beer market overnight',
    front: 'The single biggest disruption to Vietnamese beer in recent years was not a competitor or a tax. It was Decree 100, and it is the best example in Vietnamese FMCG of regulation resetting consumer behaviour.',
    back: [
      'Decree 100/2019/ND-CP took effect on 1 January 2020 and imposed a zero-tolerance blood-alcohol limit for drivers, including motorbike riders, with fines large relative to average incomes and licence suspension.',
      'Because the overwhelming majority of Vietnamese journeys are by motorbike, the rule applied to nearly every on-trade occasion — unlike in markets where drink-driving rules mainly affect car drivers.',
      'The immediate effect was a sharp fall in on-trade consumption, and enforcement has been sustained rather than fading, so the behavioural change persisted rather than reverting.',
      'How the industry adapted: more at-home and off-trade consumption, growth in low and zero-alcohol variants, partnerships with ride-hailing for designated-driver style offers, and greater emphasis on food-led venues where guests arrive by taxi.',
      'Why it is a perfect interview example: it shows a demand shock that no amount of marketing could reverse, forcing a genuine portfolio and channel response. Use it when asked how you would respond to a regulatory change.',
      'Layer it with the tax escalator and you have the category thesis in one sentence: consumption occasions constrained by enforcement, and price rising every year by law — so mix and availability are the only levers left.',
    ],
  },
  {
    module: 9, topic: 'surprising', emoji: '🍺', type: 'fact',
    title: 'Five beer facts that surprise candidates',
    front: 'Beer looks like a simple category and behaves like a complicated one.',
    back: [
      'Vietnam is one of the largest beer markets in the world by volume, consuming roughly 4.6 billion litres in 2024 — far larger than its economy alone would predict, because per-capita consumption is exceptionally high by regional standards.',
      'The brewery cannot simply make more. Fermentation and conditioning take weeks, so a successful promotion that outruns the plan cannot be met in the same month. Beer demand planning is a capacity commitment, not a forecast.',
      'Packaging often costs more than the liquid. Aluminium, glass and crowns are a large share of cost of goods, which is why pack format decisions are cost decisions before they are marketing decisions.',
      'Almost all malt and hops are imported, so a Vietnamese brewer carries direct commodity and currency exposure on inputs it cannot source locally.',
      'The zero-alcohol segment exists because of a traffic law. Decree 100’s zero-tolerance limit created demand for a product that had almost no market in Vietnam beforehand — a genuinely unusual origin story for a product category.',
    ],
  },
];

export const BEVERAGE_DEPTH_CARDS: DepthCard[] = [
  {
    module: 6, topic: 'supply-chain', emoji: '🏭', type: 'concept',
    title: 'How a soft drink is made, and why the line speed matters',
    front: 'Soft drinks are the highest-velocity FMCG process of all. The liquid is cheap and simple; the money is made and lost in filling speed, packaging and distribution.',
    back: [
      'Water treatment first: incoming water is filtered, softened and disinfected to a fixed specification, because water is the majority of the product and any variation is tasted immediately.',
      'Syrup room: concentrate or flavour base is blended with sweetener, acid, preservative and colour into a simple syrup, then diluted to final strength. In a franchise system the concentrate comes from the brand owner — which is exactly where the brand’s margin sits.',
      'Carbonation and filling: carbon dioxide is dissolved under pressure and the product is filled hot or cold depending on format. Fillers run at tens of thousands of units per hour, so a few minutes of downtime is a large volume loss.',
      'Pasteurisation and aseptic filling matter for the non-carbonated lines: ready-to-drink tea, juice and dairy-based drinks need heat treatment or aseptic filling to be shelf-stable without refrigeration, which is more complex and more expensive than filling a carbonated soft drink.',
      'Packaging dominates the cost stack: PET resin, preform blowing, cans, labels, closures and secondary packaging. Many plants blow their own bottles in line, because shipping empty bottles is shipping air.',
      'The commercial consequence: with a cheap liquid and expensive packaging and logistics, beverage profitability is driven by line efficiency, packaging cost and distribution density rather than by ingredient sourcing.',
    ],
    diagram: ['Treat water', 'Blend syrup', 'Carbonate', 'Blow & fill', 'Pasteurise or aseptic', 'Pack & palletise'],
  },
  {
    module: 7, topic: 'rnd-product', emoji: '🧪', type: 'concept',
    title: 'Sweetener systems and the reformulation problem',
    front: 'The most important R&D question in Vietnamese beverages right now is how much sugar a product contains — because from 2027 that number carries a tax.',
    back: [
      'The threshold is specific: under the Law on Excise Tax 66/2025/QH15, soft drinks meeting the national standard with sugar content above 5 grams per 100 millilitres face an 8% excise tax from 1 January 2027, rising to 10% from 1 January 2028. There is no tax in 2026.',
      'The exemption list is just as important, and candidates rarely know it: milk and dairy products, natural fruit and vegetable juices and nectars, coconut water, mineral and bottled purified water, cocoa-based products and liquid nutritional products are excluded.',
      'That creates a clear reformulation incentive: bring a product below 5 grams per 100 millilitres and the tax disappears entirely. This is a cliff, not a slope, so formulation work clusters right at the threshold.',
      'The technical difficulty is that sugar does more than sweeten. It provides body, mouthfeel and preservation, so removing it changes the whole drinking experience. High-intensity sweeteners such as sucralose, acesulfame potassium, stevia and monk fruit each carry their own taste profile and aftertaste.',
      'The usual answer is a blended sweetener system plus adjustments to acidity, flavour and texturisers, validated through sensory testing panels before any launch — because a reformulated mainstream brand that tastes different loses loyal drinkers.',
      'The alternative strategies: shrink the pack so the absolute sugar per serving falls, reposition into an exempt category such as juice or coconut water, or simply accept the tax on brands where the taste cannot be changed without damaging them.',
    ],
    visual: [
      'THE 5g/100ml SUGAR CLIFF',
      '  <= 5g/100ml   ->  no excise tax',
      '   > 5g/100ml   ->  8% (2027), 10% (2028)',
      '',
      ' EXEMPT REGARDLESS OF SUGAR:',
      '   milk & dairy | natural juice & nectar',
      '   coconut water | bottled & mineral water',
      '   cocoa products | liquid nutrition',
      '  ---------------------------------------',
      '  A cliff, not a slope: formulation work',
      '  clusters exactly at the threshold.',
    ],
  },
  {
    module: 6, topic: 'finance', emoji: '💰', type: 'concept',
    title: 'Beverage economics: cheap liquid, expensive everything else',
    front: 'A beverage P&L looks nothing like a dairy or beer P&L. Knowing where the cost actually is prevents the most common wrong answer in a beverage case.',
    back: [
      'Packaging is usually the largest single cost block — PET resin or aluminium, closures, labels and secondary packaging — which is why resin and aluminium prices move gross margin more than any ingredient does.',
      'Ingredients are comparatively small: water, sweetener, acid, flavour and preservative. In a franchise system the concentrate charge from the brand owner is the exception, and it is deliberately where brand profit is captured.',
      'Logistics is disproportionately heavy because you are shipping water. Low value density means distribution cost per case is high, and it is why plants are sited close to demand and why bottles are blown in line rather than shipped.',
      'Trade investment and cooler placement are the other big line. A cold drink sells and a warm one does not, so brands fund refrigeration in outlets — a capital commitment recovered through volume through that specific cooler.',
      'From 2027 the excise tax on sugary drinks above 5 grams per 100 millilitres enters the stack at 8%, rising to 10% in 2028 — a new line that either compresses margin or raises shelf price.',
      'The diagnostic that impresses: for any beverage growth idea, ask what it does to cost per case delivered and to throughput on the filling line, not just what it does to brand awareness.',
    ],
    visual: [
      'BEVERAGE COST STACK (illustrative)',
      'Packaging  Largest cost block',
      'Ingredients  Water and sweetener',
      'Concentrate fee  Franchise systems',
      'Conversion  Line and energy',
      'Logistics  Shipping water',
      'Trade + coolers  Cold availability',
      'Excise from 2027  Applies above 5g sugar per 100ml',
      'Profit lives in line speed, pack cost and distribution density, not in ingredients.',
    ],
  },
  {
    module: 7, topic: 'marketing-sales', emoji: '❄️', type: 'fact',
    title: 'Cold availability is the whole game',
    front: 'In a hot climate with a general-trade-dominated retail base, the beverage that is cold and within reach wins. Distribution quality beats brand preference more often than candidates expect.',
    back: [
      'The purchase is usually immediate consumption and low deliberation. A shopper who wants a cold drink now will accept the second-choice brand rather than walk to another shop, so physical availability converts directly into share.',
      'Coolers are therefore a strategic asset, not equipment. Brands place branded refrigerators in outlets, negotiate what may be stocked inside them, and audit compliance — which is a large part of what a beverage sales representative actually does all day.',
      'Route to market is built for frequency: distributors serving thousands of small outlets on repeating routes, with sales representatives auditing availability, facings, cooler purity and pricing at each visit.',
      'Demand is heat-driven and genuinely volatile. A hot week can move volume sharply, which is why capacity, inventory and delivery frequency must be planned against weather and seasonal patterns rather than a smooth annual curve.',
      'The occasions that structure the category: on-the-go refreshment, meals at home and in eateries, sports and energy, social and hosting, and health or functional need states. Each maps to a different pack and channel.',
      'The metric pairing to quote: numeric distribution tells you how many outlets carry it, weighted distribution tells you how much category sales those outlets represent, and rate of sale tells you whether the listing is actually working.',
    ],
  },
  {
    module: 8, topic: 'marketing-sales', emoji: '🏷️', type: 'concept',
    title: 'Price-pack architecture in beverages',
    front: 'Beverages is the category where price-pack architecture is most visible and most decisive. The same liquid at four sizes is four different businesses.',
    back: [
      'Small single-serve formats defend an entry price point and recruit new users in general trade, where affordability per transaction matters more than price per litre.',
      'Standard on-the-go formats carry the core immediate-consumption volume and are the pack most often placed in coolers.',
      'Large and family formats serve at-home consumption and meals, sold mainly through modern trade where a shopper is stocking up rather than buying for right now.',
      'Multipacks build basket value and pre-commit the next several occasions, which is why they are the workhorse of supermarket promotions and Tet.',
      'The discipline: manage price per litre across the ladder deliberately so the tiers do not cannibalise each other, and so a promotion on the large pack does not make the profitable small pack look absurd.',
      'The Vietnam-specific twist from 2027: the sugar tax applies as a percentage, so it magnifies absolute price differences across pack sizes and may push reformulation on the largest formats first.',
    ],
  },
  {
    module: 8, topic: 'surprising', emoji: '🍵', type: 'fact',
    title: 'The Vietnamese beverage story is tea, not cola',
    front: 'Candidates default to talking about carbonated soft drinks and global brands. The distinctive Vietnamese dynamic is elsewhere, and knowing that is a genuine differentiator.',
    back: [
      'Ready-to-drink tea built on local taste preferences has been one of the strongest home-grown FMCG stories in Vietnam, with Tan Hiep Phat scaling national brands in RTD tea and energy drinks against much larger multinationals.',
      'That matters strategically because it shows local taste knowledge and distribution reach can beat global brand equity in a category where the consumer is choosing familiarity rather than aspiration.',
      'Suntory PepsiCo leads the consolidated Vietnamese landscape while Coca-Cola and Tan Hiep Phat compete with different portfolio shapes — so “the beverage market” has a different leader depending on which segment you define.',
      'Health and functional positioning is reshaping the mix: less sugar, more tea, water, coconut water, dairy-based and functional drinks — a shift the 2027 sugar tax will accelerate rather than start.',
      'The exemption list in the new excise law effectively rewards this shift, since natural juices, coconut water, dairy drinks and bottled water sit outside the tax entirely regardless of how they are positioned.',
      'Interview move: define which beverage segment you are discussing before quoting any growth number. Carbonates, RTD tea, water, energy, juice and dairy drinks are behaving quite differently from each other.',
    ],
  },
  {
    module: 9, topic: 'surprising', emoji: '🥤', type: 'fact',
    title: 'Five beverage facts that surprise candidates',
    front: 'Beverages looks like the simplest FMCG category and hides the most counterintuitive economics.',
    back: [
      'You are mostly shipping water. Low value density makes logistics one of the largest cost lines, which is why plants are placed near demand and bottles are blown on the filling line rather than transported empty.',
      'The package usually costs more than what is inside it. Resin and aluminium prices move gross margin more than any ingredient, so packaging engineering is a margin project.',
      'A refrigerator is a marketing investment. Cooler placement and cooler purity are negotiated outlet by outlet, and a warm listing loses to a cold competitor almost every time.',
      'The sugar tax is a cliff, not a slope. Above 5 grams per 100 millilitres you pay 8% from 2027 and 10% from 2028; at or below it you pay nothing — so a fraction of a gram changes the entire P&L.',
      'Milk, juice, coconut water and bottled water are exempt from that tax no matter how sweet consumers perceive them to be, because the law defines the category rather than the taste.',
    ],
  },
];
