// Industrial & Manufacturing — deep Vietnam-specific card pack (modules 6-10).
// FY2025 statistics from the National Statistics Office, MoIT export data and S&P Global PMI releases.

import type { DepthCard } from './industryDepthTypes';

export const MANUFACTURING_DEPTH_CARDS: DepthCard[] = [
  {
    module: 6, topic: 'overview', emoji: '🏭', type: 'fact',
    title: 'Vietnam manufacturing by the numbers (2025)',
    front: 'Industrial production rose about 9.2% in 2025 — the strongest in seven years — with manufacturing and processing up 10.5% and contributing 8.4 percentage points of that growth.',
    back: [
      'The wider context: GDP grew 8.02% in 2025, its second-fastest pace in fifteen years, driven by services and industry.',
      'Category detail worth quoting: fabricated metal products +12.5%, chemicals +12.4%, leather and related products +11.1%, food processing +11.0%, electronics, computers and optical products +8.3%.',
      'Employment in industrial enterprises rose about 2.4% year on year, with the fastest growth (about 3.3%) in the foreign-invested sector — evidence that FDI is still the job engine.',
      'The S&P Global Vietnam Manufacturing PMI ended 2025 at 53.0 with business confidence at a 21-month high, though input-cost inflation hit a three-and-a-half-year high after late-year storms disrupted supply.',
    ],
  },
  {
    module: 6, topic: 'overview', emoji: '💱', type: 'fact',
    title: 'FDI is the structure of the industry',
    front: 'Disbursed foreign direct investment reached USD27.62 billion in 2025, up 9% and a five-year high — and 82.8% of it went into manufacturing and processing.',
    back: [
      'Manufacturing received USD22.88 billion of realised FDI in 2025, and also took USD9.8 billion of newly registered capital, about 56.5% of the total.',
      'Within manufacturing FDI over the first ten months of 2025, electronics attracted about USD1.5 billion across 148 projects, metal fabrication USD1.2 billion across 181 projects, electrical equipment USD730 million and rubber and plastics USD663 million.',
      'Cumulatively Vietnam has attracted more than USD526 billion of FDI since the 1987 Foreign Investment Law — the base on which Samsung, Intel, LG, Foxconn, Amkor and Hana Micron built their plants.',
      'Strategic implication: much of “Vietnamese manufacturing” is foreign-owned export assembly, so the policy goal is deeper localisation — more value captured by Vietnamese suppliers and engineers.',
    ],
  },
  {
    module: 6, topic: 'finance', emoji: '💰', type: 'concept',
    title: 'Where the money is made in a factory',
    front: 'Manufacturing profit is not made at the sales meeting — it is made or lost between the loading dock and the finished-goods warehouse.',
    back: [
      'Materials usually dominate cost of goods, so procurement, yield and scrap have more leverage than direct labour in most electronics and food plants.',
      'Conversion cost — labour, energy, maintenance, depreciation — is fixed in the short run, so output per available hour drives unit cost directly.',
      'Quality loss is hidden capacity: every reworked or scrapped unit consumed material, machine time and labour that produced nothing sellable.',
      'Working capital completes the picture: raw material, work in progress and finished goods all tie up cash, and long import lead times force bigger buffers.',
      'That gives a simple test for any improvement idea: does it add good units, cut cost per good unit, or release cash? If none of the three, it is housekeeping.',
    ],
    diagram: ['Materials & suppliers', 'Conversion cost', 'Yield & quality loss', 'Inventory & lead time', 'Cost per good unit'],
  },
  {
    module: 6, topic: 'overview', emoji: '📦', type: 'fact',
    title: 'Vietnam’s export mix tells you which factories matter',
    front: 'In 2025 computers, electronics and components exported USD106 billion, up about 46% — 22.5% of all Vietnamese exports and the first single group above USD100 billion.',
    back: [
      'The rest of the top five: machinery and equipment USD58.38 billion (+11.9%), phones and accessories USD57.61 billion (+6.9%), textiles and garments USD39.29 billion (+6.1%), footwear USD23.97 billion (+4.8%).',
      'The structural shift: in 2013 roughly 60% of exports to the US were light manufacturing (garments, footwear, toys) and electronics only about 13%. Electronics has now overtaken them.',
      'What this means operationally: electronics is component-driven, capital-intensive and yield-sensitive, while garments and footwear are labour-intensive and order-cycle driven. Do not use one metric set for both.',
      'Interview move: when asked about “Vietnamese manufacturing”, ask which sector — the answer for a Samsung supplier is nothing like the answer for a Binh Duong footwear plant.',
    ],
  },
  {
    module: 6, topic: 'supply-chain', emoji: '🗺️', type: 'fact',
    title: 'Industrial geography and the rulebook',
    front: 'Where a plant sits in Vietnam decides its labour pool, logistics cost and customs exposure. Location is strategy.',
    back: [
      'Northern cluster (Bac Ninh, Bac Giang, Hai Phong, Thai Nguyen, Hung Yen): electronics and Samsung-linked supply chains, served by Hai Phong ports and the China land border.',
      'Southern cluster (Ho Chi Minh City, Binh Duong, Dong Nai, Long An, Ba Ria-Vung Tau): diversified consumer goods, garments, food and chemicals, served by Cat Lai and Cai Mep-Thi Vai.',
      'The Ministry of Industry and Trade oversees industrial policy and trade remedies; industrial parks and export-processing zones add tax and land incentives plus bonded customs treatment.',
      'Free-trade agreements are the commercial backbone: CPTPP, EVFTA, RCEP and UKVFTA set the rules of origin that decide whether a product qualifies for preferential duty — which is why local-content percentages appear in board papers.',
    ],
  },
  {
    module: 6, topic: 'supply-chain', emoji: '🔄', type: 'fact',
    title: 'Seasonality and the order cycle',
    front: 'Factories in Vietnam plan around two clocks: the export customer’s season and the domestic Tet calendar.',
    back: [
      'Export electronics peaks from mid-year through the third quarter ahead of Western holiday launches, so new-model ramp-ups and yield problems concentrate there.',
      'Garment and footwear orders follow buyer seasons, placed months ahead of shipment, so capacity booking and material lead time drive the plan.',
      'Tet is the operational cliff: two to four weeks of reduced staffing, a pre-holiday push to build stock, and post-holiday labour attrition that must be planned for rather than discovered.',
      'Weather matters more than candidates expect: late-2025 storms lengthened supplier delivery times and pushed input costs to a multi-year high, which showed up directly in PMI data.',
    ],
  },
  {
    module: 6, topic: 'overview', emoji: '🌐', type: 'quiz',
    title: 'Market check: reading the FDI number',
    front: 'Manufacturing took 82.8% of Vietnam’s USD27.62 billion of disbursed FDI in 2025. What is the sharpest implication?',
    back: ['Vietnam’s industrial growth is still led by foreign-owned export capacity, so the strategic questions are localisation, supplier development and moving up from assembly — not simply attracting more plants.'],
    options: [
      'Domestic firms now dominate manufacturing investment',
      'Growth is still led by foreign export capacity, making localisation and supplier upgrading the real strategic issue',
      'FDI is falling and factories are leaving',
      'Manufacturing FDI is mostly in services',
    ],
    answer: 1,
  },
  {
    module: 7, topic: 'people-career', emoji: '👷', type: 'role',
    title: 'What a manufacturing MT actually does',
    front: 'Industrial graduate programmes put you next to a machine, a supplier or a spreadsheet of losses — usually all three.',
    back: [
      'Operations: attend the shift handover, walk the line, record downtime reasons, run a five-why on the biggest recurring stoppage, and quantify the fix in good units per shift.',
      'Supply chain and procurement: explode the bill of materials, check supplier lead times and safety stock, and negotiate on total cost — price plus freight plus defect plus inventory — rather than piece price.',
      'Quality: pull the defect Pareto, run a control chart, lead a corrective-action review, and audit a supplier against specification.',
      'Engineering and maintenance: analyse failure modes, plan preventive maintenance, and justify a tooling or automation investment with capacity and quality gains.',
      'Planning: build the weekly production plan against demand and capacity, then explain in the S&OP meeting why a promised order cannot ship on time — with the option that fixes it.',
    ],
  },
  {
    module: 7, topic: 'finance', emoji: '📊', type: 'concept',
    title: 'The manufacturing KPI dictionary',
    front: 'These are the numbers on the board at every daily meeting. Know the formula and what each one hides.',
    back: [
      'OEE = availability x performance x quality. A line at 85% availability, 90% speed and 97% quality runs at about 74% OEE — practise that arithmetic out loud.',
      'First-pass yield — units made right the first time, before rework. Rework flatters output and hides cost.',
      'Cycle time versus takt time — how long one unit takes against how fast customer demand requires it; the gap tells you whether debottlenecking is needed at all.',
      'On-time in-full and schedule adherence — the customer’s view of the plant, not the plant’s view of itself.',
      'Scrap rate, conversion cost per unit, inventory days and unplanned downtime hours — the four levers a graduate can realistically move in a first project.',
    ],
  },
  {
    module: 7, topic: 'people-career', emoji: '🏗️', type: 'concept',
    title: 'How a Vietnamese plant is organised',
    front: 'A factory has a clear hierarchy and a clear rhythm. Knowing both makes you useful in week one.',
    back: [
      'The plant manager owns output, cost, quality and safety; production managers run shifts through supervisors and line leaders.',
      'Support functions sit alongside: quality assurance and control, maintenance and engineering, production planning, warehouse and logistics, environment-health-safety, HR and finance.',
      'The rhythm: daily shift handover and morning production meeting, weekly planning and S&OP inputs, monthly performance review and improvement-project gates.',
      'In FDI plants there is a parallel reporting line to a regional or global technical function that owns specifications, so a local change may need overseas approval.',
      'Safety is not a side topic: in most industrial interviews, a candidate who ignores safety inside an efficiency answer is marked down immediately.',
    ],
    diagram: ['Plant manager', 'Production & shifts', 'Quality & engineering', 'Planning & warehouse', 'EHS, HR & finance'],
  },
  {
    module: 7, topic: 'rnd-product', emoji: '🧰', type: 'concept',
    title: 'Lean and Six Sigma, without the buzzwords',
    front: 'Interviewers ask about lean to find out whether you understand a management system or just memorised some Japanese words.',
    back: [
      'Lean targets waste: overproduction, waiting, transport, over-processing, inventory, motion, defects — and unused talent. The goal is flow, not speed.',
      'Standard work plus 5S makes performance repeatable. Without a standard there is nothing to improve against, only opinions.',
      'Kaizen and A3 problem solving give the structure: define the gap, measure it, find root cause, test a countermeasure, standardise it.',
      'Six Sigma attacks variation through DMAIC — define, measure, analyse, improve, control — and is strongest where a process is stable but inconsistent.',
      'The credible interview line: “I would not start a lean programme. I would start with the largest measured loss and use the tool that fits it.”',
    ],
  },
  {
    module: 7, topic: 'supply-chain', emoji: '⚙️', type: 'quiz',
    title: 'Operating check: OEE arithmetic',
    front: 'A line runs at 90% availability, 95% of rated speed and 96% first-pass quality. What is OEE, roughly?',
    back: ['About 82% (0.90 x 0.95 x 0.96 = 0.821). The value of OEE is that it shows which of the three factors to attack — here, availability loss is the largest single gap.'],
    options: ['About 94%', 'About 82%', 'About 60%', 'It cannot be calculated from these numbers'],
    answer: 1,
  },
  {
    module: 8, topic: 'supply-chain', emoji: '🔀', type: 'fact',
    title: 'China-plus-one matured into competition for value',
    front: 'Vietnam has already won the relocation argument. The 2026 question is whether it moves from assembly to higher-value stages.',
    back: [
      'Evidence of the shift: electronics FDI increasingly targets advanced electronics, industrial equipment, semiconductors and data centres rather than simple assembly, with analysts describing a move from quantity-driven growth to scale and quality.',
      'The semiconductor build-out is concrete: Decision 1018/QD-TTg targets ten advanced testing-and-packaging plants by 2030, Viettel broke ground on a 32nm chip plant at Hoa Lac with trial production targeted for 2028, and Amkor and Hana Micron already operate here.',
      'The constraints are equally concrete: engineering talent depth, power reliability, logistics costs at roughly 16-20% of GDP, and a supplier base that is still thin at tier two and tier three.',
      'Honest interview framing: Vietnam competes on reliability, workforce scale and trade access — not on the lowest wage, which is no longer true against several regional peers.',
    ],
  },
  {
    module: 8, topic: 'rnd-product', emoji: '🌱', type: 'fact',
    title: 'ESG became a market-access requirement',
    front: 'For exporters, sustainability moved from reporting to revenue. The EU carbon border mechanism is the clearest example.',
    back: [
      'The EU Carbon Border Adjustment Mechanism ran a transitional reporting phase from October 2023 and moves to its definitive regime from 2026, covering cement, iron and steel, aluminium, fertilisers, electricity and hydrogen — categories Vietnam exports.',
      'Practical effect on a Vietnamese producer: measure embedded emissions per tonne, get the data verified, then either pay or lose price competitiveness against lower-carbon suppliers.',
      'Beyond carbon, brand customers audit energy intensity, water use, waste, chemical compliance and labour standards. Failing an audit can cost an order faster than a price increase.',
      'This creates real MT projects: energy metering by line, rooftop solar and power-purchase agreements, waste recovery, and supplier emissions-data collection.',
    ],
  },
  {
    module: 8, topic: 'finance', emoji: '🤖', type: 'fact',
    title: 'Automation, wages and the productivity squeeze',
    front: 'Vietnamese manufacturing is no longer cheap in absolute terms, so output per worker became the strategic variable.',
    back: [
      'Regional minimum wages were raised again for 2026 and social-insurance contributions rise with them, so labour cost per unit only stays flat if output per hour rises.',
      'Automation here is selective rather than total: material handling, machine-vision inspection, packing and palletising come first because their payback is measurable.',
      'The investment case an MT will be asked to build: capital cost versus labour saved, plus quality improvement, capacity released, and the risk of automating a process that is not yet stable.',
      'A caution worth voicing in interview: automating an unstable process locks the instability in. Standardise first, then automate.',
    ],
  },
  {
    module: 8, topic: 'supply-chain', emoji: '🛡️', type: 'fact',
    title: 'Supply-chain resilience after the shocks',
    front: 'Several years of disruption changed how factories buy. “Cheapest supplier” is no longer the default answer.',
    back: [
      'Dual sourcing and qualified alternates for critical components, even at a small premium, because a stopped line costs far more than the premium.',
      'Deliberate buffers: safety stock sized to demand variability and supplier lead-time variability, not a flat number of weeks.',
      'Nearshoring inside Vietnam: supplier-park development and tier-two localisation cut import lead time and rules-of-origin risk under CPTPP and EVFTA.',
      'Visibility tooling: supplier delivery-performance tracking, purchase-order milestone alerts and customs monitoring — the late-2025 storms proved how quickly delivery times stretch.',
    ],
  },
  {
    module: 8, topic: 'rnd-product', emoji: '🌫️', type: 'quiz',
    title: 'Trend check: carbon border exposure',
    front: 'A Vietnamese steel exporter to the EU faces the definitive carbon border regime. What is the operationally correct first response?',
    back: ['Measure and verify embedded emissions per tonne of product. The mechanism prices carbon content, and you cannot price, reduce or negotiate an exposure you cannot yet audit.'],
    options: [
      'Increase export volume before the rules start',
      'Measure and verify embedded emissions per tonne so the exposure can be priced and reduced',
      'Switch all sales to the domestic market immediately',
      'Ignore it, since the mechanism only applies to European producers',
    ],
    answer: 1,
  },
  {
    module: 9, topic: 'overview', emoji: '📱', type: 'case',
    title: 'Samsung Vietnam: the anchor tenant',
    front: 'Samsung is the most important manufacturing employer and exporter in Vietnam, and the template for FDI-led industrialisation.',
    back: [
      'Scale: Samsung has invested since 2007 and is reported to produce around half its global smartphone output in Vietnam, with major complexes in Bac Ninh, Thai Nguyen and Ho Chi Minh City.',
      'Depth beyond assembly: a Vietnamese R&D centre of roughly 2,400 engineers, a large OLED investment, and a pledge to help train 50,000 semiconductor engineers by 2030.',
      'The supplier ecosystem is the real story for Vietnamese graduates: hundreds of tier-one and tier-two vendors are held to Samsung quality, cost and delivery standards, which is where domestic capability actually gets built.',
      'Career reality: engineering and quality tracks dominate, with Korean-style process discipline, long hours during ramp-ups, and strong technical training.',
      'Interview question this unlocks: how could Vietnam capture more value from Samsung’s presence than assembly wages?',
    ],
  },
  {
    module: 9, topic: 'overview', emoji: '🏗️', type: 'case',
    title: 'Hoa Phat: the domestic heavy-industry champion',
    front: 'Hoa Phat is Vietnam’s largest steelmaker and the clearest domestic industrial scale story — with a carbon problem attached.',
    back: [
      'Business model: integrated steelmaking from raw material through construction steel and hot-rolled coil, with the Dung Quat complex expansion aimed at substituting imported flat steel used by Vietnamese manufacturers.',
      'Demand drivers: construction, public infrastructure programmes and downstream manufacturing — fabricated metal products grew 12.5% in 2025, a useful indicator of that pull.',
      'Strategic exposure: steel is covered by the EU carbon border mechanism, so emissions intensity per tonne is now a competitiveness variable in European sales, on top of cyclical prices and import competition.',
      'For an MT: heavy industry means large-scale operations, energy and process engineering, bulk-commodity procurement and port-scale logistics — a very different skill set from electronics assembly.',
      'Interview question this unlocks: how would you protect margin in a commodity business through a downcycle?',
    ],
  },
  {
    module: 9, topic: 'overview', emoji: '🥛', type: 'case',
    title: 'Vinamilk and Masan: manufacturing inside consumer companies',
    front: 'Some of the best industrial graduate roles in Vietnam sit inside consumer-goods companies, where the factory serves a brand.',
    back: [
      'Vinamilk runs a network of dairy plants and farms with nationwide cold-chain distribution; the manufacturing challenge is food safety, traceability, shelf life and changeover flexibility across hundreds of SKUs.',
      'Masan operates food processing, seasoning, instant-noodle and beverage plants that supply its own retail network, so production planning is tied directly to WinCommerce shelf demand.',
      'The operating difference from export electronics: shorter shelf life, hygiene regimes, batch traceability and far more frequent changeovers — which makes planning and yield the core disciplines.',
      'These companies typically rotate MTs through production, quality, planning and supply chain with clear links into commercial teams, which suits candidates who want industrial depth without leaving the consumer world.',
      'Interview question this unlocks: how do you balance factory utilisation against the range complexity marketing keeps adding?',
    ],
  },
  {
    module: 9, topic: 'rnd-product', emoji: '🧮', type: 'case',
    title: 'Intel, Amkor and the semiconductor back end',
    front: 'Vietnam’s semiconductor position is in assembly, packaging and test — and that is where the graduate jobs are.',
    back: [
      'Intel Products Vietnam runs a large assembly-and-test site in Ho Chi Minh City; Amkor and Hana Micron built packaging and test plants in the north, and FPT announced a domestic test-and-packaging facility.',
      'Back-end work demands extreme process control: yield, traceability, cleanroom discipline and statistical process control matter far more than labour cost.',
      'Talent pipeline: more than 7,000 chip-design engineers today against a national target of 50,000 semiconductor personnel by 2030 — roughly 15,000 in design and 35,000 in manufacturing, packaging and testing.',
      'Realistic framing: Vietnam is not competing for leading-edge fabrication yet. The credible ambition is deeper back-end capability plus design services.',
      'Interview question this unlocks: what would make Vietnam attractive for higher-value semiconductor stages, and what is genuinely missing today?',
    ],
  },
  {
    module: 9, topic: 'people-career', emoji: '📅', type: 'fact',
    title: 'Manufacturing recruitment: how to get in',
    front: 'Industrial hiring is less programme-branded than FMCG or banking, which is an advantage if you prepare properly.',
    back: [
      'Routes in: FDI plant graduate-engineer schemes (Samsung, LG, Bosch, Schneider, Foxconn suppliers), domestic group MT programmes (Masan, Hoa Phat, Vinamilk), and supply-chain graduate roles inside consumer companies.',
      'Selection usually includes a technical or numerical test, a problem-solving exercise on a shop-floor scenario, and interviews with a plant or functional manager. Some employers add a language test in Korean, Japanese or English.',
      'What differentiates candidates is a factory-floor story: a plant visit, an internship, a student project on process improvement, or a measured efficiency gain from any job — including a restaurant shift or a campus event.',
      'Be honest about location. Most plants sit in industrial provinces rather than central Hanoi or Ho Chi Minh City, and interviewers will test your willingness to be on site.',
      'Best single preparation drill: practise drawing a process flow and naming the bottleneck from a verbal description in under two minutes. It is the most commonly tested skill.',
    ],
  },
  {
    module: 10, topic: 'people-career', emoji: '🎤', type: 'fact',
    title: 'Competency questions industrial interviewers ask',
    front: 'Manufacturing interviews test structured problem solving, safety instinct and the ability to influence a shop floor.',
    back: [
      '“A line is 20% below target. Walk me through your first day.” Expected: safety check, then data on downtime, speed and quality losses before touching solutions.',
      '“Tell me about a time you improved a process.” Give the baseline, the root cause, the intervention and the measured after-state — with units.',
      '“A supervisor with 20 years of experience disagrees with your analysis. What do you do?” Take the data to the line, observe together, and let the process settle the argument.',
      '“Quality wants to stop the line and production wants to ship. Decide.” Customer risk and safety first, then containment, then root cause — and name who you escalate to.',
      '“How would you cut cost 10% without cutting quality?” Yield, scrap, downtime, energy, qualified material substitution and labour productivity — in that order.',
    ],
  },
  {
    module: 10, topic: 'overview', emoji: '🔢', type: 'fact',
    title: 'Analyst-ready Vietnam manufacturing numbers',
    front: 'These are the figures that make an industrial answer sound informed rather than generic.',
    back: [
      '2025 industrial production index +9.2% (seven-year high); manufacturing and processing +10.5%, contributing 8.4 percentage points; GDP +8.02%.',
      'Disbursed FDI USD27.62 billion (+9%), of which manufacturing USD22.88 billion or 82.8%; cumulative FDI above USD526 billion since 1987.',
      'Exports 2025: electronics and computers USD106 billion (+46%, 22.5% of exports), machinery USD58.38 billion, phones USD57.61 billion, textiles USD39.29 billion, footwear USD23.97 billion.',
      'PMI 53.0 in December 2025 with confidence at a 21-month high; S&P Global forecast industrial production growth of about 6.7% for 2026.',
      'Talent and policy: more than 7,000 chip-design engineers today, a target of 50,000 semiconductor personnel by 2030, and ten planned advanced test-and-packaging plants.',
      'Cost context: logistics at roughly 16-20% of GDP, and input-cost inflation at a three-and-a-half-year high in late 2025.',
    ],
  },
  {
    module: 10, topic: 'people-career', emoji: '🧩', type: 'concept',
    title: 'The five manufacturing case archetypes',
    front: 'Industrial cases repeat. Recognise the type and use its chain instead of a generic profitability tree.',
    back: [
      'Increase capacity: map the process, find the true bottleneck, and exhaust debottlenecking and changeover reduction before recommending capital expenditure.',
      'Reduce cost per unit: split material, conversion, quality loss and logistics, then attack the largest with a measurable mechanism.',
      'Fix quality or a customer complaint: containment first, then root cause, then permanent corrective action and a control that prevents recurrence.',
      'Make or buy: total landed cost, capability, capacity, intellectual-property risk and lead-time exposure — not piece price alone.',
      'Footprint and localisation: where to place capacity given labour, logistics, power, rules of origin and customer proximity.',
    ],
    diagram: ['Find the bottleneck', 'Cut cost per good unit', 'Contain then fix quality', 'Make vs buy', 'Footprint & localisation'],
  },
  {
    module: 10, topic: 'people-career', emoji: '👀', type: 'fact',
    title: 'What industrial interviewers are really scoring',
    front: 'Plant leaders hire graduates they can trust near a running line. That trust is built on four visible habits.',
    back: [
      'You mention safety before efficiency, without being prompted.',
      'You quantify in physical units — units per hour, minutes of downtime, percent scrap — not only percentages of revenue.',
      'You go to where the work happens. “I would watch the process for a full shift before proposing anything” is a strong, credible answer.',
      'You leave a control behind: a standard, a check, a daily metric — evidence your fix survives after you rotate out.',
    ],
  },
  {
    module: 10, topic: 'people-career', emoji: '⏱️', type: 'concept',
    title: 'Your 60-second manufacturing answer template',
    front: 'Use this chain for capacity, cost and quality questions alike.',
    back: [
      'Step 1 — Draw the flow: inputs, key process steps, outputs, and where inventory sits.',
      'Step 2 — Name the constraint and quantify it in units per hour or minutes lost.',
      'Step 3 — Split the loss into availability, speed and quality, then pick the largest.',
      'Step 4 — Give the intervention and its cost, and compare it against the capital alternative.',
      'Step 5 — State the control: which metric is reviewed daily, by whom, and what triggers escalation.',
    ],
    diagram: ['Draw the flow', 'Quantify the constraint', 'Split the loss', 'Intervention vs capex', 'Daily control'],
  },
];
