// Insurance — deep Vietnam-specific card pack (modules 6-10).
// FY2025 premium data from the National Statistics Office and Insurance Association of Vietnam;
// market shares differ by measure (total premium versus new business), so each card names which.

import type { DepthCard } from './industryDepthTypes';

export const INSURANCE_DEPTH_CARDS: DepthCard[] = [
  {
    module: 6, topic: 'overview', emoji: '🛡️', type: 'fact',
    title: 'Vietnam insurance by the numbers (2025)',
    front: 'Total premium revenue reached about VND237.2 trillion (roughly USD9.1 billion) in 2025, up 4% — but the two halves of the market are moving at completely different speeds.',
    back: [
      'Life premiums were about VND148.8 trillion, up just 0.5%; non-life premiums were about VND88.4 trillion, up 10.3% and now roughly 37% of the market.',
      'The fourth quarter showed the same split: total premiums +4.5%, life +1.1%, non-life +11.1%.',
      'Scale of the balance sheet: total industry assets about VND1,113.6 trillion (+8.6%), technical reserves +8.8%, and roughly VND959 trillion reinvested into the economy (+10.3%).',
      'Claims and benefits paid reached about VND91.8 trillion, up 13.5% — growing much faster than premiums, which is exactly the pressure point to raise in an interview.',
    ],
  },
  {
    module: 6, topic: 'surprising', emoji: '📉', type: 'fact',
    title: 'Penetration: the opportunity and the warning',
    front: 'Life insurance penetration fell from about 1.9% of GDP in 2022 to roughly 1.3% — against Thailand at about 3.5% and Taiwan at about 8.7%.',
    back: [
      'That decline was not demographic. Gross written premiums fell about 12% in 2023 and a further 5.7% in 2024 after the bancassurance mis-selling crisis destroyed consumer trust.',
      'Policy counts fell too: active policies dropped about 7.5% in 2023 and 3.7% in 2024, so the industry lost customers, not just new sales.',
      'New business premiums reset to roughly 2017 levels, and forecasters expect only modest recovery — GlobalData projects about 3.8% growth in 2026 with the life market passing USD7 billion by 2030.',
      'The correct interview framing: low penetration is an opportunity only if trust is rebuilt. Quote both the 1.3% and the reason it fell.',
    ],
  },
  {
    module: 6, topic: 'overview', emoji: '🏆', type: 'fact',
    title: 'Who competes, and how you measure it',
    front: 'Vietnam had 86 insurers at the end of 2025 — two more than 2024, including bank-affiliated Techcom Life and Alpha Reinsurance.',
    back: [
      'Life, by total premium in 2025: Bao Viet Life about 23.5%, Manulife about 17.4%, Dai-ichi Life about 11.8%, AIA about 11.6%, Prudential about 11.4% (some sources put Bao Viet nearer 22.8% and Prudential nearer 13.5%).',
      'Life, by new business premium in 2025 — a different ranking and the better read on momentum: Bao Viet Life 20.8% (up from 16.7%), Dai-ichi 13.2%, AIA 11.3%, Manulife 8.8%, Generali 7.6%, MB Life 6.6%, Prudential 6.4%, FWD 5.5%.',
      'Concentration: the top seven life insurers accounted for about 75% of new business premium in 2025 (Milliman), and bank-affiliated insurers such as MB Life and Techcom Life are climbing fast.',
      'Non-life is a different league table: as of mid-2026 PVI led with about 18.2%, then Bao Viet above 12.2%, Bao Minh 6.6%, MIC 6.3%, VBI 6%.',
    ],
  },
  {
    module: 6, topic: 'finance', emoji: '💰', type: 'concept',
    title: 'Where an insurer’s profit really comes from',
    front: 'Insurance earns in three places, and only one of them is underwriting. Say all three and you sound trained.',
    back: [
      'Underwriting result: premiums earned minus claims incurred minus expenses. For non-life this is the combined ratio; below 100% means an underwriting profit before investment income.',
      'Investment result: premiums are collected before claims are paid, so reserves are invested. Vietnamese insurers put roughly VND959 trillion back into the economy in 2025, largely in bonds and deposits.',
      'Distribution economics: first-year commission and acquisition cost can exceed first-year premium on a life policy, so profit only appears if the policy persists for years.',
      'That is why persistency is the industry’s honesty test: a policy that lapses in year two destroys the economics of the sale that created it.',
    ],
    diagram: ['Price & select risk', 'Collect premium', 'Reserve & invest', 'Pay claims', 'Retain the customer'],
  },
  {
    module: 6, topic: 'marketing-sales', emoji: '🔀', type: 'fact',
    title: 'Distribution: four channels, four sets of problems',
    front: 'In Vietnam, how a policy is sold matters more to its profitability than which product it is.',
    back: [
      'Agency: the traditional backbone — large tied agent forces with local relationships. Strengths are trust and explanation; risks are recruitment churn and inconsistent advice quality.',
      'Bancassurance: bank branches distributing insurance. Enormous reach and the centre of the mis-selling crisis, now heavily restricted.',
      'Brokers and corporate channels: dominant in non-life commercial lines — property, marine, engineering, employee benefits.',
      'Digital and partnership: e-commerce add-ons, telco and wallet distribution, microinsurance. Cheap to acquire, small ticket, and best for simple, easily understood cover.',
      'Read every distribution question through two lenses: cost of acquisition, and the likelihood the customer understood what they bought.',
    ],
  },
  {
    module: 6, topic: 'supply-chain', emoji: '⚖️', type: 'fact',
    title: 'The rulebook after the crisis',
    front: 'Vietnam’s regulatory response to the bancassurance scandal is the single most quotable piece of insurance policy in the market.',
    back: [
      'Decree 46/2023/ND-CP tightened bancassurance conduct, disclosure and bundling; the revised Insurance Business Law prohibits selling life insurance within 60 days of loan disbursement and penalises banks that tie non-mandatory policies to loans.',
      'The effect was immediate: bancassurance revenue fell about 39% in the first six months after the rules took effect (Insurance Association of Vietnam).',
      'Other constraints shaping products: compulsory motor third-party liability, solvency and reserving requirements, product approval and filing, and agent licensing and examination rules.',
      'Non-life lines are ranked by revenue as health, then property and engineering, then motor and marine — so “insurance in Vietnam” increasingly means health cover, not car cover.',
    ],
  },
  {
    module: 6, topic: 'overview', emoji: '🚦', type: 'quiz',
    title: 'Market check: two-speed market',
    front: 'Life premiums grew 0.5% in 2025 while non-life grew 10.3%. What is the best explanation?',
    back: ['Life is still recovering from the trust and conduct crisis that reset new business, while non-life — led by health, property and motor — tracks economic activity and is less exposed to long-term advice risk.'],
    options: [
      'Vietnamese people stopped buying insurance entirely',
      'Life is recovering from a conduct-driven trust collapse while non-life tracks economic activity',
      'Non-life is cheaper so it always grows faster',
      'The statistics are inconsistent',
    ],
    answer: 1,
  },
  {
    module: 7, topic: 'people-career', emoji: '📝', type: 'role',
    title: 'What an insurance MT actually does',
    front: 'Insurance graduate programmes are more analytical than candidates expect, and more customer-facing than they fear.',
    back: [
      'Product and actuarial: rebuild a pricing assumption (mortality, morbidity, lapse), test profitability under a stress scenario, and monitor actual experience against what was assumed.',
      'Distribution and bancassurance: train and support channel partners, track conversion, product mix and persistency by branch or agency, and audit whether advice met the standard.',
      'Underwriting: assess applications and medical evidence, apply exclusions or loadings, and watch for concentration and fraud indicators.',
      'Claims and operations: validate coverage, investigate complex claims, reduce turnaround time without weakening controls, and feed recurring problems back into product design.',
      'A typical first project: analyse 13-month persistency by channel and identify which sales practices predict early lapse.',
    ],
  },
  {
    module: 7, topic: 'finance', emoji: '📊', type: 'concept',
    title: 'The insurance KPI dictionary',
    front: 'These are the terms that appear in every insurance interview. Learn what each one hides as well as what it measures.',
    back: [
      'Loss ratio and combined ratio — claims over earned premium, and claims plus expenses over earned premium. Below 100% is an underwriting profit; a low ratio can also mean under-paying claims, so read it alongside complaints.',
      'Persistency (13-month and 25-month) — the share of policies still active after one or two years; the sharpest indicator of sales quality.',
      'APE and new business value — annualised premium equivalent measures the size of new sales, while new business value measures the profit those sales create. Growth in APE with falling NBV means you sold the wrong mix.',
      'Solvency ratio — available capital against required capital; the constraint on how much risk the insurer can write.',
      'Expense ratio and claims turnaround — how efficiently the promise is administered, and how fast it is honoured.',
    ],
  },
  {
    module: 7, topic: 'people-career', emoji: '🏗️', type: 'concept',
    title: 'How a Vietnamese insurer is organised',
    front: 'Insurance separates the people who sell the promise from the people who price it, and deliberately so.',
    back: [
      'Product and actuarial own pricing, reserving, profitability testing and experience monitoring — the technical core.',
      'Distribution runs agency, bancassurance, brokers and digital channels, each with its own training, incentive and compliance regime.',
      'Underwriting and risk decide which applications are accepted and on what terms, independently of sales targets.',
      'Operations and claims administer policies and pay benefits; customer service and complaints handling sit here and feed conduct reporting.',
      'Investment and finance manage reserves, asset-liability matching and solvency; compliance and internal audit oversee conduct — a much larger function since 2023.',
    ],
    diagram: ['Actuarial & product', 'Distribution', 'Underwriting', 'Claims & service', 'Investment & compliance'],
  },
  {
    module: 7, topic: 'marketing-sales', emoji: '🪝', type: 'quiz',
    title: 'Operating check: growth versus value',
    front: 'An insurer’s new-business premium rises 20% but 13-month persistency falls from 88% to 76%. What is the honest conclusion?',
    back: ['Growth was bought with sales that customers are abandoning, so acquisition cost may never be recovered. New business value and persistency — not premium volume — tell you whether the growth is real.'],
    options: [
      'The insurer is performing well because sales grew',
      'Sales grew but quality fell; the economics may be negative once lapses are counted',
      'Persistency does not affect profitability',
      'The insurer should increase commissions further',
    ],
    answer: 1,
  },
  {
    module: 8, topic: 'surprising', emoji: '💔', type: 'fact',
    title: 'The trust reset is the whole strategic story',
    front: 'Vietnam’s life industry spent four years unwinding one of Southeast Asia’s worst mis-selling episodes. Understanding that arc is the single best preparation for an insurance interview.',
    back: [
      'What happened: complex investment-linked products were sold through bank channels to customers who often believed they were buying a deposit or a loan condition. Complaints and cancellations followed.',
      'What changed: Decree 46/2023 plus the revised Insurance Business Law imposed disclosure standards, restricted bundling and banned sales within 60 days of loan disbursement.',
      'The measurable consequence: bancassurance revenue down about 39% in the first six months, gross written premiums down 12% in 2023 and 5.7% in 2024, and penetration down to about 1.3%.',
      'Where the industry is now: actuarial firm Milliman concluded in 2026 that the worst is over, with new business rebuilt on simpler products, recorded advice and quality-linked incentives.',
    ],
  },
  {
    module: 8, topic: 'rnd-product', emoji: '🏥', type: 'fact',
    title: 'Health insurance is the growth engine',
    front: 'Health is now the largest non-life line by revenue in Vietnam, and it is where demand is genuinely pulling rather than being pushed.',
    back: [
      'Drivers: rising incomes, out-of-pocket medical costs, private hospital capacity, employer benefit programmes, and a public system that covers a base rather than everything.',
      'The catch is medical inflation: claims paid across the market rose about 13.5% in 2025 while premiums rose 4%, and health portfolios are the most exposed to that gap.',
      'Management levers: provider networks and negotiated tariffs, pre-authorisation, fraud and abuse detection, product design with co-payments and sub-limits, and repricing at renewal.',
      'For a case: health is a repricing and provider-management business more than a pure underwriting one — say that and you will stand out.',
    ],
  },
  {
    module: 8, topic: 'marketing-sales', emoji: '🏦', type: 'fact',
    title: 'Bank-affiliated insurers are the new challengers',
    front: 'The most notable competitive shift of 2025-2026 is bank-linked life insurers climbing the new-business league table.',
    back: [
      'MB Life reached about 6.6% of new business premium in 2025, up four places, and newly licensed Techcom Life entered the top five on new business within its first year, surpassing several long-established foreign insurers.',
      'Their advantage is captive distribution plus data: a bank knows income, life stage and product holdings, so targeting is far cheaper than cold agency prospecting.',
      'Their risk is the same as the crisis that created the rules: closeness to lending makes conduct oversight essential, which is exactly what the 60-day rule addresses.',
      'Strategic implication for incumbents: agency quality, brand trust and claims reputation become the differentiators, since branch access can be bought by whoever owns the bank.',
    ],
  },
  {
    module: 8, topic: 'rnd-product', emoji: '📲', type: 'fact',
    title: 'Digital, insurtech and product simplification',
    front: 'The channel shift in Vietnamese insurance is toward simple products sold digitally and complex products explained in person.',
    back: [
      'Working digital lines: travel, device and accident cover, motor renewal, and small health top-ups — low ticket, easy to understand, low advice risk.',
      'Digital claims are the bigger prize: photo-based motor claims, e-KYC, straight-through processing and faster payouts directly improve retention and reduce expense ratio.',
      'Data and analytics are used for underwriting triage, fraud detection and lapse prediction, which is where quantitative graduates add value fastest.',
      'The boundary to state clearly: complex long-term savings and protection products still need human advice under the current conduct regime, so “just sell it in an app” is not a compliant answer.',
    ],
  },
  {
    module: 8, topic: 'finance', emoji: '🚨', type: 'quiz',
    title: 'Trend check: claims outpacing premiums',
    front: 'Claims paid grew 13.5% in 2025 while total premiums grew 4%. What should an analyst do with that?',
    back: ['Treat it as a margin warning and investigate by line: medical inflation, claim frequency, product design and pricing adequacy. It signals that repricing, provider management or benefit redesign is due.'],
    options: [
      'Ignore it, since claims are always volatile',
      'Treat it as a margin warning and check pricing adequacy and medical inflation by line',
      'Conclude that insurers are becoming more generous',
      'Conclude the market is shrinking',
    ],
    answer: 1,
  },
  {
    module: 9, topic: 'overview', emoji: '🇻🇳', type: 'case',
    title: 'Bao Viet Life: the incumbent that regained share',
    front: 'Bao Viet is the domestic leader and the clearest beneficiary of a market where trust became the deciding factor.',
    back: [
      'Position: about 23.5% of total life premiums in 2025 and roughly 20.8% of new business premium, up from 16.7% — a rare case of an incumbent gaining share during a downturn.',
      'Why it worked: a trusted local brand, an extensive agency force, and less dependence on the bank channel that regulation restricted.',
      'Group breadth matters too: Bao Viet is also a major non-life player with around 12% of that market, giving it a diversified book.',
      'For a candidate: expect structured, process-heavy work with strong distribution focus and a genuinely national footprint including provincial markets.',
      'Interview question this unlocks: how would you convert brand trust into higher-value products rather than only more policies?',
    ],
  },
  {
    module: 9, topic: 'overview', emoji: '🌐', type: 'case',
    title: 'Prudential, Manulife, AIA and Dai-ichi: the foreign majors',
    front: 'The four large foreign life insurers each responded differently to the conduct crisis, which is why they are a great comparative case.',
    back: [
      'Positions in 2025 by total premium: Manulife about 17.4%, Dai-ichi about 11.8%, AIA about 11.6%, Prudential about 11.4%; on new business, Dai-ichi (13.2%) and AIA (11.3%) proved most resilient.',
      'Why the resilient ones held up: diversified distribution rather than heavy bancassurance dependence, and earlier investment in agency quality and needs-based advice.',
      'Common strategic response across all four: simpler products, recorded and verified advice, persistency-linked incentives, and claims-experience improvement as a marketing asset.',
      'Programme signal: these insurers run the market’s most structured graduate schemes — Prudential’s The Strivers is the best-known — usually rotating through distribution, product or actuarial, operations and strategy.',
      'Interview question this unlocks: how would you redesign sales incentives to improve both growth and persistency at the same time?',
    ],
  },
  {
    module: 9, topic: 'overview', emoji: '🏭', type: 'case',
    title: 'PVI and the non-life commercial market',
    front: 'Non-life is a different business from life, and PVI is the case that proves it.',
    back: [
      'PVI led non-life with about 18.2% share as of mid-2026, built on energy, marine, property and engineering risks rather than retail products.',
      'Commercial non-life is broker-intermediated and reinsurance-dependent: large industrial risks are shared with international reinsurers, so pricing follows global capacity as well as local competition.',
      'Growth drivers in Vietnam are physical — FDI factories, ports, power projects, infrastructure and rising cargo volumes all need cover, which is why non-life grew 10.3% in 2025.',
      'For an MT this is technically rich work: risk surveys, sums insured, policy wordings, deductibles and reinsurance treaties, with far less mass-market advice risk.',
      'Interview question this unlocks: how would you price a new industrial risk when you have thin local claims history?',
    ],
  },
  {
    module: 9, topic: 'people-career', emoji: '📅', type: 'fact',
    title: 'Insurance recruitment: timeline and rounds',
    front: 'Insurance programmes are smaller than banking’s but less crowded, which makes them a genuinely good target for prepared candidates.',
    back: [
      'Typical cycle: applications mid-year, aptitude and sometimes numerical or actuarial tests, an assessment centre with a group case, then interviews with a function head. Foreign insurers run the most structured versions.',
      'Actuarial tracks screen for mathematics and reward progress toward professional exams; distribution and operations tracks screen for communication and process discipline.',
      'What impresses: knowing the conduct story. A candidate who can explain the 60-day rule and why persistency matters is instantly differentiated.',
      'Prepare one concrete customer-trust story — a time you explained something complex honestly, even when it cost you something.',
      'Adjacent routes worth applying to: bank bancassurance teams, insurance broking, and health-insurance product roles inside hospital groups or insurtechs.',
    ],
  },
  {
    module: 10, topic: 'people-career', emoji: '🎤', type: 'fact',
    title: 'Competency questions insurance interviewers ask',
    front: 'Insurance interviews test integrity under sales pressure, because that is the risk this industry actually lost money on.',
    back: [
      '“A customer wants a product that is not right for them but it hits your target. What do you do?” The only good answer starts with suitability and offers an alternative.',
      '“How would you explain investment-linked insurance to someone who thinks it is a savings account?” Plain language, the risk stated first, and what happens if they stop paying.',
      '“Tell me about a time you had to deliver bad news.” Claims and underwriting decisions are exactly this job.',
      '“Why does persistency matter?” Because acquisition cost is paid up front and recovered over years — and because early lapse usually means the sale was wrong.',
      '“Why insurance and not banking?” Strong answers cite long-duration risk, actuarial pricing and the trust problem rather than “financial services” in general.',
    ],
  },
  {
    module: 10, topic: 'overview', emoji: '🔢', type: 'fact',
    title: 'Analyst-ready Vietnam insurance numbers',
    front: 'These figures let you speak precisely about a market most candidates describe only in adjectives.',
    back: [
      '2025 premiums: total about VND237.2 trillion (roughly USD9.1 billion, +4%); life about VND148.8 trillion (+0.5%); non-life about VND88.4 trillion (+10.3%, roughly 37% of the market).',
      'Balance sheet and claims: industry assets about VND1,113.6 trillion (+8.6%); claims paid about VND91.8 trillion (+13.5%); roughly VND959 trillion reinvested into the economy.',
      'Penetration: life at roughly 1.3% of GDP, down from about 1.9% in 2022, against Thailand about 3.5% and Taiwan about 8.7%.',
      'Crisis arithmetic: gross written premiums fell about 12% in 2023 and 5.7% in 2024; bancassurance revenue fell about 39% in the first six months after the new rules.',
      'Shares: life by total premium — Bao Viet about 23.5%, Manulife 17.4%, Dai-ichi 11.8%, AIA 11.6%, Prudential 11.4%; non-life led by PVI at about 18.2%.',
      'Structure: 86 insurers operating, with the top seven life players at roughly 75% of new business premium.',
    ],
  },
  {
    module: 10, topic: 'people-career', emoji: '🧩', type: 'concept',
    title: 'The five insurance case archetypes',
    front: 'Insurance cases are timing cases: cash arrives before the cost is known. Structure accordingly.',
    back: [
      'Improve portfolio profitability: loss ratio by segment, expense ratio, pricing adequacy, and whether claims inflation was passed through at renewal.',
      'Fix distribution quality: persistency by channel and agent, complaint rates, incentive design, and advice verification.',
      'Launch or reprice a product: target need, pricing assumptions, reinsurance, capital use, and the conduct risk that complexity creates.',
      'Enter a new segment such as health, SME or microinsurance: claims data availability, provider or partner network, and cost to acquire per policy.',
      'Digitise a journey: decide which journeys are safe to automate, such as renewal and small claims, and which legally require advice.',
    ],
    diagram: ['Portfolio profitability', 'Distribution quality', 'Product & pricing', 'New segment', 'Digital journey'],
  },
  {
    module: 10, topic: 'people-career', emoji: '👀', type: 'fact',
    title: 'What insurance interviewers are really scoring',
    front: 'The industry needs people who can grow sales without recreating the last crisis. That is the trait being tested.',
    back: [
      'You separate premium growth from value creation, using persistency and new business value.',
      'You talk about the customer’s understanding, not only their signature.',
      'You respect the technical side: reserves, capital and reinsurance are constraints, not paperwork.',
      'You give claims proper weight — it is the moment the product becomes real, and the cheapest marketing an insurer has.',
    ],
  },
  {
    module: 10, topic: 'people-career', emoji: '⏱️', type: 'concept',
    title: 'Your 60-second insurance answer template',
    front: 'A structure that keeps you credible on any insurance question.',
    back: [
      'Step 1 — Define the risk and the pool: who is insured, against what event, over what duration.',
      'Step 2 — Explain pricing and reserving: expected claim frequency and severity, expenses, and the capital held against surprise.',
      'Step 3 — Name the distribution channel and its conduct risk.',
      'Step 4 — Give two metrics you would track: one economic (combined ratio or new business value) and one quality (persistency or complaints).',
      'Step 5 — Close on claims and trust: how the promise gets honoured, and what that does to renewal.',
    ],
    diagram: ['Risk & pool', 'Price & reserve', 'Distribute fairly', 'Economic + quality metric', 'Claims & trust'],
  },
  {
    module: 6, topic: 'supply-chain', emoji: '🗓️', type: 'fact',
    title: 'Seasonality and the sales calendar',
    front: 'Insurance demand in Vietnam is shaped by bonus season, renewal cycles and quarter-end targets — and each one creates a different conduct risk.',
    back: [
      'The pre-Tet bonus period is the strongest window for savings-linked life products, because households have lump sums to commit; it is also when unsuitable sales are most likely.',
      'Corporate health and employee-benefit programmes cluster around January renewals, so pricing and provider negotiations happen in the final quarter of the prior year.',
      'Motor and property renewals follow policy anniversaries rather than seasons, giving non-life a steadier revenue rhythm than life.',
      'Quarter-end and year-end target pressure is the classic driver of rushed advice, which is why regulators focused on incentives and post-sale confirmation rather than on product design alone.',
    ],
  },
];
