// Casemate Domain Knowledge — 2026 depth expansion for every non-FMCG deck.
// Twenty-two researched subjects per industry generate six distinct learning angles each:
// plain meaning, operating logic, economics, decision rule, scorecard, and applied scenario.

import type { DepthCard, DepthModule } from './industryDepthTypes';
import type { TopicGroupId } from './topicGroups';

const CANONICAL_TOPICS = [
  'supply-chain',
  'rnd-product',
  'finance',
  'marketing-sales',
  'people-career',
  'surprising',
] as const satisfies readonly TopicGroupId[];

type CanonicalTopic = (typeof CANONICAL_TOPICS)[number];

export interface SprintBasicCard {
  topic: CanonicalTopic;
  title: string;
  front: string;
  back: string[];
}

type Seed = [
  topic: TopicGroupId,
  title: string,
  meaning: string,
  operatingLogic: string,
  economics: string,
  application: string,
];

function moduleFor(topic: TopicGroupId): DepthModule {
  if (topic === 'glossary') return 6;
  if (topic === 'people-career') return 9;
  if (topic === 'surprising') return 10;
  if (topic === 'marketing-sales') return 8;
  if (topic === 'finance') return 8;
  return 7;
}

function expandDepth(seeds: Seed[]): Array<DepthCard & { topic: CanonicalTopic }> {
  return seeds.flatMap(([_legacyTopic, title, meaning, operatingLogic, economics, application]) =>
    CANONICAL_TOPICS.map((topic): DepthCard & { topic: CanonicalTopic } => {
      const common = { module: moduleFor(topic), topic, emoji: '' };
      switch (topic) {
        case 'supply-chain':
          return { ...common, type: 'concept', title: `${title}: operations`, front: operatingLogic, back: [meaning, application] };
        case 'rnd-product':
          return { ...common, type: 'concept', title: `${title}: product`, front: meaning, back: [operatingLogic, economics] };
        case 'finance':
          return { ...common, type: 'fact', title: `${title}: financial impact`, front: economics, back: [meaning, application] };
        case 'marketing-sales':
          return { ...common, type: 'case', title: `${title}: market decision`, front: application, back: [operatingLogic, economics] };
        case 'people-career':
          return { ...common, type: 'role', title: `${title}: career application`, front: application, back: [meaning, economics] };
        case 'surprising':
          return { ...common, type: 'fact', title: `${title}: surprising insight`, front: economics, back: [meaning, application] };
        default: {
          const unreachable: never = topic;
          return unreachable;
        }
      }
    }),
  );
}

const BANKING: Seed[] = [
  ['banking-retail', 'Retail banking versus investment banking', 'Retail banking serves households and small firms with deposits, payments, and loans; investment banking advises large clients on capital raising and transactions.', 'Retail banking depends on repeated, regulated customer journeys and a balance sheet. Investment banking depends on specialist teams, relationships, and a pipeline of deals.', 'Retail banks earn interest spread and fees but carry credit and liquidity risk. Investment banks earn advisory or underwriting fees with lumpy revenue.', 'First identify the client, product, risk owner, and revenue source; never treat the two models as interchangeable.'],
  ['banking-retail', 'Credit underwriting', 'Underwriting decides whether a borrower can and will repay, how much to lend, and at what price and conditions.', 'Banks verify identity, income, cash flow, collateral, existing debt, and behavior, then apply policy and judgment.', 'Growth creates value only when interest and fees exceed funding cost, operating cost, and expected credit loss.', 'Approve from verified repayment capacity, not collateral value alone; stress-test income and interest rates.'],
  ['banking-retail', 'Non-performing loan ratio', 'The NPL ratio is seriously impaired loans divided by total loans and is a basic signal of asset quality.', 'Delinquency moves through collection, restructuring, provisioning, write-off, and possible recovery; timing rules affect reported ratios.', 'A low NPL ratio can hide rapid denominator growth or delayed recognition, so pair it with new NPL formation, provisions, and write-offs.', 'Compare vintages and sectors before concluding that credit quality improved.'],
  ['banking-retail', 'Net interest margin', 'NIM is net interest income divided by average earning assets and shows the spread earned by the balance sheet.', 'Loan yield, deposit mix, wholesale funding, liquidity, and rate resets move NIM at different speeds.', 'Higher NIM is not automatically better if it comes from riskier borrowers or unstable funding.', 'Decompose NIM into asset yield and funding cost, then adjust for expected loss.'],
  ['banking-commercial', 'Corporate lending', 'Corporate lending finances working capital, investment, and transactions for businesses rather than individuals.', 'Relationship teams originate needs, credit teams assess repayment, legal teams secure documentation, and operations control drawdown.', 'Large tickets create concentration risk; fee income and operating deposits can make a relationship more valuable than the loan spread alone.', 'Assess the full relationship but never let ancillary revenue override credit quality.'],
  ['banking-commercial', 'Trade finance', 'Trade finance reduces payment and delivery risk in domestic and cross-border commerce through instruments such as letters of credit and guarantees.', 'Banks check documents, counterparties, sanctions, shipment terms, and credit limits before honoring an obligation.', 'Revenue comes from fees, financing, and foreign exchange, while documentary errors and counterparty failure create risk.', 'Map who must perform, what evidence triggers payment, and which party carries each risk under the Incoterm.'],
  ['banking-commercial', 'Cash management', 'Cash management helps firms collect, pay, reconcile, forecast, and concentrate liquidity.', 'APIs, virtual accounts, payroll, merchant collection, and sweeping rules connect company systems with bank accounts.', 'Stable operating balances can lower bank funding cost while automation reduces the client’s manual work and errors.', 'Design around the client’s daily process and reconciliation pain, not a list of bank products.'],
  ['banking-investment', 'M&A advisory', 'M&A advisers help a buyer or seller assess, value, negotiate, finance, and complete a company transaction.', 'A deal moves from strategy and preparation through outreach, diligence, valuation, contracts, approvals, and closing.', 'Fees are tied to mandates and completion; value depends on strategic fit, synergies, price, execution risk, and integration.', 'Recommend a deal only when the value after realistic synergies and integration risk exceeds the price.'],
  ['banking-investment', 'Private equity', 'Private equity invests in privately held businesses and seeks returns through growth, operational improvement, leverage, and eventual exit.', 'Funds source opportunities, conduct diligence, negotiate governance, support management, and sell or list the investment later.', 'Returns depend on entry price, cash-flow growth, debt paydown, and exit multiple; leverage increases both upside and downside.', 'Build the investment case from operating value creation before relying on a higher exit multiple.'],
  ['banking-investment', 'Business valuation', 'Valuation estimates what an asset or company is worth using cash flows, comparable companies, or comparable transactions.', 'Analysts forecast operating performance, choose discount rates or multiples, and test assumptions through scenarios.', 'Small changes in growth, margin, terminal value, or discount rate can move value substantially.', 'Use more than one method, explain the range, and identify which assumptions drive it.'],
  ['banking-capital-markets', 'Bonds and yield', 'A bond is a contractual loan from investors to an issuer; yield is the return implied by price and promised cash flows.', 'Coupon, maturity, seniority, security, credit quality, and market rates determine price and risk.', 'When market yields rise, existing fixed-rate bond prices usually fall; weaker credit adds a risk premium.', 'Match the instrument’s duration and credit risk to the investor’s objective and loss capacity.'],
  ['banking-capital-markets', 'Equity instruments', 'Equity represents residual ownership after creditors are paid and can provide dividends and capital gains without guaranteed repayment.', 'Public shares trade through exchanges and brokers, while private shares depend on negotiated transactions and governance rights.', 'Value reflects expected cash flows, growth, risk, dilution, and market sentiment; volatility is not the same as permanent loss.', 'Separate the quality of the business from the price paid for its shares.'],
  ['finance', 'Basel III capital', 'Basel III links bank capital and liquidity buffers to the risks a bank takes so losses are less likely to threaten depositors or the system.', 'Assets receive risk weights, losses consume capital, and liquidity standards constrain reliance on unstable short-term funding.', 'A loan with attractive revenue can destroy value if expected loss and required capital are too high.', 'Evaluate risk-adjusted return on capital, not revenue or NIM alone.'],
  ['finance', 'Liquidity risk management', 'Liquidity risk is the danger that a bank cannot meet withdrawals or payments when due without unacceptable loss.', 'Treasury forecasts cash flows, holds liquid assets, diversifies funding, sets limits, and runs stress scenarios.', 'Excess liquidity lowers returns, but too little creates failure risk; the task is resilience at a sustainable cost.', 'Test severe deposit outflow and market-closure scenarios before setting growth targets.'],
  ['finance', 'Market risk', 'Market risk is potential loss from moves in interest rates, exchange rates, equity prices, or commodity prices.', 'Banks measure positions, sensitivities, value at risk, stress losses, and limits while separating trading and banking books.', 'Hedges reduce exposure but cost money and can create basis or counterparty risk.', 'Name the exposure, time horizon, stress move, and hedge objective before choosing an instrument.'],
  ['banking-fintech', 'Vietnam digital payments', 'Vietnam’s payment ecosystem combines banks, licensed intermediaries, QR standards, wallets such as MoMo, and merchant networks.', 'Customer money and settlement remain inside regulated structures while apps simplify discovery, authorization, and reconciliation.', 'Transaction fees are thin, so frequency, merchant acceptance, fraud control, and cross-sold services determine viability.', 'Measure active use and contribution after incentives, not registrations or gross payment value alone.'],
  ['banking-fintech', 'State Bank of Vietnam oversight', 'The SBV sets monetary policy and supervises banking, payments, foreign exchange, prudential ratios, and licensed institutions.', 'Circulars translate policy into limits, classifications, reporting, and operating requirements that banks must implement.', 'Regulation can cap growth or change product economics even when customer demand is strong.', 'State the regulatory boundary first, then design a compliant commercial response.'],
  ['surprising', 'Vietnam Big Four banks', 'Agribank, BIDV, VietinBank, and Vietcombank combine enormous scale with policy and commercial roles.', 'Their branch reach, state relationships, deposits, and corporate links shape competition differently from purely private banks.', 'Scale can lower funding cost, while mandates and legacy processes can change profitability and speed.', 'Compare institutions by segment, funding, risk, and purpose instead of assuming one league table explains all.'],
  ['surprising', 'Credit growth quotas', 'Vietnam can guide system and bank-level credit growth as a macroprudential tool rather than relying only on price.', 'A bank may have borrower demand and capital yet still need room within supervisory growth limits.', 'Scarce balance-sheet capacity raises the importance of pricing, customer selection, fee products, and portfolio rotation.', 'Treat regulatory capacity as a real resource in every lending growth case.'],
  ['people-career', 'Bank relationship manager', 'A relationship manager coordinates a client’s borrowing, deposits, payments, and bank specialists while owning trust and commercial outcomes.', 'The role diagnoses needs, prepares proposals, manages credit processes, and monitors the relationship after sale.', 'Good performance combines revenue, deposit value, credit quality, conduct, and retention.', 'Demonstrate customer judgment and risk ownership, not sales activity alone.'],
  ['people-career', 'Risk analyst', 'A risk analyst turns uncertain future losses into decisions, limits, monitoring, and clear escalation.', 'The role examines data, policy exceptions, concentrations, scenarios, and outcomes, then challenges the business constructively.', 'Strong controls protect capital and trust but should target material risk rather than create friction everywhere.', 'Explain how evidence would change your decision and what signal would trigger review.'],
  ['surprising', 'Bank runs are confidence events', 'A solvent-looking bank can fail if enough depositors demand cash faster than assets can be converted safely.', 'Information spreads quickly through digital channels, while many loans cannot be sold immediately without a discount.', 'Liquidity and confidence can deteriorate before accounting capital does, making communication and credible backstops important.', 'Separate solvency from liquidity and examine both under stress.'],
];

const TECH: Seed[] = [
  ['tech-telecom', 'Vietnam telecom market', 'Viettel, VNPT/VinaPhone, and MobiFone anchor a mature mobile market that is expanding into fibre, cloud, data centres, and digital services.', 'Operators invest in spectrum and networks, acquire subscribers, manage quality, and monetize usage across consumer and enterprise segments.', 'High fixed cost means coverage, utilization, ARPU, churn, and capital discipline drive returns.', 'Evaluate the use case and willingness to pay before treating faster technology as demand.'],
  ['tech-telecom', '5G economics', '5G adds capacity, lower latency, and device density, but technology value appears only when customers use applications that pay for it.', 'Spectrum, radios, fibre backhaul, devices, and software must work together while older networks remain supported.', 'Early capital is heavy and consumer price uplift may be limited; enterprise use cases can improve returns.', 'Prioritize locations where congestion or a valuable industrial use case justifies investment.'],
  ['tech-ai-ml', 'Machine learning workflow', 'Machine learning uses historical data to learn patterns that predict, rank, classify, or generate outputs.', 'Teams define an outcome, prepare data, train or select a model, evaluate errors, deploy it, and monitor drift.', 'Value comes from better decisions or lower work after data, compute, integration, and oversight costs.', 'Compare against a clear baseline and price the cost of each kind of error.'],
  ['tech-ai-ml', 'Generative AI in business', 'Generative AI produces new text, code, images, or other content from learned patterns and instructions.', 'A useful product combines a model with trusted context, workflow integration, evaluation, permissions, and human review.', 'Model quality alone does not create ROI; adoption, task time, error cost, and inference expense matter.', 'Start with a narrow, measurable workflow where a person can verify important outputs.'],
  ['tech-semiconductor', 'Semiconductor value chain', 'The chip industry separates design, fabrication, assembly, packaging, testing, equipment, and materials across specialized firms and countries.', 'Design files become wafers in fabs, then chips are cut, packaged, tested, and qualified for customer systems.', 'Fabs are capital intensive; design depends on talent and IP; packaging competes on yield, reliability, and utilization.', 'Place Vietnam accurately in design and back-end opportunities rather than assuming leading-edge fabrication.'],
  ['tech-semiconductor', 'Chip yield', 'Yield is the share of produced chips that pass specification and can be sold.', 'Defects can arise in design, wafer processing, packaging, equipment, materials, or test, so engineers trace patterns to root causes.', 'A small yield improvement can materially lower cost because expensive processed units stop becoming scrap.', 'Improve the dominant defect mechanism and confirm reliability before raising output speed.'],
  ['tech-blockchain', 'Blockchain fundamentals', 'A blockchain is a shared append-only record useful when parties need a common history and do not want one participant to control changes.', 'Transactions are proposed, validated by agreed rules, grouped into records, and replicated across participants.', 'Security and coordination can improve, but compute, latency, governance, and compliance may exceed a normal database.', 'Use blockchain only when shared trust is the real problem and explain why a conventional database is insufficient.'],
  ['tech-blockchain', 'Web3 token economics', 'A token can coordinate access, ownership, or incentives in a network, but issuance does not create underlying demand.', 'Rules govern supply, distribution, utility, governance, custody, and transactions while markets set a volatile price.', 'Unsustainable rewards can buy temporary users and hide weak fee revenue or retention.', 'Test the non-speculative job, recurring user value, security, and legal boundary before discussing price.'],
  ['finance', 'SaaS business model', 'Software as a Service sells continuing access to hosted software, usually through recurring subscriptions.', 'The provider builds one product, operates shared infrastructure, onboards customers, supports use, and releases updates continuously.', 'ARR, gross margin, churn, expansion, CAC, and payback reveal whether recurring growth creates value.', 'Segment retention by customer cohort and include implementation and support cost.'],
  ['finance', 'Cloud computing economics', 'Cloud computing rents computing, storage, databases, and software services on demand instead of requiring every buyer to own hardware.', 'Providers pool infrastructure across regions; customers provision resources through consoles or APIs and pay by usage or commitment.', 'Cloud improves speed and converts capital to operating cost, but uncontrolled usage and data transfer can become expensive.', 'Choose architecture from reliability, security, workload shape, lock-in, and total cost rather than headline unit price.'],
  ['marketing-sales', 'Platform economics', 'A platform enables interactions between participant groups such as buyers and sellers, with each side affecting the value of the other.', 'The platform solves discovery, trust, transaction, rules, and sometimes logistics while balancing both sides.', 'Revenue may come from commission, advertising, subscriptions, or services; liquidity and contribution matter more than sign-ups.', 'Identify the constrained side and strengthen the interaction before subsidizing everyone.'],
  ['marketing-sales', 'Product management', 'Product management aligns a valuable user problem, a feasible solution, and a viable business outcome.', 'Product teams discover needs, prioritize hypotheses, define success, ship increments, and learn from behavior.', 'Roadmap activity has no value unless it improves adoption, retention, revenue, cost, or risk.', 'Prioritize by user impact, evidence, strategic fit, effort, and opportunity cost.'],
  ['marketing-sales', 'UX research', 'User-experience research observes what people need, understand, and do so product decisions are based on evidence.', 'Teams combine interviews, usability tests, analytics, and field observation, then connect findings to design choices.', 'Better usability can lift conversion and reduce support, while poor research can optimize for vocal but unrepresentative users.', 'Match the research method to the question and test behavior, not stated preference alone.'],
  ['marketing-sales', 'Interface design fundamentals', 'Good interface design makes the next action understandable, accessible, consistent, and easy to recover from.', 'Hierarchy, labels, spacing, contrast, feedback, and error prevention guide attention through a task.', 'Small friction compounds across high-frequency journeys such as checkout, login, or payment.', 'Measure task success and comprehension across real devices and accessibility needs.'],
  ['tech-fintech', 'Vietnam technology ecosystem', 'Vietnam’s ecosystem combines local platforms such as VNG, Zalo, and MoMo with telecom groups, banks, global firms, startups, and export IT services.', 'Local companies build around Vietnamese language and behavior while global capital, cloud, and supply chains extend reach.', 'Distribution habits and regulation can matter more than a globally fashionable product category.', 'Map local user behavior, partners, licences, and incumbent channels before copying another market.'],
  ['tech-fintech', 'Digital wallet economics', 'A digital wallet simplifies payment and adjacent services but usually operates through licensed financial partners and payment rails.', 'Users fund or link accounts, merchants accept transactions, and the platform manages authorization, settlement, fraud, and support.', 'Thin fees make frequency, merchant density, incentive control, and partner revenue crucial.', 'Judge active transacting cohorts and contribution after rewards, not installs.'],
  ['rnd-product', 'Cybersecurity basics', 'Cybersecurity protects the confidentiality, integrity, and availability of systems and data.', 'Teams identify assets, reduce attack paths, authenticate users, patch systems, monitor events, respond, and recover.', 'Security reduces expected loss and preserves trust, but controls must be proportionate and usable.', 'Prioritize by asset value, threat likelihood, business impact, and recovery requirement.'],
  ['rnd-product', 'Zero-trust security', 'Zero trust assumes network location alone does not make a user or device trustworthy.', 'Every important request is authenticated, authorized with least privilege, checked for context, and logged.', 'It limits breach spread but requires strong identity, device, data, and operational foundations.', 'Protect the highest-impact journeys first and verify that controls do not create unsafe workarounds.'],
  ['people-career', 'Technology career map', 'Technology careers span software, data, security, infrastructure, design, product, sales engineering, and operations.', 'Cross-functional teams combine specialties around a customer journey or technical service with shared outcomes.', 'Role value comes from solving a bottleneck, not from a fashionable title.', 'Choose a path by preferred problems, evidence of skill, and the environment in which you learn fastest.'],
  ['surprising', 'Most technology work is outside tech firms', 'Banks, manufacturers, retailers, and logistics companies employ large technology teams because software now runs their core operations.', 'These teams build channels, data platforms, automation, security, and internal systems close to valuable industry workflows.', 'Domain knowledge can be a stronger advantage than competing only on generic coding skill.', 'Search by problem and capability as well as by company category.'],
  ['surprising', 'AI accuracy is not business value', 'A model can score well in a laboratory and still fail when users ignore it, data changes, or errors are costly.', 'Deployment changes a workflow, creates new incentives, and exposes edge cases that static evaluation misses.', 'Value equals improved outcomes minus integration, review, error, and operating cost.', 'Define the decision and error budget before choosing the model.'],
  ['surprising', 'Network effects can reverse', 'A network effect helps when more participants add value, but congestion, spam, fraud, or low-quality supply can make growth harmful.', 'Platforms must curate access, ranking, trust, and enforcement as they scale.', 'Gross users can rise while successful interactions and retention decline.', 'Track interaction quality and participant outcomes, not network size alone.'],
];

const RETAIL: Seed[] = [
  ['retail-traditional-modern', 'Retail store formats', 'Hypermarkets, supermarkets, convenience stores, specialty stores, department stores, and neighbourhood shops serve different missions.', 'Format determines location, footprint, assortment, service, trip frequency, basket, and operating model.', 'Rent, labour, stock turns, margin, and sales per square metre create different break-even points.', 'Choose a format from the customer mission and local economics, not from size alone.'],
  ['retail-traditional-modern', 'Vietnam retail landscape', 'Vietnam combines wet markets and small shops with WinMart, Saigon Co.op, Central Retail, AEON, convenience chains, and e-commerce.', 'Traditional trade wins proximity and flexible baskets while modern trade adds consistency, data, and organized assortment.', 'Channel share shifts slowly because habit, fresh food, location, and household income matter.', 'Build separate customer propositions and supply models for each channel.'],
  ['supply-chain', 'Assortment planning', 'Assortment planning chooses which products, variants, sizes, and price points each store or channel should carry.', 'Retailers combine customer demand, space, supplier terms, seasonality, substitution, and local variation.', 'Too much choice traps cash and creates markdown; too little choice loses missions and basket value.', 'Set a role for every SKU and remove duplication only after testing substitution.'],
  ['marketing-sales', 'Category management', 'Category management treats a related group of products as a business with a shopper purpose and financial target.', 'A category manager sets role, assortment, shelf, price, promotion, supplier plan, and measures.', 'The goal is total category growth and profit, not simply accepting the supplier with the largest budget.', 'Start from the shopper mission and guard against shifting sales between near-identical items.'],
  ['marketing-sales', 'Retail pricing architecture', 'Pricing architecture creates understandable relationships among entry, mainstream, premium, pack sizes, and promotions.', 'Retailers monitor competitors, elasticity, costs, basket roles, and customer price perception.', 'A few known-value items shape price image while margin can come from less-comparable products.', 'Protect trust on visible items and test total basket contribution rather than item margin alone.'],
  ['marketing-sales', 'Promotion effectiveness', 'A promotion is effective only when incremental contribution and strategic learning exceed discount and execution cost.', 'Teams define baseline sales, estimate incrementality, account for stock-up and cannibalization, and inspect post-event demand.', 'Revenue can rise while profit falls if existing buyers simply pay less or switch from another product.', 'Approve from incremental units and contribution, not uplift percentage alone.'],
  ['retail-ecommerce', 'Omnichannel retail', 'Omnichannel connects stores, websites, apps, inventory, payment, delivery, and service into one customer journey.', 'Customers may discover in one channel, buy in another, return elsewhere, and expect one account and accurate availability.', 'Shared inventory improves convenience but adds picking, delivery, returns, and attribution cost.', 'Design around the end-to-end mission and assign one owner to cross-channel failures.'],
  ['retail-ecommerce', 'E-commerce contribution', 'Online retail contribution is net revenue after product cost, platform fees, marketing, picking, packing, delivery support, returns, and service.', 'Traffic converts into orders that must be fulfilled accurately and retained beyond incentives.', 'GMV can grow rapidly while each order loses cash.', 'Track contribution by cohort and order type before scaling paid traffic.'],
  ['supply-chain', 'Inventory turnover', 'Inventory turnover shows how often stock is sold and replaced during a period.', 'Demand, order size, lead time, service targets, and SKU breadth determine average inventory.', 'Faster turns release cash and reduce obsolescence but can increase stockouts when buffers become too thin.', 'Compare turnover with availability and gross margin, not in isolation.'],
  ['supply-chain', 'Replenishment planning', 'Replenishment converts store demand and stock position into orders that restore target availability.', 'Systems consider forecast, on-hand, on-order, safety stock, case pack, lead time, shelf capacity, and delivery schedule.', 'Poor parameters create both empty shelves and excess backroom stock.', 'Fix data and process exceptions before raising every safety-stock target.'],
  ['supply-chain', 'Shrinkage control', 'Shrinkage is stock lost through theft, fraud, damage, expiry, and record error.', 'Retailers combine receiving controls, rotation, access rules, cycle counts, analytics, training, and investigation.', 'Every lost unit gives up its full retail margin while some controls add labour and customer friction.', 'Target the largest verified loss mechanism and measure net benefit after control cost.'],
  ['supply-chain', 'Fresh-food waste', 'Fresh-food waste is unsold or unsafe inventory caused by short shelf life, handling, forecasting, or presentation.', 'Ordering, temperature, rotation, preparation, markdown timing, and donation or disposal rules interact daily.', 'High availability can lift sales yet destroy margin when leftovers are written off.', 'Optimize contribution and freshness together by daypart and store.'],
  ['marketing-sales', 'Customer loyalty programs', 'A loyalty program exchanges value and recognition for identifiable repeat behavior and permissioned customer insight.', 'Members earn or receive benefits while the retailer segments activity and tests personalized offers.', 'Blanket points can subsidize existing purchases; value comes from changed frequency, basket, retention, or supplier funding.', 'Measure incremental behavior against a comparable non-treated group.'],
  ['marketing-sales', 'Visual merchandising', 'Visual merchandising uses layout, displays, signs, lighting, and product presentation to make shopping easier and support the brand.', 'Teams guide traffic, clarify categories, create focal points, and maintain standards at store level.', 'A beautiful display has no value if it blocks replenishment, hides price, or fails to convert.', 'Test customer navigation, conversion, basket, and operational upkeep.'],
  ['marketing-sales', 'Private-label strategy', 'Private label is merchandise owned by the retailer and produced to its specification.', 'Retailers select categories, design positioning, source suppliers, control quality, and give the brand shelf support.', 'It can improve margin and differentiation but concentrates reputation and inventory risk with the retailer.', 'Enter where customer trust, scale, supplier capability, and a clear value gap align.'],
  ['retail-convenience', 'Convenience-store dayparts', 'Dayparts are distinct demand periods such as breakfast, lunch, afternoon, evening, and late night.', 'Assortment, food preparation, staffing, and displays change as customer missions shift through the day.', 'A small store needs high sales density, so slow stock and missed peak missions are costly.', 'Plan by store cluster and hour instead of applying one all-day assortment.'],
  ['retail-department-stores', 'Department-store concessions', 'A concession lets a brand operate space inside a department store and pay rent or commission rather than selling through simple wholesale.', 'The store curates traffic and standards while the brand may own staff, stock, pricing, and service.', 'Economics depend on footfall, conversion, sales density, commission, and shared marketing.', 'Clarify stock ownership and customer-data rights before comparing performance.'],
  ['finance', 'Store-level profit and loss', 'A store P&L shows whether one location covers product cost, labour, occupancy, utilities, shrinkage, and allocated support.', 'Sales and gross margin flow through controllable and fixed costs to store contribution.', 'Network growth can hide weak mature stores if new openings drive headline revenue.', 'Use same-store trends and four-wall contribution before approving more locations.'],
  ['people-career', 'Retail category manager career', 'A category manager combines customer insight, supplier negotiation, analytics, pricing, promotion, and inventory decisions.', 'The role works across stores, supply chain, finance, marketing, and vendors with a weekly trading rhythm.', 'Success balances sales, margin, stock turns, availability, and customer trust.', 'Show how you make a trade-off with data and then execute it in stores.'],
  ['people-career', 'Store operations leader', 'A store leader turns commercial plans into safe, consistent service through people and routines.', 'They schedule labour, receive stock, maintain standards, solve exceptions, and coach frontline teams.', 'Small improvements repeated across every shift can outweigh one large head-office idea.', 'Prioritize customer safety, availability, and the few routines that drive them.'],
  ['surprising', 'The shelf is a scarce asset', 'Shelf space is limited working capital and customer attention, not free storage.', 'Every facing changes visibility, replenishment frequency, and opportunity for another item.', 'Supplier funding can tempt a retailer to keep unproductive products that reduce category value.', 'Allocate space from demand, margin, strategic role, and service need.'],
  ['surprising', 'More stores can weaken a chain', 'Rapid expansion can cannibalize nearby stores, stretch managers, worsen supply reliability, and lock in poor sites.', 'Network effects are local: delivery routes may improve while sales per store and execution quality fall.', 'Total revenue can rise while same-store sales and return on invested capital decline.', 'Stage expansion by cluster and require repeatable unit economics before accelerating.'],
];

const MANUFACTURING: Seed[] = [
  ['supply-chain', 'Production planning', 'Production planning decides what to make, how much, and when based on demand, inventory, capacity, materials, and service goals.', 'Planners translate forecasts and orders into material plans and a feasible master schedule.', 'Too much production ties cash and risks obsolescence; too little loses sales and disrupts customers.', 'Balance service, inventory, changeover, and capacity rather than maximizing line activity.'],
  ['supply-chain', 'Detailed scheduling', 'Scheduling assigns jobs to specific machines, lines, people, and time windows.', 'Rules consider due date, setup sequence, batch size, maintenance, labour, and bottlenecks, then adapt to disruptions.', 'A feasible schedule protects throughput and delivery; frequent last-minute changes create hidden loss.', 'Freeze near-term priorities where practical and escalate only material exceptions.'],
  ['supply-chain', 'Lean manufacturing', 'Lean removes work that consumes resources without creating customer value while improving flow and problem visibility.', 'Teams stabilize standards, observe the process, reduce waiting and movement, limit work in progress, and solve causes.', 'Lower lead time and inventory release cash, but indiscriminate cuts can remove resilience or quality checks.', 'Improve flow from the customer backward and preserve controls that prevent serious risk.'],
  ['supply-chain', 'Six Sigma', 'Six Sigma is a disciplined method for reducing variation and defects using data and root-cause analysis.', 'DMAIC defines the problem, measures the baseline, analyzes causes, improves the process, and controls the gain.', 'It is valuable for recurring, measurable defects but excessive analysis can slow obvious fixes.', 'Use it when variation is material and the process can be measured reliably.'],
  ['rnd-product', 'ISO 9001 quality system', 'ISO 9001 is a management-system standard for consistent processes, customer focus, documented control, and continual improvement.', 'Organizations define responsibilities, manage documents, audit practice, correct problems, and review performance.', 'Certification supports trust but does not prove every product is defect-free.', 'Inspect whether the system changes daily behavior, not whether a certificate exists.'],
  ['rnd-product', 'Statistical process control', 'SPC uses process data over time to distinguish normal variation from signals that something changed.', 'Control charts compare measurements with statistically derived limits and trigger investigation for unusual patterns.', 'Reacting to every fluctuation can make variation worse, while ignoring a true signal creates defects.', 'Stabilize the process before tightening specifications or blaming operators.'],
  ['rnd-product', 'First-pass yield', 'First-pass yield is the share of units that meet requirements without rework or repair.', 'Defects are recorded at each step, traced to causes, corrected, and prevented through process control.', 'Rework hides poor quality while consuming labour, capacity, materials, and delivery time.', 'Track first pass separately from final pass and attack the largest repeat defect.'],
  ['supply-chain', 'Supplier integration', 'Supplier integration shares plans, specifications, quality signals, and improvement work across company boundaries.', 'Buyers segment suppliers, align forecasts, qualify changes, audit risk, and solve recurring issues jointly.', 'Partnership can reduce inventory and defects, but dependence creates concentration and information risk.', 'Integrate deeply where criticality and mutual capability justify the switching cost.'],
  ['manufacturing-electronics', 'Electronics assembly', 'Electronics assembly places and connects components into products under tight process, cleanliness, and test requirements.', 'Material kitting, surface-mount placement, soldering, assembly, software loading, test, and packing form a controlled flow.', 'Material dominates cost while yield, uptime, and customer utilization determine conversion margin.', 'Trace defects to component, machine, method, design, or handling before adding inspection.'],
  ['manufacturing-automotive', 'Automotive supplier tiers', 'Automotive supply chains organize system suppliers, component suppliers, and raw-material providers into qualified tiers.', 'Parts move through strict design approval, traceability, quality, and delivery processes before vehicle assembly.', 'Tooling and qualification create switching cost, while recalls can create losses far beyond part price.', 'Evaluate lifetime volume, warranty exposure, and customer concentration before accepting a program.'],
  ['overview', 'Vietnam industrial zones', 'Industrial zones cluster serviced land, infrastructure, factories, labour access, and administrative support for manufacturers.', 'Investors compare location, power, water, logistics, workforce, suppliers, incentives, and expansion space.', 'Low rent cannot compensate for unreliable utilities or expensive inbound and outbound movement.', 'Choose from total landed economics and resilience over the project life.'],
  ['overview', 'FDI manufacturing in Vietnam', 'Foreign direct investment has made Vietnam a major electronics, apparel, furniture, and equipment export base.', 'Anchor firms bring capital, standards, suppliers, orders, and training while local value depends on deeper domestic capability.', 'Gross exports can be high even when imported inputs keep local value added modest.', 'Measure domestic supplier depth and capability transfer, not export value alone.'],
  ['finance', 'Factory fixed and variable cost', 'Factory economics separate capacity-related fixed cost from materials, energy, labour, and other costs that move with output.', 'Volume spreads fixed cost until bottlenecks, overtime, quality loss, or new capital change the curve.', 'A low unit cost at full utilization can be misleading when demand is volatile.', 'Compare contribution, cash, and break-even across realistic utilization scenarios.'],
  ['finance', 'Capital investment approval', 'Factory CAPEX approval tests whether equipment, automation, or capacity creates enough risk-adjusted cash value.', 'Teams define need, options, throughput, labour, quality, maintenance, ramp-up, tax, and residual value.', 'Headline payback can ignore working capital, downtime, learning curve, and demand risk.', 'Approve from bottleneck relief and scenario-based cash flow, not technology appeal.'],
  ['finance', 'Labour cost dynamics', 'Labour cost includes wages, benefits, recruitment, training, overtime, turnover, supervision, and productivity.', 'A lower wage location may require more workers or suffer higher turnover and weaker supplier support.', 'Unit labour cost depends on output per paid hour, not salary alone.', 'Compare total productive labour cost and skill availability by process.'],
  ['marketing-sales', 'Export manufacturing', 'Export manufacturing serves foreign customers whose specifications, delivery windows, compliance, and currency shape the operating model.', 'Orders require sourcing, production, quality documents, customs, transport, and customer qualification.', 'FX, freight, tariffs, rejects, and payment terms can erase an apparent conversion-cost advantage.', 'Calculate landed contribution and cash cycle by destination and customer.'],
  ['rnd-product', 'Environmental compliance', 'Environmental compliance controls emissions, wastewater, waste, chemicals, and resource use within permits and law.', 'Plants monitor sources, operate treatment, maintain records, prepare emergencies, and correct exceedances.', 'Noncompliance can stop production, damage communities, trigger penalties, and lose customers.', 'Treat legal limits as constraints, then design prevention and transparent monitoring.'],
  ['people-career', 'Factory operations manager', 'An operations manager integrates safety, people, quality, delivery, cost, maintenance, and improvement across shifts.', 'Daily management reviews abnormalities, assigns owners, protects standards, and develops supervisors.', 'Optimizing one KPI can damage another, so balanced control matters.', 'Lead with safety and quality, then improve flow at the real constraint.'],
  ['people-career', 'Industrial engineer', 'Industrial engineering designs efficient work systems that combine people, equipment, material, information, and space.', 'The role studies time, layout, capacity, ergonomics, standard work, and line balance.', 'Productivity gains create value only when they produce good output without unsafe pace or hidden inventory.', 'Validate changes with operators and measure total process output.'],
  ['surprising', 'Power reliability can outweigh wages', 'Advanced factories need stable electricity quality and increasingly need credible low-carbon power.', 'Interruptions and voltage problems stop sensitive processes, damage material, and force backup investment.', 'One outage can cost more than months of wage savings on a high-value line.', 'Include power quality, redundancy, and energy source in every location case.'],
  ['surprising', 'Localisation is a capability ladder', 'Buying locally is not a percentage target; suppliers must progressively meet specification, quality, delivery, cost, traceability, and engineering requirements.', 'Supplier development moves from simple inputs toward tooling, precision components, design participation, and innovation.', 'Premature substitution can raise total cost through defects or disruption.', 'Localize by qualified capability and development plan, not nationality alone.'],
  ['surprising', 'Inventory can hide factory problems', 'Large buffers make delivery appear stable while masking unreliable equipment, long changeovers, defects, and poor planning.', 'When inventory is reduced carefully, process failures become visible and can be solved.', 'Cutting buffer before fixing instability creates shortages; keeping it forever traps cash.', 'Reduce inventory in controlled steps alongside reliability improvement.'],
];

const LOGISTICS: Seed[] = [
  ['logistics-freight', 'Road freight', 'Road freight offers flexible door-to-door movement and is the dominant domestic mode for many Vietnamese shipments.', 'Carriers plan vehicles, drivers, routes, loads, rest, tolls, and backhauls around delivery windows.', 'Fuel, utilization, empty kilometres, maintenance, and driver productivity drive cost.', 'Use road where flexibility and time justify it, then improve load factor and backhaul.'],
  ['logistics-freight', 'Ocean freight', 'Ocean freight moves large volumes internationally at low cost per unit but with longer and more variable transit.', 'Exporters book capacity, prepare containers and documents, clear customs, and connect inland legs with port schedules.', 'Rates, surcharges, detention, demurrage, container imbalance, and inventory in transit shape landed cost.', 'Plan from total lead-time risk, not the advertised sailing time.'],
  ['logistics-freight', 'Air freight', 'Air freight is fast and reliable for high-value, urgent, or perishable goods but expensive per kilogram.', 'Capacity booking, security screening, customs, ground handling, and airport connections must align.', 'Speed can prevent stockout or obsolescence, but routine air use may signal planning failure.', 'Compare the cost of delay with the full premium before expediting.'],
  ['logistics-freight', 'Rail and inland waterway', 'Rail and waterways can move dense long-haul freight efficiently where terminals, schedules, and connecting legs fit.', 'Cargo is consolidated, transferred at terminals, moved in bulk, then delivered by another mode.', 'Lower line-haul cost and emissions can be offset by handling, frequency, and first-last-mile expense.', 'Use total corridor economics and service requirement to choose multimodal routes.'],
  ['logistics-warehousing', 'Warehouse receiving', 'Receiving verifies incoming quantity, condition, identity, and documentation before stock becomes available.', 'Appointments, unloading, checks, discrepancy handling, labelling, and put-away form one controlled flow.', 'Errors at receipt propagate into inventory inaccuracy, picking failure, claims, and delay.', 'Capture problems at the dock and separate urgent exception handling from normal flow.'],
  ['logistics-warehousing', 'Warehouse slotting', 'Slotting assigns products to storage and pick locations based on velocity, size, compatibility, and handling needs.', 'Teams analyze order lines and travel, then position fast movers and related items to reduce movement safely.', 'Better slotting raises picks per hour without buying automation or space.', 'Re-slot as demand changes and protect weight, hazard, and temperature rules.'],
  ['logistics-warehousing', 'Picking accuracy', 'Picking accuracy is the share of order lines selected in the correct item and quantity.', 'Location design, scanning, labels, verification, training, and exception control prevent mistakes.', 'A wrong pick creates repacking, redelivery, returns, lost trust, and inventory error.', 'Remove ambiguity at source before adding repeated inspection.'],
  ['logistics-last-mile', 'Last-mile density', 'Delivery density is successful stops or parcels achieved within a route area and time.', 'Carriers consolidate orders, sequence routes, contact recipients, manage cash, and handle failed attempts.', 'Higher density spreads rider and vehicle cost, while failure and distance raise cost per delivered parcel.', 'Grow density in coherent zones before expanding a thin national footprint.'],
  ['logistics-last-mile', 'Cash on delivery', 'Cash on delivery lets recipients pay when a parcel arrives, but turns the carrier into a temporary cash handler.', 'Riders collect, record, reconcile, safeguard, and remit funds while merchants wait for settlement.', 'COD adds refusal, fraud, reconciliation, and working-capital cost.', 'Encourage prepayment while designing secure controls for customers who still need COD.'],
  ['logistics-last-mile', 'Reverse logistics', 'Reverse logistics moves returns, reusable assets, repairs, recycling, or disposal back through the network.', 'The process authorizes return, collects, inspects, sorts, credits, and chooses resale, repair, recovery, or disposal.', 'Poor reverse flow ties cash and space and can cost more than the original outbound move.', 'Design disposition rules before collecting everything into one warehouse.'],
  ['logistics-planning', 'Demand forecasting', 'Forecasting estimates future demand to support inventory, capacity, purchasing, and transport decisions.', 'Teams combine history, events, market signals, and judgment, then measure bias and error at the decision level.', 'A forecast has value only when it improves a decision relative to a simple baseline.', 'Use ranges and scenarios where uncertainty is larger than the benefit of false precision.'],
  ['logistics-planning', 'Safety stock', 'Safety stock is inventory held above expected demand to absorb uncertainty in demand or replenishment.', 'Its level depends on variability, lead time, desired service, review frequency, and substitution options.', 'More buffer improves availability but consumes cash and can expire or become obsolete.', 'Set service by item importance rather than applying one blanket target.'],
  ['logistics-planning', 'Inventory optimization', 'Inventory optimization balances service, order cost, holding cost, uncertainty, and product constraints across many items.', 'Items are segmented, parameters are calculated, exceptions are reviewed, and performance feeds the next cycle.', 'The goal is not minimum inventory but minimum total cost at the promised service.', 'Focus analyst attention on items where a decision can materially change outcome.'],
  ['logistics-freight', 'Incoterms', 'Incoterms define which party arranges transport, pays specified costs, and carries risk at points in an international shipment.', 'The chosen term works with the sales contract, insurance, documents, customs responsibilities, and physical handover.', 'A low purchase price can become expensive when freight risk and charges sit with the buyer.', 'State the named place and exact Incoterm version; do not assume it defines payment or title.'],
  ['logistics-freight', 'Customs compliance', 'Customs compliance ensures classification, value, origin, permits, and declarations accurately reflect traded goods.', 'Importers and brokers prepare evidence, file declarations, pay duties, respond to inspection, and retain records.', 'Errors create delay, penalties, reassessment, and licence risk far beyond saved duty.', 'Build classification and origin from product facts and auditable documents.'],
  ['logistics-freight', 'Port operations', 'A port transfers cargo between vessels and inland transport while managing berths, yards, equipment, gates, and documents.', 'Vessel planning, crane moves, yard placement, customs release, and truck appointments must synchronize.', 'Congestion increases vessel time, container dwell, truck queues, and inventory delay.', 'Improve the bottleneck across the whole port community, not one operator’s local utilization.'],
  ['overview', 'Vietnam logistics market', 'Vietnam’s trade geography combines northern and southern production clusters, long domestic corridors, major ports, and fast e-commerce delivery.', 'Local carriers such as GHN and GHTK compete with Viettel Post and international 3PLs across different service layers.', 'Fragmentation, empty backhaul, infrastructure, and manual processes keep logistics cost high.', 'Segment parcel, contract logistics, forwarding, and freight rather than treating one market average as useful.'],
  ['logistics-warehousing', 'Cold-chain logistics', 'Cold chain keeps temperature-sensitive products within a validated range from origin to use.', 'Qualified storage, vehicles, packaging, sensors, alarms, handling time, and contingency plans protect each handoff.', 'A single excursion can destroy safety or shelf life even if average temperature looks acceptable.', 'Manage lane-level exposure and proof, not equipment ownership alone.'],
  ['people-career', 'Supply-chain planner', 'A planner balances demand, stock, production, suppliers, capacity, and customer promises across time horizons.', 'The role reviews signals, resolves constraints, publishes plans, and learns from forecast and service outcomes.', 'Good planning reduces expensive firefighting without hiding uncertainty.', 'Communicate assumptions and exceptions early rather than forcing a false single number.'],
  ['people-career', 'Warehouse operations leader', 'A warehouse leader protects safety, inventory accuracy, service, productivity, and people development across shifts.', 'Daily control covers volume, staffing, equipment, backlog, errors, and abnormal conditions.', 'Speed without accuracy or safety simply moves cost downstream.', 'Stabilize standard work, then improve the largest end-to-end delay.'],
  ['surprising', 'Vietnam geography creates empty backhaul', 'The long north-south shape and uneven freight flows make it hard to find a paying return load for every truck.', 'Carriers use networks, exchanges, flexible equipment, and customer combinations to improve directional balance.', 'An empty return still consumes fuel, driver time, tolls, and asset life.', 'Price and design lanes from round-trip economics.'],
  ['surprising', 'Fast delivery can increase emissions', 'A shorter promise often fragments orders and sends vehicles before they are full.', 'Consolidation windows, local inventory, pickup points, and route density determine whether speed is efficient.', 'Revenue from speed can be outweighed by low utilization, repeated attempts, and expensive inventory placement.', 'Offer speed by customer need and charge or consolidate where urgency is low.'],
];

const INSURANCE: Seed[] = [
  ['insurance-life', 'Life versus non-life insurance', 'Life insurance covers long-duration mortality, survival, or savings-related risks; non-life covers shorter risks such as motor, property, health, and liability.', 'Life contracts require long-term assumptions and reserves, while non-life portfolios renew and reprice more frequently.', 'Persistency and investment spread matter greatly in life; loss and expense ratios dominate non-life.', 'Identify duration, insured event, reserve, and distribution economics before comparing products.'],
  ['insurance-risk', 'Underwriting principles', 'Underwriting selects and prices risks so each policy is fair to the pool and sustainable for the insurer.', 'Underwriters gather exposure information, apply rules and models, set terms, and monitor portfolio outcomes.', 'Loose underwriting can grow premium quickly while creating claims that appear later.', 'Base terms on material risk evidence and explain any exception.'],
  ['insurance-risk', 'Risk pooling', 'Insurance works by pooling many uncertain individual losses so the group’s total outcome becomes more predictable.', 'Premiums from many policyholders fund claims, expenses, reserves, capital, and a reasonable return.', 'Pools fail when risks are too correlated, badly selected, or priced without enough data and capital.', 'Check independence, concentration, and severe common-event scenarios.'],
  ['insurance-risk', 'Expected loss', 'Expected loss is the probability of an insured event multiplied by its expected financial severity.', 'Actuaries segment exposure, estimate frequency and severity, adjust for trend, and allow for uncertainty.', 'Premium must also cover expenses, capital, reinsurance, and margin, so expected loss is not the final price.', 'Separate frequency and severity to identify the real driver.'],
  ['insurance-risk', 'Actuarial reserves', 'A reserve is an estimate of money needed today for claims and obligations arising from policies already written.', 'Actuaries project future cash flows, discount where appropriate, add margins, and update assumptions as experience emerges.', 'Under-reserving overstates current profit and shifts the problem forward.', 'Inspect assumption change and development over time, not the latest point estimate alone.'],
  ['insurance-general', 'Claims management', 'Claims management verifies coverage and loss, supports the customer, controls leakage, and settles the right amount promptly.', 'Notification leads to triage, evidence, assessment, repair or treatment, fraud checks, decision, payment, and recovery.', 'Delay harms trust and adds handling cost, while weak controls increase fraud and overpayment.', 'Design fast paths for simple claims and specialist review for material exceptions.'],
  ['insurance-general', 'Motor insurance', 'Motor insurance can cover mandatory third-party liability and optional damage, theft, or other risks.', 'Pricing considers vehicle, driver, use, location, repair cost, history, and selected coverage.', 'Repair inflation, fraud, and parts cost can raise loss ratios even when claim count is stable.', 'Track claim frequency and severity separately by segment and repair channel.'],
  ['insurance-general', 'Health insurance', 'Health insurance pays covered medical costs under defined limits, networks, exclusions, and authorization rules.', 'Members access providers, claims are coded and reviewed, and insurers manage fraud, utilization, and care quality.', 'Medical inflation and unnecessary use can outpace premium growth.', 'Balance access, affordability, provider incentives, and transparent coverage.'],
  ['insurance-general', 'Property insurance', 'Property insurance protects buildings, equipment, stock, or business interruption against specified events.', 'Risk engineers assess construction, occupancy, protection, location, values, and continuity before terms are set.', 'One catastrophe can affect many policies together, so accumulation and reinsurance matter.', 'Model total exposure by location and peril, not policy by policy only.'],
  ['insurance-general', 'Liability insurance', 'Liability insurance covers defined legal obligations for injury, damage, or professional error caused to others.', 'Coverage depends on the duty, event, claim wording, defence, limits, exclusions, and jurisdiction.', 'Claims can be infrequent but severe and slow to settle.', 'Clarify the triggering event and maximum accumulation before pricing.'],
  ['insurance-risk', 'Reinsurance', 'Reinsurance transfers part of an insurer’s portfolio risk to another insurer in exchange for premium.', 'Treaties cover a defined book while facultative arrangements cover individual risks; structures can share proportionally or above a retention.', 'Reinsurance protects capital and volatility but costs margin and introduces counterparty risk.', 'Buy protection around credible severe loss and concentration scenarios.'],
  ['insurance-distribution', 'Insurance agents', 'Agents explain and distribute insurance on behalf of an insurer and must support suitable, truthful decisions.', 'Recruitment, training, needs analysis, advice, documentation, service, and supervision shape conduct.', 'Commission can encourage sales but can also create mis-selling when incentives ignore persistency and customer outcome.', 'Reward quality, retention, and compliance alongside production.'],
  ['insurance-distribution', 'Bancassurance', 'Bancassurance distributes insurance through a bank’s customer relationships and channels.', 'Banks identify eligible needs while licensed processes handle advice, consent, underwriting, and policy service.', 'Access can lower acquisition friction, but pressured or unclear sales damage trust and persistency.', 'Separate banking decisions from insurance consent and measure suitable long-term retention.'],
  ['insurance-distribution', 'Digital insurance distribution', 'Digital distribution lets customers discover, quote, buy, service, and claim through online journeys.', 'Identity, product explanation, underwriting questions, payment, documents, and support must work without hidden human fixes.', 'Automation can lower cost for simple products but abandonment and misunderstanding can rise.', 'Digitize products customers can understand and provide escalation at important decisions.'],
  ['finance', 'Loss ratio', 'Loss ratio is incurred claims divided by earned premium and shows the share of premium consumed by insured losses.', 'It includes paid claims and changes in claim reserves for the coverage already earned.', 'A low ratio may reflect under-reserving or unusually mild experience rather than durable quality.', 'Analyze by accident period, product, and claim driver.'],
  ['finance', 'Combined ratio', 'Combined ratio adds loss ratio and expense ratio for non-life insurance.', 'Claims and operating costs are compared with earned premium to reveal underwriting performance before investment income.', 'Below 100% indicates underwriting profit, but mix and reserve movement still matter.', 'Decompose the result and avoid using investment gains to excuse weak underwriting.'],
  ['finance', 'Life-policy persistency', 'Persistency measures how many policies remain active after a defined time.', 'Affordability, suitable advice, payment success, service, and product understanding influence whether customers continue.', 'Early lapse can destroy customer value and fail to recover acquisition cost.', 'Track cohorts by channel and reason, then fix suitability before retention campaigns.'],
  ['overview', 'Vietnam insurance market', 'Vietnam’s market includes Bảo Việt, Prudential, Manulife, AIA, PVI, and other life and non-life insurers under national supervision.', 'Growth depends on household protection needs, trust, bank and agent channels, digital access, and economic conditions.', 'Low penetration suggests potential but does not guarantee profitable or suitable demand.', 'Build growth from a clear protection gap and customer capacity to maintain coverage.'],
  ['overview', 'Insurance regulation in Vietnam', 'Vietnam’s insurance regulator sets licensing, solvency, product, distribution, reporting, and customer-protection requirements.', 'Insurers translate law into product approval, capital, conduct controls, disclosures, and supervision.', 'Regulation protects policyholders whose claims may arise years after sale.', 'State the legal and conduct boundary before optimizing conversion.'],
  ['people-career', 'Actuarial career', 'Actuaries use statistics, finance, and business judgment to price risk, set reserves, manage capital, and test uncertainty.', 'The work combines data, assumptions, models, governance, and communication with product, finance, and risk teams.', 'A technically precise model is ineffective if decision makers cannot understand its limits.', 'Explain assumptions, sensitivity, and business action in plain language.'],
  ['surprising', 'Insurance sells a future promise', 'Customers pay now for service that may occur much later, so trust and financial strength are part of the product.', 'Policy wording, reserves, capital, service, and claims behavior determine whether the promise is credible.', 'Aggressive acquisition can raise current premium while weakening future obligations and reputation.', 'Evaluate the entire policy lifetime, not the sale.'],
  ['surprising', 'No claim is not always success', 'A low claim rate can mean low risk, but it can also mean customers do not understand coverage or face barriers to claiming.', 'Insurers must compare expected events, notification, rejection, service, and customer outcomes.', 'Suppressing valid claims improves short-term ratios but destroys the purpose of insurance.', 'Investigate the reason for low claims before celebrating it.'],
];

const TOBACCO: Seed[] = [
  ['tobacco-operations', 'Tobacco product types', 'Combustible cigarettes burn tobacco; heated-tobacco products heat processed material; vaping products aerosolize liquid. Their mechanisms and legal status differ.', 'Each type has different materials, manufacturing, quality, waste, and risk-control requirements.', 'Global category shifts do not override Vietnam’s local prohibitions and public-health rules.', 'Begin every discussion with current law and health evidence.'],
  ['tobacco-operations', 'Leaf sourcing', 'Leaf sourcing procures agricultural tobacco with defined variety, chemistry, quality, traceability, and responsible farming controls.', 'Seed, field practice, harvest timing, curing, grading, storage, and purchase decisions shape the usable crop.', 'Weather and quality variation affect yield, inventory, blend flexibility, and farmer income.', 'Support traceable legal supply and never treat an agricultural input as uniform.'],
  ['tobacco-operations', 'Leaf curing', 'Curing controls temperature, humidity, and airflow after harvest to develop stable leaf properties.', 'Leaves move through carefully managed stages before grading and storage.', 'Poor curing destroys value that later processing cannot fully recover.', 'Use process control and farmer training to reduce variation and unsafe practice.'],
  ['tobacco-operations', 'Tobacco blending', 'Blending combines leaf grades and components to achieve a consistent legal product specification.', 'Teams manage recipes, material variability, sensory targets, availability, cost, and regulatory limits.', 'Substitution can protect supply or cost but may affect quality consistency and compliance.', 'Require specification, traceability, and approved change control.'],
  ['tobacco-operations', 'Cigarette manufacturing', 'Manufacturing converts prepared tobacco, paper, filters, and packaging into traceable finished units.', 'Primary processing conditions material; making forms rods; packing applies warnings, tax marks, and quality checks.', 'Yield, downtime, material loss, energy, and compliance determine conversion performance.', 'Never trade traceability or legal markings for throughput.'],
  ['tobacco-operations', 'Packaging traceability', 'Traceability links legal product batches and tax markings to production and controlled distribution.', 'Serials, records, reconciliation, and channel checks help distinguish legitimate supply from diversion or counterfeit.', 'Strong traceability protects tax revenue, quality accountability, and enforcement.', 'Design auditability across every handoff, not only inside the factory.'],
  ['tobacco-regulation', 'Health warnings', 'Health warnings communicate serious risks prominently on tobacco packaging under law.', 'Artwork, size, language, rotation, production control, and market inspection ensure compliant display.', 'Warnings are a public-health requirement, not optional brand communication.', 'Treat legal artwork control as a release condition for every pack.'],
  ['tobacco-regulation', 'Plain-packaging trend', 'Plain packaging standardizes pack appearance to reduce brand promotion while preserving required product identification and warnings.', 'Governments define permitted colors, fonts, placement, and markings; manufacturers adapt packaging systems.', 'The policy reduces packaging’s promotional role and can increase compliance complexity.', 'Discuss it as a health-policy instrument and plan lawful implementation only.'],
  ['tobacco-regulation', 'Advertising restrictions', 'Tobacco advertising, promotion, and sponsorship are heavily restricted because commercial exposure can encourage harmful use.', 'Rules cover media, retail, events, brand stretching, digital activity, and indirect promotion.', 'Ordinary consumer-marketing playbooks are not an available growth option.', 'Route every activity through legal and compliance review and prioritize public-health obligations.'],
  ['tobacco-regulation', 'Vietnam regulatory boundary', 'Vietnam prohibits e-cigarettes and heated-tobacco products, while legal combustible tobacco remains tightly controlled.', 'Government, customs, health, market surveillance, and licensed businesses enforce product and channel rules.', 'A global portfolio opportunity may have no lawful local route.', 'State the current Vietnam rule first and never propose a workaround.'],
  ['finance', 'Tobacco excise tax', 'Excise is a selective tax that raises tobacco price and government revenue while supporting public-health goals.', 'Tax can be ad valorem, specific, or mixed, and interacts with retail price, tax stamps, and enforcement.', 'Higher tax changes legal-market price and can strengthen health outcomes; illicit supply requires targeted enforcement.', 'Model tax transparently without treating health policy as a commercial obstacle.'],
  ['finance', 'Price-volume-mix', 'Price-volume-mix separates revenue change caused by unit price, number of units, and portfolio composition.', 'Analysts bridge one period to another and isolate tax, trade, and currency where relevant.', 'Revenue can rise even while legal volume declines, so headline growth does not imply more consumption.', 'Report each driver clearly and place declining consumption in its public-health context.'],
  ['finance', 'Illicit-trade economics', 'Illicit tobacco avoids tax and control, undercutting legal prices while bypassing age, quality, and traceability safeguards.', 'Supply may cross borders or use counterfeit channels; enforcement combines intelligence, customs, stamps, and prosecution.', 'It harms public revenue and can weaken health policy, but it is not a reason to abandon taxation.', 'Recommend lawful traceability and enforcement, never imitation or facilitation.'],
  ['tobacco-commercial', 'Restricted route to market', 'A lawful tobacco route to market moves only through permitted products, entities, outlets, and controlled records.', 'Manufacturers forecast and distribute through authorized channels while monitoring diversion and compliance.', 'Availability goals are constrained by law and public health rather than ordinary reach maximization.', 'Optimize control, forecasting, and lawful service without promotional expansion.'],
  ['tobacco-commercial', 'Portfolio premiumization', 'Premiumization is a shift in legal sales mix toward higher-priced products rather than an increase in units.', 'Price tiers, tax, adult consumer switching, and product availability change portfolio composition.', 'It can support revenue during volume decline, but must not become a youth or non-user recruitment strategy.', 'Separate mix from volume and assess every action against law and health safeguards.'],
  ['rnd-product', 'Reduced-risk evidence', 'Any reduced-risk claim requires robust independent scientific evidence about exposure, behavior, and population health, not a product label.', 'Assessment spans toxicology, clinical evidence, actual use, switching, dual use, initiation, and long-term surveillance.', 'Lower measured exposure does not automatically prove lower disease risk or positive population impact.', 'Use cautious evidence language and follow local law, which may prohibit the product.'],
  ['rnd-product', 'Quality control in tobacco', 'Quality control verifies legal materials, dimensions, moisture, physical integrity, packaging, warnings, and traceability.', 'Sampling and in-line checks detect drift while release systems prevent nonconforming product entering lawful channels.', 'Consistency cannot make a harmful product safe; quality control protects specification and compliance only.', 'Use precise scope and never confuse manufacturing quality with health safety.'],
  ['people-career', 'Tobacco compliance role', 'Compliance professionals translate health, tax, product, trade, and conduct rules into controls and decisions.', 'They review activities, train teams, monitor execution, investigate concerns, and escalate independently.', 'The function protects legal licence and public trust and must be able to stop activity.', 'Demonstrate independence, documentation, and willingness to choose the lawful outcome.'],
  ['people-career', 'Agronomy career', 'Agronomy roles support legal crop quality, farmer practice, traceability, safety, and environmental stewardship.', 'Teams work across seed, soil, inputs, harvest, curing, procurement, and farmer development.', 'Better yield and consistency can improve farmer economics while reducing waste and unsafe input use.', 'Focus on responsible agriculture and transferable crop-science skills.'],
  ['surprising', 'Declining volume can coexist with revenue growth', 'Price, tax, and mix can lift nominal revenue while the number of legal units sold falls.', 'A proper bridge separates units, manufacturer net price, excise, and portfolio mix.', 'This pattern is common in mature regulated categories and must not be misread as consumption growth.', 'Always report volume beside value.'],
  ['surprising', 'Illicit trade is geographically concentrated', 'Illicit supply often clusters around particular borders and routes rather than spreading evenly across a country.', 'Targeted intelligence and enforcement can therefore outperform broad commercial assumptions.', 'National averages can hide local hotspots and waste inspection resources.', 'Segment by route and evidence while avoiding unsupported accusations.'],
  ['surprising', 'Regulation defines the strategy set', 'In heavily regulated harmful categories, many ordinary growth tactics are intentionally unavailable.', 'Law, health policy, tax, product status, and channel permission determine what can be considered before economics.', 'A commercially attractive idea outside that boundary has zero legitimate value.', 'Filter options for legality and public-health impact before scoring financial return.'],
];

const BASIC: Seed[] = [
  ['glossary', 'Term Sheet: scarcity', 'Scarcity means wants exceed the limited time, money, labour, or resources available.', 'Every choice uses a constrained resource and therefore prevents another use.', 'Scarcity creates trade-offs even when no cash changes hands.', 'Name the constrained resource before proposing a solution.'],
  ['glossary', 'Term Sheet: opportunity cost', 'Opportunity cost is the value of the best alternative given up when a choice is made.', 'Choosing one project consumes capital and attention that cannot be used elsewhere at the same time.', 'A profitable option can still be wrong when another feasible option creates more value.', 'Compare against the best realistic alternative, not doing nothing only.'],
  ['glossary', 'Term Sheet: marginal change', 'Marginal means the effect of one additional unit or small change rather than the total average.', 'Decisions compare the extra benefit with the extra cost at the current level.', 'A business may be profitable overall while one more order loses money.', 'Use marginal analysis for the next decision and average analysis for overall performance.'],
  ['economics-micro', 'Demand curve', 'A demand curve shows how much buyers would purchase at different prices, holding other important factors constant.', 'Income, tastes, substitutes, expectations, and buyer count can shift the whole curve.', 'Price movement changes quantity demanded; a demand shift changes willingness to buy at every price.', 'Separate movement along the curve from a shift before explaining sales change.'],
  ['economics-micro', 'Supply curve', 'A supply curve shows how much sellers would offer at different prices, holding other conditions constant.', 'Input cost, technology, capacity, expectations, and seller count can shift supply.', 'Higher cost can raise equilibrium price and reduce quantity even when demand is unchanged.', 'Identify whether the shock came from buyers, sellers, or both.'],
  ['economics-micro', 'Elasticity', 'Elasticity measures how strongly one variable responds proportionally to another.', 'Price elasticity compares percentage quantity change with percentage price change while cross-elasticity examines substitutes or complements.', 'Elastic demand makes price increases risky for revenue; inelastic demand raises policy and fairness questions for essentials.', 'Estimate within the relevant range and time period rather than using one universal number.'],
  ['economics-micro', 'Consumer surplus', 'Consumer surplus is the difference between what a buyer was willing to pay and what the buyer actually paid.', 'Different buyers have different willingness to pay, creating surplus across units sold.', 'Pricing, quality, and competition divide total value between customers and firms.', 'Use it to discuss welfare and value capture without assuming higher firm profit is the only objective.'],
  ['economics-micro', 'Market structures', 'Perfect competition, monopolistic competition, oligopoly, and monopoly describe different seller concentration, differentiation, and entry barriers.', 'Structure shapes pricing power, rivalry, innovation, and strategic reaction.', 'An oligopolist must anticipate competitors, while a price-taking firm mainly manages cost.', 'Classify from evidence about alternatives and barriers, not company size alone.'],
  ['economics-micro', 'Game theory', 'Game theory studies decisions whose outcomes depend on what other decision makers choose.', 'Players, actions, payoffs, information, timing, and repeated interaction define the game.', 'A locally best move can create a poor joint outcome, as in a price war.', 'Map likely reactions and incentives before recommending a move.'],
  ['economics-micro', 'Externalities', 'An externality is a cost or benefit affecting people outside the transaction and not fully reflected in price.', 'Pollution creates external cost; vaccination can create external benefit.', 'Unpriced effects make private decisions diverge from social value.', 'Consider tax, subsidy, standards, property rights, or information based on the mechanism.'],
  ['economics-macro', 'GDP and growth', 'GDP measures final goods and services produced within an economy during a period.', 'Consumption, investment, government spending, and net exports form the expenditure measure.', 'Real GDP removes price change while GDP per person gives a rough scale of average output, not wellbeing.', 'Use several indicators and state whether figures are nominal, real, total, or per person.'],
  ['economics-macro', 'Inflation', 'Inflation is a sustained rise in the general price level that reduces money’s purchasing power.', 'Demand pressure, supply shocks, wages, expectations, exchange rates, and money conditions can contribute.', 'Different households face different baskets, so one index is an average experience.', 'Diagnose the source and persistence before choosing a policy.'],
  ['economics-macro', 'Monetary policy', 'Monetary policy uses interest rates, liquidity, and related tools to influence demand, inflation, credit, and exchange conditions.', 'Central-bank actions pass through market rates, banks, borrowers, asset prices, and expectations with delay.', 'Tighter policy can slow inflation and growth; looser policy can support demand but add price or financial risk.', 'Account for lag, banking conditions, and supply-side causes.'],
  ['economics-macro', 'Fiscal policy', 'Fiscal policy uses government spending, taxes, and transfers to influence demand, distribution, and productive capacity.', 'Budgets direct resources and automatically respond to the cycle through taxes and benefits.', 'Deficits can stabilize recession or fund investment but create debt-service and crowding risks when poorly used.', 'Judge the purpose, timing, multiplier, financing, and long-term capacity effect.'],
  ['economics-macro', 'Vietnam macroeconomic profile', 'Vietnam is a fast-growing, trade-intensive manufacturing and services economy with significant foreign investment.', 'Exports, domestic consumption, public investment, credit, exchange management, and global demand interact.', 'High trade exposure supports growth but transmits external demand and supply-chain shocks.', 'Connect a business case to sector, currency, credit, and global-cycle sensitivity.'],
  ['economics-macro', 'International trade theory', 'Trade can raise total output when places specialize according to comparative advantage, even if one is more productive in every activity.', 'Relative opportunity cost guides specialization while transport, scale, policy, and supply security shape real outcomes.', 'Gains are not shared automatically; industries and workers can face adjustment costs.', 'Separate total national gain from distribution and resilience effects.'],
  ['economics-macro', 'Business cycle', 'The business cycle describes expansions and contractions around an economy’s long-term trend.', 'Demand, credit, inventory, investment, confidence, policy, and shocks reinforce changing phases.', 'Different sectors lead or lag the cycle, so one national label does not predict every company.', 'Use multiple indicators and scenarios rather than timing a turning point from one data release.'],
  ['economics-micro', 'Behavioral economics', 'Behavioral economics studies predictable ways real decisions differ from perfectly informed, fully rational models.', 'Loss aversion, present bias, framing, defaults, and limited attention shape choice.', 'A helpful default can improve outcomes, but manipulation can damage welfare and trust.', 'Design choice architecture transparently and measure long-term customer outcomes.'],
  ['economics-toolkits', 'Worked toolkit: market sizing', 'Market sizing estimates a total opportunity from explicit drivers rather than a guessed headline number.', 'A bottom-up model multiplies target users, usage, and price; a top-down model filters a larger reference market.', 'The value is in assumptions and decision relevance, not false precision.', 'Example: 2 million target households × 3 purchases × $4 gives a $24 million annual market before share.'],
  ['economics-toolkits', 'Worked toolkit: break-even', 'Break-even is the volume where contribution exactly covers fixed cost.', 'Contribution per unit equals price minus variable cost, and fixed cost is divided by that contribution.', 'Lower price raises break-even unless demand or variable cost improves enough.', 'Example: $100,000 fixed cost ÷ $20 contribution requires 5,000 units.'],
  ['economics-toolkits', 'Worked toolkit: profitability tree', 'A profitability tree separates profit into revenue and cost drivers that can be tested without double counting.', 'Revenue can split into customers, frequency, units, and price; cost can split into variable and fixed components.', 'The tree directs analysis toward the largest evidence-backed driver.', 'Example: if profit falls, test volume, mix, unit margin, and fixed cost before proposing broad cuts.'],
  ['economics-toolkits', 'Worked toolkit: scenario analysis', 'Scenario analysis tests how a decision performs under coherent alternative futures.', 'Teams choose uncertain drivers, build downside, base, and upside assumptions, then identify triggers and responses.', 'It exposes fragility that one average forecast hides.', 'Example: stress demand, price, FX, and cost together rather than changing one cell in isolation.'],
];

export const BANKING_SPRINT_CARDS = expandDepth(BANKING);
export const TECH_SPRINT_CARDS = expandDepth(TECH);
export const RETAIL_SPRINT_CARDS = expandDepth(RETAIL);
export const MANUFACTURING_SPRINT_CARDS = expandDepth(MANUFACTURING);
export const LOGISTICS_SPRINT_CARDS = expandDepth(LOGISTICS);
export const INSURANCE_SPRINT_CARDS = expandDepth(INSURANCE);
export const TOBACCO_SPRINT_CARDS = expandDepth(TOBACCO);

export const BASIC_ECONOMICS_SPRINT_CARDS: SprintBasicCard[] = expandDepth(BASIC);
