// Tobacco — deep Vietnam-specific card pack (modules 6-10).
// A regulated harmful-product category: every card starts from the legal and public-health boundary.
// Market-size estimates diverge widely by source, so each figure names its source and basis.

import type { DepthCard } from './industryDepthTypes';

export const TOBACCO_DEPTH_CARDS: DepthCard[] = [
  {
    module: 6, topic: 'overview', emoji: '🚫', type: 'fact',
    title: 'The legal boundary comes first',
    front: 'Since 1 January 2025 Vietnam bans the production, trade, import, storage, transport and use of e-cigarettes and heated tobacco products under National Assembly Resolution 173/2024/QH15.',
    back: [
      'The resolution passed on 30 November 2024, and customs implemented it immediately — Official Letter 17/TCHQ-GSQL of 2 January 2025 prohibited clearance of e-cigarettes, heated tobacco products, and the components and raw materials used to make them.',
      'Practical consequence: any “reduced-risk product” strategy that works in Japan, the UK or Indonesia is simply unavailable in Vietnam. A candidate who proposes it has failed the question.',
      'Combustible cigarettes remain legal but tightly controlled: licensed production and distribution, tax stamps, health warnings, advertising and promotion bans, and smoke-free place rules.',
      'Interview move: open any tobacco answer by stating the legal boundary and the public-health objective. In this category, compliance literacy is the credibility test.',
    ],
  },
  {
    module: 6, topic: 'overview', emoji: '📏', type: 'fact',
    title: 'Market size: quote the range, not one number',
    front: 'Published estimates of Vietnam’s tobacco market differ by several billion dollars, so name your source and your basis.',
    back: [
      'Euromonitor valued the Vietnamese tobacco industry at about VND104,094.9 billion (roughly USD4.4 billion) in 2022; IMARC estimates the cigarette market at about USD4.8 billion in 2025 growing near 3.6% a year.',
      'Broader “tobacco products” estimates run much higher — one research house puts the 2024 market above USD12 billion — because the definition and channel coverage differ.',
      'What is not disputed: consumption is overwhelmingly male, retail is dominated by store-based traditional trade, and volume is mature rather than growing fast.',
      'Prevalence context: roughly two in five Vietnamese adult men smoke, one of the higher rates globally, which is why tobacco control is a national health priority rather than a commercial debate.',
    ],
  },
  {
    module: 6, topic: 'finance', emoji: '🧾', type: 'fact',
    title: 'The excise reform that changes everything from 2027',
    front: 'The new Law on Excise Tax (Law 66/2025/QH15, in force from 1 January 2026) adds a specific tax to cigarettes on top of the 75% ad valorem rate, phased in from 2027.',
    back: [
      'The roadmap per 20-cigarette pack: VND2,000 from 1 January 2027, VND4,000 in 2028, VND6,000 in 2029, VND8,000 in 2030 and VND10,000 in 2031.',
      'Cigars follow a parallel ladder from VND20,000 to VND100,000 per stick, and pipe or raw tobacco from VND20,000 to VND100,000 per 100 grams or millilitres.',
      'Why a specific tax matters analytically: an ad valorem rate scales with the declared price, so cheap brands stay cheap. A flat amount per pack raises the floor and compresses the gap between budget and premium brands.',
      'The policy rationale is affordability: tax has averaged only around 36.8% of cigarette retail price in Vietnam, far below the World Health Organization benchmark and regional peers such as Singapore.',
    ],
  },
  {
    module: 6, topic: 'overview', emoji: '🏢', type: 'fact',
    title: 'Who operates in the legal market',
    front: 'Vietnam’s legal tobacco market is led by a state corporation, with international companies present through joint arrangements.',
    back: [
      'Vinataba (Vietnam National Tobacco Corporation), established in 1985, held close to 58% of the cigarette market in 2022 and is state-owned — the government appoints its chair and chief executive.',
      'International players including British American Tobacco and Japan Tobacco International participate through licensed manufacturing, joint ventures and distribution arrangements rather than free-standing operations.',
      'Because promotion is banned, competition runs through price tiers, distribution coverage, availability at licensed retail, and product consistency — not advertising.',
      'Governance point worth raising carefully: state ownership of a producer alongside public-health objectives creates an inherent policy tension, which is exactly the kind of observation interviewers reward when stated neutrally.',
    ],
  },
  {
    module: 6, topic: 'marketing-sales', emoji: '📦', type: 'fact',
    title: 'Route to market and the illicit parallel channel',
    front: 'Legal tobacco moves through licensed wholesale into traditional retail — and competes with an untaxed channel of meaningful size.',
    back: [
      'Government estimates put illicit cigarettes at about 15% of the national market; an independent study using a consistent methodology found about 13.72% of consumption in 2017, down from an earlier estimate despite tax increases.',
      'Illicit trade is highly concentrated geographically: over 84% was found in southern provinces bordering Cambodia, with two smuggled brands accounting for more than 80% of the illicit volume.',
      'That evidence matters in an interview: it undercuts the argument that any tax rise automatically causes smuggling, and points to border enforcement and market surveillance as the real levers.',
      'Legal channel controls: production and trading licences, tax stamps, invoicing and traceability, plus retail-level inspection by market surveillance authorities.',
    ],
  },
  {
    module: 6, topic: 'finance', emoji: '🧮', type: 'quiz',
    title: 'Market check: specific versus ad valorem tax',
    front: 'Why does adding a flat VND per pack change market structure more than raising the percentage rate?',
    back: ['A flat amount per pack hits cheap brands hardest in percentage terms, raising the price floor and narrowing the gap to premium. An ad valorem rate scales with price, so budget products stay relatively cheap and downtrading remains easy.'],
    options: [
      'It does not change anything, only revenue',
      'A flat per-pack amount raises the price floor and compresses the gap between budget and premium brands',
      'It only affects imported cigarettes',
      'It reduces the price of premium brands',
    ],
    answer: 1,
  },
  {
    module: 6, topic: 'supply-chain', emoji: '⚖️', type: 'concept',
    title: 'Who regulates what',
    front: 'Four institutions shape every commercial decision in this category. Naming them correctly is a fast credibility win.',
    back: [
      'The National Assembly sets the legal frame — the Law on Prevention and Control of Tobacco Harms, Resolution 173/2024/QH15 and the Law on Excise Tax.',
      'The Ministry of Health leads tobacco control, health warnings, smoke-free places and the Tobacco Harm Prevention Fund, and has proposed expanding smoke-free areas, enlarging pictorial warnings and tightening retail control.',
      'The Ministry of Industry and Trade licenses production, trading and distribution capacity; the Ministry of Finance sets and collects excise and administers tax stamps.',
      'Customs and market surveillance enforce at the border and in retail; Vietnam is also a party to the WHO Framework Convention on Tobacco Control, which constrains industry participation in policymaking.',
    ],
    diagram: ['National Assembly', 'Ministry of Health', 'MoIT licensing', 'Ministry of Finance', 'Customs & surveillance'],
  },
  {
    module: 7, topic: 'people-career', emoji: '📋', type: 'role',
    title: 'What an MT in a regulated category actually does',
    front: 'The work is unusual: most commercial creativity is legally unavailable, so value comes from compliance, execution and analysis.',
    back: [
      'Commercial planning: track legal-market volume by region and price tier, model excise pass-through scenarios, and review distribution coverage — with every idea screened against promotion rules.',
      'Operations: run high-speed manufacturing with strict specification control, tax-stamp accountability, batch traceability and waste reduction.',
      'Leaf and supply chain: manage agricultural variability, grading, curing quality and storage conditions so a controlled blend stays consistent.',
      'Regulatory and corporate affairs: monitor tax and product rules, prepare compliance guidance, and support anti-illicit-trade cooperation without confusing advocacy for permission.',
      'What you will not do: consumer advertising, sampling, influencer work or youth-facing activity. If an interviewer asks for a campaign idea, the correct answer explains why it is not lawful.',
    ],
  },
  {
    module: 7, topic: 'finance', emoji: '📊', type: 'concept',
    title: 'The metric set in a regulated category',
    front: 'Ordinary FMCG metrics only half apply here. These are the numbers a regulated-market analyst actually uses.',
    back: [
      'Legal-market volume and share — taxed units sold through lawful channels; total consumption is larger than the legal market because of illicit supply.',
      'Price/mix — the revenue effect of price increases and portfolio composition; in a declining-volume category this is the main line of defence, subject to affordability effects.',
      'Excise incidence — tax as a share of retail price (Vietnam has averaged around 36.8%), which drives both revenue and consumption outcomes.',
      'Illicit-trade share — consumption outside taxed channels, currently estimated at roughly 13-15% and geographically concentrated.',
      'Compliance metrics — stamp reconciliation, licence coverage, audit findings and incident counts. In this category a control failure destroys more value than a weak commercial plan.',
    ],
  },
  {
    module: 7, topic: 'supply-chain', emoji: '🗓️', type: 'concept',
    title: 'Seasonality and demand patterns',
    front: 'Tobacco demand in Vietnam is steady rather than seasonal, with two visible exceptions.',
    back: [
      'Tet and festival periods lift gifting and social consumption, and premium tiers see a temporary mix improvement.',
      'Excise changes create their own artificial cycle: forward buying by trade ahead of a known tax increase, then a soft period afterwards — which is why the 2027-2031 roadmap will distort quarterly comparisons.',
      'Price increases trigger downtrading to cheaper legal brands or, where enforcement is weak, substitution toward illicit product. Both show up as volume decline for premium tiers.',
      'Analytical discipline: when reading a volume change, always separate underlying consumption, trade inventory movement and channel substitution before drawing a conclusion.',
    ],
  },
  {
    module: 7, topic: 'surprising', emoji: '🔍', type: 'quiz',
    title: 'Operating check: volume versus consumption',
    front: 'Legal cigarette volume falls 6% after an excise increase. What can you conclude about consumption?',
    back: ['Not much on its own. The decline could be genuine quitting or reduced smoking, downtrading within the legal market, trade destocking after forward buying, or substitution into illicit product. You need illicit-share and trade-inventory data before concluding.'],
    options: [
      'Consumption fell by exactly 6%',
      'Nothing definitive — it could be quitting, downtrading, destocking or illicit substitution',
      'The tax increase failed',
      'Illicit trade must have doubled',
    ],
    answer: 1,
  },
  {
    module: 8, topic: 'overview', emoji: '🔒', type: 'fact',
    title: 'Trend one: tighter control, not liberalisation',
    front: 'Every regulatory move in Vietnam since 2024 has narrowed the commercial space. Assume that direction continues.',
    back: [
      'The 2025 prohibition on e-cigarettes and heated tobacco closed the category transition that the global industry pursued elsewhere.',
      'Health authorities have proposed expanding complete smoking bans to more venues, increasing the pack area covered by text and pictorial warnings to about 85%, and tightening control of retail outlets.',
      'The excise roadmap from 2027 to 2031 is legislated rather than proposed, so it is a planning fact, not a scenario.',
      'Interview implication: strategy questions in this category are about lawful execution, cost control and compliance under shrinking optionality — not growth.',
    ],
  },
  {
    module: 8, topic: 'surprising', emoji: '🕵️', type: 'fact',
    title: 'Trend two: enforcement is the competitive battleground',
    front: 'With advertising banned and taxes rising, the biggest swing factor in legal volume is how effectively illicit supply is suppressed.',
    back: [
      'The evidence base is unusually good: illicit share was measured at about 13.72% of consumption in 2017, lower than a comparable 2012 estimate despite tax increases in between.',
      'Concentration matters for policy: more than 84% of illicit product was found in southern provinces bordering Cambodia, which argues for targeted border inspection rather than nationwide crackdowns.',
      'Enforcement tools: tax stamps and traceability, licence audits, market surveillance, and cooperation between customs, police and provincial authorities.',
      'Analytical caution for interviews: the industry claim that tax rises always increase smuggling is contested by this data. Present both sides and cite the study.',
    ],
  },
  {
    module: 8, topic: 'overview', emoji: '🫁', type: 'fact',
    title: 'Trend three: public-health economics',
    front: 'In this category the social cost is part of the analysis, not an externality you can ignore in an interview.',
    back: [
      'Vietnam maintains a Tobacco Harm Prevention Fund financed by a compulsory contribution from tobacco producers and importers, used for cessation and prevention programmes.',
      'The public-health objective is explicit: reduce prevalence, particularly among men and young people. Tax, smoke-free places, warnings and advertising bans are the recognised instrument set.',
      'State revenue interest and the health objective coexist, which is why excise design is debated as a fiscal question and a health question at the same time.',
      'How to handle this in interview: state the harm plainly, analyse the legal market on its own terms, and never propose anything that could increase consumption among young people.',
    ],
  },
  {
    module: 8, topic: 'marketing-sales', emoji: '✅', type: 'quiz',
    title: 'Trend check: what is legally available',
    front: 'A global tobacco company asks how to grow in Vietnam. Which option is lawful?',
    back: ['Improving lawful supply-chain execution, compliance and cost control in the legal cigarette market. Heated tobacco and e-cigarettes are prohibited from 2025, and consumer advertising and promotion are banned.'],
    options: [
      'Launch heated tobacco products as a lower-risk alternative',
      'Improve lawful execution, compliance and cost control in the legal cigarette market',
      'Run an influencer campaign targeting young adults',
      'Import e-cigarette components for local assembly',
    ],
    answer: 1,
  },
  {
    module: 9, topic: 'overview', emoji: '🇻🇳', type: 'case',
    title: 'Vinataba: a state incumbent inside a health policy',
    front: 'Vinataba is the dominant legal producer and the only Vietnamese company where state ownership, agriculture and tobacco control intersect directly.',
    back: [
      'Position: close to 58% of the cigarette market in 2022, with the flagship Vinataba brand among the most widely sold; the state appoints its chair and chief executive.',
      'Operating scope: leaf sourcing and farmer relationships, processing and blending, high-speed manufacturing, tax-stamped distribution through licensed wholesale.',
      'The strategic bind: as excise rises from 2027 and health rules tighten, volume-led growth is not available, so the realistic agenda is lawful-market control, cost efficiency and quality consistency.',
      'Career reality: state-enterprise governance means structured processes, slower decisions, and heavy documentation — plus genuine exposure to agricultural supply chains and regulated manufacturing.',
      'Interview question this unlocks: how should a state producer improve legal-market control without stimulating consumption?',
    ],
  },
  {
    module: 9, topic: 'overview', emoji: '🌐', type: 'case',
    title: 'BAT and JTI in Vietnam: global playbook, local limits',
    front: 'The multinationals operate here without the two levers they rely on elsewhere: advertising and next-generation products.',
    back: [
      'Both participate through licensed manufacturing, joint arrangements and distribution rather than free-standing local operations, and both are constrained by the promotion ban.',
      'Globally these companies pivoted toward heated tobacco, vapour and oral nicotine as cigarette volumes declined. Vietnam’s 2025 prohibition closed that route entirely in this market.',
      'What is left as competitive capability: portfolio and price-tier management, distribution coverage and trade execution, manufacturing quality, and compliance governance across partners and retailers.',
      'Talent note: these companies run structured graduate and management-trainee routes regionally, and commercial, supply-chain and corporate-affairs roles are the usual entry points. Check current-year eligibility, since Vietnamese intake varies by year.',
      'Interview question this unlocks: how should a global company allocate resources in a market that has banned its designated growth category?',
    ],
  },
  {
    module: 9, topic: 'people-career', emoji: '🔀', type: 'case',
    title: 'The adjacent employers most candidates should consider',
    front: 'If you are studying this deck to understand regulated markets rather than to join a tobacco company, these are the transferable destinations.',
    back: [
      'Alcohol and beverages (HEINEKEN, Sabeco, Carlsberg): excise-taxed, advertising-restricted and distribution-heavy — the closest analogue in operating physics.',
      'Pharmaceuticals and health products: product approval, promotion restrictions, traceability and safety monitoring — heavy compliance with a positive social mission.',
      'Licensed gaming, betting and lotteries: taxed, socially scrutinised, and managed with the same compliance-first logic.',
      'Public sector and policy roles: tax policy, market surveillance, customs and health regulation — where this analysis is used for enforcement rather than commerce.',
      'The transferable skill is identical across all of them: making commercial decisions inside a legal boundary you cannot negotiate.',
    ],
  },
  {
    module: 9, topic: 'people-career', emoji: '🧭', type: 'fact',
    title: 'Recruitment and the ethical question you will be asked',
    front: 'Interviewing in a harmful-product category means you will be asked to justify the choice. Prepare a real answer.',
    back: [
      'Expect it directly: “How do you feel about working in tobacco?” Interviewers want a considered position, not enthusiasm and not an apology.',
      'Credible framings: the legal market exists and needs competent compliance; the role is operations, supply chain or regulatory rather than demand creation; or an honest statement that you are targeting adjacent regulated industries instead.',
      'What fails: claiming the harm is exaggerated, proposing tactics that skirt the promotion ban, or showing no awareness that marketing to young people is prohibited.',
      'Practical route in: commercial planning, supply chain, manufacturing and corporate affairs, usually with a numerical test and a compliance-scenario interview.',
      'Whatever you decide, know the rules. A candidate who can explain Resolution 173/2024/QH15 and the 2027-2031 excise ladder shows diligence that transfers to any regulated sector.',
    ],
  },
  {
    module: 10, topic: 'people-career', emoji: '🎤', type: 'fact',
    title: 'Competency questions in a regulated category',
    front: 'Interviews here test judgement, not creativity. Every scenario is really a compliance scenario.',
    back: [
      '“A distributor proposes an in-store display that borders on promotion. What do you do?” Stop it, document it, escalate, and offer a compliant alternative.',
      '“How would you respond to a competitor gaining share through illicit product?” Report and cooperate with enforcement; you cannot compete with an untaxed channel by matching its behaviour.',
      '“Excise rises VND2,000 per pack in 2027. What is your plan?” Model pass-through by price tier, expect downtrading and forward buying, protect availability and cost, and be honest about volume decline.',
      '“Tell me about a time you refused to do something profitable.” This is the single most predictive question in this sector.',
      '“Why this industry?” Answer in terms of operations, compliance and regulated-market analysis — the honest reasons — rather than brand excitement.',
    ],
  },
  {
    module: 10, topic: 'overview', emoji: '🔢', type: 'fact',
    title: 'Analyst-ready Vietnam tobacco numbers',
    front: 'Precise, sourced figures for a category where most candidates have only vague impressions.',
    back: [
      'Legal frame: Resolution 173/2024/QH15 bans e-cigarettes and heated tobacco from 1 January 2025; customs implemented it via Official Letter 17/TCHQ-GSQL on 2 January 2025.',
      'Excise: Law 66/2025/QH15 effective 1 January 2026 keeps the 75% ad valorem rate and adds a specific tax of VND2,000 per 20-cigarette pack in 2027, rising to VND10,000 by 2031; cigars VND20,000 to VND100,000 per stick.',
      'Tax burden: excise has averaged only about 36.8% of cigarette retail price, well below the World Health Organization benchmark.',
      'Market: Euromonitor valued the industry near VND104,094.9 billion (about USD4.4 billion) in 2022; IMARC estimates about USD4.8 billion for cigarettes in 2025.',
      'Structure: Vinataba held close to 58% of the cigarette market in 2022; illicit trade is estimated at roughly 13.7-15% of consumption, with over 84% concentrated in southern border provinces.',
      'Public health: roughly two in five adult Vietnamese men smoke, and a Tobacco Harm Prevention Fund is financed by industry contributions.',
    ],
  },
  {
    module: 10, topic: 'people-career', emoji: '🧩', type: 'concept',
    title: 'The four regulated-market case archetypes',
    front: 'Cases in this category are narrower than in FMCG, and that narrowness is the point.',
    back: [
      'Excise pass-through: how much of a tax increase can be passed to price, what happens to volume and mix, and where downtrading or illicit substitution appears.',
      'Lawful-market control: distribution coverage, licence compliance, stamp reconciliation and retail execution — growing legal share without growing consumption.',
      'Compliance failure response: containment, investigation, remediation, regulator communication, and the control that prevents recurrence.',
      'Portfolio and cost: with promotion unavailable, margin defence comes from price tiers, manufacturing efficiency, leaf sourcing and overhead discipline.',
    ],
    diagram: ['Excise pass-through', 'Lawful-market control', 'Compliance response', 'Portfolio & cost'],
  },
  {
    module: 10, topic: 'people-career', emoji: '⏱️', type: 'concept',
    title: 'Your 60-second regulated-market answer template',
    front: 'This structure works for tobacco, alcohol, pharmaceuticals, gaming and any other category where law comes before commerce.',
    back: [
      'Step 1 — State the legal boundary and the public-health or public-interest objective behind it.',
      'Step 2 — Define the lawful market: who may produce, sell and buy, through which licensed channel.',
      'Step 3 — Give the economics inside that boundary: tax incidence, price tiers, cost base and volume trend.',
      'Step 4 — Name the compliance risk and the control that manages it.',
      'Step 5 — Close by naming what you would refuse to do, and why. In a regulated category that sentence is the answer.',
    ],
    diagram: ['Legal boundary', 'Lawful market', 'Economics inside it', 'Compliance control', 'What you refuse'],
  },
  {
    module: 7, topic: 'people-career', emoji: '🏗️', type: 'concept',
    title: 'How a tobacco business is organised',
    front: 'The org chart tells you where the real work is: agriculture, controlled manufacturing, licensed distribution and regulatory affairs.',
    back: [
      'Leaf and agriculture: farmer contracting, agronomy support, grading, curing and storage — an agricultural supply chain with weather and quality variability.',
      'Manufacturing: high-speed rod making and packing under tight specification, with tax-stamp accountability and batch traceability as core controls.',
      'Commercial and trade: licensed wholesale relationships and retail availability, managed without any promotional toolkit.',
      'Regulatory, legal and corporate affairs: an unusually large function, monitoring tax and product rules and owning compliance guidance.',
      'Finance and control: excise accounting alone is a specialist discipline, because tax is one of the largest lines in the P&L.',
    ],
    diagram: ['Leaf & agronomy', 'Manufacturing', 'Excise & stamps', 'Licensed distribution', 'Regulatory affairs'],
  },
  {
    module: 6, topic: 'supply-chain', emoji: '🌿', type: 'fact',
    title: 'The agricultural base most candidates never mention',
    front: 'Before it is a regulated consumer product, tobacco is a crop — and that supply side is a legitimate, technical part of the industry.',
    back: [
      'Vietnamese leaf is grown in provinces including Tay Ninh, Gia Lai, Cao Bang and Lang Son, typically under contract farming arrangements with processors.',
      'Post-harvest curing controls moisture and chemistry, and grading determines which blends the leaf can enter — so agricultural quality directly constrains product consistency.',
      'Because harvests vary with weather, buyers hold inventory across seasons, which makes working capital and storage conditions a genuine operational issue.',
      'Policy angle worth knowing: farmer livelihoods are part of the political economy of tobacco control, which is why transition support for growers appears in policy debate.',
    ],
  },
  {
    module: 10, topic: 'people-career', emoji: '👀', type: 'fact',
    title: 'What interviewers in regulated categories are scoring',
    front: 'The bar here is different from FMCG: they are testing whether you can be trusted with a licence.',
    back: [
      'You state the legal boundary before the commercial idea, every time.',
      'You separate public-health objectives from company economics instead of blurring them into one story.',
      'You use the right metrics — legal-market volume, price/mix, excise incidence, illicit share — rather than generic brand-equity language.',
      'You show you would escalate rather than improvise when something looks non-compliant. That single instinct is the hiring signal.',
    ],
  },
];
