// Banking & Financial Services — deep Vietnam-specific card pack (modules 6-10).
// Figures are FY2025 actuals or the most recent published data, with the source and period named
// so a candidate can quote them safely in an interview.

import type { DepthCard } from './industryDepthTypes';

export const BANKING_DEPTH_CARDS: DepthCard[] = [
  {
    module: 6, topic: 'overview', emoji: '🏦', type: 'fact',
    title: 'Vietnam banking by the numbers (FY2025)',
    front: 'System credit grew roughly 19% in 2025 — far above the State Bank of Vietnam’s customary 15% target — while sector net interest margin fell to about 2.9% from 3.5% in 2024. Growth was fast and thin at the same time.',
    back: [
      'Credit expansion was driven by infrastructure, FDI-linked industrial activity, real estate and a recovery in retail lending (FiinRatings, FY2025 sector review).',
      'Credit outstanding to the economy now exceeds 140% of GDP, which is why the SBV is tightening rather than loosening: for 2026 it set a ~15% system target, capped Q1 lending at 25% of each bank’s annual quota, and limited each bank’s real-estate lending growth.',
      'Sector non-performing loans held at roughly 1.9%, but that stability was bought with write-offs (net write-offs rose to about 1.3% of average gross loans) and denominator growth from fast lending — not from borrowers suddenly repaying.',
      'Interview move: never say “Vietnamese banks are growing fast” without the second half of the sentence — volume grew, spread compressed, and asset quality was managed through write-offs.',
    ],
  },
  {
    module: 6, topic: 'overview', emoji: '🏛️', type: 'fact',
    title: 'Who actually competes in Vietnamese banking',
    front: 'There are four tiers, and they do not compete for the same thing: state-controlled giants, private joint-stock banks, foreign banks, and policy banks.',
    back: [
      'State-controlled: Vietcombank, BIDV, VietinBank and Agribank carry the largest balance sheets, the cheapest institutional deposits and much of the government’s preferential-rate lending. Vietcombank posted FY2025 pre-tax profit of about VND44 trillion (~USD1.76 billion), up 4.2%.',
      'Private joint-stock: Techcombank, VPBank, MB, ACB, HDBank, SHB, TPBank and Sacombank compete on retail growth, digital experience and fee ecosystems. Techcombank ended 2025 with total assets of about VND1,192 trillion.',
      'Foreign: HSBC, Standard Chartered, UOB, Shinhan and Woori serve multinationals, trade finance, FDI corridors and affluent retail. Their MT programmes (for example UOB’s Management Associate) are smaller and regionally networked.',
      'Policy banks (Vietnam Development Bank, Vietnam Bank for Social Policies) lend on mandate, not on margin — useful to mention when a case involves financial inclusion or subsidised credit.',
    ],
  },
  {
    module: 6, topic: 'finance', emoji: '💰', type: 'concept',
    title: 'Where a bank’s profit is actually created',
    front: 'Trace one dong from deposit to profit and you can answer almost any banking case.',
    back: [
      'Funding: current and savings accounts (CASA) are the cheap end; term deposits and interbank funding are the expensive end. Vietcombank ran a 33.7% CASA ratio in FY2025.',
      'Asset pricing: loan yield must cover funding cost, expected credit loss, capital charge and operating cost before it becomes margin.',
      'Fee and non-interest income: cards, FX, trade finance, wealth, securities and insurance distribution diversify away from spread — and are the main answer to NIM compression.',
      'Provisions and cost: credit cost (Techcombank: 0.6% last-twelve-months in FY2025) and cost-to-income (Vietcombank: 38.8%) decide how much of the spread survives to pre-tax profit.',
    ],
    diagram: ['Deposits & funding', 'Loan pricing', 'Fee & FX income', 'Provisions', 'Operating cost', 'Pre-tax profit'],
  },
  {
    module: 6, topic: 'finance', emoji: '📐', type: 'fact',
    title: 'Read any Vietnamese bank in five ratios',
    front: 'Two FY2025 profiles show how differently two strong banks earn money. Learn the shape, not just the definitions.',
    back: [
      'Vietcombank FY2025: NIM 2.7% (from 2.9%), NPL about 0.6%, CASA 33.7%, cost-to-income 38.8%, ROAE 15.3%, loan-loss reserve coverage about 259%. Credit grew 15.5%, and preferential-rate credit reached roughly VND800 trillion — near half its loan book — which is a direct explanation for the low margin.',
      'Techcombank FY2025: quarterly NIM 3.9%, NPL 1.13%, loan-to-deposit ratio 76.5% against the 85% regulatory cap, credit +18.36% year-to-date, retail credit +30.8% to about VND372 trillion, corporate +13.4% to about VND452 trillion.',
      'The mix explains the margin: Techcombank grew unsecured retail lending sharply and cut real-estate exposure inside its corporate book to 30.7% from 33.2%; Vietcombank carries policy-priority lending at administered rates.',
      'Interview move: when asked “which bank is better?”, compare risk-adjusted return — NIM minus credit cost, then cost-to-income — rather than headline profit.',
    ],
  },
  {
    module: 6, topic: 'supply-chain', emoji: '⚖️', type: 'fact',
    title: 'The rulebook: SBV, credit quotas and capital',
    front: 'Vietnamese banking is quantity-regulated as well as price-regulated. A bank cannot simply decide to lend more.',
    back: [
      'The State Bank of Vietnam allocates annual credit growth room bank by bank, and in 2026 added an intra-year constraint: no more than 25% of the full-year quota may be lent in Q1, with real-estate lending growth capped at the prior year’s total lending growth.',
      'Prudential limits that appear in cases: loan-to-deposit ratio capped at 85%, capital adequacy under Circular 41 on a Basel II-style risk-weighted basis with banks progressively adopting Basel III liquidity and buffer practices, plus reserve requirement ratios the SBV can cut selectively (it halved the ratio for Vietcombank, MB, VPBank and HDBank ahead of a peak season).',
      'Consumer-protection and conduct rules bind product design: bank staff may not sell life insurance within 60 days of loan disbursement, and tying non-mandatory insurance to a loan is penalised.',
      'Say the regulator’s name. “SBV”, “Circular” and “credit room” in one answer signal that you have read the sector, not just a bank’s annual report.',
    ],
  },
  {
    module: 6, topic: 'supply-chain', emoji: '🎋', type: 'fact',
    title: 'Seasonality: Tet, quarter-end and the Q4 sprint',
    front: 'Vietnamese bank performance is not evenly spread across the year, and MTs feel it in their first quarter.',
    back: [
      'Q4 is the peak lending quarter: corporates draw working capital for Tết production and stock building, and banks race to use remaining credit room before it expires.',
      'The weeks before Tết bring the largest cash and payment demand of the year; the SBV routinely supports system liquidity in that window, including targeted reserve-requirement cuts.',
      'January and February are then slow for new lending but heavy on collections, campaign resets and annual target setting — which is exactly when most MT cohorts onboard.',
      'Retail deposit competition intensifies around year-end and Tết bonuses; funding cost spikes there feed directly into next quarter’s NIM.',
    ],
  },
  {
    module: 6, topic: 'overview', emoji: '📉', type: 'quiz',
    title: 'Market check: why margins fell',
    front: 'Sector NIM fell from about 3.5% in 2024 to about 2.9% in 2025 while credit grew ~19%. What is the most complete explanation?',
    back: ['Loan yields were pushed down by competition and policy-priority lending while deposit costs rose — so fast volume growth was not enough to hold spread. Growth and margin moved in opposite directions.'],
    options: [
      'Banks stopped lending to companies',
      'Asset yields compressed (competition and preferential-rate credit) while funding costs rose',
      'The SBV banned fee income',
      'Customers repaid all their loans early',
    ],
    answer: 1,
  },
  {
    module: 7, topic: 'people-career', emoji: '🗓️', type: 'role',
    title: 'A banking MT’s first 90 days, function by function',
    front: 'Programmes rotate every four to six months. Here is what the work actually looks like in each seat.',
    back: [
      'Retail / branch banking: pull segment dashboards, sit in on customer conversations, track CASA acquisition and card activation, and prepare a branch or region performance pack for the weekly business review.',
      'Wholesale / SME: build client one-pagers, spread financial statements, map wallet share against competitors, and support credit proposals with industry evidence.',
      'Risk: rebuild a scorecard cut, test early-warning triggers, and read vintage curves — a cohort of loans by disbursement month — to see whether recent growth is deteriorating.',
      'Digital / data: instrument an onboarding funnel, quantify drop-off at eKYC, and size the cost saving of moving a paper process to app.',
      'Finance / treasury: rebuild the NIM walk (volume, rate, mix), reconcile transfer pricing between units, and explain a variance to a business head who has ten minutes.',
    ],
  },
  {
    module: 7, topic: 'finance', emoji: '📊', type: 'concept',
    title: 'The banking KPI dictionary MTs are tested on',
    front: 'These are the terms used inside Vietnamese banks every week. Being fluent here is the cheapest credibility you can buy.',
    back: [
      'CASA ratio — current and savings balances over total deposits; the single biggest lever on funding cost.',
      'Credit cost — provision expense over average loans (Techcombank: 0.6% LTM in FY2025); pair it with NIM to get risk-adjusted spread.',
      'Loan-loss reserve coverage (LLR / LLCR) — provisions held against NPLs; system coverage was about 84% in Q3 2025 while Vietcombank held about 259%.',
      'NPL formation and SML (special-mention loans, Group 2) — the early-warning bucket; sector SML fell to roughly 1.2% by end-2025 from about 1.9%.',
      'RWA, CAR, LDR, LCR/NSFR — the constraint set: how much risk the capital base can carry and how liquid the funding must stay.',
    ],
  },
  {
    module: 7, topic: 'people-career', emoji: '🏗️', type: 'concept',
    title: 'How a large Vietnamese bank is organised',
    front: 'Knowing who signs what tells you where an MT actually adds value — and who will challenge your proposal.',
    back: [
      'The Board and its ALCO (asset-liability committee) set risk appetite, funding structure and pricing floors; the CEO’s business divisions must operate inside them.',
      'Business divisions split by customer, not product: Retail, SME, Wholesale/Corporate, plus Treasury and Financial Markets trading the balance sheet.',
      'Second line: independent Credit Risk, Market and Liquidity Risk, Compliance and AML sit outside sales reporting lines deliberately — an MT recommendation dies here if it lacks a risk answer.',
      'Enablement: Operations, Technology, Data, Finance and HR, plus the branch network as a distribution channel with its own P&L discipline.',
      'Subsidiaries matter in Vietnam: securities arms (TCBS, VPBankS, MBS), consumer-finance units and insurance ventures sit under the group and carry different regulators.',
    ],
    diagram: ['Board & ALCO', 'Retail / SME / Wholesale', 'Treasury', 'Risk & Compliance', 'Ops, Tech & Data', 'Branch network'],
  },
  {
    module: 7, topic: 'people-career', emoji: '🔁', type: 'role',
    title: 'Which rotations MT programmes actually offer',
    front: 'Bank MT programmes are usually organised into streams rather than a single generalist path. Choose with your evidence, not your mood.',
    back: [
      'Business / commercial stream: retail, SME or wholesale banking, ending in a relationship or segment-management role. Best fit if your evidence is persuasion, targets and client work.',
      'Risk and credit stream: underwriting, portfolio risk, collections analytics. Best fit if your evidence is analytical rigour and comfort saying no.',
      'Technology and Data/AI streams have become their own tracks — Techcombank Future Gen runs Technology, Data & AI, Business and General Management streams, and VPBank Young Talents 2026 was explicitly aimed at IT, computer science, data science and AI/ML majors.',
      'Finance, treasury and operations rotations are less advertised but give the fastest whole-bank literacy, because everything eventually shows up in the balance sheet.',
      'Ask in interview which rotations are guaranteed versus indicative, and how placement at the end is decided — it is a strong question and it protects you.',
    ],
  },
  {
    module: 7, topic: 'finance', emoji: '⚖️', type: 'quiz',
    title: 'Operating check: risk-adjusted spread',
    front: 'Bank A has NIM 3.9% and credit cost 1.6%. Bank B has NIM 2.7% and credit cost 0.4%. Which statement is best supported?',
    back: ['After credit cost, A retains 2.3% and B retains 2.3% — the same risk-adjusted spread. Headline NIM alone ranks them wrongly; you must net off expected losses (and then compare cost-to-income).'],
    options: [
      'Bank A is clearly more profitable because NIM is higher',
      'Their risk-adjusted spreads are effectively equal; cost-to-income and capital use decide',
      'Bank B is insolvent',
      'Credit cost is irrelevant to profitability',
    ],
    answer: 1,
  },
  {
    module: 8, topic: 'rnd-product', emoji: '📱', type: 'fact',
    title: 'Vietnam is now a digital-first banking market',
    front: 'This is the most quotable trend in Vietnamese banking, and most candidates only say “mobile banking is growing”.',
    back: [
      'In H1 2026 Vietnam recorded more than 15 billion cashless transactions worth over VND190 quadrillion — volume up 34.28% and value up 12.24% year on year, equivalent to more than 28 times GDP (State Bank of Vietnam).',
      'At many credit institutions over 95% of transactions now run through digital channels, and more than 89% of Vietnamese aged 15 and above hold a payment account.',
      'The direction of travel is visible in the mix: in the first five months of 2026 internet-banking transaction volume rose about 53% and QR payment value roughly 40%, while ATM transactions fell about 9%.',
      'Identity is the enabler: biometric and chip-based citizen-ID authentication has been deployed by dozens of banks and payment intermediaries, with more than 160 million customer records verified — which is why account opening moved from branch to phone.',
    ],
  },
  {
    module: 8, topic: 'finance', emoji: '🗜️', type: 'fact',
    title: 'The margin squeeze and the hunt for yield',
    front: 'The defining strategic problem of 2025-2026 is that lending grew fast while spread shrank. Watch what banks did about it.',
    back: [
      'Repricing the asset mix: banks pushed into higher-yield unsecured retail, cards and consumer lending. Techcombank’s unsecured book grew about 3.5 times in FY2025 and margin lending through its securities arm rose sharply.',
      'Defending funding: CASA campaigns, payroll and merchant acquiring, ecosystem accounts, and zero-fee transfers exist to buy cheap deposits, not to be generous.',
      'Growing fee income: cards, FX, trade finance, wealth management and securities distribution reduce dependence on spread — the reason bancassurance restrictions hurt so much.',
      'Cost discipline: automation and digital servicing are how a bank keeps cost-to-income near or below 40% while margin compresses. Quote Vietcombank’s 38.8% CIR as the benchmark.',
    ],
  },
  {
    module: 8, topic: 'surprising', emoji: '🕳️', type: 'fact',
    title: 'Asset quality: what a flat NPL ratio hides',
    front: 'A stable non-performing loan ratio can mean healthy borrowers — or aggressive write-offs plus fast loan growth. In 2025, Vietnam was mostly the second.',
    back: [
      'Sector NPLs stayed near 1.9% while net write-offs rose to about 1.3% of average gross loans and the loan book itself grew ~19%, mechanically diluting the ratio.',
      'The improving early-warning signal is real though: special-mention (Group 2) loans fell to roughly 1.2% from about 1.9%, meaning fewer loans were newly deteriorating.',
      'Provisioning kept building: listed banks’ provision stock rose about 10% year on year, and system loan-loss coverage recovered to roughly 84% by Q3 2025, with Vietcombank, VietinBank, Techcombank and Bac A Bank above 100%.',
      'For 2026 analysts expect less write-off and more debt sale and asset-resolution tooling — so bad-debt resolution mechanics, collateral enforcement and the secondary debt market are live case topics.',
    ],
  },
  {
    module: 8, topic: 'marketing-sales', emoji: '🚫', type: 'fact',
    title: 'Bancassurance: how one rule reset a revenue line',
    front: 'Vietnam’s bancassurance clampdown is the clearest example in the market of conduct regulation rewriting a P&L.',
    back: [
      'Decree 46/2023/ND-CP tightened bancassurance conduct, disclosure and bundling; the revised Insurance Business Law bans selling life insurance within 60 days of loan disbursement and penalises tying non-mandatory policies to loans.',
      'Bancassurance revenue fell about 39% in the first six months after the rules took effect (Insurance Association of Vietnam) — a fee line that many banks had been counting on for double-digit growth.',
      'The strategic response was quality over volume: needs-based advice, post-sale confirmation calls, persistency-linked incentives, and a shift of fee ambition toward cards, FX, wealth and investment banking.',
      'Interview move: use this to show you understand that in financial services distribution power without suitability is a liability, not an asset.',
    ],
  },
  {
    module: 8, topic: 'overview', emoji: '🌐', type: 'fact',
    title: 'Capital markets: the FTSE upgrade changes the funding map',
    front: 'From 21 September 2026 Vietnam is reclassified by FTSE Russell from Frontier to Secondary Emerging market status — phased across four tranches into September 2027.',
    back: [
      'The September 2026 review added 117 Vietnamese stocks to the FTSE Global Equity Index Series, including 17 securities firms; indicative constituents span FPT, Masan, Vinamilk and brokerages such as SSI, VNDirect, Vietcap and Techcom Securities.',
      'Initial index weights are small (roughly 0.35% of the FTSE Emerging All Cap Index), so the honest framing is structural access to global passive and active capital rather than an immediate flood of money.',
      'The plumbing mattered more than the label: a global broker model and non-prefunding framework (Circular 08/2026/TT-BTC) were the reforms that unlocked it — useful detail that shows you read past the headline.',
      'Securities firms are the direct beneficiaries because margin lending is capped at two times equity, so they raised capital to lend more — SSI moved to lift charter capital from about VND20.8 trillion toward VND25 trillion.',
    ],
  },
  {
    module: 8, topic: 'marketing-sales', emoji: '⏳', type: 'quiz',
    title: 'Trend check: the 60-day rule',
    front: 'Why did Vietnam ban life-insurance sales within 60 days of loan disbursement?',
    back: ['To break the implied link between getting a loan and buying a policy. Bundling produced unsuitable sales and early lapses, so the regulator separated the two conversations in time.'],
    options: [
      'To reduce paperwork for banks',
      'To stop borrowers feeling that a policy purchase was a condition of credit approval',
      'Because insurance is illegal in Vietnam',
      'To increase bank fee income',
    ],
    answer: 1,
  },
  {
    module: 9, topic: 'overview', emoji: '🥇', type: 'case',
    title: 'Techcombank: the profitability template and Future Gen',
    front: 'Techcombank is the private-bank benchmark for high margin plus low credit cost, and its Future Gen programme is the most structured banking MT route in Vietnam.',
    back: [
      'FY2025 evidence: total assets about VND1,192 trillion, net interest income VND38.2 trillion (+7.5%), quarterly NIM 3.9%, NPL 1.13%, credit cost 0.6% LTM, LDR 76.5% versus the 85% cap.',
      'Strategy in one line: shift the book toward higher-yield retail (retail credit +30.8%; unsecured about 3.5x) while trimming concentration — real-estate share of corporate lending down to 30.7% from 33.2%.',
      'Future Gen 2027 is a 24-month fast-track under the bank’s Key Talent programme with six-month rotations across four streams: Technology, Data & AI, Business, General Management. Based in Hanoi, open to final-year students and candidates with under two years of experience.',
      'Programme specifics worth knowing: applications ran 30 July to 30 September 2026, offers in November, onboarding January 2027; the Tech & Data track advertises starting pay from about USD1,000 per month.',
      'Interview question this unlocks: how would you defend a 3.9% NIM if the SBV caps real-estate lending growth and unsecured credit costs rise?',
    ],
  },
  {
    module: 9, topic: 'overview', emoji: '🧾', type: 'case',
    title: 'Vietcombank: scale, policy lending and the low-risk trade-off',
    front: 'Vietcombank shows the state-controlled model: enormous balance sheet, the market’s best asset quality, and margin that policy partly determines.',
    back: [
      'FY2025: pre-tax profit about VND44 trillion (~USD1.76 billion, +4.2%), credit +15.5%, NIM down to 2.7%, NPL about 0.6% (a ~30% reduction), loan-loss coverage about 259%, ROAE 15.3%, cost-to-income 38.8%.',
      'The trade-off is explicit: preferential-rate credit reached roughly VND800 trillion, near 49% of the loan book, supporting national growth priorities while capping yield.',
      'What this means for an MT: the work skews toward large corporates, FDI clients, trade finance, treasury and process industrialisation rather than aggressive retail risk-taking.',
      'Culture signal: state-controlled banks reward process discipline, exam-based selection and long tenure; private banks reward speed and target delivery. Match your story to the one you are actually applying to.',
      'Interview question this unlocks: if half your book earns policy-set rates, where do you find profitable growth without raising credit risk?',
    ],
  },
  {
    module: 9, topic: 'overview', emoji: '📶', type: 'case',
    title: 'VPBank and MB: retail scale, consumer finance and tech talent',
    front: 'These two show a different growth engine — mass-market retail plus a technology workforce strategy.',
    back: [
      'VPBank pairs retail and SME banking with consumer finance (FE Credit, with SMBC as strategic partner) and a securities arm, VPBankS, that is now among the largest brokerages by profit.',
      'VPBank Young Talents 2026 was a 15-month development programme aimed squarely at IT, computer science, data science and AI/ML graduates for its technology and enterprise data & analytics blocks, based in Hanoi, applications closing 5 June 2026.',
      'MB pursued some of the fastest credit growth in the system in recent years alongside a large digital user base; it was also one of four banks (with Vietcombank, VPBank and HDBank) granted a 50% reserve-requirement reduction ahead of a peak season.',
      'Read the pattern: private banks are hiring MTs as much for data and technology capability as for relationship management. A quantitative story is now a banking story.',
      'Interview question this unlocks: how would you grow unsecured consumer lending after a bad-debt cycle without repeating it?',
    ],
  },
  {
    module: 9, topic: 'overview', emoji: '📲', type: 'case',
    title: 'MoMo, VNPay and ZaloPay: fintech as the fourth competitor',
    front: 'Payment platforms do not hold banking licences, but they own the daily habit — and they hire MT-style graduate cohorts.',
    back: [
      'MoMo (company-reported user base above 30 million) monetises through merchant payments, bill payments, financial-service distribution and mini-apps rather than transfer fees; VNPay dominates bank-linked QR acquiring; ZaloPay leans on Zalo’s messaging reach.',
      'They operate as payment intermediaries under SBV licensing, so lending, deposit-taking and insurance distribution require a bank or insurer partner — a constraint candidates routinely miss.',
      'Their economics are thin per transaction and heavy on incentives, so the interview question is always the same: which cohort retains without a voucher, and what is revenue per active user?',
      'Bank-fintech competition is really co-opetition: banks supply licences, balance sheet and settlement; platforms supply distribution and frequency. Frame partnership economics, not a winner-takes-all story.',
      'Interview question this unlocks: which three metrics would prove a wallet’s growth is economically healthy rather than subsidy-driven?',
    ],
  },
  {
    module: 9, topic: 'people-career', emoji: '📅', type: 'fact',
    title: 'The banking recruitment calendar you can plan around',
    front: 'Banking MT cycles in Vietnam are predictable. Build your calendar backwards from onboarding, not forwards from the job post.',
    back: [
      'A concrete cycle: Techcombank Future Gen 2027 opened applications 30 July 2026, closed 30 September, made offers in November and onboards in January 2027 — roughly six months from CV to first day.',
      'Typical round structure: online application and CV screen, then an aptitude test (numerical, logical, verbal), then an assessment centre with a group case and presentation, then panel interviews with business heads, and sometimes a final leadership interview.',
      'Test preparation matters more in banking than in most sectors because the numerical screen is genuinely eliminative. Practise ratio, growth-rate and percentage-change questions under time pressure.',
      'Eligibility is tight: most programmes require final-year students or under two years of full-time experience, so a gap year of unrelated work can close the door — check before you plan.',
      'Foreign-bank programmes (UOB Management Associate, and regional graduate schemes) often run on a different, earlier calendar with regional assessment centres. Track them separately.',
    ],
  },
  {
    module: 10, topic: 'people-career', emoji: '🎤', type: 'fact',
    title: 'Competency questions banking interviewers actually ask',
    front: 'Banking interviews test judgement under risk. Prepare stories that show you can say no with evidence.',
    back: [
      '“Tell me about a time you had to deliver a target you did not believe in.” They are testing whether you escalate with data or quietly miss.',
      '“A client you like is asking for a loan your analysis does not support. What do you do?” Name the cash-flow evidence, offer a structured alternative (smaller limit, collateral, covenant), and keep the relationship.',
      '“Walk me through how you would explain NIM to a customer.” They are testing whether you can simplify without becoming wrong.',
      '“What would you do in your first month if you found an error in a report everyone relies on?” Controls, escalation and documentation are the answer, not heroics.',
      '“Why banking and not consulting or FMCG?” Answer with the mechanism you find interesting — balance-sheet risk, funding, credit — not with prestige.',
    ],
  },
  {
    module: 10, topic: 'overview', emoji: '🔢', type: 'fact',
    title: 'Ten analyst-ready Vietnam banking numbers',
    front: 'Memorise these with their period and source. Two precise numbers beat ten adjectives.',
    back: [
      'System credit growth ~19% in 2025 versus the SBV’s customary ~15% target; credit to the economy above 140% of GDP.',
      'Sector NIM ~2.9% in FY2025, down from ~3.5% in 2024; sector NPL ~1.9% with net write-offs ~1.3% of average gross loans.',
      'Vietcombank FY2025: PBT ~VND44 trillion, NIM 2.7%, NPL ~0.6%, CASA 33.7%, CIR 38.8%, ROAE 15.3%.',
      'Techcombank FY2025: assets ~VND1,192 trillion, quarterly NIM 3.9%, NPL 1.13%, LDR 76.5% (cap 85%), retail credit +30.8%.',
      'Cashless payments H1 2026: >15 billion transactions, >VND190 quadrillion, +34.28% in volume, >28x GDP; >89% of adults hold a payment account; >95% of transactions digital at many banks.',
      'Bancassurance revenue fell ~39% in the first six months after the 60-day rule took effect; FTSE Russell reclassification effective 21 September 2026 with 117 stocks added.',
    ],
  },
  {
    module: 10, topic: 'people-career', emoji: '🧩', type: 'concept',
    title: 'The five banking case archetypes',
    front: 'Almost every banking case you will be given is one of these five. Recognise the type in the first 30 seconds.',
    back: [
      'Grow low-cost funding: who has a payroll or merchant relationship we do not own, what habit makes the account primary, and what does a 1-point CASA gain do to NIM?',
      'Price a product or loan: funding cost plus expected loss plus capital charge plus operating cost plus target return — then sanity-check against competitor pricing and elasticity.',
      'Fix a deteriorating portfolio: cut new-origination risk, tighten early collections, restructure viable borrowers, provision honestly, and prove it in the vintage curves.',
      'Launch or fix a digital journey: quantify funnel drop-off, name the compliance constraint (eKYC, biometrics, AML), and show cost-to-serve savings.',
      'Enter a segment (SME, affluent, green finance): size the wallet, name the risk model gap, decide build-versus-partner, and state the capital consumption.',
    ],
    diagram: ['Grow CASA', 'Price the risk', 'Fix the portfolio', 'Digitise the journey', 'Enter a segment'],
  },
  {
    module: 10, topic: 'people-career', emoji: '👀', type: 'fact',
    title: 'What banking interviewers are really scoring',
    front: 'Three candidates give the same recommendation; one gets the offer. The difference is usually these four habits.',
    back: [
      'You quantify. Every claim carries a number, a unit and a period — “NIM 2.7% in FY2025” rather than “margins are low”.',
      'You name the constraint. Capital, credit room, LDR, liquidity or conduct rules — a recommendation without a constraint reads as untested.',
      'You separate growth from quality. Vintage curves, sell-through of provisions, persistency of deposits: show that you know results appear with a lag.',
      'You are comfortable being unpopular. Banking rewards people who can decline a deal politely and document why.',
    ],
  },
  {
    module: 10, topic: 'people-career', emoji: '⏱️', type: 'concept',
    title: 'Your 60-second banking answer template',
    front: 'Use this chain out loud. It converts scattered knowledge into a structured, senior-sounding answer.',
    back: [
      'Step 1 — Define the customer and the balance-sheet effect: is this about funding, assets, or fees?',
      'Step 2 — Quantify the economics: yield or fee, minus funding cost, minus expected credit loss, minus cost to serve.',
      'Step 3 — Name the regulatory or capital constraint that could stop the plan.',
      'Step 4 — Give one leading indicator you would watch in the first 90 days (CASA mix, activation rate, Group 2 formation).',
      'Step 5 — Close with the risk you would accept and the one you would refuse. Bankers trust candidates who bound their own recommendation.',
    ],
    diagram: ['Customer & balance sheet', 'Risk-adjusted economics', 'Regulatory constraint', 'Leading indicator', 'Accepted vs refused risk'],
  },
];
