// Phase 2 deep-enrichment pack C — Insurance and Tobacco.
// Same intent as packs A and B: fill the operating-process, R&D/product, commercial and
// insider-fact chapters that the original packs under-served, with Vietnam-specific evidence.

import type { DepthCard } from './industryDepthTypes';

export const INSURANCE_PHASE2_CARDS: DepthCard[] = [
  {
    module: 7, topic: 'supply-chain', emoji: '🧮', type: 'concept',
    title: 'How actuarial pricing actually works for a life insurer',
    front: 'Pricing a life policy is the clearest example in business of selling something whose true cost you will not know for thirty years. This is the actual sequence a Vietnamese life insurer follows.',
    back: [
      'Set the assumptions: mortality and morbidity (how many claim and when), lapse and persistency (how many stop paying), expenses per policy, and the investment return earned on reserves while the premium is held. Each is a judgement backed by experience data and industry tables.',
      'Project the cash flows: for a model policy, project premiums in against claims, benefits, commissions and expenses out across the full policy term, then discount back to today. The price must cover expected cost plus a margin for risk and profit.',
      'Test profitability: run the projection against a required return to produce the new business value and margin. Because first-year commission and acquisition cost can exceed first-year premium, a policy is loss-making at outset and only becomes profitable if it persists — which is why persistency is the whole game.',
      'Stress and sensitivity: rerun with worse mortality, higher lapse, lower investment return and higher medical inflation. The pricing decision is made on the stressed case, not the central case.',
      'Reserve and hold capital: once sold, the insurer must hold technical reserves against future obligations and capital against the risk that experience turns out worse than assumed — which is what the solvency ratio measures.',
      'Monitor experience: actual claims, lapses and expenses are compared with assumed, and persistent gaps trigger repricing at renewal or product redesign. In Vietnam this matters most in health, where claims paid grew about 13.5% in 2025 against total premium growth of only 4%.',
    ],
    visual: [
      'PRICING A LIFE POLICY',
      '  Assumptions: mortality | lapse | expense | yield',
      '        |',
      '  Project cash flows across the full term',
      '   Yr 1   premium in  <  commission + expense',
      '   Yr 2+  premium in  >  running cost',
      '   Yr 7+  cumulative profit turns positive',
      '        |',
      '  Stress test  ->  price on the STRESSED case',
      '        |',
      '  Reserve + capital  ->  solvency ratio',
      '  ----------------------------------------------',
      '  A lapse in year 2 means the acquisition cost',
      '  is never recovered. That is the whole risk.',
    ],
  },
  {
    module: 8, topic: 'rnd-product', emoji: '🧬', type: 'concept',
    title: 'How an insurance product is designed and approved',
    front: 'Insurance product development is regulated design. Knowing the gates explains why insurers move slowly and why “just sell it in an app” is not a compliant answer.',
    back: [
      'Need definition first: which risk, for which customer, over what duration — income protection, critical illness, hospital cash, endowment savings or investment-linked. The Vietnamese growth need right now is health, which is why it has become the largest non-life line by revenue.',
      'Benefit structure: sum insured, waiting periods, exclusions, co-payments and sub-limits. These are the levers that make a product affordable without making it worthless, and they are precisely where consumer misunderstanding originates.',
      'Price and reinsure: actuarial pricing, then a decision on how much risk to retain and how much to cede to a reinsurer — which matters most for large or unfamiliar risks where local claims history is thin.',
      'File and approve: product documentation, policy wording and disclosure pass internal risk and compliance review and then the regulatory filing regime. Agent training material and the sales script are part of the product, not an afterthought.',
      'Distribution and conduct design: choose the channel, the commission structure and the advice standard. Since 2023 this means recorded or verified advice, post-sale confirmation calls, and persistency-linked incentives rather than pure volume incentives.',
      'The simplification trend worth naming: simple, easily understood cover can be sold digitally with low advice risk, while complex long-term savings and protection still legally require human advice under the current conduct regime.',
    ],
    diagram: ['Define the need', 'Benefit design', 'Price & reinsure', 'File & approve', 'Channel & conduct', 'Monitor experience'],
  },
  {
    module: 8, topic: 'finance', emoji: '🏦', type: 'fact',
    title: 'The investment book: an insurer is also an asset manager',
    front: 'Most candidates describe insurance as selling policies. Half the economics is what happens to the money between the premium and the claim.',
    back: [
      'The float is enormous. Vietnamese insurers held total industry assets of about VND1,113.6 trillion in 2025 and reinvested roughly VND959 trillion into the economy, up 10.3% — which makes the sector one of the country’s largest institutional investors.',
      'Asset-liability matching is the discipline: a thirty-year protection liability needs long-duration assets, so government and corporate bonds and term deposits dominate rather than equities. A duration mismatch leaves the insurer exposed when rates move.',
      'Investment return is a pricing assumption, not a bonus. If realised yields fall below the rate assumed when a savings-linked policy was priced, the product becomes less profitable or loss-making even when claims behave exactly as expected.',
      'This is why the two halves interact: an underwriting result at a combined ratio just under 100% plus a solid investment result is a good year, and an underwriting loss can be survivable if the investment book carries it. That is a legitimate strategy rather than an accident.',
      'For an MT this is where actuarial, finance and treasury meet: reserve adequacy, solvency ratio, duration matching and the capital charge attached to each asset class.',
    ],
  },
  {
    module: 7, topic: 'marketing-sales', emoji: '🧑‍💼', type: 'fact',
    title: 'How the agency channel actually operates',
    front: 'Agency is the backbone of Vietnamese life insurance and the channel most candidates cannot describe. It is a recruitment machine as much as a sales one.',
    back: [
      'Agents are typically self-employed and commission-paid, licensed after examination, and organised in hierarchies where unit and branch managers earn overrides on the production of the agents they recruit and develop.',
      'That structure creates the industry’s defining tension: recruiting many agents lifts short-term sales because new agents sell to their own network first, but it produces high agent turnover and inconsistent advice quality — which is exactly how a persistency problem gets manufactured.',
      'The quality levers now used instead: tighter recruitment standards, professional full-time agent tiers, activity management rather than headcount targets, and compensation weighted toward persistency and customer outcomes rather than first-year premium alone.',
      'This is why diversified insurers held up better through the trust crisis. Bao Viet Life lifted new-business share to about 20.8% in 2025 from 16.7%, and Dai-ichi at 13.2% and AIA at 11.3% proved most resilient — all less dependent on the bank channel that regulation restricted.',
      'The metric that reveals the truth about any agency force: 13-month and 25-month persistency by agent cohort. If new-business premium rises while persistency falls, the growth is being borrowed from next year.',
    ],
  },
  {
    module: 8, topic: 'marketing-sales', emoji: '🏛️', type: 'concept',
    title: 'Bancassurance after the rules: what a compliant sale looks like',
    front: 'Bancassurance was not banned in Vietnam — it was re-engineered. Being able to describe the compliant version is one of the sharpest signals available in an insurance interview.',
    back: [
      'The binding constraints: Decree 46/2023/ND-CP tightened conduct, disclosure and bundling, and the revised Insurance Business Law prohibits selling life insurance within 60 days of loan disbursement and penalises tying non-mandatory policies to a loan.',
      'What a compliant sale now involves: a documented needs analysis before any product is shown, explicit disclosure that the policy is optional and separate from the credit decision, recorded or verified advice, and a post-sale confirmation call checking the customer understood what they bought.',
      'Incentives had to change with it. Bank staff scorecards moved from first-year premium volume toward persistency, complaint rates and quality-of-advice measures, because paying for volume alone simply recreates the original problem.',
      'The measurable consequence of getting it wrong the first time: bancassurance revenue fell about 39% in the first six months after the rules took effect, and life gross written premiums fell about 12% in 2023 and a further 5.7% in 2024.',
      'The channel is not dead — it is being rebuilt by different players. MB Life reached about 6.6% of new business premium in 2025 and newly licensed Techcom Life entered the top five on new business within its first year.',
      'The line to remember: in financial services, distribution power without suitability is a liability, not an asset.',
    ],
  },
  {
    module: 6, topic: 'surprising', emoji: '🌏', type: 'fact',
    title: 'The penetration gap is far bigger than people assume',
    front: 'Everyone repeats that Vietnamese insurance is under-penetrated. Almost nobody knows the size of the gap — or that penetration actually went backwards.',
    back: [
      'Vietnamese life penetration is roughly 1.3% of GDP, down from about 1.9% in 2022. Thailand sits near 3.5% and Taiwan near 8.7%, so this is not a gap of a few percentage points — it is a multiple.',
      'The decline is the genuinely surprising part. This was not slow demographic drift: gross written premiums fell about 12% in 2023 and a further 5.7% in 2024, while active policies dropped roughly 7.5% and then 3.7%. The industry lost customers, not just new sales.',
      'New business premium reset to approximately 2017 levels — seven years of growth erased by a conduct crisis rather than an economic one.',
      'Recovery is expected to be modest rather than explosive: forecasters project around 3.8% growth in 2026 with the life market passing USD7 billion by 2030, and actuarial firm Milliman concluded in 2026 that the worst is behind the market.',
      'The framing that earns the offer: low penetration is only an opportunity if trust is rebuilt. Quote the 1.3% and immediately explain why it fell — that pairing is what separates an informed answer from a brochure.',
    ],
    visual: [
      'LIFE INSURANCE PENETRATION (% of GDP)',
      ' Taiwan    |################################ ~8.7%',
      ' Thailand  |############# ~3.5%',
      ' Vietnam   |##### ~1.3%    (was ~1.9% in 2022)',
      ' -------------------------------------------',
      ' Vietnam went BACKWARDS while peers held.',
      ' Cause: a conduct crisis, not the economy.',
    ],
  },
  {
    module: 9, topic: 'surprising', emoji: '😲', type: 'fact',
    title: 'Five insurance facts that surprise candidates',
    front: 'Insurance is the industry where the intuitive answer is most often the wrong one.',
    back: [
      'Growing sales can destroy value. If new-business premium rises 20% while 13-month persistency falls from 88% to 76%, the acquisition cost may never be recovered — premium volume and profit can move in opposite directions.',
      'Claims are growing far faster than premiums. Claims paid rose about 13.5% in 2025 against total premium growth of 4%, driven by medical inflation — which makes health a repricing and provider-management business rather than a pure underwriting one.',
      'Non-life is the growth story now, not life. Non-life premiums grew 10.3% in 2025 to about VND88.4 trillion while life grew just 0.5%, and health has become the largest non-life line by revenue, ahead of motor.',
      'The banks are becoming the insurers. MB Life and Techcom Life climbed the new-business table quickly on captive distribution and customer data — the same structural advantage that created the conduct problem in the first place.',
      'A low loss ratio is not automatically good news. It can mean disciplined underwriting, or it can mean claims are being declined too readily. Always read it alongside complaint volumes and claims turnaround time.',
    ],
  },
];

export const TOBACCO_PHASE2_CARDS: DepthCard[] = [
  {
    module: 9, topic: 'marketing-sales', emoji: '🚩', type: 'case',
    title: 'BAT, Philip Morris and Vinataba: share and distribution, accurately',
    front: 'The common framing is “the multinationals versus Vinataba”. The real structure is stranger and more interesting: the multinationals operate through Vinataba, and one of them is far larger than the other.',
    back: [
      'Transnational tobacco companies are required to operate in Vietnam through joint ventures with Vinataba, and Vinataba holds the majority ownership in those ventures. Vina-BAT was established in 2011 with British American Tobacco; the Philip Morris relationship dates to 1994 and became Vinataba - Philip Morris in 2010.',
      'The share picture (Euromonitor, 2022): Vinataba close to 58% of the cigarette market, British American Tobacco nearly 29%, Imperial Brands about 7% on the single brand Bastos, and Philip Morris International only about 3% with Marlboro. BAT — not PMI — is the substantial foreign player, and it has more than doubled its share since 2001.',
      'Positioning differs sharply: Vinataba anchors the mainstream and value tiers with brands including Vinataba, Thang Long and Hoan Kiem, while BAT dominates the mid-range and premium tiers with Craven A, White Horse and State Express 555.',
      'Distribution is state-shaped rather than market-shaped. The government holds a monopoly on cigarette importation other than duty-free goods, production and trading require licences, and product moves through licensed wholesale into traditional retail under tax-stamp control.',
      'The volume structure worth quoting: the market has been stable above 100 billion cigarettes a year since 2015, split roughly 60% Vietnamese products, about 22% foreign brands manufactured in Vietnam, and around 18% illegally imported.',
      'Interview question this unlocks: if you cannot advertise, cannot import freely, and must manufacture through a joint venture with the market leader, what is actually left as a source of competitive advantage?',
    ],
    visual: [
      'CIGARETTE MARKET SHARE (2022, Euromonitor)',
      ' Vinataba (state) |#################### ~58%',
      ' BAT              |########## ~29%',
      ' Imperial Brands  |##  ~7%',
      ' PMI              |#   ~3%',
      ' Others           |#   ~3.5%',
      ' -----------------------------------------',
      ' BAT, PMI and JTI all operate through JOINT',
      ' VENTURES in which Vinataba holds majority.',
    ],
  },
  {
    module: 7, topic: 'supply-chain', emoji: '🏭', type: 'concept',
    title: 'How a cigarette is actually manufactured',
    front: 'This is an agricultural processing business running at extreme speed under tax control. Being able to describe the line separates a serious candidate from a curious one.',
    back: [
      'Leaf procurement and curing: contract farming in provinces including Tay Ninh, Gia Lai, Cao Bang and Lang Son, then curing to control moisture and chemistry, and grading that determines which blends the leaf can enter.',
      'Threshing and redrying: leaf is separated from stem, conditioned to a target moisture and packed for storage. Because harvests vary with weather, processors hold inventory across seasons — so storage conditions and working capital are genuine operational issues.',
      'Blending and casing: multiple leaf grades and types are blended to a specification so the product tastes identical batch after batch, with casing and flavour applied to the blend. Consistency is the entire product promise in a category with no advertising.',
      'Rod making and packing: high-speed machines form the rod, attach the filter, cut to length, then pack, apply the tax stamp and mandated health warnings, and bundle into cartons. Speeds run into thousands of units per minute, so a small defect rate is a large absolute number.',
      'Excise and stamp accountability: every stamp is reconciled, because tax on the product is one of the largest lines in the P&L. Excise accounting is a specialist finance discipline in this industry rather than a routine task.',
    ],
    diagram: ['Leaf & curing', 'Threshing', 'Blending & casing', 'Rod making', 'Packing & stamps', 'Licensed wholesale'],
  },
  {
    module: 8, topic: 'rnd-product', emoji: '🔬', type: 'concept',
    title: 'What R&D means where you cannot launch a new category',
    front: 'Vietnam banned e-cigarettes and heated tobacco from 1 January 2025, closing the innovation route the global industry took everywhere else. What remains is narrow, technical and worth understanding.',
    back: [
      'Blend development: matching a target taste profile from available leaf grades as crop quality varies year to year, so the consumer experiences no change. This is the main ongoing technical work in the category.',
      'Filter and rod engineering: filter construction, ventilation and paper specification affect measured tar and nicotine yields, which are regulated and tested rather than marketed.',
      'Analytical testing and quality control: moisture, weight, draw resistance, ventilation and yield testing under statistical process control — the same discipline as any regulated manufacturing operation.',
      'Packaging and compliance: pack format, materials and cost, all constrained by mandated health warnings, with Vietnamese health authorities having proposed increasing warning coverage toward about 85% of the pack area.',
      'The boundary to state explicitly in an interview: reduced-risk product development is simply not available in Vietnam. National Assembly Resolution 173/2024/QH15 prohibits the production, trade, import, storage, transport and use of e-cigarettes and heated tobacco, and customs implemented it immediately in January 2025.',
    ],
  },
  {
    module: 8, topic: 'finance', emoji: '💵', type: 'concept',
    title: 'Excise pass-through arithmetic you can do in an interview',
    front: 'From 2027 Vietnam adds a flat specific tax per pack on top of the 75% ad valorem rate. Working through what that does to a price ladder is the single most likely quantitative question in this category.',
    back: [
      'The roadmap is legislated, not proposed: Law 66/2025/QH15 adds VND2,000 per 20-cigarette pack from 1 January 2027, then VND4,000 in 2028, VND6,000 in 2029, VND8,000 in 2030 and VND10,000 in 2031.',
      'Why a flat amount reshapes the market: it is the same absolute increase for a cheap pack and a premium pack, so it is a far larger percentage increase at the bottom. The price floor rises and the gap between budget and premium compresses.',
      'The behavioural consequences, in order of likelihood: downtrading within the legal market, forward buying by trade ahead of each known increase followed by a soft quarter, and where enforcement is weak, substitution into illicit product.',
      'The pass-through decision itself: pass the full tax through to price and protect margin per unit while losing volume, or absorb part of it to defend volume and share. The answer depends on price elasticity by tier and on what competitors do.',
      'The context that makes the reform make sense: excise has averaged only around 36.8% of cigarette retail price in Vietnam, far below the World Health Organization benchmark and regional peers such as Singapore. This is an affordability correction, not simply a revenue grab.',
    ],
    visual: [
      'A FLAT TAX HITS CHEAP PACKS HARDEST',
      '                BUDGET PACK    PREMIUM PACK',
      ' Price today        20,000          35,000',
      ' +2,000 (2027)      22,000          37,000',
      '   = increase        +10%            +5.7%',
      ' +10,000 (2031)     30,000          45,000',
      '   = increase        +50%           +28.6%',
      ' ------------------------------------------',
      ' The floor rises, the budget-premium gap',
      ' narrows, and downtrading gets harder.',
    ],
  },
  {
    module: 8, topic: 'surprising', emoji: '📈', type: 'fact',
    title: 'Why Vietnam is still a growth market for a declining product',
    front: 'Global cigarette consumption has been falling for years, yet Vietnam is consistently described as a growth market. Both statements are true, and reconciling them makes a genuinely good interview answer.',
    back: [
      'Volume is mature; value is not. The market has held above 100 billion cigarettes a year since 2015, but value has grown — IMARC estimates the cigarette market near USD4.8 billion in 2025, growing around 3.6% a year, driven by price and mix rather than by more smokers.',
      'Affordability has been the quiet driver. With excise averaging only around 36.8% of retail price, cigarettes became cheaper relative to rising incomes — which is precisely the gap the 2027-2031 specific-tax roadmap is designed to close.',
      'The demographic base is large and slow-moving: roughly two in five Vietnamese adult men smoke, one of the higher rates globally, and a growing adult population sustains a stable smoker base even as prevalence rates edge down.',
      'The 2025 prohibition on e-cigarettes and heated tobacco removed the substitution route that has accelerated cigarette decline in Japan, Korea and much of Europe — so the combustible category is not losing volume to a next-generation product here.',
      'And roughly 13.7% to 15% of consumption sits outside the taxed market, concentrated with over 84% in southern provinces bordering Cambodia — so part of what looks like legal-market weakness is an enforcement issue rather than falling demand.',
      'The honest closing line: this is a growth market in revenue terms because of price, tax structure and the absence of substitutes — not because more Vietnamese people are choosing to smoke.',
    ],
  },
  {
    module: 9, topic: 'surprising', emoji: '🤨', type: 'fact',
    title: 'Five regulated-market facts that surprise candidates',
    front: 'Every one of these reverses an assumption people bring into a tobacco or regulated-category interview.',
    back: [
      'Higher tobacco taxes did not obviously increase smuggling. An independent study using a consistent method measured illicit trade at about 13.72% of consumption in 2017, lower than a comparable 2012 estimate despite tax increases in between. Present both sides and cite the study — the industry claim is contested, not settled.',
      'Philip Morris is a minor player in Vietnam. It holds roughly 3% of the cigarette market with Marlboro, while British American Tobacco holds nearly 29% — the opposite of most candidates’ assumptions about global brand strength.',
      'The state sits on both sides of the table. Vinataba is state-owned with the government appointing its chair and chief executive and contributing over VND10 trillion a year to the budget, while the Ministry of Health simultaneously leads tobacco control and runs a Tobacco Harm Prevention Fund financed by industry contributions.',
      'A volume decline tells you almost nothing on its own. A 6% fall after an excise rise could be quitting, downtrading, trade destocking after forward buying, or illicit substitution — you need illicit-share and trade-inventory data before concluding anything.',
      'The transferable skill is the real point. Alcohol, pharmaceuticals, licensed gaming and public-sector policy roles all demand the same discipline: making commercial decisions inside a legal boundary you cannot negotiate. That is why this deck is worth studying even if you never apply to a tobacco company.',
    ],
  },
];
