// Logistics & Supply Chain — deep Vietnam-specific card pack (modules 6-10).
// 2025 port, parcel and company data; cost-to-GDP estimates name their source because they differ.

import type { DepthCard } from './industryDepthTypes';

export const LOGISTICS_DEPTH_CARDS: DepthCard[] = [
  {
    module: 6, topic: 'overview', emoji: '🚛', type: 'fact',
    title: 'Vietnam logistics by the numbers (2025)',
    front: 'Vietnam’s freight and logistics market is worth roughly USD52 billion — but it costs the economy 16-20% of GDP to move goods, against a global average near 10%.',
    back: [
      'Estimates differ and you should say so: the Ministry of Industry and Trade’s Vietnam Logistics Report 2025 puts logistics costs at about 17-18% of GDP, while the Ho Chi Minh City Logistics and Port Association argues total costs now exceed 20%.',
      'Regional comparison makes the gap concrete: Singapore around 8%, Malaysia around 11-13%, Thailand around 14%. The national target is 13-15% of GDP by 2030 plus a top-40 place in the World Bank Logistics Performance Index.',
      'Last-mile delivery alone is estimated at about 53% of total logistics cost, which is why density, route planning and first-attempt delivery dominate operational discussion.',
      'Interview move: quote the cost ratio and then name one structural cause — fragmented trucking, thin multimodal and rail use, port-road congestion, empty backhauls. A number plus a cause beats either alone.',
    ],
  },
  {
    module: 6, topic: 'supply-chain', emoji: '🚢', type: 'fact',
    title: 'Ports and freight: the physical backbone',
    front: 'Vietnam’s seaports handled about 34.36 million TEU of containers in 2025, up roughly 11%, on total cargo of about 1.17 billion tonnes (+12%).',
    back: [
      'The southern gateway cluster around Cai Mep-Thi Vai and Cat Lai serves Ho Chi Minh City and the industrial south; Cai Mep-Thi Vai handled about 5.6 million TEU in the first nine months of 2025 and can take the largest vessel classes.',
      'The northern gateway of Hai Phong and Lach Huyen serves the electronics belt of Bac Ninh, Bac Giang and Thai Nguyen and connects to the China land border.',
      'Throughput was projected to reach roughly 36.7 million TEU in 2026, so capacity timing — when a terminal opens relative to demand — is a recurring investment case.',
      'Why it matters commercially: port choice sets inland trucking distance, and inland trucking is where Vietnamese logistics cost concentrates.',
    ],
  },
  {
    module: 6, topic: 'overview', emoji: '📦', type: 'fact',
    title: 'The parcel market: fast growth, falling prices',
    front: 'E-commerce made Vietnam a parcel economy: about 3.5 billion parcels shipped in the first ten months of 2025, up roughly 32%.',
    back: [
      'Postal and express revenue reached about VND75 trillion over the same ten months, up about 26.9% — revenue growing slower than volume, which tells you price per parcel is falling.',
      'Average revenue per shipment is around VND21,200, so this is a business of pennies per parcel, won or lost on route density and failed deliveries.',
      'Market shares (Vietdata): Viettel Post about 17.2%, SPX Express 15.7%, GHTK 14.5%, VNPost 13.8%, J&T Express 10.6%, GHN 7.9%, EMS 3.1%, with the rest spread across small players.',
      'Structural shift to note: platform-owned carriers such as SPX for Shopee took share while independents were squeezed, and Ninja Van moved to exit Vietnam as competition intensified.',
    ],
  },
  {
    module: 6, topic: 'overview', emoji: '🧩', type: 'concept',
    title: 'The four logistics business models',
    front: 'Never say “logistics” without naming the model — they have completely different economics.',
    back: [
      'Asset owners (shipping lines, airlines, truck fleets, port terminals): high fixed cost, so utilisation is everything and earnings swing with freight rates.',
      'Freight forwarders, asset-light (Expeditors, Bee Logistics, ITL, plus carriers’ forwarding arms): earn the spread between bought and sold capacity, plus documentation and customs value-add.',
      '3PL and contract logistics run warehousing, fulfilment and distribution for a client under multi-year contracts; 4PL orchestrates other providers without owning assets.',
      'Parcel and last-mile networks (Viettel Post, GHTK, GHN, J&T, SPX): dense sortation-and-rider systems where cost per parcel falls as drop density rises.',
      'Ownership rule worth knowing: foreign ownership of Vietnamese logistics services is generally capped near 49% and local firms hold roughly 65% of the market, which is why joint ventures are common.',
    ],
    diagram: ['Asset owner', 'Forwarder', '3PL / 4PL', 'Last-mile network', 'Shipper in-house'],
  },
  {
    module: 6, topic: 'supply-chain', emoji: '🛃', type: 'fact',
    title: 'Regulation, incentives and customs',
    front: 'Logistics is a licensed, paperwork-heavy industry. Knowing the rulebook separates a candidate from a hobbyist.',
    back: [
      'The Ministry of Industry and Trade leads logistics development policy, transport authorities and the maritime administration oversee ports and waterways, and customs sits under the Ministry of Finance.',
      'Customs runs on the VNACCS/VCIS electronic system; bonded warehouses and free-trade-zone treatment let goods sit duty-suspended, which is a real working-capital lever for importers.',
      'Rules of origin under CPTPP, EVFTA, RCEP and UKVFTA make documentation part of the product’s value — a missing certificate erases the duty saving that justified the sourcing decision.',
      'Incentives exist: qualifying logistics-infrastructure projects can access corporate income tax holidays and land-use reductions, which is why port and warehouse announcements cluster around industrial zones.',
    ],
  },
  {
    module: 6, topic: 'supply-chain', emoji: '🌊', type: 'fact',
    title: 'Seasonality: peaks that break networks',
    front: 'Logistics demand is spiky, and the spikes are predictable — which means failure to plan for them is a management failure.',
    back: [
      'Export peak runs mid-year into the third quarter as factories ship for Western holiday seasons, tightening ocean and air capacity and lifting rates.',
      'Domestic parcel peaks land on the double-date online sale days (9.9, 10.10, 11.11, 12.12) and the pre-Tet gifting weeks, when volumes can multiply within days.',
      'Tet itself stops the network: riders and drivers return home, so carriers publish cut-off dates and shippers pre-position inventory.',
      'Weather is a structural risk, not an excuse: the late-2025 storms lengthened supplier delivery times and lifted costs, visible in national PMI data.',
    ],
  },
  {
    module: 6, topic: 'finance', emoji: '🧮', type: 'quiz',
    title: 'Market check: cost per parcel',
    front: 'Parcel volume grew about 32% while postal and express revenue grew about 26.9%. What does that gap tell you?',
    back: ['Average revenue per parcel is falling, so carriers are competing on price. Profit then depends on cutting cost per parcel faster than price falls — through drop density, automation and fewer failed deliveries.'],
    options: [
      'Carriers are raising prices successfully',
      'Price per parcel is falling, so cost per parcel must fall faster to protect margin',
      'Volume growth guarantees profit growth',
      'The data is contradictory and cannot be interpreted',
    ],
    answer: 1,
  },
  {
    module: 7, topic: 'people-career', emoji: '📋', type: 'role',
    title: 'What a logistics MT actually does',
    front: 'Logistics graduate roles put you inside a live network where yesterday’s exception cannot wait until next week.',
    back: [
      'Operations: review last night’s service performance and backlog, reallocate riders or trucks, chase missed connections, and close out claims with a root cause rather than an apology.',
      'Commercial and key account: map a customer’s lanes and service requirements, build a rate proposal that operations can actually deliver, and review margin by account monthly.',
      'Solutions design: model a warehouse or transport network, size capacity and inventory policy, and present the service-versus-cost trade-off with explicit assumptions.',
      'Procurement and carrier management: source carriers, negotiate lanes, track tender acceptance and on-time performance, and keep backup capacity qualified before you need it.',
      'A typical first project: reduce failed first-attempt deliveries in one district, quantified in cost per parcel and rider hours saved.',
    ],
  },
  {
    module: 7, topic: 'finance', emoji: '📊', type: 'concept',
    title: 'The logistics KPI dictionary',
    front: 'These metrics run the network. Learn the formula and the behaviour each one drives.',
    back: [
      'OTIF (on-time in-full) — the customer’s single measure of whether the promise was kept; measure it at order level, not shipment level.',
      'First-attempt delivery rate — in Vietnamese last mile this is the cost lever: every failed attempt duplicates rider time, and cash-on-delivery raises the failure rate.',
      'Cost per parcel, per stop, per pallet or per container — always pick the unit that matches the customer promise.',
      'Load factor and backhaul utilisation — a truck returning empty earns nothing but still burns fuel, driver hours and depreciation.',
      'Dwell time and inventory days — how long goods wait at a port, hub or warehouse; dwell is the hidden tax in Vietnamese gateway congestion.',
    ],
  },
  {
    module: 7, topic: 'people-career', emoji: '🏗️', type: 'concept',
    title: 'How a Vietnamese logistics operator is organised',
    front: 'Understanding who owns capacity versus who sells it explains almost every internal conflict you will see.',
    back: [
      'Commercial: sales and key accounts sell service levels and prices; pricing or yield management sets the rate card and approves exceptions.',
      'Operations: hub and sortation, line-haul, last-mile branches, warehousing, and a control tower monitoring exceptions in real time.',
      'Network and solutions design sits between them, modelling what the network can profitably promise.',
      'Support: procurement of carriers and fuel, customs and compliance, technology (routing, tracking, warehouse systems), finance and claims.',
      'The recurring tension: sales promises a service the network cannot deliver at that price. A good MT answer names this and proposes a joint review of lane-level margin.',
    ],
    diagram: ['Commercial & pricing', 'Solutions design', 'Hub & line-haul', 'Last mile', 'Control tower & claims'],
  },
  {
    module: 7, topic: 'finance', emoji: '📍', type: 'quiz',
    title: 'Operating check: density economics',
    front: 'A rider makes 40 deliveries per shift in a dense urban district and 18 in a rural one, with the same daily cost. What follows?',
    back: ['Cost per parcel is more than twice as high in the rural district. That is why carriers price rural service differently, consolidate drop points, use partner agents, or schedule fewer delivery days per week there.'],
    options: [
      'Rural delivery is cheaper because there is less traffic',
      'Cost per parcel is far higher rurally, so pricing, consolidation or frequency must change',
      'Delivery density has no effect on cost',
      'The rider should simply work longer hours',
    ],
    answer: 1,
  },
  {
    module: 8, topic: 'marketing-sales', emoji: '🕶️', type: 'fact',
    title: 'Platform-owned delivery is squeezing independents',
    front: 'The biggest structural change in Vietnamese last mile is that the demand owners built their own carriers.',
    back: [
      'SPX Express (Shopee) reached about 15.7% share, and platform-integrated capacity plus VNPost and Viettel Post now dominate, while independents lost ground — Ninja Van moved to exit Vietnam.',
      'The mechanism is simple: a platform can guarantee volume to its own network, which buys density that an independent carrier must pay to acquire.',
      'Consequence for independents: specialise (bulky goods, cold chain, cross-border, B2B), win non-platform merchants, or become the overflow capacity that platforms use at peak.',
      'Consequence for merchants: carrier choice is increasingly bundled with the sales channel, so logistics cost is negotiated inside platform fees rather than separately.',
    ],
  },
  {
    module: 8, topic: 'supply-chain', emoji: '🚧', type: 'fact',
    title: 'Cross-border and bonded logistics with China',
    front: 'Vietnam’s land border with China is becoming a logistics product, not just a crossing point.',
    back: [
      'Viettel Post opened a bonded warehouse at its Lang Son logistics park in January 2026 — about 5,880 square metres of warehouse and 8,700 square metres of yard, connected directly to the VNACCS/VCIS customs system.',
      'Why this matters: bonded storage next to the Huu Nghi and Coc Nam crossings cuts clearance time for import-export flows and supports cross-border e-commerce fulfilment.',
      'Market size context: cross-border e-commerce logistics was worth roughly USD1.2 billion in 2025 and is projected around USD2.06 billion by 2030 (about 11.5% CAGR).',
      'The strategic idea to carry into interviews: reducing dwell time at a border is economically equivalent to adding capacity, and it costs far less.',
    ],
  },
  {
    module: 8, topic: 'rnd-product', emoji: '🛤️', type: 'fact',
    title: 'Infrastructure, multimodal and the cost target',
    front: 'Cutting logistics costs from 17-20% of GDP toward 13-15% by 2030 requires modal shift, not just better trucks.',
    back: [
      'The stated priorities are multimodal transport, better use of inland waterways, and rail connections linking industrial zones to the Cai Mep-Thi Vai port cluster.',
      'Inland waterways are Vietnam’s underused advantage: barge movement in the Mekong and Red River deltas is cheaper per tonne-kilometre than road, but needs terminals and reliable depth.',
      'Deep-sea capacity keeps expanding: Gemadept’s Gemalink can take megaship classes, and its Nam Dinh Vu cluster reached about 2 million TEU of capacity with phase 3 in the north.',
      'Digitalisation is the cheap lever: electronic customs, shared truck platforms, and warehouse management systems reduce waiting, which is the largest hidden cost.',
    ],
  },
  {
    module: 8, topic: 'rnd-product', emoji: '🌿', type: 'fact',
    title: 'Green logistics and customer requirements',
    front: 'Emissions reporting has entered logistics tenders, so it is now commercial rather than reputational.',
    back: [
      'Multinational shippers increasingly require emissions data per shipment, which pushes carriers toward measurement, route optimisation, load consolidation and electric two-wheeler fleets in cities.',
      'Carriers are signing green-transport partnerships — Gemadept and CMA CGM cooperated on green transport — because customers now score it in vendor selection.',
      'The honest constraint: electrification of long-haul trucking in Vietnam is limited by charging infrastructure and payload economics, so most credible near-term gains come from load factor and modal shift.',
      'For a case: the cheapest carbon reduction in logistics is usually the empty kilometre you never drive.',
    ],
  },
  {
    module: 8, topic: 'rnd-product', emoji: '🚢', type: 'quiz',
    title: 'Trend check: reducing national logistics cost',
    front: 'Which intervention most directly attacks Vietnam’s high logistics cost ratio?',
    back: ['Shifting volume to multimodal and inland waterway routes and cutting dwell time, because road haulage and waiting dominate the cost base. Buying more trucks adds capacity without addressing the structural inefficiency.'],
    options: [
      'Buying more trucks',
      'Modal shift to waterway and rail plus dwell-time reduction at ports and borders',
      'Raising delivery prices',
      'Reducing export volumes',
    ],
    answer: 1,
  },
  {
    module: 9, topic: 'overview', emoji: '📭', type: 'case',
    title: 'Viettel Post: record profit on flat revenue',
    front: 'Viettel Post is the largest domestic parcel carrier and a clean example of margin discipline during a price war.',
    back: [
      'FY2025: net revenue about VND20,846.8 billion — barely up on 2024 — yet post-tax profit reached a record VND404.9 billion, up 5.7%, with fourth-quarter profit up 17.3%.',
      'Total assets grew about 18.3% to roughly VND7,529 billion as the company invested in logistics parks, warehousing and cross-border infrastructure instead of chasing parcel share at any price.',
      'Strategic direction: from parcels toward integrated logistics — bonded warehousing at Lang Son, a Da Nang logistics centre, automated sortation and enterprise supply-chain services.',
      'What that means for an MT: exposure to network design, automation projects and cross-border customs work inside a state-linked group with structured processes.',
      'Interview question this unlocks: how do you grow profit when parcel prices are falling and volume growth is going to platform-owned carriers?',
    ],
  },
  {
    module: 9, topic: 'overview', emoji: '🏗️', type: 'case',
    title: 'Gemadept: infrastructure with a timing problem',
    front: 'Gemadept is Vietnam’s leading listed port and logistics operator, and the best local case study in capital-intensive timing.',
    back: [
      'Scale: about 5.079 million TEU handled across its port system in 2025, with revenue and pre-tax profit reaching roughly 123% and 139% of target.',
      'Asset quality is the moat: Gemalink is among a small group of ports able to receive megaship classes, and the Nam Dinh Vu cluster reached about 2 million TEU of capacity after phase 3 opened.',
      'The risk is capital intensity: a terminal is a fixed, decade-long bet, so utilisation ramp and the timing of new capacity matter more to returns than freight-rate cycles.',
      'For an MT: terminal work means yard planning, berth productivity, equipment utilisation and commercial negotiation with shipping lines — heavier and more analytical than parcel operations.',
      'Interview question this unlocks: how would you evaluate a new port-capacity investment in Vietnam, and what would make you delay it?',
    ],
  },
  {
    module: 9, topic: 'overview', emoji: '🏍️', type: 'case',
    title: 'GHTK, GHN and J&T: the independent last mile',
    front: 'Independent carriers built Vietnamese e-commerce delivery and now must defend that position against platform-owned networks.',
    back: [
      'Positions: GHTK about 14.5% share, J&T Express about 10.6%, GHN about 7.9% — all built on merchant integrations, sortation hubs and large rider networks.',
      'Their operating obsessions: drop density per route, first-attempt success, cash-on-delivery reconciliation, and returns handling, which is a bigger cost line than candidates expect.',
      'Response options: serve non-platform merchants and social sellers, specialise in bulky or fragile goods, win on returns handling, or act as overflow capacity at peak.',
      'This is the market where operations analytics genuinely decides winners, so quantitative graduates get real responsibility quickly.',
      'Interview question this unlocks: how would you improve rural service without doubling cost per parcel?',
    ],
  },
  {
    module: 9, topic: 'overview', emoji: '🌏', type: 'case',
    title: 'Maersk, DHL and Expeditors: the global operators',
    front: 'Global forwarders and carriers run the most structured logistics graduate programmes in Vietnam.',
    back: [
      'What they do here: ocean and air freight, customs brokerage, contract logistics and integrated supply-chain services for exporters and multinational shippers.',
      'Their edge is network plus systems — global capacity, visibility platforms and standard operating procedures a single Vietnamese exporter cannot build alone.',
      'Programmes such as Expeditors’ Management Trainee rotate through operations, customer service, customs and commercial, with heavy emphasis on process discipline and client communication.',
      'Foreign ownership limits mean many operate through joint ventures or licensed local partners, so understanding the corporate structure is genuinely useful in interview.',
      'Interview question this unlocks: which customer segments most value an integrated forwarder, and which are better served by a cheap point-to-point carrier?',
    ],
  },
  {
    module: 9, topic: 'people-career', emoji: '📅', type: 'fact',
    title: 'Logistics recruitment: how to get in',
    front: 'Logistics hiring rewards candidates who understand flow, cost and exceptions — not just Incoterms vocabulary.',
    back: [
      'Routes in: global forwarder and carrier programmes (Expeditors, Maersk, DHL), domestic operators (Viettel Post, Gemadept, ITL, Bee Logistics, Transimex), platform logistics arms, and supply-chain graduate roles inside FMCG, retail and manufacturing.',
      'Selection usually includes a numerical or logical test, a scenario exercise (a delayed shipment, a capacity shortfall, a customer escalation), and interviews with operations and commercial managers.',
      'Preparation that works: learn one shipment end to end — booking, pickup, export customs, main leg, import customs, delivery, proof of delivery — and be able to name where cost and risk sit at each step.',
      'Know your Incoterms (EXW, FOB, CIF, DAP) well enough to say who bears cost and risk at each handover. It is a standard screening question.',
      'Expect shift or on-call exposure in operations rotations. Interviewers ask about it deliberately, so answer honestly.',
    ],
  },
  {
    module: 10, topic: 'people-career', emoji: '🎤', type: 'fact',
    title: 'Competency questions logistics interviewers ask',
    front: 'Logistics interviews test composure under exceptions and the instinct to quantify before promising.',
    back: [
      '“A customer’s shipment will miss its deadline. What do you do in the next hour?” Confirm facts, tell the customer early with options, then fix root cause — in that order.',
      '“Tell me about a time you handled several urgent problems at once.” Show a triage rule, not heroics: what you did first and why.',
      '“A key account wants a 10% rate cut. How do you respond?” Analyse lane-level margin, load factor and service cost, then trade volume commitment or flexibility for price.',
      '“Where would you look first if delivery costs rose 8% with flat volume?” Failed attempts, route density, fuel, subcontractor mix, returns rate.',
      '“Why logistics?” The strongest answers name the puzzle — finite capacity, variable demand, promises with a deadline — rather than “I like supply chains”.',
    ],
  },
  {
    module: 10, topic: 'overview', emoji: '🔢', type: 'fact',
    title: 'Analyst-ready Vietnam logistics numbers',
    front: 'Six clusters of figures that make a logistics answer sound like it came from inside the industry.',
    back: [
      'Market and cost: freight and logistics around USD52 billion in 2025; logistics costs 16-20% of GDP (MoIT report: 17-18%) against a 2030 target of 13-15% and a global average near 10%.',
      'Ports: about 34.36 million TEU handled in 2025 (+11%) on 1.17 billion tonnes of cargo (+12%); Cai Mep-Thi Vai about 5.6 million TEU in nine months; roughly 36.7 million TEU projected for 2026.',
      'Parcels: about 3.5 billion shipments in the first ten months of 2025 (+32%); postal and express revenue about VND75 trillion (+26.9%); average revenue per shipment around VND21,200.',
      'Share: Viettel Post about 17.2%, SPX 15.7%, GHTK 14.5%, VNPost 13.8%, J&T 10.6%, GHN 7.9%; local firms hold roughly 65% of the market and foreign ownership is generally capped near 49%.',
      'Companies: Viettel Post FY2025 revenue about VND20,846.8 billion with record post-tax profit of VND404.9 billion; Gemadept handled about 5.079 million TEU.',
      'Structure: last mile is roughly 53% of logistics cost, and cross-border e-commerce logistics was about USD1.2 billion in 2025.',
    ],
  },
  {
    module: 10, topic: 'people-career', emoji: '🧩', type: 'concept',
    title: 'The five logistics case archetypes',
    front: 'Logistics cases are network cases. Optimise the whole flow rather than one cheap lane.',
    back: [
      'Reduce cost per delivery: attack failed first attempts, route density, load factor and returns before touching rates.',
      'Design or redesign a network: how many hubs, where, how far from demand, and what service promise each node can support.',
      'Win or defend an account: lane-level margin, service requirements, capacity commitment, and what you would refuse to promise.',
      'Handle a peak or disruption: forecast the spike, pre-position capacity, set a triage rule, and define the customer communication protocol.',
      'Improve working capital across the chain: inventory days, dwell time, bonded storage and payment terms — logistics decisions are cash decisions.',
    ],
    diagram: ['Cost per delivery', 'Network design', 'Account economics', 'Peak & disruption', 'Working capital'],
  },
  {
    module: 10, topic: 'people-career', emoji: '👀', type: 'fact',
    title: 'What logistics interviewers are really scoring',
    front: 'Operators hire people who will not panic and will not over-promise. Four habits show that.',
    back: [
      'You quantify per unit: cost per parcel, per stop, per container — never just total cost.',
      'You think in networks: you check what a local fix does to the rest of the flow before recommending it.',
      'You plan for exceptions: you name the failure mode and the recovery process, because exceptions are where margin dies.',
      'You communicate early: telling a customer bad news with options is scored as strength, not weakness.',
    ],
  },
  {
    module: 10, topic: 'people-career', emoji: '⏱️', type: 'concept',
    title: 'Your 60-second logistics answer template',
    front: 'Use this chain for cost, service and network questions alike.',
    back: [
      'Step 1 — Name the flow: origin, nodes, mode, destination, and the service promise attached to it.',
      'Step 2 — Find the constraint: capacity, congestion, labour, customs clearance, or delivery attempts.',
      'Step 3 — Quantify cost per completed unit and identify the largest component.',
      'Step 4 — Propose the intervention and state what it does to service level as well as to cost.',
      'Step 5 — Stress-test it: peak season, a storm, a border delay, a carrier failure — and name the fallback.',
    ],
    diagram: ['Map the flow', 'Find the constraint', 'Cost per unit', 'Intervention', 'Stress test'],
  },
];
