// Phase 2 deep-enrichment pack B — Consulting & Professional Services and Logistics & Supply Chain.
// Same intent as pack A: fill the operating-process, R&D/product, commercial and insider-fact
// chapters that the original packs under-served, with Vietnam-specific evidence.

import type { DepthCard } from './industryDepthTypes';

export const CONSULTING_PHASE2_CARDS: DepthCard[] = [
  {
    module: 7, topic: 'supply-chain', emoji: '🗓️', type: 'concept',
    title: 'How an engagement actually runs, week by week',
    front: '“We solve client problems” tells an interviewer nothing. This is the real rhythm of a six-to-eight week strategy or diligence case, and knowing it makes every case answer more concrete.',
    back: [
      'Week 0 — scoping and staffing: the partner agrees the problem statement, workstreams, fee basis and what is explicitly out of scope. A staffing manager assigns a partner, a manager, one or two consultants and an analyst, sized by the fee and the leverage the pyramid needs.',
      'Week 1 — mobilisation: kickoff with the client sponsor, a data request list, an interview plan, and a hypothesis map so the team knows what it is trying to prove or disprove. The storyline is drafted now in skeleton form, not at the end.',
      'Weeks 2-3 — evidence gathering: parallel workstreams running interviews, data analysis and benchmarking, with an internal review every week where the manager challenges the logic and the partner challenges the “so what”. An interim readout in week 3 prevents surprises later.',
      'Weeks 4-5 — synthesis and testing: findings harden into recommendations, financial impact is quantified, and the team pressure-tests the answer against the objections the client will raise. Working sessions replace presentations, because you want the client arguing with the analysis before the steering committee rather than during it.',
      'Week 6 onward — decision and close: the steering committee is a decision meeting, not a debate, because the sponsor has already been pre-wired. Then handover with named owners and milestones, and if the firm is good, a measured outcome that becomes the credential for the next sale.',
      'The cadence underneath all of it: a daily team check-in, a weekly internal review, a weekly or fortnightly client touchpoint, and a document that is always presentable even when it is incomplete.',
    ],
    visual: [
      'WK  CLIENT-FACING         INTERNAL',
      ' 0  scope + fee agreed    staff the pyramid',
      ' 1  kickoff, data ask     hypothesis map',
      ' 2  interviews            first analysis review',
      ' 3  INTERIM READOUT       storyline v1',
      ' 4  working session       quantify the impact',
      ' 5  pre-wire the sponsor  pressure-test answer',
      ' 6  STEERING CO decision  handover + owners',
      ' -------------------------------------------',
      ' Rule: no surprises in the final meeting',
    ],
  },
  {
    module: 7, topic: 'supply-chain', emoji: '👥', type: 'fact',
    title: 'The staffing model: how you actually get put on a project',
    front: 'Your career in a consulting firm is decided largely by which projects you are staffed on — and staffing is a real internal market that nobody explains to graduates.',
    back: [
      'A staffing or resource manager matches available people to sold work, balancing utilisation targets, skill fit, client preference, location and development needs. Bench time is pure margin loss, so unstaffed people are highly visible.',
      'Leverage decides the shape: a project sold at a given fee can only afford a certain junior-to-senior mix, which is why an analyst-heavy team is more profitable provided quality holds.',
      'Partners lobby for people they have worked with before, so performance on one project directly determines the quality of the next. This is the compounding mechanism behind “your reputation is your career”.',
      'Practical consequence for a new joiner: being reliable and easy to work with on an unglamorous project gets you staffed on a better one faster than being brilliant and difficult on a prestigious one.',
      'A strong question to ask at interview: how are staffing decisions made in the first year, and how much choice does an analyst have? The answer tells you a great deal about the firm.',
    ],
  },
  {
    module: 8, topic: 'rnd-product', emoji: '🧰', type: 'fact',
    title: 'What consultants actually use day to day, beyond PowerPoint',
    front: 'Candidates assume consulting is slides and Excel. The real toolkit is wider, and naming it accurately is an easy differentiator.',
    back: [
      'Analysis and modelling: Excel remains the core modelling tool, joined by SQL for pulling client data, Python or R for larger datasets, and Alteryx for repeatable data preparation where the same messy join has to run every week.',
      'Visualisation and reporting: Tableau and Power BI for dashboards the client keeps after the project ends — increasingly a deliverable in its own right rather than a slide appendix.',
      'Market and company databases: Euromonitor, Nielsen and Kantar for consumer data, S&P Capital IQ and Refinitiv for company financials, GlobalData and Statista for sizing, plus Vietnamese primary sources such as the National Statistics Office, the State Bank of Vietnam and the Ministry of Industry and Trade.',
      'Expert networks: GLG, Third Bridge and similar services let a team speak to former executives in a category within days. In Vietnam, where published data is thin and often inconsistent, these calls frequently carry more weight than any database.',
      'Firm intellectual property: proprietary benchmarks, diagnostic tools, industry models and prior deliverables — the reusable assets that raise value without adding hours, which is why internal knowledge search matters more than outsiders expect.',
      'AI tooling now absorbs the first draft of research, document review, data cleaning and slide drafting. The honest framing for an interview: the value moves to knowing which question to ask and whether the answer is credible.',
    ],
  },
  {
    module: 7, topic: 'finance', emoji: '💹', type: 'concept',
    title: 'Project margin arithmetic you can do out loud',
    front: 'Three numbers explain the entire economics of a professional-services firm: rate, utilisation and leverage. Combining them makes you sound like someone who could run a project, not just staff one.',
    back: [
      'Rate is what the client pays per unit of time, set by perceived value and brand rather than by cost. Realisation is what you actually collect after discounts and write-offs, and the gap between the two is where quiet losses hide.',
      'Utilisation is billable hours over available hours. Every unbilled week is salary with no revenue against it, which is why staffing decisions are political.',
      'Leverage is the junior-to-senior ratio on the engagement. More analysts per partner raises margin because juniors cost less than they bill — provided quality holds and rework does not eat the saving.',
      'The Vietnamese context makes this concrete: staff costs run about 50% of revenue at EY Vietnam and roughly 52.5% at Deloitte Vietnam, but about 60.3% at PwC Vietnam. A firm at 60% has materially less room for overhead, investment and profit than one at 50%.',
      'Scope creep is the silent killer on fixed-fee work: two extra analyses at no extra fee mean more delivery hours against unchanged revenue. The correct response is a documented change request that resets either scope or fee.',
    ],
    visual: [
      'PROJECT MARGIN',
      '  Fee  = rate x hours x realisation',
      '  Cost = salary cost of the whole pyramid',
      '',
      '  Partner    1  |  high cost, few hours',
      '  Manager    1  |',
      '  Consultant 2  |  the margin engine',
      '  Analyst    2  |  lowest cost, most hours',
      '  -----------------------------------------',
      '  More leverage  -> more margin',
      '  Scope creep    -> hours up, fee flat -> loss',
    ],
  },
  {
    module: 8, topic: 'marketing-sales', emoji: '🎣', type: 'fact',
    title: 'How consulting firms actually sell',
    front: 'Nobody cold-calls a chief executive. Understanding how work is really originated explains why senior consultants are paid to create demand rather than deliver it.',
    back: [
      'Most work comes from existing clients. A well-delivered project creates the next one, which is why repeat rate is a headline metric and why partners obsess over the relationship as much as the deliverable.',
      'Referrals and networks do the rest. In Vietnam, where the senior business community is comparatively small and relationship-driven, personal credibility travels faster than any marketing campaign.',
      'Thought leadership creates the entry point: a published market study, a regulatory briefing on the global minimum tax or IFRS conversion, a sector outlook — all designed to make the firm the obvious call when the problem lands.',
      'Formal procurement matters for large corporates and the public sector: a request for proposal, a written response, a pitch, then a panel decision on approach, team and price.',
      'The proposal is the product at this stage — problem statement, approach, workplan, named team, fee basis, and critically what is out of scope, because that line is what protects margin later.',
    ],
  },
  {
    module: 9, topic: 'surprising', emoji: '🌏', type: 'fact',
    title: 'Who actually works in Vietnamese consulting',
    front: 'Candidates routinely assume the good jobs go to expatriates and that a foreign degree is required. The structure of the market says close to the opposite.',
    back: [
      'The Big Four Vietnamese practices are overwhelmingly staffed by Vietnamese professionals. Deloitte Vietnam alone reports more than 1,200 professionals across Hanoi and Ho Chi Minh City — a scale that could not conceivably be filled by expatriate hiring.',
      'The reason is structural rather than sentimental: audit and tax are licensed professions requiring Vietnamese qualification and local regulatory knowledge, and clients need people who can read Vietnamese-language filings and deal with local authorities.',
      'Strategy houses run smaller Vietnamese teams and supplement them with regional and global experts staffed from Singapore, Bangkok or Jakarta for specific projects — so you work with expatriates on a project basis rather than beneath a permanent expatriate layer.',
      'What this means practically: Vietnamese language plus local market knowledge is an asset in this market, not a limitation. The genuine differentiators are structured thinking and numerical control, both of which are trainable and testable.',
      'The scarce profile is not “international”. It is someone who can run rigorous analysis in English and hold a technical conversation with a Vietnamese finance director in Vietnamese. If that describes you, say so explicitly.',
    ],
  },
  {
    module: 9, topic: 'surprising', emoji: '🧯', type: 'fact',
    title: 'Five consulting facts that surprise candidates',
    front: 'Each of these corrects an assumption that costs candidates offers.',
    back: [
      'The Vietnamese firms are far smaller than the brands suggest. EY Vietnam led the Big Four audit entities at about VND1,473.7 billion of FY2025 revenue — roughly USD58 million — with PwC Vietnam near VND648 billion and Deloitte Vietnam about VND634 billion.',
      'Prestige does not mean profit. EY Vietnam’s post-tax profit was only around VND24 billion on that revenue, a very thin net margin. That is a deliberate choice to buy market share and coverage, and an excellent thing to discuss in an interview.',
      'Regulation, not strategy fashion, is the growth engine. The 15% global minimum tax under Resolution 107/2023/QH15, transfer-pricing rules under Decree 132/2020 as amended in 2025, and the IFRS conversion roadmap create multi-year programmes clients cannot postpone.',
      'The audit firm often cannot sell you everything. Independence rules restrict which advisory services may be sold to an audit client, so “cross-sell the whole platform” is not how a Big Four firm actually works.',
      'In-house teams compete for the same graduates. Banks, Viettel, FPT, Masan and Vingroup all run internal strategy and transformation functions hiring an identical profile — usually with better hours and narrower exposure.',
    ],
  },
];

export const LOGISTICS_PHASE2_CARDS: DepthCard[] = [
  {
    module: 7, topic: 'supply-chain', emoji: '📜', type: 'concept',
    title: 'How a 3PL contract works, versus asset-heavy logistics',
    front: 'Third-party logistics and asset ownership are two completely different businesses that both call themselves logistics. The contract structure is what separates them.',
    back: [
      'A 3PL contract is a multi-year agreement to run a defined scope — warehousing, fulfilment, transport, or all three — against agreed service levels, for a client who keeps ownership of the inventory. The 3PL sells capability and management, not steel.',
      'Two pricing structures dominate. Open book means the client sees actual cost and pays a management fee, often with a gainshare clause splitting savings: transparent, lower margin, longer relationship. Closed book means a fixed rate per pallet, per case or per order, where the provider keeps efficiency gains and carries the risk of having estimated cost wrongly.',
      'The commercial teeth sit in the annexes: service-level agreements with penalties for missed on-time-in-full, minimum volume commitments, an inventory-accuracy standard, a claims and liability cap, and an indexation clause for fuel and wage inflation.',
      'Dedicated versus shared changes the economics completely. A dedicated facility is effectively the client’s cost base with the provider’s management on top; a shared multi-user site lets the provider spread fixed cost across several clients, which is where the real margin is.',
      'Asset-heavy logistics is the opposite model: you own the ships, trucks, warehouses or terminals, carry the depreciation, and live or die on utilisation and freight rates. Fixed cost is enormous, so an idle asset is the worst outcome in the business.',
      'Interview move: when someone says “logistics margins are thin”, ask which model they mean. The answer for a parcel network and the answer for a deep-sea terminal are not remotely the same.',
    ],
    visual: [
      '                3PL / ASSET-LIGHT   ASSET-HEAVY',
      ' Owns            management,        ships, trucks,',
      '                 systems, people    terminals',
      ' Revenue         fee per unit or    rate x volume',
      '                 open book + fee',
      ' Key risk        SLA penalties,     utilisation,',
      '                 cost estimate      freight cycle',
      ' Fixed cost      low                very high',
      ' Contract        2-5 years          decades of capex',
      ' Margin driver   shared sites,      asset ramp,',
      '                 gainshare          berth/fleet use',
    ],
  },
  {
    module: 8, topic: 'rnd-product', emoji: '🛰️', type: 'fact',
    title: 'The technology stack that actually runs a network',
    front: 'Logistics competes on information as much as on trucks. These are the systems an MT will be asked about, and what each one is actually for.',
    back: [
      'Transport management system: plans loads, assigns carriers, optimises routes and settles freight. This is where load factor and backhaul utilisation are won or lost.',
      'Warehouse management system: directs putaway, picking and replenishment inside a facility and owns inventory accuracy. A 3PL contract usually specifies which system is used and who pays for the configuration.',
      'Route optimisation and rider apps: last-mile sequencing, proof of delivery, cash-on-delivery reconciliation and failed-attempt reason codes — the data behind first-attempt delivery rate, which is the single biggest cost lever in Vietnamese last mile.',
      'Control tower and visibility platforms: exception monitoring across the whole flow so a missed connection surfaces before the customer notices. Multinational shippers now score this capability during vendor selection.',
      'Customs and compliance: Vietnam clears electronically through VNACCS/VCIS, and bonded warehouse or free-trade-zone treatment allows duty-suspended storage — a genuine working-capital lever for importers rather than mere paperwork.',
      'Where automation actually pays here: sortation hubs and warehouse mechanisation, because parcel volume is high and labour cost is rising. Long-haul electrification stays constrained by charging infrastructure and payload economics.',
    ],
    diagram: ['Order capture', 'TMS planning', 'WMS pick & pack', 'Line-haul', 'Route optimise', 'Control tower'],
  },
  {
    module: 9, topic: 'finance', emoji: '📊', type: 'fact',
    title: 'Logistics margins in Vietnam, and why they differ so wildly',
    front: 'There is no such thing as “the logistics margin”. Two Vietnamese listed logistics companies can differ by fifty percentage points of EBITDA margin, and the reason is the business model rather than management quality.',
    back: [
      'Gemadept ran an EBITDA margin around 54% in 2025 on a gross margin near 44%. That is what port and terminal infrastructure looks like: enormous fixed capital, very low marginal cost per container once the berth exists, and pricing protected by the scarcity of deep-water capacity.',
      'Viettel Post ran an EBITDA margin of roughly 2.9% to 3.5% on about VND20,847 billion of revenue. That is what a parcel network looks like: revenue passes almost straight through to line-haul, rider and sortation cost, with average revenue per shipment around VND21,200.',
      'Transimex, a diversified forwarder and logistics operator, sits between them with a net profit margin around 10% — asset-light forwarding earns the spread between bought and sold capacity plus documentation and customs value-add.',
      'So why does Vietnamese logistics look weak against regional peers in aggregate? Because the national mix skews toward low-margin trucking and parcel, the market is fragmented with local firms holding roughly 65% of it, and structural inefficiency — logistics costs of 16-20% of GDP against a global average near 10% — shows up as cost the industry absorbs rather than margin it keeps.',
      'The specifically Vietnamese drags: empty backhauls on trunk routes, port-road congestion and dwell time, thin multimodal and rail usage, and a parcel price war where volume grew about 32% while revenue grew only 26.9%.',
      'The analyst habit worth building: never quote a logistics margin without naming the asset model behind it. That alone will put you ahead of most candidates.',
    ],
    visual: [
      'EBITDA MARGIN BY MODEL (Vietnam, 2025)',
      ' Port / terminal    |##################### ~54%',
      ' Forwarding / 3PL   |####   ~8-12% (net ~10%)',
      ' Contract logistics |###    ~6-10%',
      ' Parcel / last mile |#      ~3-5%',
      ' ------------------------------------------',
      ' Gemadept ~54% EBITDA vs Viettel Post ~3.5%.',
      ' Same industry. Completely different business.',
    ],
  },
  {
    module: 8, topic: 'marketing-sales', emoji: '🤝', type: 'concept',
    title: 'How a forwarder or 3PL wins an account',
    front: 'Logistics is sold through tenders and service credibility, not advertising. Knowing the sequence lets you answer any “how would you win this client” question.',
    back: [
      'Qualification and discovery: map the prospect’s lanes, volumes, seasonality and service requirements, and find the specific pain — usually missed cut-offs, customs delays or inventory inaccuracy rather than price.',
      'The tender: large shippers run a formal request for quotation covering a rate card by lane, service-level commitments, technology and visibility requirements, and compliance and sustainability questionnaires. Emissions data per shipment now appears routinely.',
      'Costing and pricing: build lane-level cost bottom-up, then decide margin per lane rather than in aggregate — because tenders are usually won on a handful of high-volume lanes and lost on the exceptions.',
      'Solution design: the differentiator is rarely price. It is what you promise operationally — network design, dedicated versus shared capacity, the peak-season plan, and the escalation process when something fails.',
      'Implementation and review: onboarding is where accounts are actually lost. Then monthly reviews on on-time-in-full, cost per unit and claims, with lane-level margin reviewed on the provider side.',
      'The discipline that protects you: never sell a service level the network cannot deliver at that price. That gap is the most common internal conflict in every logistics business.',
    ],
  },
  {
    module: 7, topic: 'marketing-sales', emoji: '💱', type: 'concept',
    title: 'What actually goes into a freight rate',
    front: 'A quoted rate looks like one number and is really a stack. Being able to break it apart is the logistics equivalent of building a P&L.',
    back: [
      'Ocean and air freight: a base rate per container or per kilogram, plus bunker or fuel surcharge, terminal handling at both ends, documentation, and peak-season or congestion surcharges. The base rate moves with the market cycle; the surcharges are the part clients forget to budget.',
      'Customs and compliance: clearance fees, duty and VAT advanced on the client’s behalf, certificates of origin and inspection costs. Under CPTPP, EVFTA, RCEP and UKVFTA a missing origin certificate erases the duty saving that justified the sourcing decision in the first place.',
      'Inland and last mile: trucking to and from port, waiting time, and delivery cost per stop — which varies enormously with density. A rider making 40 urban drops per shift versus 18 rural drops at the same daily cost means more than double the cost per parcel.',
      'Risk and administration: cargo insurance, demurrage and detention when containers sit too long, a claims provision, and payment terms — because financing a client’s freight for 60 days is a genuine cost.',
      'The Incoterm decides who pays which block. EXW, FOB, CIF and DAP shift cost and risk at different handover points, and getting this wrong in an interview is an immediate mark-down.',
    ],
    visual: [
      'A FREIGHT RATE, UNPACKED',
      '  Base ocean / air rate     market cycle',
      '+ Bunker or fuel surcharge  index linked',
      '+ Terminal handling (x2)    port tariff',
      '+ Documentation & customs   fixed per shipment',
      '+ Inland haulage            distance + waiting',
      '+ Last mile per stop        DENSITY DRIVEN',
      '+ Insurance, demurrage      risk',
      '+ Margin',
      '  The Incoterm decides where the client',
      '  stops paying and the provider starts.',
    ],
  },
  {
    module: 9, topic: 'surprising', emoji: '🎯', type: 'fact',
    title: 'Five logistics facts that surprise candidates',
    front: 'Logistics rewards people who know where the cost actually sits. Each of these puts it somewhere candidates do not expect.',
    back: [
      'The last mile is roughly 53% of total logistics cost — not the ocean leg. The expensive part of moving a product across the world is the final few kilometres to a door.',
      'Parcel prices are falling while volume booms. About 3.5 billion shipments moved in the first ten months of 2025, up roughly 32%, while postal and express revenue grew only about 26.9% — so revenue per parcel, around VND21,200, is shrinking.',
      'The platforms became the carriers. SPX Express reached about 15.7% share on Shopee volume, and competition intensified enough that Ninja Van moved to exit Vietnam entirely.',
      'Foreign ownership of Vietnamese logistics services is generally capped near 49% and local firms hold roughly 65% of the market — which is why global names so often operate through joint ventures and licensed local partners.',
      'Cutting dwell time is economically identical to building capacity, at a fraction of the cost. Viettel Post’s bonded warehouse at Lang Son, connected directly to the VNACCS/VCIS customs system, is that idea made concrete at the Chinese border.',
    ],
  },
];
